---
title: "Course Intro"
subtitle: ""
Week: 1
slide-format: revealjs
---

[Weekly design](https://changjunlee.com/teaching/ds101/weekly/)

<br>

### About Course

-   Course description

-   Weekly design

-   Text books

-   Flipped learning

-   PBL

-   Score

-   Communication

<br>

### Why R?

**3 Reasons to learn R programming for data science**

R isn't a general purpose language, but depending on where or how you plan to work, it could offer a lot of perks that aren't available with a general purpose language.

**1. R is built for statistics:** Heavy statistical analysis is possible with Python, but you won't get the syntax-specific libraries and functions as you do with R. The language makes it much more intuitive to build and communicate results from these specific types of programs. Statisticians and data analysts use R to manage large datasets more easily using standard machine learning models and [data mining]{.underline}.

**2. R is academic:** R is almost a default for working in academia. R is well suited for a subfield of machine learning known as statistical learning. Anyone with a formal statistics background should recognize the syntax and construction of R.

**3. R is intuitive for analysis:** R may not work with a wide variety of projects, but it is the best choice for analysis and inference work. If you plan to work in a specialized field, you'll want a specialized programming language. R also offers a powerful environment ideally suited to the types of [data visualizations]{.underline} data scientists employ.

Source: <https://www.edx.org/resources/r-vs-python-for-data-science-explainer-learning-tips>

<br>

### Install gadgets

-   Install R, R Studio, & Rtools

    -   **R**

        -   For window <https://cran.r-project.org/bin/windows/base/>

        -   For mac <https://cran.r-project.org/bin/macosx/>

    -   **R Studio**

        -   <https://posit.co/download/rstudio-desktop/>

    -   **Rtools** (only for window user)

        -   <https://cran.r-project.org/bin/windows/Rtools/>

        -   To install R packages containing C/C++ language for window users (no need for Linux and Mac users)

-   Things you need to know

    -   Don't Use OneDrive.

        -   Use Github instead

        -   Many people get an error when installing because of OneDrive

    -   Set Windows user name to English

        -   If Korean characters are mixed in the installation path, there is a high probability of error occurrence

-   Installation Order

    -   **Step 1** ‑ Download the file

        -   Download R, Rtools, Rstudio installation files

    -   **Step 2** - Install R

        -   Unified installation path: All will be installed in the `C:/R` folder

        -   Run in administrator mode when running the R installation file

        -   After installing R, grant write permission to the R folder, Right-click and turn off read only

    -   **Step 3** ‑ Install Rtools

        -   Administrator mode execution installation and folder setting as C:\\R\\rtools40

        -   Create environment variable RTOOLS40_HOME after installation: Value - C:\\R\\rtools40\\

        -   Add *%RTOOLS40_HOME%\\usr\\bin\\* to the Path variable.

    -   **Step 4** - Install Rstudio

        -   Right-click and run as administrator - installation path C:\\R\\Rstudio

        -   Check rtools connection with Sys.which("make") command after installation

<br>

### Textbooks for the course

-   **R4DS:** [R for Data Science](https://r4ds.had.co.nz/index.html) (written by *Hadley Wickham* and *Garrett Grolemund*)
    -   is an excellent resource for learning data science using R, covering data manipulation, visualization, and modeling with R. The book is available as a free online resource.
-   **RC2E:** [R Cookbook](https://rc2e.com/) (written by *JD Long* and *Paul Teetor*)
    -   is a comprehensive resource for data scientists, statisticians, and programmers who want to explore the capabilities of R programming for data analysis and visualization.
-   **RGC:** [R Graphic Cookbook](https://r-graphics.org/index.html) (written by *Winston Chang)*
    -   is a practical guide that provides more than 150 recipes to help you generate high-quality graphs quickly, without having to comb through all the details of R's graphing systems
-   **MDR:** [Statistical Inference via Data Science (Modern Dive)](https://moderndive.com/index.html) (written by *Chester Ismay* and *Albert Y. Kim*)
    -   is a comprehensive textbook that provides an accessible and hands-on approach to learning the fundamental concepts of statistical inference and data analysis using the R programming language.
-   **ISR:** [Introductory Statistics with R](https://link.springer.com/book/10.1007/978-0-387-79054-1) (written by *Peter Dalgaard*)
    -   is a great resource for learning basic statistics with a focus on R programming. This book covers a wide range of statistical concepts, from descriptive statistics to hypothesis testing and linear regression, along with R code examples.
