---
title: "Final Presentation"
subtitle: ""
Week: 16
---

[Weekly design](https://changjunlee.com/teaching/ds101/weekly/)

<br>

### Announcement

**Final Project Submission & Peer Evaluation**

Hi everyone, how is your team project coming along? - Final submission deadline: Tuesday, June 17, by 10:00 AM

**Final Output** (by team)

-   Submission link: <https://forms.gle/SaZbXyB7Z7cKhBKc7>

Peer evaluation deadline: - Also due by Tuesday, June 17, at 10:00 AM

**Peer Review** (by individual)

-   Submission Link: <https://forms.gle/Xa5oEp8PAPPDQCna9>

Class on Tuesday, June 10, will be held as a Team Consulting Session 09:00–11:50 at Room 9B312

-   Attendance is not mandatory.
-   Not all teams need to come—just drop by if you have questions or want to check in on your progress.
-   If your team needs more time together, feel free to use this time accordingly.

Since the final submission is a YouTube link, this might be our last offline meeting. Feel free to stop by and say goodbye in person!

<br>

**Output:** Data analysis report & Presentation Video

**Report**

> Any format is possible (PPT, word, notion web page link, pdf, and so on).

-   Report example (but not limited)

    -   Data Preparing (or Collecting)

    -   Explore data (Descriptive stats)

    -   Set your hypothesis (or research questions)

    -   Visualize data to confirm your hypo or RQs

    -   Explain your findings

    -   Expanding your findings to implications

<br>

**Presentation Video**

> Making videos for 10 mins presentation (in any language),

-   Submit a Youtube link
