---
title: "인터랙션 사이언스, UX"
subtitle: "이대호" 
Week: 10
format: html
slide-format: revealjs
---

[Weekly content](https://changjunlee.com/teaching/cul_tech_101/weekly_2/)

<br>

수업에 참석하기 전, 아래 활동을 완료하시기 바랍니다:

1.  pre-class video 시청

2.  Discussion 제출 (pre-class 내용과 Question)

    -   Submission due: 수업전 일요일 자정까지

<br>

#### **Week 10: 인터랙션 사이언스, UX**

-   Date: 20240507

```{=html}
<!-- -->
```
-   [수업자료](content/cnt_w10_ldh.pdf)

```{=html}
<!-- -->
```
-   Pre-class video

    -   Human-Computer Interaction and User Interface Design \| Tony Tang

    {{< video https://www.youtube.com/watch?v=2Tgu7w3UCNo >}}

<br>

-   Discussion

<br>

<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSenvz_BRyEfroMdZDlmD9AMsvOI_N3vNvK1igjWFSza02q4CA/viewform?embedded=true" width="640" height="831" frameborder="0" marginheight="0" marginwidth="0">

로드 중…

</iframe>

------------------------------------------------------------------------

### Best Discussion

> AI 등 인공지능, 기계 등의 기술이 점점 발전되면서 사회가 많이 변했다고 느꼈습니다. 이제 어느 가게를 가도 키오스크 없는 곳을 찾기 어렵고, 모바일 앱으로 주문이 안되는 곳을 찾기 어려운 것도 하나의 예시라고 생각합니다. 어느 순간부터 우리 생활에 기술이 가장 깊숙히 들어와있다고 느껴졌습니다. 그냥 오랜 시간 기술과 함께 사회를 이루어갔기 때문이라고 생각했는데, 이 영상을 보고 인간이 편리함을 느끼게끔 기술이 변했다고 생각했습니다. 인간이 느끼는 사회의 불편함을 기술이 해결하고 있다고 생각했습니다. 그리하여 이제는 이런 기술 없이는 살 수 없는 분위기, 사회가 형성된 것이라 예상했습니다. 수요가 많아져 발전되는 속도가 빨라지면 공급이 더뎌져 빈 공간이 생기기 마련입니다. 카페 아르바이트를 하며 키오스크를 어려워하는 고령층분들이 눈에 많이 밟힙니다. 그럴 때마다 저희 부모님도 생각나면서 이런 기술이 발전하면 이 기술을 모든 사람이 잘 활용할 수 있도록 교육, 안내를 잘 해야 하지 않을까 생각합니다.

<br>

> 시스템을 만드는 디자이너들이 실제로 시스템을 사용하는 사람들이 아닌 경우가 많다는 이야기가 가장 공감이 갔습니다. UX research로 인터뷰를 시행한 경험이 있는데, 실제로 해당 제품을 사용하는 사용자가 아니다보니, 어떤 점이 불편할지, 어떤 점을 조사해야 할 지 인터뷰 질문을 구성하는 과정 자체가 막막하기도 했습니다. 영상에서 나온, 디자이너들이 시스템이 어떻게 사용될 것인지 가정한다는 구절이, 제 상황을 정확히 지적하고 있었습니다. 사용자 경험 연구와 사용자 경험 디자인에서 해야 할 일은 사용자가 누구인지를 이해하기 위해 공감 도구를 개발하는 것이라고 하는데, 어떻게 하면 사용자 입장에서 생각할 수 있을지 여전히 아리송한 상황입니다. 특히 요즘에는 사용자들의 유형이 개별화되다보니, 보편적인 사용자 디자인을 만들기는 더욱 어렵게 느껴집니다.

<br>

> 외국인이 음료수 “갈아만든 배”의 “배”를 IdH 로 읽는다던지, 너구리를 뒤집어 읽어 “RTA”로 본다던지의 사례를 보면서 웃은적이 있다. 하지만 이번 영상을 보며 위 사례를 미루어 좋은 커뮤니케이션, 디자인이 무엇인지 생각해볼 수 있었다. 위의 경우에는 그저 문자의 차이에서 생긴 단순한 해프닝으로 볼수 있지만, 적어도 좋은 커뮤니케이션이 일어났다고는 할 수 없을 것이다. 어떤 제품, 서비스 등을 기획 및 제작함에 그 의도에 맞는 공통된 행동 양식을 보일 수 없다면 그것은 좋은 디자인이 아닌 것이다. 만약 우리가 “밥 뭐 먹었니?”라고 물어보면 “도시락 먹었어”로 대답하지, “응/아니”라고 대답하지 않듯, 좋은 UX디자인은 자신이 의도한 대로 사용자의 행동을 유도하는 “의도에 따른 행동 유도”로 정리할 수 있을 것 같다.

<br>

> 인터랙션 사이언스와 UX 분야가 이론부터 기술을 총망라하는 분야임을 알 수 있었다. 사용자에 대한 관심을 기술로 풀어낸다는 점에서, 굉장히 매력적인 분야인 것 같다. 인터랙션 사이언스에서 인터랙션은 어떤 의미일 수 있을지 생각해보게 되었다. 처음에는 단순 기술을 고안하는 인간과, 기술을 실현하는 도구인 컴퓨터(혹은 그외 도구) 간의 교류라고 생각했는데 영상을 보니 사용자와, 사용자를 생각하는 기획자와의 교류 사이에 도구가 연결되어 있는 소통으로도 뜻을 이해하게 되었다.

<br>

> 영상 처음 부분에 실패한 UX 디자인의 예시를 보며, 과연 나도 살면서 저러한 제품들, 혹은 상황들은 마주한 적이 있는가에 대해 생각해보게 되었습니다. 생각해보면 저러한 상황들은 다수 있었습니다. 간단한 예시를 들자면, 요즘에는 어떠한 사이트에 들어가려면 간편하게 로그인을 구글로 로그인하기, 카카오톡으로 로그인하기 버튼을 누르면 빠르게 로그인을 할 수 있습니다. 하지만 가끔씩 그렇지 않은 사이트들도 다수 있는데요, 로그인을 하려고 다른 페이지로 넘어가는 순간 보이는 복잡한 로그인 단계를 보면 한숨부터 나오게 됩니다. 과연 이러한 정보까지 입력을 굳이 해야되나 싶을 정도입니다. 영상에서 나오는 예시들을 보며 많이 답답했고, 공감을 얻은 것 같아 흥미로웠습니다. 또한 실패한 UX 디자인을 보면서, 어떻게 저러한 제품이 상용화가 되었는지 많은 의문이 들었습니다.

<br>

> 기술이라는 것이 인간의 의도를 실현해주는 역할을 한다고 생각하는데, 이 인터렉션 사이언스는 '소통'이라는 의도를 실현해주는 역할을 하며, 그 의도를 망각해서는 안된다고 느꼈다. 소통을 원활히 하기 위해서 영상 속의 사람들은 무의식을 연구하고, 공감 도구를 활용하고 프로토 타입을 제작하는 등의 노력을 기울인다고 이해했다. 결국 우리 컬처앤테크놀로지전공생의 역할은 이 '소통'이라는 것을 개발자와 협업해 원활하게 해주는 사람이 아닐까 싶었다.

<br>

### Best Questions

1.  **(인터랙션 사이언스와 AI)** "인터랙션 사이언스는 인간과 기술이 상호작용하는 방법과 현상에 대한 이론을 다양한 학제간 접근을 통해 연구하는 학문이라고 정의를 내리고 있고, 기술을 통해 중요한 정보 전달을 강조하는 중간 시스템의 역할은 해당 정보를 가장 적절하고 맥락에 맞게 제공하는 것, 즉 기술은 맥락을 이해하고 정보를 적절하게 제공해야 한다는 것이 위의 영상의 핵심이라고 생각했습니다. 몇주 전 수업시간에 음성인식 기술 관련해서 의견을 작성했었는데요. 기술은 맥락을 이해하고 정보 전달에 탁월해야 한다는 것이 인터랙션 사이언스가 존재하는 이유들 중 하나라면, 음성인식 비서 즉 AI 기술들이 인간의 언어의 맥락을 파악하고 이를 전달하거나 완벽하게 이해할 수 있을 것이라고 생각하시는 지 질문 드리고 싶습니다. 예를 들어 중의적인 표현이나, 사람의 억양, 단어 선택에 따라 말의 의미가 정말 많이 바뀌는데 이러한, 음성적인 정보도 파악이 가능하다고 생각하시는 지 궁금합니다.

<br>

2.  **(인터랙션 사이언스와 심리학)** "인터랙션 사이언스, UX 디자인도 점점 더 개인화된 경험을 개선하기 위해 집중할 것이라 추측된다. 이를 위해서는 사용자의 경험을 이해하기 위한 심리적 측면의 연구도 선행되어야 할 것 같은데, 실제로 인터랙션 사이언스와 UX 디자인을 구상할 때 이론적인 연구가 얼만큼 수행되고 적용되는지 궁금하다. 또한 인터랙션 사이언스와 UX를 기획하고 구체화할 때, 이론연구와 기술구현 그리고 이후 영향분석의 과정까지 정말 다양한 분야의 지식이 필요할 것 같다. 지금은 기술구현 측면이 더 두드러지고 있는 것 같은데, 이러한 현상에 대한 전문가의 견해가 궁금하다. 앞으로 인터랙션 사이언스와 UX가 발전하기 위해서는 어떤 점에 더 집중해야 하는지도 의견을 묻고 싶다."

<br>

3.  **(특이성 vs. 대중성)** 사용자와 기술 간 상호작용을 이해하고 설계하는 과학이라고 불리는 인터랙션 사이언스와, 사용자 경험을 나타내는 UX는 서로 밀접한 관련이 있다는 것은 누구나 다 알고 있는 사실입니다. 학문적 영역과 디자인 접근 방식의 결합을 통해 실생활의 문제점들을 해결할 수 있다고 생각하는데, 결국 사람들 다수의 공통의 사고를 얼마나 잘 분석해 내는지가 중요한 요소로 작용할 것이라고 생각합니다. 이 과정에서 사람들의 특이성에 초점을 두고 특성에 기반한 해결책을 마련하는 것이 좋은지, 모두가 알고 있는 대중성에 초점을 두고 노말한 요소를 만들어내는 것이 좋은지 궁금합니다.
