---
title: "서비스 디자인, 데이터 드리븐 마케팅"
subtitle: "설상훈" 
Week: 11
format: html
slide-format: revealjs
---

[Weekly content](https://changjunlee.com/teaching/cul_tech_101/weekly_2/)

<br>

수업에 참석하기 전, 아래 활동을 완료하시기 바랍니다:

1.  pre-class video 시청

2.  Discussion 제출 (pre-class 내용과 Question)

    -   Submission due: 수업전 일요일 자정까지


<br>

#### **Week 11: 서비스 디자인, 데이터 드리븐 마케팅**

-   Date: 20240514

-   [수업자료 1](content/cnt_w11_ssh_1.pdf)

-   [수업자료 2](content/cnt_w11_ssh_2.pdf)

-   Pre-class video

    -   Why Data Marketing So Important \| 세바시

    {{< video https://www.youtube.com/watch?v=vXTaU0SPBOM >}}

    -   Age of Experience, Data+Service \| 설상훈 교수님

    {{< video https://www.youtube.com/watch?v=FtyPfko5fvQ >}}


<br>

-   Discussion

<br>

<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSe0pJPq-zO6j1lt_GbX2WG55Xl2UOo4bCogNKgDRw7RL0t1Eg/viewform?embedded=true" width="640" height="988" frameborder="0" marginheight="0" marginwidth="0">로드 중…</iframe>




------------------------------------------------------------------------

### Best Discussion

> 글부터 미디어까지, 형태에 따라 의사소통의 해상도가 높아지며 경험의 전달률이 높아진다는 내용이 흥미로웠다. 동시에 모든 의사소통의 행위자가, 자신의 경험의 전달률을 높이고 싶은 목적으로 의사소통에 임하는 것은 아니라는 것 역시 느꼈다.
실제로 나는 영상 미디어보다 텍스트를 선호하는데, 영상 미디어에서는 그 영상의 기획/제작/공유자의 의도가 너무 직관적으로 다가와서 오히려 수용자로 하여금 거리감을 마련해주지 않다고 느껴지기 때문이다. 의사소통 과정에서 틈을, 이를테면 노이즈를 만들어주는 텍스트가 나에게는 해상도가 낮을 수는 있어도 의사소통을 더 편하게 해주는 형태인 것이다. 
그래서 앞으로 데이터를 통한 경험 전달률을 무조건 극대화하는 게 아닌, 더 높은 해상도를 원하면서 동시에 수용할 수 있는 상대와 분야에 한정해 이뤄져야 하지 않을까 생각했다.

<br>

> 현재 ‘우리는 인공지능에 의존하게 될 것이다.’ 혹은 ‘인공지능이 인간을 대체할 것이다’라는 우려와 두려움에 조금씩 잠식되어 가는 중인 것 같습니다. 하지만, 영상에서도 언급하고 있는 내용처럼 인간이 할 수 있는 일, 인간이 더 잘할 수 있는 일인 “해석”과 그 결과로 새로운 통찰을 찾는 것이 있습니다. 역사적으로 인간과 비인간을 구분함에 인간은 항상 자신들만이 할 수 있는 것만을 찾아왔습니다. 인공지능이 발달한다고 해서 인간이 설 수 있는 자리가 없는 것은 아닐 것입니다. 인공지능을 활용해서 다만 우리가 현재로서는 느끼기 어려운 또 다른 인간의 장점들이 드러나고, 그것을 발전시키는 방향으로 변화할 것이라고 생각합니다.
양극단에 있는 데이터 역시도 간과해서는 안된다는 내용이 가장 기억에 남습니다. 특히, 경험에는 좋고 나쁜 것이 없으며 그것을 나눌 수도 없다는 부분이 인상깊었습니다. 비슷한 맥락에서 몇 주전 “자연어처리”를 주제로 수업을 진행했을 때, 장애인의 목소리가 되어주는 AI 기술과 관련된 영상이 제시되었는데, 이 역시도 일반적으로 우리가 지나칠 수 있는 이들의 경험, 그리고 이들의 경험을 더 나은 방향으로 발전시킬 수 있도록 하는 것이 또 하나의 기회로 작용할 수 있으며, 데이터는 이런 측면에서 우리가 쉽게 지나칠 수 있는 부분을 알려주는 수단이라고 생각합니다.

<br>

> 데이터 기반 의사결정이 중요하다고 들었는데, 늘 '어떤 데이터'를 가지고 '어떤 가설'을 만들어야하는지 궁금했었다. 영상에서 예시로 나온 '예측 정교화를 위한 여러 가설들'을 보니, 어쩌면 당연한 이야기들이었다. (ex. 긍정적인 바이럴과 판매량 비례하여 증가) 
해당 가설을 검증하기 위해 필요한 데이터, 이 데이터를 수집하기 위한 키워드를 차례로 붙여보니 '어떤 데이터'들이 필요한지 쉽게 와닿았다. 가설과 검증이라고 해서 처음부터 새롭고 신박하며 복잡하지만, 논리적으로 타당해야한다고 생각했는데, 창의력은 검증 과정이 아니라 검증 결과를 통해 마케팅 아이디어를 도출하는데에 필요하다는 것을 깨달았다. 
경험데이터 정규분포표에 나타냈을 때, 양쪽 끝에 해당되는 이상치를 배제하지 않음으로서 아직 오지 않은 트렌드를 예측할 수 있다는 것을 알게 되었다. 이 데이터들을 입체적으로 분석해보면 지금 유행하고 있는 데이터와 아닌 것으로 구분할 수 있고, 메인 데이터를 제거하면 가치있는 데이터를 사용할 수 있게 된다. 결국 낮은 신뢰도의 데이터 구간 중에서도 신뢰도가 더 낮은 데이터들이 서비스 디자인에서는 유효하게 작용할 수 있다는 것을 알았다.

<br>

> 강연에서 제시된 구체적인 사례를 보고 마케팅에서 데이터를 어떻게 활용할 수 있는지, 데이터가 어떤 효과를 가져올 수 있는지를 이해할 수 있었습니다. 그리고 사례를 보니 좋은 마케팅은 어느 산업 분야에서나 중요 요소라는 것이 새삼 느껴지는데, 추상적으로 존재했던 소비자들의 니즈나 평가를 데이터 수집을 통해 정량적으로 확인할 경우, 마케팅 계획이 더 효율적으로 이루어질 수 있을 것 같습니다. 그리고 모든 사람들이 데이터 마케팅의 중요함을 알고 채택할 경우, 더욱 중요해지는 것은 데이터 수집의 영역보다 해석 방식이 될 것이라는 점도 깨달았습니다. 
경험을 전달하는 데에 있어서 어떤 방식이 의사소통의 해상도가 높은지 순서대로 나타낸 부분이 인상 깊었습니다. 가장 해상도가 높은 경험을 실현하는 방법으로는 지금까지 프로토 타입과 메타버스가 있다는 것을 알게 되었고, '앞으로 그 이상 어떤 방법이 있을 것인가'에 대한 질문에 대해 깊게 생각해보게 되었습니다. 

<br>

### Best Questions

1.    **(그래서 어떤 데이터가 필요할까요?)** 데이터 기반 접근이 마케팅 전략에 큰 영향을 주고 있다는 사실은 인지하고 있는데, 질문하고 싶은 것은 서비스 디자인과 데이터 드리븐 마케팅을 효과적으로 통합하기 위해서는 어떤 종류의 데이터가 필요한지 궁금합니다. 그리고 이러한 데이터를 수집하고 분석하여 서비스 디자인에 어떻게 반영할 수 있는지도 궁금합니다.

<br>

2.    **(비주류 데이터를 바라보는 관점)** 데이터 베이스의 마케팅에 초점을 두게 되면 두번째 영상에서 언급된 양 끝의 데이터는 점점 더 소외될 것이다. 데이터에 의해 주된 정보, 유행중인 문화는 더욱 부각되고 마케팅 됨으로써 더더욱 주류가 될 것이다. 하지만 이러한 현상이 지속된다면 문화가 단면적이게 되지 않을까라는 의문을 갖게 되었다. 실제로 세계적으로 문화 획일화가 기하급수적인 속도로 진행되고 있다.

<br>

3.    **(크롤링의 어려움)** 최근 구글을 비롯한 주요 웹사이트에서 서드 파티 쿠키를 제한함으로서 사용자들의 정보를 모으기가 점점 더 어려워진다고 생각합니다. 이러한 상황에 대해 어떻게 보시고, 데이터 드리븐 마케팅의 방식이 어떠한 방식으로 발전할 것이라거 보시는 지 궁금합니다. 
