---
title: "한류와 팬덤"
subtitle: "이종명" 
Week: 6
format: html
slide-format: revealjs
---

[Weekly content](https://changjunlee.com/teaching/cul_tech_101/weekly_2/)

<br>

수업에 참석하기 전, 아래 활동을 완료하시기 바랍니다:

1.  pre-class video 시청

2.  Discussion 제출 (pre-class 내용과 Question)

    -   Submission due: 수업전 일요일 자정까지

<br>

#### **Week 6: 한류와 팬덤**

-   Date: 20240409

-   [수업자료](content/cnt_w6_ljm.pdf)

-   Pre-class video

    -   All I Really Need To Know, I Learned From KPOP \| Donald Lim \| TEDxYouth\@SJCS

    {{< video https://www.youtube.com/watch?v=452sJcNYKcM >}}

    -   Has K-pop prepared us for the metaverse? \| Alex Karlsson \| TEDxBrunkebergstorg

    {{< video https://www.youtube.com/watch?v=DNBZ0q2o5hw >}}

<br>

-   Discussion

<br>

<iframe src="https://docs.google.com/forms/d/e/1FAIpQLScXXj_U_DtYDA_7uhDWmeGRPvxGoWb45heDgO946K4NPNuQKQ/viewform?embedded=true" width="640" height="988" frameborder="0" marginheight="0" marginwidth="0">

로드 중…

</iframe>

------------------------------------------------------------------------

#### Q&A Session

**한류와 K-Pop의 글로벌 확산 및 팬덤 문화**

-   **(스타가 팬을 대하는 태도가 성공에 미치는 영향)** 한류가 전세계적으로 유행하는 데에는 팬덤도 큰 영향을 미치고 있는지에 대해 여쭙고 싶습니다. 또한, 미국의 유명 가수인 테일러 스위프트를 보면 자신의 팬을 대하는 태도에서 한국의 K-Pop 아이돌(연예인)들과 유사한 점이 있다고 생각하는데, 이러한 특징이 테일러 스위프트의 성공에 기여하였다고 보시는 지에 대해 여쭤보고 싶습니다. 만약 그렇다면 이러한 K-Pop의 특징은 점차 세계화될 것이라 전망하시는 지에 대해서도 궁금합니다.

> 팬덤이 K-Pop 세계화에 큰 영향을 미친것은 사실입니다. 하지만 주목해야할 점은, 테일러 스위프트처럼 스타성, 대중성이 큰 가수와 달리 K-Pop은 보다 섬세함이 특징적입니다. 여기에는 소셜 미디어 활용이라는 기술적 차원이 접목됩니다. 미디어 기술이 관여되고 케이팝 산업과 가수들이 이를 적극 활용한 것입니다. 예컨대 스타들과 위버스 등 소셜 미디어 플랫폼에서의 라이브채팅(유료회원)을 할 수 있도록, 더 가까이 내적 친밀감을 유도합니다. 이를 통해 케이팝 팬덤은 능동적 수용자로 자리매김하고, 미디어 기술과 엔터테인먼트 산업계가 팬덤을 상업적으로 활용하는 것이 복합적으로 작용한 형태가 작금의 K-Pop 시장인 것입니다. 이중 하나만 없어도 향후 케이팝 세계적 인기는 어렵다고 해석할 수 있습니다.

<br>

-   **(팬덤 갈등)** KPOP의 흥행 덕분에 여러 아이돌 가수들이 많이 생겨났고, 다양한 팬덤들 또한 많이 생겼다. 하지만 이런 팬덤들 간의 갈등과 구분짓기 같은 문제들이 없지 않아 있는데, 이와 같은 것은 어떻게 해결하면 좋을지 궁금합니다.

> 팬덤 갈등은 기실 유구한 역사입니다. 여러분들이 아마 보셨을지 모르겠습니다만, \<응답하라 1997\>과 같은 드라마에서도 묘사되는 바, “HOT” 팬덤과 “잭스키스” 팬덤의 갈등이 실제 사회적 문제로 대두되기도 했습니다. 이는 비단 한국만의 문제가 아니기도 합니다. 외국에서도 팬덤들 간의 충돌이 빈번하게 일어납니다. 아이돌 등과 같은 팝 아티스트 뿐만 아니라, 스포츠 계에서도 일어나는 일이지요. 따라서 쉽게 해결될 수 있는 문제라고 생각되지는 않습니다. 어찌보면 팬심이라는 것이 해결되어서도 안될 일일 것 같기도 하고요. 다만, 그것이 사회적 문제로 확산되지 않도록 경각심을 갖고 모두가 이해하고 관리하는 노력이 필요한 차원으로 접근해야겠습니다.

-   **(팬과 스타의 관계**)팬덤의 문화는 사실 플라토닉 러브를 뛰어넘어서 유사연애와 어떻게 보면 위험한 심리 현상을 일으킨다고 봅니다. 메타버스를 활용하여 팬들이 본인의 스타에게 접근성이 높아져 더 가까워졌다는 인식을 가지게 되면 스토킹이나 유사연애 같은 안 좋은 심리적 현상이 늘어나지 않을까 걱정이 됩니다. 교수님께서는 메타버스를 팬덤에 적용하는 것에 어떤 부작용이 있을 것이라고 생각하시며, 어느 정도로 메타버스를 활용하는 것이 옳다고 생각하시나요?

-   "1. 팬과 연예인의 관계는 복잡하고 다양한 관계인데, 이 관계도 **열정적인 지지와 함께 이성과 존중을 유지**해야 하며, **팬덤에서 발생하는 극단적인 행동에 대해 회사에서 관리나 도움을 줄 수 있을까요?**

-   "이번 카리나 이재욱 열애설에 아이돌들의 연애를 격하게 지탄하는 팬들의 모습이 외신으로 보도되면서 국제적으로 한국의 팬덤 문화에 대한 얘기가 나눠졌습니다. '돈은 덕후가 쓰고 용서는 머글이 한다.' 파벌과 '진짜 현생을 살아라' 파로 나눠서 갑론을박이 펼쳐지고 있는데 아이돌의 연애에 대한 팬덤의 반응과 앞으로 팬덤 문화는 어떻게 발전해야 한다고 생각하시는지 궁금합니다."

-   **(과격한 팬덤 활동?)** 앨범 판매량 부풀리기 등 k팝 팬들의 과격한 행동을 어떻게 보십니까.

-   팬덤의 건전성과 수익성은 양립할 수 있나요?

-   **(팬밍아웃, 부끄러움?)** 국내 케이팝 팬들은 팬덤에 속해있는걸 부끄러워 한다. 한국 팬덤 사이에는 일코라는 용어가 있을 정도이다. 하지만 해외에서는 kpop을 좋아하는 것을 부끄러하지 않는다. 이 차이가 있는 이유가 궁금하다

-   케이팝 아이돌을 보며 그들이 전하고자 하는 메세지를 알기보다 그들의 멋진 겉면만 보고 좋아하는 사람들도 상당하다. 이는 과연 바람직하지 않은 것이라고 말할 수 있을까?

> K-Pop을 주도하는 보이그룹과 걸그룹의 과거 형태로 볼 수 있는 비틀즈, 백스트릿 보이즈, 원 디렉션, 스파이스 걸즈 등의 그룹들의 소통 방식을 보면, 과거 적절한 소통의 도구가 부재했습니다. 즉 소셜 미디어와 같은 기술이 없었습니다. 이로 인해 스타와 대중의 거리감을 상당히 했습니다. 거기에서 오는 신비주의 등이 새로운 아티스트의 색깔을 만드는 장점도 있었습니다. 그러나 지금의 기술 문화 시대에는 그런 것 없이, 질문자께서 말씀하신대로 일상에 대한 접근을 넘어 유사 연애, 스토킹과 같은 접촉, 스며듦이 심각한 문제가 되고 있습니다.
>
> K-Pop은 미디어 기술의 발달에 편승하여 거리감을 좁히며 소통하며 전 지구적인 인기를 누려 왔습니다. 그러나 반대급부로, 오히려 이 때문에 스타들로 하여금 또 다른 노동을 초래하기도 했습니다. 즉 노래하고 춤추는 것 이외에 팬과 소통이라는 것을 강요당하는 것이지요.
>
> 팬덤 문화를 하나로 설명하기란 불가능에 가까우며, 또 과격한 반발심 역시 어제오늘의 일만은 아닙니다. 90년대 후반, 연예 산업 발달과 함께 소위 ‘빠순이’라고 불리는 열혈 팬층의 활동이 사회적 문제로 급격히 대두되어 문제시되었습니다. 그들은 저마다의 아이돌에게 열혈 팬심을을 자청하며 파벌을 형성하고, (심지어는 그룹 내 멤버 간 팬 갈등도 있었습니다 - 문희준 간미연 열애설 당시 간미연은 면도칼 등 위협도구를 받기도 했습니다-) 팬덤은 하나의 시대적 현상으로 이해될 필요가 있습니다. 즉 인간이 특정 대상을 신격화고, 심리학적으로 광적으로 따르는 것으로 보아야지, 그것을 K-Pop이라고, 카리나라고, 누구라고 특정할 필요는 없다고 봅니다.

<br>

**케이팝 산업의 현황 및 도전**

-   **(앨범 구매의 본질적인 변화)** 최근 앨범 구매의 목적이 바뀌었다. 더 이상 자신의 아이돌과 연결하기 위해 애정을 쏟는 것이 아니라 이제는 하나의 유통 화폐가 된 포토카드 구매에 치중하고 있다. 앨범 구매의 본질적인 변화에 대해 교수님은 어떻게 생각하십니까?

-   외국어 가사와 외국인 멤버가 해외에서 K-POP이 통하기 위한 필요조건일지 아닐지 궁금합니다.

-   최근 에스파 카리나의 열애설로 sm 주가가 하락하는 모습까지 보이는 큰 파장을 일으켰습니다. 이를 해외에서는 한국의 팬덤 문화는 연예인의 사생활까지 관여한다라고 저격하기도 했습니다. 우리나라의 이런 팬덤 문화가 발달한 이유는 무엇일까요? 그리고 앞으로도 이런 자유롭지 못한 팬덤 문화가 지속될까요? 혹여나 해외 특히 미국처럼 자유롭게 변할 가능성은 없을까요?

> 저는 그 본질은 크게 달라지지 않았다고 생각합니다. 그 옛날, 소위 ‘덕질’의 선조들이라 불리는 서구 스타워즈, 스타트렉 덕질 하는 사람들도 소장용, 재판매용 앨범, 디스크 등을 하나씩 더 구매하기도 하는 등 다양한 형태로 팬 소비를 했습니다. 낯설지 않기에, 본질적인 변화는 아니라고 생각합니다.
>
> 최근 한국인 없는 K-Pop 그룹이 등장하고, 영어, 중국어, 일본어 등으로 된 노래들을 내놓는 일이 빈번합니다. 이른바 융합(Convergence)가 더욱 가속화되는 모양새입니다. 강의 중에서 말씀드렸듯이, 문화와 기술의 융합뿐만 아니라 문화와 문화 간의 융합도 더욱 강화될 것으로 보입니다. 한국적 문화의 맥락을 지키는 것도 K-Pop의 힘을 오롯이 가꾸는 일이겠지만, 한편으로는 BTS가 다이너마이트, 버터, 퍼미션투댄스 와 같이 다양한 영어 노래로 국제적 성공을 거둔 것처럼 글로벌 시장에서의 성공을 위해 영어 노래 전략을 융화했듯이 융합적 전략을 구사할 필요는 있을 것입니다.
>
> K-Pop 현상을 BTS를 중심으로 풀어낸 미국의 한 사설([[https://www.dw.com/en/whats-behind-the-bts-phenomenon/a-62113315]{.underline}](https://www.dw.com/en/whats-behind-the-bts-phenomenon/a-62113315) )에서는, 한류 신화의 몇 가지 특징 중 하나로 ‘개인적 문제에 대한 터부시’를 꼽고 있습니다. 이는 비단 K-Pop 만의 문제가 아닙니다. 고 이선균씨의 문제도 마찬가지입니다. 이는 한국의 문화적 배경과 맞닿아 있는 것으로 이해됩니다. 아마 미국처럼 자유롭게 될 가능성은 지극히 낮아 보입니다. 이는 역사적 배경과 민족성에서 분리될 수 없는 배경 때문일 것입니다.

<br>

-   **(NEXT K?)** k-pop, k-beauty가 현 한류라고 생각하는데 혹시 다음 k가 붙을 문화는 무엇이라고 예측하시나요?

-   K-POP이 세계적으로 확산되면서 한국의 콘텐츠 산업이 겪게 된 도전과 기회는 무엇이 있나요?

-   K-pop의 시장 가치가 국내외로 높게 인정받고 있는데, 왜 엔터사의 평균 보수는 (대기업에 준하는 정도로) 높은 편이 아닌지 궁금합니다.

> 한류의 새로운 미래는 FOOD라 생각합니다. 이제 먹거리에 대한 관심이 높아지고 있습니다. 진정으로 음식 문화에 대한 세계인의 관심이 전지구적으로 높아지고 있으며, 냉동 김밥, 만두, 김치 등에 대한 수요가 확산되고 있는 것이 시장에서도 관찰됩니다.
>
> 엔터사의 평균 보수.... 는 계약직의 한계로서 방송사 계약 구조.... 의 불공정성 때문입니다. 이 모든 것들은 선배들의 잘못된 관행과 시장의 불균형성 때문입니다. 여러분들이 조금씩 바꿔나갈 수 있기를 고대해봅니다. 미안합니다. \^\^;;

<br>

**디지털 시대의 콘텐츠 소비와 팬덤의 변화**

-   메타버스는 어떤 모양으로 발전하게 될까? 메타버스가 발전을 거듭나면, 언젠가 메타버스가 우리의 일상이 될 수 있을까?

-   메타버스를 통한 K-pop의 가능성은 아이돌 그룹의 온라인 플랫폼 활성화 등을 통해 입증되고 있는 것 같습니다. 앞으로 이런 플랫폼을 비롯한 산업 전반이 글로벌적 관점에서 어떻게 변화할지 궁금합니다.

-   점점 기술이 접목되고 있는 한류 시장에서 팬들이 이를 진정으로 선호할 수 있을까? 이에 따른 매출 변화에 어떻게 대응할 수 있을까? (ex. 에스파의 컨셉에 불호가 있었음)

-   플레이브의 성공요인, 그리고 플레이브와 같은 가상 아이돌이 지속적으로 성공할 수 있을지에 대한 교수님의 인사이트가 궁금합니다.

> 메타버스는 아직 놀이문화 중심으로 크게 자리잡지 못한 느낌입니다. VR/AR 시장이 정착되지 못한 것은 크게 두 가지 이유라고 생각되는데, 하나는 일상에서의 불편함(착용, 사용의 불편함 – 배터리 문제, 무게감, 이질감 등), 다른 하나는 충분한 앱의 부재 두 가지 이유라 사료됩니다. 반면 마이너한 한류 팬덤 시장에서 이를 접목할 수 있을 것인가에서, 반은 회의적이고, 반은 희망적일 수 있습니다. 국내 OTT 시장에서 유일하게 흑자를 내는 것이 바로 애니매이션 OTT 플랫폼입니다. 마이너한 플랫폼 소구층에서 독자적으로 소비층을 확보해낸다면 이를 시장으로 만들어내는 힘이 생기듯, 메타버스 시장도 충분히 확보해낼 수 있을 것입니다.
>
> 플레이브, 저는 그 선조격인 아담... 부터 알던 세대로서, 다소간에 회의적이긴 합니다. 그럼에도 일본에서는 버츄얼 아이돌이 성공하고(최근 도쿄 출장을 다녀왔는데, 거리에서도, 또 모바일로 소비하는 사람들의 모습에서도 충분히 그 시장과 수요를 짐작할 수 있을 정도였습니다) 확장하는 모습을 볼 때 한국에서도 가능성을 점칠 수 있었습니다. 다만 한국에서는 보다 즉물적이고 현실적인 것들을 쫓는 인상이 강합니다. 한국의 감각적인 것들, 강렬한 것들을 찾는 민족성과 맞닿은 것이 아닐까 개인적으로 생각해 봅니다. 따라서 플레이브의 성공 그 다음을 짐작하기란 대단히 힘듭니다만, 그럼에도 보다 감각적이면서 더 즉물적인 무언가를 소구할 수 있는 가상의 아이돌이라면 소비할 수용자가 있지 않을까 짐작해 봅니다.

<br>

**OTT 와 진로**

-   ott 플랫폼으로 한국 작품도 많이 국제적인 사랑을 받고 있다고 생각하는데, ott 관련해서 진로를 결정한다면 어떤 준비를 하면 좋을까요?"

> ‘한국 OTT 시청자의 OK를 받으면, 전세계에서 OK다’라는 우스갯소리가 있다고 합니다. 그만큼 한국 시장의 시청자 눈이 높습니다. 콘텐츠 큐레이터, 기획자, 플랫폼 중개업, 심지어는 카피라이터와 OTT 포스터 디자이너, OTT 플랫폼 유튜브 콘텐츠 관리자 까지 다양한 2차, 3차 생산자 영역까지 크리에이터 영역이 펼집니다. 컬쳐 앤 테크놀로지 분야의 전공자들이 뛰어들 수 있는 영토가 더욱 넓어지고 있습니다.
