---
title: "데이터 시각화의 예술"
subtitle: "전서연" 
Week: 7
format: html
slide-format: revealjs
---

[Weekly content](https://changjunlee.com/teaching/cul_tech_101/weekly_2/)

<br>

수업에 참석하기 전, 아래 활동을 완료하시기 바랍니다:

1.  pre-class video 시청

2.  Discussion 제출 (pre-class 내용과 Question)

    -   Submission due: 수업전 일요일 자정까지

<br>

#### **Week 7: 데이터 시각화의 예술**

-   Date: 20240416

-   Pre-class video

    -   The beauty of data visualization - David McCandless

    {{< video https://www.youtube.com/watch?v=5Zg-C8AAIGg >}}

    -   Data Visualization Best Practices - Stephanie Evergreen

    {{< video https://www.youtube.com/watch?v=zrRPszgMK08 >}}

<br>

-   Discussion

<br>

<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSdFI8iFJg1vHZo-ugESun8Yjtr5bvOWZ76FzU2d4pXJcN6D1A/viewform?embedded=true" width="640" height="988" frameborder="0" marginheight="0" marginwidth="0">

로드 중…

</iframe>

------------------------------------------------------------------------

### Best Discussion

#### #1

> 고등학교 때부터 정보라는 과목이 정식으로 생기면서 배운 경험이 있습니다. 그 때 엑셀 활용 방법을 배우면서 데이터 자료를 정리하는 방법을 배웠습니다. 네이터 검색 데이터를 활용한 그래프 만들기를 했었는데, 그 때 네이터 검색 키워드로 데이터가 정렬되는 모습을 보며 현대 사회에서는 사람들을 군집으로 분류하기 편리해졌다고 생각했습니다. 저는 그 때, 우산의 검색량이 가장 높아지는 달은? 이라는 주제로 과제를 진행했고 7, 8월이 가장 압도적일 것이라 예상했는데 결과는 의외로 3월 혹은 6월이 많았습니다. 함께 검색된 키워드 데이터를 통해 봄비 혹은 장마를 대비하기 위해서라는 이유를 얻었습니다. 이처럼 현대 사회에서는 데이터의 시각화를 통해 사회 현상을 읽을 수 있으며 이제는 이를 상업적으로 이용해야지만 살아남을 수 있겠다는 생각을 했습니다.
>
> 또한 영상을 통해 증거의 등급을 매길 수 있다는 점을 새롭게 알게 되었습니다. 사실 저는 데이터 시각화는 사람들의 주관적인 생각을 시각화했다고 생각했습니다. 그래서 많이 나올 수록 무조건 좋은 게 아니라고 생각했습니다. 물론 증거의 등급을 나눈다고 해서 많이 나온 데이터가 무조건 옳고, 좋은 것은 아니지만 좀 더 신뢰를 가질 수 있을 것이라 생각합니다. 앞으로도 데이터 시각화에 대해 좀 더 편리하고 보다 정확한 기술이 나온다면 자료 수집 과정에서 시간을 상당히 줄일 수 있을 것이라 예상합니다.

<br>

> 데이터 시각화는 영상에서 설명하는 것과 같이 복잡한 데이터를 이해하기 쉽고, 효과적으로 사람들에게 전달하는 수단인 것 같습니다. 데이터를 시각화하는 가장 기초적인 방법은 차트나 그래프 등이 있습니다. 이는 우리가 접하기 가장 쉬운 방법 중 하나인데요, 영상에서 나온 것과 같이 다양한 디자인과 패턴으로도 시각화가 가능하다는 것을 새롭게 알게되었습니다. 작년 2학기 때 구글 코랩으로 데이터를 시각화하는 법을 배웠었는데요, 그 당시에도 그냥 숫자로만 데이터를 보는 것보다 시각화하는 것이 데이터를 습득하는 데 더 많은 도움이 된다고 생각했었습니다. 오늘 영상 시청 후, 아트에 관심이 있는 저는, 앞으로 데이터를 시각화하는 데에 있어 디자인과 패턴 등이 얼마나 더 다양해질 지 궁금해졌습니다.

<br>

> 저는 데이터 시각화에 대해 더 깊이 이해하게 되었습니다. 데이터 시각화는 단순히 데이터를 제시하는 것이 아니라 예술과 과학의 결합이기도 합니다. 복잡한 데이터를 단순화하고 추세와 패턴을 강조하며 데이터 스토리를 설명하고 탐색을 지원하고 비교를 촉진하여 복잡한 정보를 효과적으로 전달할 수 있습니다. 데이터 시각화의 목적은 데이터를 표시하는 것뿐만 아니라 시각적 효과를 통해 일관된 이야기를 전달하고 청중이 논리적 순서로 주요 통찰력을 이해하도록 안내하는 것입니다. 대화형 시각화는 청중에게 자신의 관심사와 필요에 따라 관련 통찰력을 찾을 수 있는 독립적인 데이터 탐색 기회를 제공합니다. 이 정보 폭발의 시대에 데이터 시각화는 중요한 의사소통 도구가 되었습니다.간결하고 명확하며 적절한 시각화 유형 선택과 데이터 스토리텔링.. 탐색 지원 및 비교 촉진과 같은 모범 사례를 준수함으로써 데이터의 아름다움을 더 잘 발견하고 데이터를 더 깊이 이해하고 활용하며 의사 결정과 행동에 대한 보다 강력한 지원을 제공할 수 있습니다.

#### #2

> 이 영상에서는 데이터 전문가가 사용하는 데이터 시각화 툴에 대해 많이 배우게 되었던 것 같습니다. QuickBooks Online부터 Excel과 Tableau까지 정말 많은 시각화 툴이 발전되고 있으며, 더불어 많은 회사들도 해당 툴을 활용하여 경영을 발전하는 트렌드를 보이고 있는 점이 신선했습니다(Salesforce, Survey Monkey 등). 해외 회사 말고 국내 회사들은 어떤 시각화 툴을 사용하고 있는지 궁금증이 들게되었습니다! 더불어 영상을 보면서 데이터 시각화에 대해 조금 친근함을 느끼게 되었습니다. 어릴 때 자주했던 마인드 맵이나 to do list 작성 등등, 이 모든 것들도 나의 머릿 속 정보들을 시각화하여 정리하는 것이라고 말해주는 작가의 말 한마디 덕에, 멀게만 느껴졌던 데이터 시각화가 생각보다 우리의 삶 가까이에 활용되고 있었음을 새삼 깨닫게 되었습니다!

<br>

> 데이터 시각화에 인간의 개입이 중요하다고 밝힌 점이 인상깊었다. 결국 시각화 결과물을 받아들이는 자는 인간이기에, 인간이 보기 용이하려면 당연히 인간의 개입이 중요할 수밖에 없으리라는 생각이 든다. 그러나 이렇게 당연한 점이 중요하게 작용하는 이유는, 다양한 기술이 활성화된 이 시대에, 그저 자동화된 프로그램이나 생성형 AI 등 시각화 툴이 그려주는 데이터 형상들을 정제 없이 그대로 받아들인다면 데이터에 대한 주도적인 인사이트를 얻지 못할 가능성이 매우 크기 때문이다. 인간이 스스로 시각화를 할 만한 가치가 있는 데이터의 특성들을 선택할 수 있는 능력을 가지고 있어야 사회에 필요한 요소들을 시각적으로 바로 받아들일 수 있기 때문이다.

<br>

### Best Questions

**1. 데이터 시각화의 한계와 가능성에 대한 깊은 고민**

데이터 시각화를 통해 일어난 일들을 분석하고, 앞으로 일어나는 일에 대해 추측하는부분에 있어 도움을 주는 것은 사실입니다. 하지만 역사를 보면 알 수 있듯이 생각지도 못한 일들이 우리 가운데에 일어나고 변화와 혁신을 주기도 합니다. 이러한 부분에서 데이터 시각화가 오히려 혁신을 불러일으키는 데에 방해를 줄 수도 있을 것이라 생각이 드는데, 어떻게 하면 혁신을 가로막지 않으면서도 데이터 시각화를 통해 영감을 줄 수 있을지 궁금합니다.

<br>

**2. 데이터 시각화의 목적에 대한 의문 제기로 출발점과 목적을 다시 생각하게 만드는 질문**

사회에서 데이터를 활용하는 것이 일반화되기까지 얼마 되지 않았다고 생각하는데, 데이터 시각화가 시작된 계기가 궁금합니다. 어떤 것에 활용하기 위해 시작되었나요?

데이터는 사람들에 의해 형성이 된다고 하잖아요. 근데 반대로 데이터에 의해 만들어지는 사회 흐름, 상황으로 인해 사람들이 따라가는 것은 아닌가요? 예를 들어, 어떤 신규 카페의 검색량이 높아져 이 카페가 인기 카페로 분류되고, 사람들이 많이 방문하는 것처럼 말입니다. 만약 아니라고 해도 앞으로도 그러지 않을 것이라고 생각하시나요?

<br>

**3. 데이터 시각화의 신뢰성에 대한 중요한 이슈**

1\. 사전 영상을 보고 나서 데이터 시각화에 대한 회의감이 좀 많이 들었던 것 같습니다. 두 영상의 작가는 모두 우리가 데이터를 통해 얻고자 하는 답과 통찰력만 가지고 있다면, 그것에 맞춰서 데이터를 시각화할 수 있다고 합니다.

의도적으로 일부 데이터를 시각화 단계에서 제외를 하거나, 왜곡하는 방향으로 시각화 차트를 만들 수도 있어 오히려 의사결정에 혼란을 줄 수 있다면, 데이터는 일부 중요한 의사결정자에게만 공개하는게 낫지 않을까요?

데이터를 시각화를 하는 것이 진실을 알려주기보다는 많은 사람에게 나의 의견을 뒷받침받기 위한 전략으로 보입니다.모든 사람들에게 시각화된 데이터를 공개를 해야하는 이유는 무엇인가요?

2\. 영상은 해외 데이터 전문가가 강연을 하여서 해외에서 사용하는 시각화 툴을 많이 알려주었다. 국내에서는 어떤 시각화 툴이 유행을 하고 있는지, 시각화를 전문적으로 하는 기업이 있는지, 교수님께서 눈여겨 보는 시각화 트렌드가 있는지 궁금증이 들게되었습니다!
