---
title: "문화콘텐츠와 자연어 처리"
subtitle: "구영은" 
Week: 8
format: html
slide-format: revealjs
---

[Weekly content](https://changjunlee.com/teaching/cul_tech_101/weekly_2/)

<br>

수업에 참석하기 전, 아래 활동을 완료하시기 바랍니다:

1.  pre-class video 시청

2.  Discussion 제출 (pre-class 내용과 Question)

    -   Submission due: 수업전 일요일 자정까지

<br>

#### **Week 8: 문화콘텐츠와 자연어 처리**

-   Date: 20240423

-   Pre-class video

    -   Text 데이터를 활용한 개인화 음악 추천서비스 웹 데모 구축 (혁신성장청년인재양성사업 프로젝트 발표)

    {{< video https://www.youtube.com/watch?v=GLCvewkD8uk >}}

    -   \[TED\] Why can't AI 'think' like us?

    {{< video https://www.youtube.com/watch?v=wvupyiFq1Js >}}

    -   \[TED\] The language of computational linguistics.

    {{< video https://www.youtube.com/watch?v=NkOO6n0pZIU >}}

    -   \[엔씨소프트\] 장애인의 목소리가 되어주는 AI 기술

    {{< video https://www.youtube.com/watch?v=ae-yuvyhwtc >}}

    -   \[노마드코더\] 민트 초코 논란! 자연어 처리(NLP)로 종결해드림.

    {{< video https://www.youtube.com/watch?v=QTgRNer2epE >}}

<br>

-   Discussion

<br>

<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSf3C0wOA_iO7biU5IN2K2jTAGuXBvqUnMboit4bmUjoo-4Q9g/viewform?embedded=true" width="640" height="964" frameborder="0" marginheight="0" marginwidth="0">

로드 중…

</iframe>

------------------------------------------------------------------------

### Best Discussion

> 넷플릭스에서 collaborative filtering을 통해 영화 추천을 한다는 것을 알고 있었습니다. 이 기술을 음악 스트리밍 플랫폼에서 진행한다면 좀 더 다양한 장르를 접할 수 있다고 생각했습니다. 개인적으로 저는 영화보다 노래를 다양하게 즐기기 어렵다고 생각합니다. 그 이유는 영화는 상영관에서 상영하는 영화를 보고 고를 수 있고 또 스토리가 있기 때문에 대부분 SF가 아닌 이상 이해하는 데에만 집중할 수 있기 때문입니다. 그러나 음악은 락, 인디밴드, 발라드 등 정말 많은 장르가 있고 이는 취향이 확고하게 드러난다고 생각합니다. 그래서 collaborative filtering이 적용된다면 개인 취향이 아닌 것 같아 도전하지 못했던 노래들도 쉽게 접할 수 있지 않을까 생각했습니다.
>
> 제가 FLO 앱을 사용하는데, 그 앱은 '3월 4일에 들은 노래와 비슷한 플레이리스트' 이렇게 추천을 해주곤 합니다. 저는 이 기능이 정말 좋았던 게, 이런 노래 장르를 좀 더 들어보고 싶다고 생각한 찰나에 비슷한 느낌의 노래를 찾지 않아도 접할 수 있었기 때문입니다. 개인화된 맞춤 서비스가 더 강해질 수록 확증편향이 강해진다고 생각했는데 그 안에서 다른 길로 뚫릴 수도 있겠다고 생각했습니다.

<br>

> 1번 - 제한된 데이터로 유저의 의도를 파악했다고 했는데 이 과정에서 정보의 왜곡이 일어날 수 있지 않을까 라는 생각이 들었습니다. 자료가 적다보니 조금의 분석 방향이 달라질 경우, 전체 분석의 의도, 흐름이 달라질 수 있을 것 같은데, 이런 경우 어떤 식으로 보안이 가능할까요? 인기상품, 컨텐츠 필터링, 유저를 통한 필터링 총 세가지를 영상에서 이야기 해줬는데 이러한 알고리즘이 꽤 도움이 될 것이라는 생각이 들었습니다. 다만 이미 에플뮤직, 멜론, 유튜브 뮤직 사이트에서 비슷한 알고리즘을 사용하고 있다고 체감했고, 따라서 현행 알고리즘과 차이점을 느끼지 못했던 것 같습니다.
>
> 4번 - AI 음성을 탑재한 기술을 통해 단일한 톤이 아닌, 사람의 말투, 억양 등을 담고 있는 목소리 기술이 상당히 도움이 많이 될 것이라는 것을 깨달았습니다. 평소 사람과 사람 사이의 말에서 중요한 요소 중 하나가 목소리의 억양, 말투, 톤이라고 생각했는데 이런 것을 장애인의 목소리가 되어주는 그러한 목소리에서 고려하지 못했다는 점에 스스로의 생각이 짧았던 것 같습니다. AI의 기술의 발달도 모든 사람들이 향유할 수 있는, 그런 베리어 프리적인 기술이 되었으면 좋겠다는 생각이 들었습니다. 기술의 발달이 어떤 사람은 포함되고 포함되지 않는, 불공평한 분야갸 되지 않았으면 좋겠다는 생각을 하게 되었습니다.

<br>

> (두 번째 영상) Generalization is not the reality. 영상 속 작가의 이 한 마디는 아무리 AI가 발전하더라도 철학 인문 계열의 전문가는 사라지지 않을 수 있겠다는 희망을 주었습니다. AI는 세상에 공개되어있는 대부분의 사람들이 바라보는 세상을 학습합니다. 하지만 과연 다수가 바라보는 시각이 항상 옳을까요? 우리는 데이터와 알고리즘을 창조하는 동시에 영향을 받기도 합니다. 바쁘게 변해가는 사회 속에서 우리가 구축한 인공지능에게 압도당하거나 휩쓸리지 않기 위해서는, 서로 올바른 영향을 주고 받기 위해서는 인문 계열의 전문가가 끊임없이 세상의 정의에 대해 철학적으로 탐구해야 겠다고 생각했습니다.

<br>

> 2번영상과 3번 영상에서 일관되게 AI는 인간과 사고하는 방식이 다르다고 말하고 있다. 이부분이 인상적이고 너무 공감됐다. 물론 기술이 발전하면서 AI가 학습한 데이터의 양은 기하급수적으로 늘고 있지만 여전히 부족한 것이 사실이며, 과연 인간의 사고방식을 온전히 구현할 수 있을지에 대한 현실적 의문이 든다.
>
> 이와 관련해 개인적으로 최근에 겪었던 재미있는 이야기를 해보자면, 수업을 같이 듣는 친구들끼리 개설된 단톡방이있는데, 평소에 서로의 이름에 \~튜브(에: 홍길동 - 길동튜브/홍튜브)를 붙여 부른다. 카카오톡에서도 그렇게 부르면서 이야기를 떨고 있는데 어느 한 친구가 카카오톡 AI 대화요약 기능을 사용한 결과가 재미있다며 캡쳐해서 보내줬다. 그 결과는 “튜브에 관련된 무의미한 대화”였다.
>
> 데이터가 많이 학습된건 사실이지만, 특정 집단에서 맥락에 맞춰 쓰이는 단어들을 AI는가이해하지 못하고 있는 것이다. 인간의 언어는 결국 약속에 의한 것인데 AI는 그 약속을 지키는 것처럼 모방하는 것일 뿐이지, 약속을 이해하지는 못한다고 생각한다.

<br>

> AI를 어디까지나 인간을 보조하기 위한 수단, 있으면 좋고 없으면 마는, 그런 존재라고 생각해왔다. 하지만 장애인을 위핸 “나의 ACC”앱을 보면서 누군가에게는 AI가 반드시 필요할 수도, 새로운 기회를 주는 것일 수도 있다는 생각이 들었다.
>
> 또한 기술을 가진 이들과 그렇지 못한 이들의 격차가 마치 자연의 순리처럼 당연하게 여겨지는 사회에서 이런 사례들은 그래도 우리 사회가 아직은 어둡지만은 않다는 생각이 들게한다. “배워서 남주랴?” 이제는 다 옛 말이다. 이제는 배워서 남을 주는 것이 남을 위한 길이기도 하고 새로운 영역을 개척하는 나의 길이기도 한 것 같다.

<br>

> \[엔씨소프트\] 장애인의 목소리가 되어주는 AI 기술
>
> 영상을 통해 AAC라는 의사소통 툴을 처음 알게되었습니다. 2015년에 서비스가 제작되었지만, 이제 알았다는 점이 아주 조금은 부끄럽기도 합니다. 의사소통은 사람과 사람간의 소통인데 의사소통에 어려움을 겪는 분들께 이러한 서비스는 정말 많은 도움이 될 것 같다는 생각이 듭니다. 또한 리뉴얼된 버전이 소통을 하며 감정을 전달하는 데에 있어 훨씬 더 잘 될 것 같고 어려움을 겪는 이들의 삶의 질을 향상시켜준다는 생각이 듭니다. 본 영상을 시청한 모두가, 그리고 '나의 AAC'라는 어플을 알고 있는 사람들이 어플을 설치한다면, 앞으로 세상을 살면서 마주할 의사소통에 어려움을 겪는 이들과 조금 더 원활한 소통을 할 수 있을 것이라 예상한다.

<br>

### Best Questions
