---
title: "가상/증강현실 콘텐츠 제작"
subtitle: "김태원" 
Week: 12
format: html
slide-format: revealjs
resources: 
  - "content/cnt_w12.m4a"
---

[Weekly content](https://changjunlee.com/teaching/cul_tech_101/weekly_2/)

<br>

수업에 참석하기 전, 아래 활동을 완료하시기 바랍니다:

1.  pre-class video 시청

2.  Discussion 제출 (pre-class 내용과 Question)

    -   Submission due: 수업전 일요일 자정까지


<br>

#### **Week 12: 가상/증강현실 콘텐츠 제작**

-   Date: 20240521

-   수업 녹음 자료 (For 예비군 수강생)

<audio controls src="content/cnt_w12.m4a"></audio>

<br>

-   Pre-class video

    -   상상이 현실화가 되는 세계, 그 중심에 서서 외치다 \| 서동일 오큘러스VR코리아 지사장

    {{< video https://www.youtube.com/watch?v=CTLHkFRq4Mk >}}

    -   What is extended reality? \| The Gadget Show

    {{< video https://www.youtube.com/watch?v=wr6t5_qxxx4 >}}
    
    -   소아암, 장기치료 어린이를 위한 디지털 테마파크 \| RGB MAKERS
    {{< video https://www.youtube.com/watch?v=7cEOudNRGc8 >}}


<br>


-   아래 영상들은 RGB MAKERS 사에서 제작한 작품들입니다. 


    -   2021 CSR 필름 페스티벌-희망 나눔 부문(보건복지부장관상) 수상작
    {{< video https://www.youtube.com/watch?v=QrYHB45bv8M >}}

    -   Tabernacle; Realistic Bible Experience Contents
    {{< video https://www.youtube.com/watch?v=_KmwGOkxYnc >}}
    
    -   김태원 대표님 수업을 통해 학생들이 제작한 영상: healing planet metaverse space makers
    {{< video https://www.youtube.com/watch?v=aFWmUWElAAc >}}

<br>

-   Discussion

<br>

<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSeUaEXFUH19I7W77OBzSG1anwVxZGau_QSuGbSiIO-xh6WlRA/viewform?embedded=true" width="640" height="1146" frameborder="0" marginheight="0" marginwidth="0">로드 중…</iframe>



------------------------------------------------------------------------

### Best Discussion

> 
1) 
이 영상은 12주간 내가 봤던 모든 사전 영상 중 가장 흥미로운 영상이었다. 나는 이제껏 인간이 가상의 공간에 침투하는 것은 봐왔지만, 가상의 것이 현실로 구현되는 것은 처음 봤기에 더욱 신선하였다. 가상/증강 현실로 없는 공간을 창작하고, LED가 설치되지 않은 곳까지 확장하여 가상 현실을 확장하고, 가상 현실에 멀리있는 사람이나 존재하지 않은 사물을 불러올 수 있었다. 어릴 적 본 <레디플레이어 원>이라는 영화가 생각날 정도로 세상은 생각보다 더욱 고도화된 기술력을 가지고 있었다. 하지만 가장 충격이었던 점은 이 영상이 무려 3년 전 영상이라는 것이다. 3년이 지난 지금은 어느 정도로 기술이 발전하였을까? XR기술을 직접 체험해보고 싶다고 생각하게 되는 영상이었다. 
2)
이 영상은 12주간 내가 봤던 모든 사전 영상 중 가장 흥미로운 영상이었다. 나는 이제껏 인간이 가상의 공간에 침투하는 것은 봐왔지만, 가상의 것이 현실로 구현되는 것은 처음 봤기에 더욱 신선하였다. 가상/증강 현실로 없는 공간을 창작하고, LED가 설치되지 않은 곳까지 확장하여 가상 현실을 확장하고, 가상 현실에 멀리있는 사람이나 존재하지 않은 사물을 불러올 수 있었다. 어릴 적 본 <레디플레이어 원>이라는 영화가 생각날 정도로 세상은 생각보다 더욱 고도화된 기술력을 가지고 있었다. 하지만 가장 충격이었던 점은 이 영상이 무려 3년 전 영상이라는 것이다. 3년이 지난 지금은 어느 정도로 기술이 발전하였을까? XR기술을 직접 체험해보고 싶다고 생각하게 되는 영상이었다. 첫 번째 영상에서, 서동일 사장님은 VR이 우리에게 어릴 적 이루지 못한 꿈을 이루게 해줄 것이라고 말하였다. 어릴 때부터 나는 런닝맨과 1박2일과 같은 방송을 보면서, 방송용 레크레이션 게임을 창작해보고 싶다는 생각을 하였지만, 방송 업계가 많이 저물면서 나는 자연스럽게 나의 꿈을 접게 되었다. 사실 IT기술이 점점 우리 사회에 스며들면서, 나라는 사람이 무엇을 할 수 있는지에 대해 고민하는 과정을 계속해서 반복해왔다. 내가 할 수 있는 일은 인공지능이 훨씬 더 빠르고 정확하게 처리해주기에, 나라는 사람이 쓸모가 있는 분야가 있을까라는 회의감도 들었었다.
3)
이 영상은 이러한 나의 고민을 타파하였다. 방송용 게임에서 VR 게임으로 시각을 전환하니, 소비자들이 흥미를 느낄만한 콘텐츠를 새롭게 기획하는 것은 결국 인간의 영역이겠구나 생각하였다.영상에서 소아암 환자를 타겟으로 어린아이의 시각에 맞게 테마파크, 총게임, 롤러코스터 등의 콘텐츠를 제작하는 것을 보면서, 나라면 어떤 식의 게임을 기획하였을지 생각하게 되었다. VR 콘텐츠 크리에이터라는 직업에 대해 희망을 가지게 되면서 어릴 적 꿈을 실현해보고 싶다는 희망을 가지게 되었다. 

<br>

> 2)
가상 환경을 구축하는 것은 단순히 초록 배경에서 디자인 그래픽을 입힌 것이라고 생각했는데 LED를 이용해 입체적으로 가상 환경을 구축하는 것을 보며 신기했습니다.언젠가 모든 TV쇼가 저 기술을 활용하여 배경을 구축할 수 있지 않을까 생각했습니다. 조금 다른 이야기일 수 있지만 최근에 종방한 눈물의 여왕이라는 드리마에서도 AI를 활용하여 눈이 오는 배경을 만들어냈다고 했습니다. 이제는 촬영지를 찾으러 다니지 않아도 원하는 배경을 보다 정확하게 구현할 수 있으니 효율적이라고 생각합니다.
3)
아이들이 좋아하는 모습을 보면서 저도 모르게 흐뭇해졌습니다. 문득 이 영상을 보다가 어르신분들이 떠올랐습니다. 매장에 거의 대부분이 키오스크로 주문을 하는데, 어르신분들께 키오스크를 하는 상황을 VR로 제작하여 연습해보도록 만드는 상품은 어떨까 생각해보았습니다. 그렇다면 직접 가서 키오스크를 이용하는 데에 조금이라도 어려움을 덜어드릴 수 있지 않을까 생각했습니다. 사회의 어려움, 문제를 해결하기 위해 재밌는 방법으로 해결할 수 있는 것도 VR의 기능이구나 느꼈습니다.

<br>

> 상상이 현실화되는 세계는 매우 독특하고 환상적인 개념입니다. 이러한 세계에서는 개인의 생각과 꿈이 현실의 형태로 나타나므로, 이는 인간의 창의력과 내면의 욕망을 물리적인 현실로 전환시키는 능력을 부여합니다. 상상력이 현실이 되는 이 세계에서는 무한한 가능성과 동시에 예측 불가능한 위험들이 존재합니다.
두번째 영상을 통해서 가상 세계 기술은 교육 분야에서도 엄청난 잠재력을 보여주습니다. 가상 현실 기술을 통해 학생들은 전 세계의 역사 유적지를 탐방하거나 우주의 신비를 탐험하거나 심지어 인체 내부를 공부하는 등 다양한 학습을 할 수 있습니다. 이러한 몰입형 학습 방식은 학생들의 학습 흥미를 높일 뿐만 아니라, 지식에 대한 이해도를 깊게 합니다.
생병에 걸린 아이들이 AR 등 기술을 통해 즐겁게 노는 모습을 보니, 나도 진심으로 기쁩니다. 기술의 발전은 단순히 오락을 넘어서, 병마와 싸우는 아이들에게 희망과 웃음을 선사합니다. 병원이라는 제한된 공간에서 아이들은 가상 현실을 통해 다양한 세상을 탐험하고, 그들의 상상력을 자유롭게 펼칠 수 있습니다. 이 과정에서 아이들은 잠시나마 고통을 잊고, 순수한 기쁨을 느낄 수 있습니다. 이러한 모습을 보면서, 기술이 사람들에게 줄 수 있는 긍정적인 영향력에 대해 다시금 깨닫게 됩니다. 아이들이 건강하게 자라날 수 있도록, 그리고 그들이 더 많은 행복을 느낄 수 있도록 도와주는 기술의 힘에 감사함을 느낍니다.

<br>

> Make people to experience impossible!라는 목적 자체가 사람들에게 다양한 경험을 제공할 수 있고 여러가지 중요한 의미를 내포하고 있는 것 같습니다. 우선 이 목적은 사용자들에게 일상적인 한계를 뛰어넘는 새로운 경험을 제공합니다. 또한 소비자들이 현실에서 경험할 수 없는 상황, 장소, 또는 감정을 가상현실을 통해 체험하게 한다는 것은 소비자들의 만족도를 높이고 더 많은 관심과 참여를 유도할 수 있을 것 같습니다. 앞으로의 기술 발전을 통해 가능해질 새로운 경험에는 어떤 것들이 새롭게 생길지에 대한 궁금증을 유발하는 영상이었던 것 같습니다.
XR기술은 실제와 가상세계를 융합한 것이다. 화면을 보며 바닥에 있는 타이어를 가리키거나 보는 것이 가능한 것과 같이 가상환경과 실제환경이 함께 상호작용하다. 또한, 소형 스튜디오 공간만 있어도 몰입할 수 있는 가상환경을 화면 상에도 더 크게 만들 수 있다는 이점이 있다. 그만큼, XR 기술의 발전은 가상환경과 실제환경의 연결을 도울 수 있다는 점을 알 수 있었다. 
이러한 디지털 테마파크는 고통을 참고 있는 아이들의 힘든 시간을 조금이나마 즐겁게, 잠시나마 아이들의 아픔을 잊게 해줄 수 있는 좋은 아이디어인 것 같다고 느껴졌습니다. 영상에서 보이는 게임에 집중하는 아이들의 모습은 너무나도 사랑스럽습니다.

<br>

> 이 영상을 통해 가상현실의 필요성과 가능성에 대해 생각하게 되었다. 인간 대신 기계에게 일을 시킬 수 있도록하는 에너지 발전기나 공장 등 일상 속 필수적인 기술과 달리 가상 현실은 버추얼휴먼처럼 우리에게 꼭 필요한 것인지 이것이 어디에 쓰일 수 있을지 감이 잘 안 잡힌다. 그런데 돈, 시간, 두려움, 건강 등으로 인한 현실 속 제약에서 벗어나 꿈을 간접적으로나마 이룰 수 있게 해준다는 점에 있어 다양한 가능성이 존재하는 분야임을 알게 되었다. 가상현실을 구현하는 기술뿐만 아니라 이 기술을 어떤 식으로 활용할 수 있을지 상상하는 것이 중요한 것 같다. XR(확장 현실)이 구현되는 방식을 간단하게나마 시각적으로 볼 수 있었다. 또한 가상현실 관련 기술을 생각했을 때, 단순 가상현실이나 현실 세계에 가상의 요소를 덧입힌 증강현실 정도만 생각했는데, 이 모든 기술을 결합한 XR에 대해 좀 더 배울 수 있었다. 마커를 통해 가상의 물체도 실시간으로 움직이는 기술이 정말 인상깊었고, 좀 더 구체적인 기술의 메커니즘을 배워보고 싶다는 열망이 생겼다. 
첫 번째 영상에서 언급한 메시지 중 하나가 구현된 한 가지 예시가 이 영상에 나왔다. 건강이라는 제약 조건에 의해 놀이공원이나 신체 놀이 등을 하기 힘든 소아암 어린이들이 가상현실 기술을 통해 간접적이지만 정말 실감 나게 디지털 테마파크를 체험할 수 있는 것이 정말 의미가 있다고 느꼈다. 실제 놀이공원을 마음 껏 갈 수 있는 사람이라면 디지털 테마파크에 큰 흥미를 못 느낄 수도 있지만, 병원을 벗어나기 힘든 장기 치료 어린이들에게 디지털 테마파크는 훨씬 큰 의미를 가질 수 있겠다는 생각을 했다. 이렇게 제약을 갖고 있는 사람들과 상황들을 관찰해서 해당 기술의 순기능을 발휘하는 것이 중요하다고 본다. 

<br>


### Best Questions

1.    어린이 소아암 관련 영상을 보면서 단순히 가상 증강 현실 콘텐츠가 사람들의 오락과 여가 시간을 보내기 위한 수단이 아닌 그 이상의 더움이 될 수 있댜는 것을 몸소 깨달을 수 있었습니다. 이러한 가상/ 증강 현실 콘텐츠로 많은 병들을 고칠 수 있을 것 같은데 교수님께서 생각하실 때 어떤 분야의 의료와 접목이 가능하실거라고 생각하시나요? 개인적으로는 정신 질환을 치료하는데고 꽤나 좋은 치료방법으로 사용할 수 있을 것 같다는 생각이 들었습니다.

<br>

2.    코로나19 창궐 당시 가상현실이나 메타버스와 관련한 붐이 잠시 일었다가 소강 상태에 접어든 데에는 감염병 사태가 종국의 단계에 들어선 것도 있겠지만 미진한 기기 보급과도 관련이 있다고 생각합니다. 일반 디스플레이로도 가상현실 콘텐츠의 감상이 불가능한 것은 아니지만 창작자의 의도대로 콘텐츠가 감상되기 위해선 적어도 구글 카드보드라도 쓰는 것이 맞을 터이나 아직까지 많은 사람들이 HMD 장비를 머리에 장착하고 손에 무엇인가 쥐는 행위를 번거롭고 거추장스럽게 여기는 것이 아닌가 생각합니다. 결국 사용자의 경험 향상을 위한 기술 발전의 모멘텀이 필요하다고 보는데 업계에서는 이러한 문제점 해결을 위해 어떤 기술적 노력을 하고 있는지 궁금합니다. 

<br>

3.    가상/증강현실 관련 콘텐츠는 게임이나 여행 등 유흥적인 요소가 현재 우선적으로 활성화되고 산업에 높은 비중을 차지하고 있는 것 같습니다. 이 때, 일반 게임도 과몰입하고 현실 세계와 구분이 안되는 중독 문제가 이슈가 됐었는데, 가상/증강현실 관련 게임은 그 몰입도가 일반 게임에 비해 엄청날 것 같습니다. 그래서 현실 세계와 구분이 안되는 정도는 아니더라도, 더 쉽게 중독되고 현실을 살기보다는 가상현실 속 게임을 계속해서 즐기는 문제도 발생할 수 있을 것 같다는 생각이 들었습니다. 그래서 정부 차원에서는 만약 가상/증강현실이 대중화된다면 게임 관련 규제를 내릴 수 밖에 없을 것 같은데 이에 대한 산업의 대처방안, 중독 문제에 관련된 교수님의 의견이 궁금합니다. 

