---
title: "융합콘텐츠와 창업"
subtitle: "윤영훈" 
Week: 13
format: html
slide-format: revealjs
---

[Weekly content](https://changjunlee.com/teaching/cul_tech_101/weekly_2/)

<br>

수업에 참석하기 전, 아래 활동을 완료하시기 바랍니다:

1.  pre-class video 시청

2.  Discussion 제출 (pre-class 내용과 Question)

    -   Submission due: 수업전 일요일 자정까지


<br>

#### **Week 13: 융합콘텐츠와 창업**

-   Date: 20240528

-   Pre-class video

    -   GPT 있는데 왜 또 만들어요? 손쉽게 이해하는 AI 개발 트렌드와 비하인드

    {{< video https://www.youtube.com/watch?v=clhDOUk3yjU >}}

    -   세상을 바꾸는 뉴콘텐츠

    {{< video https://www.youtube.com/watch?v=WKC7RL3F0kU >}}

    -   콘텐츠 창업에서 가장 중요한 것 \| CEO 노정석

    {{< video https://www.youtube.com/watch?v=gW6WTuaKp6g >}}

<br>

-   Discussion

<br>

<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSdL7tfjtiYGoYGPWvzlw2KAHvtU4XUUFtRZScqiLsE9zAMJxw/viewform?embedded=true" width="640" height="1122" frameborder="0" marginheight="0" marginwidth="0">로드 중…</iframe>





------------------------------------------------------------------------

### Best Discussion

> 
1) 
나는 이 영상을 보기 전까지, AI를 창업에 가져온다는 생각은 너무나도 큰 자본과 기술력이 필요할 것이라는 편견에 휩싸여 생각조차 안했었다.  하지만 수직적 AI라는 개념을 알게 되면서, AI시장에서도 틈새시장이 존재한다는 점을 알게 되었다. 특정 산업 분야에서 문제를 해결하기 위해 AI를 활용하거나 창작하는 것은 생각보다 도전할만하며, 특히 여러 수직적 회사 중 런웨이(runway)라는 회사가 가장 인상깊었다. 


<br>

> 1)
VR과 AR과 MR의 명확한 개념과 실제 적용 사례를 비교하며 의미를 이해할 수 있었다. 그중에서도 흥미로운 것은 VR툰이었다. 드라마 기획자를 꿈꾸는 입장에서, 드라마라는 콘텐츠 역시 VR, AR, MR과 같은 기술요소를 접목시키는 시기가 올 수 있다고 생각하는데, 웹툰 시장에서는 이미 그런 시도가 있다는 점에서 큰 인사이트가 되었다.
웹툰은 스토리를 이미지 단위로 전달하고, VR은 이미지를 실감나게 구현하는 기술이라는 점에서 콘텐츠 특성과 기술 특성이 잘 접목된 것 같다. 다만 드라마는 여러 이미지들이 연결된 장면이 스토리 단위라서, 동일한 접근으로 기술 접목을 하면 부자연스러울 수 있을 것 같다.
드라마 콘텐츠 기획자로서, 드라마의 특성과 기술의 특성을 모두 잘 이해해야 앞으로 드라마 시장에서의 새로운 콘텐츠를 상상하고 실제로 구현해낼 수 있을 것이라 생각한다. 때문에 기술 분야에 대한 심도 깊은 이해가 결국 앞으로의 콘텐츠 기획과 창작에 인사이트가 될 것임을 다시 인지할 수 있었던 영상이었다.
2)  "꾸준히 하나를 하고 싶어도, 큰 거 하나를 이루지 못했기에 끊임없이 도전하는 것이다." 연쇄 창업가를 하는 이유에 대해 솔직하게 발언하신 게 인상적이다.
창업은 돈을 벌어야 하는 것과는 별개로, 계속 상상해내고 상상해낸 것을 구현해내고 구현해낸 것의 한계를 부딪혀야 하고, 그 한계를 계속 버텨내야 하고, 버텨내면서 극복해내야 하는 과정의 연속인 것 같다. 설령 극복이 안 되어도 사명감과 진정성으로 계속 견뎌내야 한다.
나 역시 이전에 청년협동조합 법인을 세우고, 사업자로서 2년 가량 활동하면서 나에 대한 발견을 할 수 있었다. 나는 스스로 창의적이며 창조하는 것을 좋아하는 사람인 줄 알았지만, 그것을 업으로 지속할 만큼의 집념과 진정성이 부족한 사람이었다.
이처럼 창업은 즐거움보다는 고통을 더 자주 느끼게 되는 과정임은 분명하지만, 그만큼 무엇이든 '보게 하는' 기회임도 분명하다. 나 자신에 대해, 또 내가 관심 있던 주제에 대해, 나의 가치관에 대해, 폭넓게는 정말 사회에 대해서도. 뭐든 그전에는 보지 못했던 것을 보게 한다는 점에서, 영상의 발언자와는 다르게 대학생 시절 창업을 도전하는 것을 권장해보고 싶다. 

<br>

> 1)
거대언어모델(LLM)이 중요한 것을 알고 있었지만, 이 영상을 통해 왜 중요한지를 좀 더 구체적으로 알게 되었다. 어떤 분야의 인공지능이던 결국 인간과 소통하려면 인간의 언어를 이해해서 아웃풋을 만들어내거나, 인공지능이 알아낸 정보를 자연어로 표현해야 하기 때문에 인공지능의 코어에 해당하는 것을 이해할 수 있었다. 
2)
AI의 발전으로 인해 일자리가 줄어든다는 부정적인 예측들도 있고, 그것이 일정 부분 맞는 예측이긴 하지만 한 편으로는 개인들이 쉽고 저렴하게 더 퀄리티 있는 콘텐츠나 작업을 할 수 있도록 하는 것도 사실인 것 같다. NC의 LLM을 개발하신 분께서 마지막에 말씀하신 것처럼 인공지능을 활용해서 더 고차원적인 활동을 어떤 식으로 할 수 있을지 상상하고 고민하는 것이 중요한 것 같다. 
구글과 같이 큰 회사에 자신의 회사를 매각하며 큰 성공을 거두었으면서도 끊임없이 창업을 하시는 노정석 CEO님의 열정이 가장 인상깊었다. 사람들은 사업을 단순히 돈벌이 수단으로 여기곤 하지만 하지만 노대표님의 경우 수익 창출 그 이상을 것을 위해 창업을 하시는다는 것을 그 짧은 영상을 통해서도 알 수 있었다. "이건 확실히 올 미래이고, 내가 하지 않으면 아무도 하지 않을 것 같아"라는 정신이 있어야 한다는 말씀을 하셨다. 이러한 생각을 해야 창업을 할 수 있을 것 같고, 이런 생각을 하려면 전문적인 지식과 더불어 시장을 읽는 능력, 보통 사람들이 알아차리지 못하는 문제를 인식하는 통찰력 등이 필요할 것 같다. 

<br>


### Best Questions

1.    AI 기술이 콘텐츠 창작을 어느정도 자동화하고 창의력을 보조하는 도구로 활용될 수 있다는 점이 인상적이었습니다. 이러한 AI 기술을 이용한 콘텐츠 창작이 창업 초기 단계에서 어떤 이점을 제공할 수 있을까요? 또한, 창업을 준비하는 사람들이  AI 기술을 효과적으로 활용하기 위해 고려해야 할 중요한 요소는 무엇인가요?

<br>

2.    창업 시 자신이 하는 일이 성공할 것이라고 확신할 수 있는 방법은 무엇인가요?창업을 준비하는 과정에서 가장 큰 불확실성은 바로 성공 가능성입니다. 많은 시간과 자원을 투자하기 전에, 그 사업 아이디어가 성공할 가능성이 높은지 평가할 수 있는 방법을 알고 싶습니다. 이는 창업자들이 더 나은 의사결정을 하고 리스크를 최소화하는 데 도움이 될 것입니다. 성공 여부를 미리 판단할 수 있는 지표나 방법이 있다면, 창업 과정에서 자신감을 가질 수 있을 것입니다. 




















