---
title: "엔터테인먼트 경영"
subtitle: "이동찬" 
Week: 14
format: html
slide-format: revealjs
---

[Weekly content](https://changjunlee.com/teaching/cul_tech_101/weekly_2/)

<br>

수업에 참석하기 전, 아래 활동을 완료하시기 바랍니다:

1.  pre-class video 시청

2.  Discussion 제출 (pre-class 내용과 Question)

    -   Submission due: 수업전 일요일 자정까지


<br>

#### **Week 14: 엔터테인먼트 경영**

-   Date: 20240604

-   Pre-class video

    -   How Netflix changed entertainment -- and where it's headed \| Reed Hastings

    {{< video https://www.youtube.com/watch?v=LsAN-TEJfN0 >}}
<br>

-   Discussion

<br>

<iframe src="https://docs.google.com/forms/d/e/1FAIpQLScD72iAoT-jP7Nnr889UbC-AKYCIBb1glEGj3mg8dIfupS16A/viewform?embedded=true" width="640" height="831" frameborder="0" marginheight="0" marginwidth="0">로드 중…</iframe>




------------------------------------------------------------------------

### Best Discussion

> 넷플릭스가 현재의 넷플릭스가 되는 과정에서 얼마나 과감하고 혁신적인 결정들을 내려야 했는지 알게 되었다. 초등학생 시절에 잠시 미국에 살았을 때 넷플릭스에서 DVD를 빌려서 보곤 했었는데, 몇년후에 넷플릭스가 스트리밍 서비스로 변신하여 한국을 더불어 전세계에 진출해 있었다. 서비스 사용자 입장에선 단순히 영상을 보는 매체가 DVD에서 인터넷 스트리밍으로 바꼈으니 넷플릭스도 그렇게 바뀐 것이라 생각했는데, 전세계적인 비즈니스가 되기 위해선 미리 시대의 흐름을 읽고, 그 새로운 것을 시도하는 용기가 필요하다는 것을 인터뷰를 통해 알게 되었다. 현재에서 되돌아보면 당연해보이는 것들이 당시에는 전혀 없던 것들(예를 들어 Binge-watching, streaming)이었고, 누군가는 그것을 최초로 사업화했다는 것이다. 
넷플릭스의 문화는 많은 자유와 책임이라고 했다. 모두가 정보를 공유하고, 일부 상사들이 결정하는 것이 아닌 각자가 자유롭게 결정하는 방식이다. 구글이나 넷플릭스와 같은 혁신적이고 전세계적인 기업들의 공통점인 것 같다. 자유에는 책임이 따른다는 말이 있듯, 자유로우면 오히려 많은 지적인 사람들의 책임감 있는 아이디어들을 더 많이 모을 수 있는 것 같다.

<br>

> OTT 서비스에서 오리지널 콘텐츠에 투자하는 이유와 수익 모델에 대해 더 깊게 이해할 수 있었습니다. 다른 회사에 저작권이 있는 작품을 들여와 제공하는 것은 회원을 만족시키는 데에는 도움이 되지만, 넷플릭스라는 브랜드에 대한 인상을 강력하게 만드는 데에는 큰 영향을 주지 않는다고 한 점이 인상깊었고, 이것이 OTT 브랜드에서 오리지널 콘텐츠를 늘려 가고 있는 이유가 될 것 같습니다.
회원제이기 때문에 많은 회원을 유치하는 것이 목표이고,  그렇기 때문에 어떤 작품이 얼마나 더 큰 이익을 주는가를 세세하게 분석하는 것을 많이 중요하지 않다고 여기며 다양한 분위기를 제공하는 것에 초점을 맞추는 점도 뜻밖이었습니다.
그런데 제가 OTT 서비스를 사용해온 방식들을 생각해 보니 강의 내용에 들어맞는 것 같습니다. 저는 넷플릭스를 사용하고 있는데, 넷플릭스가 특정 콘텐츠를 가지고 있기 때문에 이 서비스를 사용하기로 결정한 것이 아니라, 오히려 넷플릭스를 결제했기 때문에 알지도 못했던 다양한 콘텐츠를 새롭게 시청하게 되고, 시청 경험이 계속되니까 회원을 유지하고 있는 것 같습니다. 티빙이나 디즈니 플러스 같은 다른 서비스는 보고 싶은 콘텐츠가 있을 때만 결제하는데, 이 경우 OTT 브랜드 오리지널 시리지였던 경우가 많았습니다... 

<br>

> ranked value와 reavealed value로 사용자의 별점 평가과 실제 시청 경험의 차이를 짚어낸 것이 인상적이었다. 결국 사용자가 '의식'해서 콘텐츠를 평가하는 것과, '무의식'으로 콘텐츠를 시청하는 것은 다른 층위의 가치가 작용한다는 것이다.
놀라운 건 이것을 짚어내고, 바로 서비스에 반영했다는 것이다. 넷플릭스는 기존에 있던 별점 평가 시스템을 제외하고, '좋아요-별로예요' 정도로 평가 시스템을 축소했다. 별점이 사용자의 실제 시청 경험에 유익하지 않다는 것을, 사용자 스스로도 인식하기 전에 먼저 인식하고 적용해서 사용자 경험에 편의를 더한 것이다.
이렇게 인식하고, 그 인식을 바로 반영해내는 결단력이 지금의 넷플릭스를 있게 한 원동력이구나 싶었다.

<br>


### Best Questions

1.    2011년 넷플릭스는 '하우스 오브 카드'에 회사 수익의 상당 부분을 차지하는 1억 달러 가량을 투자했는데, 이는 가히 큰 위험이라고 말할 수 있다. 수익의 상당 부분이면 그 결과가 좋지 않을 때 거의 부도가 날 수 있는데, 결과적으로는 성공했지만 이러한 결정을 내리기 위해서는 어떤 것이 필요할까? 하이 리스크를 겁내 큰 도전을 하지 못할 사람들이 더 많다고 생각되는데, 큰 결심과 올바른 선택을 하기 위해서 필요한 자질과 근거에는 무엇이 있을지에 대해 궁금하다.

<br>

2.    "최근 OTT 업계는 과거와 달리 점차 정체되고 있다고 생각합니다. 넷플릭스에서는 이를 해결하기 위해서 계정 공유 금지 정책을 실시하고 있습니다. 교수님께서는 OTT 업계의 이러한 공유 금지가 더욱 확산할 것으로 전망하실 지 여쭤보고 싶습니다. 또한, 이러한 정책이 OTT를 구독하고 있는 사용자들이 감소하는 효과를 불러와, 전반적으로 산업을 축소시킬 지, 아니면 더욱 소비를 증가시켜 시장을 더욱 크게 만들 것으로 전망하시는 지에 대해서도 알고 싶습니다.

<br>

3.    저번학기 (2023-2)에 문화테크놀로지2 수업을 수강하면서 테오의 국내 프로그램 특징을 분석하고 테오의 프로그램을 분류해 어떤 플랫폼에 공급하면 좋을지에 대한 조별 발표를 진행했었습니다. 당시 국내 OTT 서비스의 미래와 테오의 프로그램을 엮어서 발표했었었는데요. 국내의 웨이브와 티빙의 합병이 진행되냐 마냐 논의가 진행되는 상태였어서 자세한 국내 엔터의 방향성이 결정된지 않았다는 피드백을 받았던 기억이 납니다. 최근 뉴스에서 웨이브와 티빙의 합병이 가시화되고 있다는 뉴스를 보았는데요. 이러한 국내 오티티 시장의 변화가 엔터 사업 내의 큰 영향을 끼칠 수 있을 것인지에 대한 의견이 궁금합니다!  

