---
title: Course description & Communication
---

------------------------------------------------------------------------

### Course description

> `문화와 기술1` 은 문화, 콘텐츠, 문화 산업, 기술의 융합과 관련된 다양한 주제에 대해 소개하고 주제와 관련된 여러가지 궁금점을 함께 탐구하기 위해 고안된 입문 수준의 학부 수업이다. 본 과정에서는 글로벌융합학부 컬쳐앤테크놀로지융합전공의 세부 트랙인 `콘텐츠`, `컬처`, `테크`, `경영`의 카테고리에 대해 세부 주제를 가르치는 교강사와 각 분야 전문가를 초청하여 개괄하고 좌담을 통해 토론과 Q&A를 진행한다. 이 과정에서 학생들은 콘텐츠 기획과 제작부터 음악, 패션, 게임, 데이터 과학, 인공지능, 메타버스 등 다양한 문화 산업에 기술이 어떻게 융합되고 있는지 이해하고, 학생 개인 맞춤형 세부 트랙에 대한 구상에 대한 통찰력을 얻게 된다. 컬처앤테크놀로지융합전공으로 (원정공 또는 다중 전공으로) 진입하여 세부 전공 탐색이 필요한 학생들에게 수강을 권한다.

</br>

### Goal

-   **문화와 기술의 융합을 이해**: 학생들은 기술이 어떻게 문화적 표현에 영향을 미칠 뿐만 아니라 필수적인 부분이 되어 콘텐츠가 생성, 소비 및 배포되는 방식을 형성하는지 탐구.

-   **문화 산업의 동향을 분석**: 음악(K-pop 및 엔터테인먼트에 중점), 패션, 게임 및 디지털 콘텐츠 생태계를 포함한 주요 문화 산업의 현재 동향을 비판적으로 분석할 수 있는 도구를 학생들에게 제공.

-   **신흥 기술 탐구**: 중요한 목표 중 하나는 학생들이 데이터 시각화, 자연어 처리, 메타버스, 상호 작용 과학, UX(사용자 경험) 디자인, 가상/증강 현실 콘텐츠 제작과 같은 새로운 기술에 익숙해지는 것.

-   **콘텐츠 제작의 혁신 촉진**: 서비스 디자인과 데이터 중심 마케팅의 원리를 이해함으로써 학생들은 문화 콘텐츠 제작 공간 내에서 혁신하는 방법을 배우게 된다.

-   **기업가적 사고 장려:** 스타트업 생태계와 엔터테인먼트 관리에서 문화와 기술의 교차점을 조사하여 기업가적 사고를 고취시키는 것을 목표로 함.

</br>

### Time & Location

-   (1h) 플립러닝 콘텐츠.

-   (2h) 화요일 09:20 \~ 10:50 \@국제관 첨단강의실\[9B217\]

</br>

### Weekly Design

| Week |    Date    | Topic                               | Guest  | Note |
|:----:|:----------:|:------------------------------------|:------:|:----:|
|  1   | 03/05/2024 | **Course Intro**                    |        |      |
|      |            | **콘텐츠 기획과 제작**              |        |      |
|  2   | 03/12/2024 | 융합 콘텐츠 기획과 제작             | 강혜원 |      |
|      |            | **문화와 문화 산업**                |        |      |
|  3   | 03/19/2024 | 음악, K-pop, 엔터테인먼트           | 정헌섭 |      |
|  4   | 03/26/2024 | 패션과 뉴테크                       | 류현석 |      |
|  5   | 04/02/2024 | 게임 & 인터랙티브 디자인            | 김수완 |      |
|  6   | 04/09/2024 | 한류와 팬덤                         | 이종명 |      |
|      |            | **문화 기술**                       |        |      |
|  7   | 04/16/2024 | 데이터 시각화의 예술                | 전서연 |      |
|  8   | 04/23/2024 | 문화콘텐츠와 자연어 처리            | 구영은 |      |
|  9   | 04/30/2024 | 메타버스와 메타휴먼                 | 원종서 |      |
|  10  | 05/07/2024 | 인터랙션 사이언스, UX               | 이대호 |      |
|  11  | 05/14/2024 | 서비스 디자인, 데이터 드리븐 마케팅 | 설상훈 |      |
|  12  | 05/21/2024 | 가상/증강현실 콘텐츠 제작           | 김태원 |      |
|      |            | **문화 콘텐츠 경영**                |        |      |
|  13  | 05/28/2024 | 융합콘텐츠와 창업                   | 윤영훈 |      |
|  14  | 06/04/2024 | 엔터테인먼트 경영                   | 이동찬 |      |
|  15  | 06/11/2024 | **Wrap-up Exam**                    |        |      |

: {.secondary .hover}

</br>

### About Lecturer (Modulator)

**Changjun LEE**

-   Home: <https://changjunlee.com/>

Associate Professor (Head of Culture & Tech)

School of Convergence. SKKU.

> As a computational social scientist, I bring a unique interdisciplinary perspective to the fields of economics, innovation studies, and convergence technologies. With a background in natural sciences, including a bachelor’s degree in biology and chemistry, I went on to earn a Ph.D. in technology management, economics, and policy. My research focuses on utilizing computational methods to tackle a wide range of social phenomena, including technology evolution & regional growth, knowledge management, and technology & convergence innovation. I am passionate about using technology and data to drive innovation and solve real-world problems.

-   **Research interest:** Media & Innovation, Immersive media and users' behavior, Technology management, Data Science

-   **Teaching:** Culture & Technology \| Data Science in CNT

-   Things I love

    -   Research

    -   Chat & Coffee & MBTI

    -   Travel

    -   Play (Things)

</br>

### Flipped Learning

-   주차별 주제 기초 지식에 대한 내용으로 사전 학습([수업홈 확인](https://changjunlee.com/teaching/cul_tech_101/weekly_2/))

-   사전 학습 내용에 대한 Discussion & Questions: [Google Form 제출(수업 시작 전까지)]{.underline}

-   사전 학습 내용 외에 해당 영역에 대한 질문도 함께 제출

    -   해당 영역의 이슈, 진로, 산업 전망 등 다양한 내용으로 질문 (한 개 이상 제출)

</br>

### Lecture

-   주차별 주제에 대한 Overview

-   주차별 주제 수업의 내용과 결과물 소개

-   해당 영역의 학습, 산업, 이슈, 그리고 진로에 대한 내용

</br>

### **좌담**: 토론과 Q&A

-   모듈레이터의 기초 질문들

-   학생의 사전 질문

-   학생의 즉석 질문 (APP을 통해)

</br>

### Evaluation

-   Attendance (10 %)

-   Preclass Discussion & Questions Submission (20 %)

-   Participation (20 %)

-   Wrap-up Exam (50 %)

    -   영역별 3문항 \* 13영역 + 1 = 40문항

</br>

### Communication

-   Notices & Questions

    -   Please join Kakao open-chat room

        -   <https://open.kakao.com/o/gHUaD37f>

        -   입장하셔서 이름을 꼭 출석부에 있는 이름으로 설정해주세요.

-   Personal counsel (Scholarship, recommendation letter, etc.)

    -   CJ-counselling room (Anything but the class content)

        -   CJ상담실: <https://open.kakao.com/o/s8zTrYCf>
