---
title: Course description & Communication
---

------------------------------------------------------------------------

<Br>

### Course description

> 인간-컴퓨터 상호 작용(HCI)에 적용되는 통계 및 데이터 과학의 기본 개념을 소개하고 연구에 적용할 수 있는 역량을 갖출 수 있도록 수업을 구성하였음. 데이터 분석 도구인 R 프로그래밍을 활용하여 실험(또는 설문) 데이터를 효과적으로 분석, 해석 및 시각화하는 데 필요한 기술을 갖추는 것을 목표로 한다.

</br>

### Time & Location

-   Wed 09:00 \~ 11:30 \@국제관 첨단e+강의실(9B313)

</br>

### Weekly Design

| Week |    Date    | Topic                                  |   Note   |
|:----:|:----------:|:---------------------------------------|:--------:|
|  1   | 09/03/2025 | Course Intro                           | ARS 참가 |
|  2   | 09/10/2025 | HCI 실험 디자인 및 실제 연구 사례 소개 |          |
|  3   | 09/17/2025 | R의 데이터 유형 및 구조(1)             |          |
|  4   | 09/24/2025 | R의 데이터 유형 및 구조(2)             |          |
|  5   | 10/01/2025 | 데이터 시각화와 기술 통계(1)           |          |
|  6   | 10/08/2025 | (휴강)                                 | 추석연휴 |
|  7   | 10/15/2025 | 데이터 시각화와 기술 통계(2)           |          |
|  8   | 10/22/2025 | 확률과 통계                            |          |
|  9   | 10/29/2025 | 통계적 추론                            |          |
|  10  | 11/05/2025 | 실험 & 통계 분석 실습                  |          |
|  11  | 11/12/2025 | 회귀 분석과 통계적 추론                |          |
|  12  | 11/19/2025 | Hayes Models                           |          |
|  13  | 11/26/2025 | 구조방정식 모델 & Clustering           |          |
|  14  | 12/03/2025 | Other Topics                           |          |
|  15  | 12/10/2025 | 논문 복기 발제                         |          |
|  16  | 12/17/2025 | 15주차 발제에 대한 Report 제출         |          |

: {.secondary .hover}

<br>

-   첫주차 강의는 **녹화 강의**입니다 (ARS Electronica 참여)

</br>

### About Lecturer (Modulator)

<br>

**Changjun LEE**

Associate Professor (Head of Culture & Tech)

School of Convergence. SKKU.

[changjunlee.com](https://changjunlee.com/){.uri}

</br>

### Evaluation

-   Attendance & Participation (20 %)

-   QZ (30 %)

-   Final Report (50 %)

</br>

### Communication

-   Notices & Questions

    -   Please join Kakao open-chat room

        -   <https://open.kakao.com/o/ghnamdPh>

        -   입장하셔서 이름을 꼭 출석부에 있는 이름으로 설정해주세요.

-   Personal counsel (Scholarship, recommendation letter, etc.)

    -   CJ-counselling room (Anything but the class content)

        -   CJ상담실: <https://open.kakao.com/o/s8zTrYCf>

<br>

### Textbooks **(but not limited to)**

-   [Statistical Inference via Data Science (Modern Dive)](https://moderndive.com/index.html) (written by Chester Ismay and Albert Y. Kim)

    > "ModernDive: An Introduction to Statistical and Data Sciences via R" by Chester Ismay and Albert Y. Kim is a comprehensive textbook that provides an accessible and hands-on approach to learning the fundamental concepts of statistical inference and data analysis using the R programming language. The book covers a wide range of topics, including data visualization, data summarization, probability and distributions, statistical inference, hypothesis testing, and linear regression, and emphasizes the importance of data visualization, reproducibility, and statistical thinking. With its use of the tidyverse suite of packages, numerous exercises and examples, and guidance on how to use R and RStudio, "ModernDive" is a valuable resource for students and practitioners who want to develop their data analysis skills.
