---
title: PBL (Project Based Learning)
subtitle: Final project
---

<br>

### Project Call

From Problem Definition to Insightful

> In this project, students will embark on a hands-on journey through the complete machine learning pipeline. The goal is to apply the knowledge gained in class to define a real-world problem, collect relevant data, preprocess it, and perform data analysis either to (1) predict a target variable (supervised learning) or (2) uncover patterns in the data (unsupervised learning). The emphasis is on understanding the logical process from problem identification to generating insights and effectively telling the story of your analysis in a final report.

-   **Objectives:** (related to score)

    -   To develop a clear and well-defined **problem statement**.

    -   To understand the **data collection** process and gather data relevant to the problem.

    -   To apply appropriate **data preprocessing** techniques to clean and prepare the data for analysis.

    -   To explore the data using [**machine learning techniques for prediction or pattern discovery**]{.underline}.

    -   To **communicate findings** and the logical reasoning behind them in a structured, compelling report.

-   **Deliverable:** Submit a final report that includes all steps of your project. [Any format is possible (PPT, word, notion web page link, pdf, and so on).]{.underline} Your report should include:

    -   **Introduction**: Problem definition and context.

    -   **Data Description**: Dataset, source, and preprocessing steps.

    -   **Analysis**: Methods, models, or algorithms used, and results.

    -   **Conclusion**: Insights, limitations, and potential next steps.

    -   **Appendix**: Any additional resources, code snippets, or references.

    -   **Final report due date**: 17 Dec (Tue) 09:00 (Before the class)

    -   In addition to the final report, teams will have two options for presenting their project:

        1.  **In-Class Presentation**: Teams may choose to present their project during the final class session. Each team will have **10 minutes** to showcase their work. This will be followed by a brief Q&A session.

        2.  **YouTube Video Submission**: Alternatively, teams can submit a **10-minute YouTube video** where they present their project in a similar format. The video link should be shared along with the final report.

-   Grading criteria

    -   **Problem Definition (10%)**: Clarity, relevance, and impact of the problem statement.
    -   **Data Collection (10%)**: Appropriateness and quality of the data, description of the data collection process.
    -   **Data Preprocessing (15%)**: Completeness of data cleaning, appropriateness of techniques, and explanation of decisions.
    -   **Data Analysis (30%)**: Correctness of the methods used, depth of analysis, and justification of conclusions.
    -   **Final Report (20%)**: Quality of storytelling, structure, and clarity of presentation, visualizations, and overall communication.
    -   **Presentation (15%):** Quality of communication to audiances

-   Students organize teams that meet several conditions.

    -   4\~5 members in a team

    -   Background diversity: no homogeneous majors in a team

    -   Exception: Allowed if persuasion is possible for sufficient reasons

    -   Use Kakao openchat room to recruit your team members

-   **Teams**

    |   A    |   B    |   C    |    D    |          E           |   G    |          L           |          M           |
    |:------:|:------:|:------:|:-------:|:--------------------:|:------:|:--------------------:|:--------------------:|
    | 민범기 | 성나연 | 강소리 | Lauren  | [김나영]{.underline} | 안제민 |        김세민        |        정은채        |
    | 김지연 | 안혜리 | 경동현 | Tobias  | [박찬진]{.underline} | 윤승현 |        김예담        |        임채민        |
    | 이현규 | 조준범 | 배민준 | Alexis  | [석건하]{.underline} | 최경석 |        김희서        |        이채빈        |
    | 장태혁 | 강윤지 | 안새별 | Jennfer | [신경철]{.underline} | 박재원 | [오자윤]{.underline} | [장수진]{.underline} |
    | 백정은 | 박선영 | 이지우 | Swayam  | [이상혁]{.underline} |        |                      |                      |

    -   A

        -   **민범기** CT

        -   **김지연** 소비자

        -   **이현규** 시스템경영공학

        -   **장태혁** CT

        -   **백정은** DS

    -   B

        -   **성나연** 문정

        -   **안혜리** 문정

        -   **조준범** AI

        -   **강윤지** 독독

        -   **박선영** 국국

    -   C

        -   **강소리** CT

        -   **경동현** DS

        -   **배민준** CT

        -   **안새별** CT

        -   **이지우** CT

    -   D

        -   Lauren Anne Nicolas

        -   Tobias Maximilian

        -   Alexis Jean Claude Dhermy

        -   Jennifer Zhang

        -   Mehra Swayam

    -   E

        -   [**김나영** AI]{.underline}

        -   [**박찬진** DS]{.underline}

        -   [**석건하** 경영]{.underline}

        -   [**신경철** 한문]{.underline}

        -   [**이상혁** 통계]{.underline}

    <!-- -->

    -   G

        -   **안제민** DS

        -   **윤승현** 경영

        -   **최경석** 스포츠과학

        -   **박재원** DS

    -   L

        -   **김세민** AI

        -   **김예담** CT

        -   **김희서** AI

        -   [**오자윤** 의상]{.underline}

    -   M

        -   **정은채** AI

        -   **임채민** DS

        -   **이채빈** DS

        -   [**장수진** 디자인]{.underline}
