---
title: Weekly Content
# subtitle: 학습 도구
---

<br>

## **Intro**

<br>

### **Week 1: Course Intro**

-   Date: 20240305

-   Class: Course Introduction

    -   An overview of the course

<br>

## **Part I: 콘텐츠 기획과 제작**

<br>

### **Week 2: 융합 콘텐츠 기획과 제작**

-   Date: 20240312

-   Pre-class video

    -   덕후에서 콘텐츠 크리에이터가 되는 방법 \| 대도서관
 
    -   좋은 컨텐츠를 만드는 법 \| 에이틴 제작사

    -   Why AI Will Spark Exponential Economic Growth \| Cathie Wood \| TED

    -   Discussion & Questions Submission

-   Class

    -   Guest Lecturer: 강혜원 교수(SKKU)

    -   Modulator: 이창준 교수(SKKU)

<br>

## **Part II: 문화와 문화 산업**

<br>

### **Week 3: 음악, K-pop, 엔터테인먼트**

-   Date: 20240319

-   Pre-class video

    -   What if You Could Sing in Your Favorite Musician's Voice? \| Holly Herndon \| TED

    -   음악 한 곡을 발매하는데 돈이 얼마나 들까?

    -   소속사 없이 음원 유통하는 법

    -   Discussion & Questions Submission

-   Class

    -   Guest Lecturer: 정헌섭 교수(SKKU)

    -   Modulator: 이창준 교수(SKKU)

<br>

### **Week 4: 패션과 뉴테크**

-   Date: 20240326

-   Pre-class video

    -   How data is driving the future of fashion \| Steve Brown \| TED Institute

    -   The New Reality of Fashion is Digital \| Gala Marija Vrbanic \| TED

    -   Discussion & Questions Submission

-   Class

    -   Guest Lecturer: 류현석 교수(SKKU)

    -   Modulator: 이창준 교수(SKKU)

<br>

### **Week 5: 게임 & 인터랙티브 디자인**

-   Date: 20240402

-   Pre-class video

    -   게임 과몰입, 게임 잘못일까요? \| 한덕현 중앙대학교 병원 정신건강의학과 교수 \| \| 세바시

    -   Discussion

-   Class

    -   Guest Lecturer: 김수완 교수(SKKU)

    -   Modulator: 이창준 교수(SKKU)

<br>

### **Week 6: 한류와 팬덤**

-   Date: 20240409

-   Pre-class video

    -   All I Really Need To Know, I Learned From KPOP \| Donald Lim \| TEDxYouth\@SJCS

    -   Has K-pop prepared us for the metaverse? \| Alex Karlsson \| TEDxBrunkebergstorg

    -   Discussion & Questions Submission

-   Class

    -   Guest Lecturer: 이종명 교수(SKKU)

    -   Modulator: 이창준 교수(SKKU)

<br>

## **Part III: 문화 기술**

<br>

### **Week 7: 데이터 시각화의 예술**

-   Date: 20240416

-   Pre-class video

    -   The beauty of data visualization - David McCandless

    -   Data Visualization Best Practices - Stephanie Evergreen

    -   Discussion & Questions Submission

-   Class

    -   Guest Lecturer: 전서연 강사

    -   Modulator: 이창준 교수(SKKU)

<br>

### **Week 8: 문화콘텐츠와 자연어 처리**

-   Date: 20240423

-   Pre-class video

    -   Text 데이터를 활용한 개인화 음악 추천서비스 웹 데모 구축 (혁신성장청년인재양성사업 프로젝트 발표)

    -   NLP Project - Emotion In Text Classifier App with Streamlit and Python

    -   Discussion & Questions Submission

-   Class

    -   Guest Lecturer: 구영은 교수(SKKU)

    -   Modulator: 이창준 교수(SKKU)

<br>

### **Week 9: 메타버스와 메타휴먼**

-   Date: 20240430

-   Pre-class video

    -   버추얼 아이돌 그룹 플레이브의 탄생 과정과 기술 이야기 (언리얼 페스트 2023 서울)

    -   Discussion & Questions Submission

-   Class

    -   Guest Lecturer: 원종서 교수(SKKU)

    -   Modulator: 이창준 교수(SKKU)

<br>

### **Week 10: 인터랙션 사이언스, UX**

-   Date: 20240507

-   Pre-class video

    -   Human-Computer Interaction and User Interface Design \| Tony Tang

    -   Discussion & Questions Submission

-   Class

    -   Guest Lecturer: 이대호 교수(SKKU)

    -   Modulator: 이창준 교수(SKKU)

<br>

### **Week 11: 서비스 디자인, 데이터 드리븐 마케팅**

-   Date: 20240514

-   Pre-class video

    -   Why Data Marketing So Important \| 세바시

    -   Age of Experience, Data+Service \| 설상훈 교수님

    -   Discussion & Questions Submission

-   Class

    -   Guest Lecturer: 설상훈 교수(SKKU)

    -   Modulator: 이창준 교수(SKKU)

<br>

### **Week 12: 가상/증강현실 콘텐츠 제작**

-   Date: 20240521

-   Pre-class video

    -   상상이 현실화가 되는 세계, 그 중심에 서서 외치다 \| 서동일 오큘러스VR코리아 지사장

    -   What is extended reality? \| The Gadget Show

    -   Discussion & Questions Submission

-   Class

    -   Guest Lecturer: 김태원 대표(RGB Makers)

    -   Modulator: 이창준 교수(SKKU)

<br>

## **Part IV: 문화 콘텐츠 경영**

<br>

### **Week 13: 융합콘텐츠와 창업**

-   Date: 20240528

-   Pre-class video

    -   GPT 있는데 왜 또 만들어요? 손쉽게 이해하는 AI 개발 트렌드와 비하인드

    -   세상을 바꾸는 뉴콘텐츠

    -   콘텐츠 창업에서 가장 중요한 것 \| CEO 노정석

    -   Discussion & Questions Submission

-   Class

    -   Guest Lecturer: 윤영훈 대표 (주)ASSI

    -   Modulator: 이창준 교수(SKKU)

<br>

### **Week 14: 엔터테인먼트 경영**

-   Date: 20240604

-   Pre-class video

    -   How Netflix changed entertainment -- and where it's headed \| Reed Hastings

    -   Discussion & Questions Submission

-   Class

    -   Guest Lecturer: 이동찬 경영총괄 (TEO Universe)

    -   Modulator: 이창준 교수(SKKU)

<br>

## **Conclusion**

<br>

-   다가오는 인공지능의 시대

    -   AI 4대 석학' 앤드류 응, 공개강연


### **Week 15: Wrap-up Exam**

-   Date: 20240611
