project:
  type: website

website:
  title: "CJL & Lab"
  page-footer:
    left: "License: [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/)."
    right:
      - icon: github
        href: https://github.com/ChangjunChrisLee/
      - icon: twitter
        href: https://twitter.com/Dr_CJLee
  navbar:
    right:
      - href: about.qmd
        text: About
      - text: Courses
        menu:
          - text: All Courses
            href: teaching/index.qmd
          - text: Data Science 101
            href: teaching/ds101/index.qmd
          - text: Machine Learning 101
            href: teaching/ml101/index.qmd
          - text: Media & Data Science
            href: teaching/media_ds/index.qmd
          - text: Culture & Technology
            href: teaching/cul_tech/index.qmd
          - text: Data Journalism
            href: teaching/data_journalism/index.qmd
      - text: Research
        menu:
          - text: Publications
            href: research/index.qmd
          - text: Work in progress
            href: research/working.qmd
      - text: Proj
        href: proj/index.qmd
      - text: Blogs
        href: blogs/index.qmd
      - text: LAB
        href: https://ctcl.netlify.app
        
format:
  html:
    theme: Yeti
    # css: styles.css
    toc: true
    linestretch: 1.25
    langfont:
      ko: NanumMyeongjo