project:
  type: website

website:
  title: "CJL & Lab"
  page-footer:
    left: "License: [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/)."
    right:
      - icon: github
        href: https://github.com/ChangjunChrisLee/
      - icon: twitter
        href: https://twitter.com/Dr_CJLee
  navbar:
    right:
      - href: about.qmd
        text: About
      - text: Courses
        menu:
          - text: All Courses
            href: teaching/index.qmd
          # - text: CNT101
          #   href: teaching/cul_tech_101/index.qmd
          # - text: CNT102
          #   href: teaching/cul_tech/index.qmd
          # - text: DS101
          #   href: teaching/ds101/index.qmd  
          - text: ML101
            href: teaching/ml101/index.qmd
          - text: STAT101
            href: teaching/grad_stat/index.qmd
          - text: IMCT
            href: teaching/grad_immersive/index.qmd
      - text: Research
        href: research/index.qmd
      - text: Proj
        href: proj/index.qmd
      - text: Blogs
        href: blogs/index.qmd
      - text: LAB
        href: https://ctcl.netlify.app
        
format:
  html:
    theme: Yeti
    # css: styles.css
    toc: true
    linestretch: 1.25
    langfont:
      ko: NanumMyeongjo