project:
  type: website

website:
  title: "CJL Lab"
  page-footer:
    left: "License: [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/)."
    right:
      - icon: github
        href: https://github.com/ChangjunChrisLee/
      - icon: twitter
        href: https://twitter.com/Dr_CJLee
      - icon: envelope
        href: mailto:changjun.chris.lee@gmail.com
  navbar:
    right:
      - href: about.qmd
        text: About
      - text: Courses
        menu:
          - text: All Courses
            href: teaching/index.qmd
          - text: Data Science 101
            href: teaching/ds101/index.qmd
          - text: Machine Learning 101
            href: teaching/ml101/index.qmd
          - text: Media & Data Science
            href: teaching/media_ds/index.qmd
      - text: Proj
        menu:
          - text: All Projects
            href: proj/index.qmd
          - text: "생애첫연구"
            href: proj/proj_01.qmd
          - text: "신진연구자지원사업"
            href: proj/proj_02.qmd
      - text: Research
        menu:
          - text: Publications
            href: research/index.qmd
          - text: Working in progress
            href: research/working.qmd
      - text: Blogs
        href: blogs/index.qmd
format:
  html:
    theme: Yeti
    css: styles.css
    toc: true
    linestretch: 1.25