---
title: "Changjun LEE"
format: html
editor: visual
---

<br>

:::: panel-tabset
### Bio

**Sungkyunkwan University (SKKU)**

College of Computing and Informatics

-   School of Convergence. *Dep. of Culture & Technology* (***Head***)

Graduate Schools (I'm affiliated in):

-   Dep. of Interaction Science
-   Dep. of Immersive Media Engineering (Metaverse Graduate School)

✉ changjunlee\@skku.edu

------------------------------------------------------------------------

> *As a computational social scientist, I use data and technology to analyze societal phenomena, exploring how the evolution of knowledge and technology drives innovation and economic growth.*

My academic journey began with undergraduate studies in biology and chemistry, where I developed a strong foundation in scientific thinking and inquiry. I later pursued a Ph.D. in technology management, economics, and policy, gaining expertise in analyzing the complex interplay between technology and society. This interdisciplinary background has equipped me to conduct research that bridges natural and social sciences, enabling a holistic approach to problem-solving.

My research inclueds two main areas.

-   First, I investigate [**how the knowledge and technologies of firms and regions evolve and how these dynamics influence innovation and economic growth**]{.underline}. This work aims to uncover the mechanisms behind regional economic vitality and corporate innovation while providing insights for effective policies and strategies.

-   Second, I focus on **t[he adoption, diffusion, and broader implications of cutting-edge technologies such as artificial intelligence (AI), fintech, and the Internet of Things (IoT)]{.underline}**. In particular, I am deeply interested in **Human-AI Interaction**—how people engage with AI-driven technologies, the factors that shape user acceptance, and the societal impact of these interactions. I aim to uncover key drivers of technology adoption and provide actionable insights for designing user-centered, ethical, and impactful technology-based businesses and policies.

> *I have a particular passion for applying computational methods and machine learning algorithms to analyze data, helping to untangle complex social issues and find practical solutions.*

My work spans diverse areas, including AI-embedded services and products, and OTT media platforms, where I have explored consumer behavior and market trends. My goal is to ensure that my research goes beyond academic discourse to provide meaningful implications for industry leaders and policymakers while contributing to new theoretical frameworks in innovation studies and technology management. Through timely and practical research, I aim to create a bridge between academic insights and real-world applications, driving impactful changes across various sectors.

### Bio (Kor)

::: {lang="ko"}
**성균관대학교**

소프트웨어융합대학\
글로벌융합학부 컬쳐앤테크놀로지융합전공 (전공주임)\
**대학원:** 인터랙션사이언스학과 \| 실감미디어공학과

✉ changjunlee\@skku.edu

------------------------------------------------------------------------

> *"저는 계산사회과학자로서 데이터 과학과 인공지능을 활용해 사회 현상을 분석하고, 지식과 기술의 진화가 혁신과 경제 성장에 미치는 영향을 연구하고 있습니다."*

학부에서는 생물학과 화학을 전공하며 자연과학적 사고와 탐구 능력을 키웠고, 이후 기술 경영·경제 및 정책 분야에서 박사 학위를 취득하며 기술과 사회의 복잡한 관계를 심층적으로 분석하는 역량을 쌓아왔습니다. 이러한 학문적 여정은 과학적 기초와 사회과학적 접근을 결합하여 학제 간 융합 연구를 수행하는 데 중요한 밑거름이 되었습니다.

제 연구는 크게 두 가지 축으로 이루어집니다.

-   [**첫째, 기업과 지역 사회의 지식과 기술이 어떻게 진화하고 이러한 변화가 혁신과 경제 성장에 어떤 영향을 미치는지를 탐구**]{.underline}하는 것입니다. 이를 통해 지역 경제의 역동성과 기업 혁신의 메커니즘을 이해하고, 효과적인 정책 및 전략을 제안하는 데 기여하고자 합니다.

-   [**둘째, 인공지능(AI), 핀테크, 사물인터넷(IoT)과 같은 최신 기술이 소비자와 사회에 수용되고 확산되는 과정을 데이터 기반으로 분석**]{.underline}합니다. 특히, **인간과 AI 간 상호작용(Human-AI Interaction)**에 주목하여, 이러한 기술이 사용자에게 어떻게 받아들여지고, 어떤 요인이 수용에 영향을 미치는지, 그리고 사회에 미치는 영향을 탐구합니다. 이를 통해 사용자 중심적이고 윤리적인 기술 기반 비즈니스와 정책 개발에 실질적인 통찰을 제공하고자 합니다.

> *"방법론적으로는, **계산적 방법론과 머신러닝 알고리즘을 활용해 데이터를 분석**하는 것을 좋아하고, 이를 통해 **복잡한 사회적 문제를 이해하고 해결하는 데 관심**을 두고 있습니다."*

인공지능이 포함된 모든 서비스와 상품, OTT 미디어 플랫폼 등 다양한 영역에서 소비자 행동과 시장 동향을 분석한 연구를 수행해왔고 앞으로 나올 새로운 기술 융합 서비스에 관심이 많습니다. 연구자로서 제 바람은 실용적이고 시의적인 연구를 통해 연구가 그저 논문으로 끝나지 않고 실용적 관점에서 산업 및 정책 관계자들에게 의미 있는 시사점을 제공하는 것입니다.
:::
::::

<br>

### Employment

-   **Sungkyunkwan University** (SKKU), Seoul, Republic of Korea\
    [College of Computing and Informatics](https://sw.skku.edu/eng_sw/index.do)\
    [School of Convergence](https://sco.skku.edu/sco/index.do)

    -   Associate Professor (2023 \~ present)

-   **Hanyang University** (ERICA), Ansan, Republic of Korea\
    Dep. of Media & Social Informatics

    -   Associate Professor (2022 \~ 2023)
    -   Assistant Professor (2019 \~ 2022)

-   **University College Dublin**, Republic of Ireland\
    [Spatial Dynamics Lab](https://www.ucd.ie/sdl/)

    -   Senior Postdoctoral Research Fellow (2017 \~ 2019)

-   **National University of Singapore**, Singapore\
    [Lee Kuan Yew School of Public Policy](https://lkyspp.nus.edu.sg/)

    -   Postdoctoral Research Associate (2015 \~ 2017)

<br>

### Education

-   Ph.D. in Economics (*Technology Management & Policy*)

    -   **Seoul National University**, Seoul, Republic of Korea (2010 - 2015)\
        [Technology Management, Economics, and Policy Program](https://temep.snu.ac.kr/en)\
        Dissertation: [*Research on the Growth Mechanism of Platform Ecosystem*](https://s-space.snu.ac.kr/handle/10371/119960#export_btn)

-   B.Sc. in Biology & Chemistry

    -   **Yonsei University**, Seoul, Republic of Korea (2004 - 2010)

<br>

### Teachings 

-   **Culture & Technology**: 2024-S, 2023-F
-   **Data-Science101**: 2024-S, 2022-F, 2021-F, 2020-F/S, 2019-F
-   **Machine Learning 101**: 2024-F, 2023-S, 2022-S, 2021-S, 2020-F
-   **Database101**: 2022-S, 2021-S, 2020-S
-   **Basic Math & Statistics for Data Science**: 2021-S
-   **(Grad)** Media & Data-Science: 2023-S, 2022-S, 2021-S
-   **(Grad)** Media User Data Analysis: 2022-F
-   **(Grad)** Statistics for Interaction Science: 2024-F
-   Capstone Design: 2021-S

<br>

### Internal and External Positions

-   Editorial Roles

    -   **한국혁신학회지**: 부편집위원장 (2021–Present)
    -   **정보사회와미디어**: 편집위원 (2023–Present)
    -   **정보통신정책학회지**: 편집위원 (2022–Present)
    -   **디지털경제사회연구**: 편집위원 (2024–Present)
    -   **한국방송학보**: 편집위원 (2023)
    -   **한국언론학보**: 편집위원 (2023)

-   Professional Associations

    -   한국언론학회 ([The Korean Society for Journalism & communication Studies](https://comm.or.kr/))
        -   총무이사 (51대, 2025) \| 연구이사 (49대, 2023)
    -   한국방송학회 ([Korean Association for Broadcasting & Telecommunication Studies](https://kabs.or.kr/))
        -   연구이사 (34대, 2023; 36대, 2024)
    -   미디어경영학회 ([Korea Media Management Association](https://kmma.org/))
        -   총무이사 (2023-2024) \| 연구이사 (2022, 2025)
    -   한국정보사회학회 ([Korean Association for Information Society](https://infoso.org/))
        -   연구이사 (2025)
    -   사이버커뮤니케이션학회 ([Cyber Communication Academic Society](http://www.cybercom.or.kr/))
        -   총무이사 (2022) \| 기획이사 (2023-2025)
    -   한국IT서비스학회 (Korean IT Service Association)
        -   운영이사 (2024)

-   Advisory Board Activities

    -   **정보통신정책연구원 (KISDI)**: Associate Researcher (2022–Present)
    -   **한국과학기술기획평가원 (KISTEP)**: Associate Researcher (2023–2024)
    -   **한국생산기술연구원 (KITECH)**: Advisor (2021–2023)
    -   **마이크로밀엠브레인 (Embrain)**: Associate Researcher (2023–Present)
    -   **NAVER**: Advisor (2024–Present)

<br>

### Achievements

-   **2023-2, 2024-1, 2024-2**: Voted as "**Student-Chosen Best Professor**" in the School of Convergence, Department of Culture & Technology, SKKU.
-   **2022**: Recipient of the **Outstanding Paper Academic Award** from the Korea Media Management Association.
-   **2022**: Granted the **Outstanding Achievement Special Promotion** by Hanyang University (ERICA).
-   **2021**: Honored with the **International Research Division Academic Award (New Faculty Award)** at Hanyang University (ERICA).
-   **2021**: Winner of the **IC-PBL Rookie Division Excellence Award**, Hanyang University (ERICA).

<br>

### Publications

-   ORCID: <https://orcid.org/0000-0002-8859-9796>

-   National Researcher Number: 11291477

::: panel-tabset
##### Publication keywords

<iframe src="research/keyword_wordcloud.html" frameborder="10" width="100%" height="400">

</iframe>

##### Co-author network

<iframe src="research/coauthor_network.html" frameborder="0" width="100%" height="700" scrolling="no" allowfullscreen>

</iframe>
:::

#### **2024**

-   Choi, Y., & **Lee, C.\*** (2024). Profiling the AI speaker user: Machine learning insights into consumer adoption patterns. *PLoS ONE, 19*(12), e0315540. <https://doi.org/10.1371/journal.pone.0315540>
-   Choi, Y., **Lee, C.\***, & Han, S. (2024). Predicting wearable IoT adoption: Identifying core consumers through machine learning algorithms. *Telematics and Informatics,* 93, 102176. <https://doi.org/10.1016/j.tele.2024.102176>
-   Choi, Y., Han, S., & **Lee, C.\*** (2024). Exploring drivers of fintech adoption among elderly consumers. *Technology in Society,* 78, 102669. <https://doi.org/10.1016/j.techsoc.2024.102669>
-   Kim, K., Maliphol, S., Shim, D., & **Lee, C.\*** (2024). Exploring the interplay between social distancing, innovation adoption, and privacy concerns amid the COVID-19 crisis. *Science and Public Policy,* 51(6), 1257-1266. [https://doi.org/10.1093/scipol](https://doi.org/10.1093/scipol/scae024)
-   **Lee, C.**, & Ji, S. W.\* (2024). Strategies for launching streaming content: Assessing movie-country relatedness and its impact on international popularity. *PLoS ONE, 19*(6), e0305433. <https://doi.org/10.1371/journal.pone.0305433>
-   Choi, Y. W., & **Lee, C.\*** (2024). Time-of-day and day-of-week effects on TV and OTT media choices: Evidence from South Korea. *Journal of Theoretical and Applied Electronic Commerce Research, 19*(1), 1–19. <https://doi.org/10.3390/jtaer19010001>

#### **2023**

-   **Lee, C.**, Na, C., & Kim, K. (2023). The effect of watching OTT late at night on the sleep pattern of users. *Sleep and Biological Rhythms, 21,* 395–407. <https://doi.org/10.1007/s41105-023-00459-z>
-   Kim, J., & **Lee, C.\*** (2023). The return of the king: The importance of killer content in a competitive OTT market. *Journal of Theoretical and Applied Electronic Commerce Research, 18*(2), 976–994. <https://doi.org/10.3390/jtaer18020050>
-   Na, C. H., **Lee, C.**, & Kim, E. D.\* (2023). The optimal open innovation strategy with science-based partners for venture firm’s innovation capabilities: Focusing on innovation modes. *Science, Technology, and Society, 28*(2), 235–256. <https://doi.org/10.1177/09717218231160442>
-   Liu, H. S., **Lee, C.**, Kim, K., et al. (2023). Factors influencing the intention to use "untact" services by service type. *Sustainability, 15*(4), 2870. <https://doi.org/10.3390/su15042870>
-   Park, I., Shim, H., Kim, J., **Lee, C.**, & Lee, D.\* (2023). The effects of popularity metrics in news comments on the formation of public opinion: Evidence from an internet portal site. *The Social Science Journal,* *60*(2), 367–382. <https://doi.org/10.1080/03623319.2020.1768485>
-   Kim, K., Lee, J., & **Lee, C.\*** (2023). Which innovation type is better for production efficiency? A comparison between product/service, process, organizational, and marketing innovations using stochastic frontier and meta-frontier analysis. *Technology Analysis & Strategic Management, 35*(1), 59–72. <https://doi.org/10.1080/09537325.2021.1965979>
-   Kim, K., Kogler, D. F., **Lee, C.**, & Kang, T.\* (2023). Changes in regional knowledge bases and their effects on local labor markets: Evidence from France (1985–2015). *Applied Spatial Analysis and Policy,* 16, 1–22. <https://doi.org/10.1007/s12061-022-09444-4>

#### **2022**

-   Shim, D., **Lee, C.**, & Oh, I.\* (2022). Analysis of OTT users’ watching behavior for identifying a profitable niche: Latent class regression approach. *Journal of Theoretical and Applied Electronic Commerce Research, 17*(4), 1564–1580. https://doi.org/10.3390/jtaer1704079
-   Shon, M., Lee, D., & **Lee, C.\*** (2022). Inward or outward? Direction of knowledge flow and firm efficiency. *International Journal of Technology Management, 90*(1–2), 102–121. <https://doi.org/10.1504/IJTM.2022.124617>
-   Park, I., Lee, J., Lee, D., **Lee, C.**, & Chung, W. Y.\* (2022). Changes in consumption patterns during the COVID-19 pandemic: Analyzing revenge spending motivations of different emotional groups. *Journal of Retailing and Consumer Services, 65,* 102874. <https://doi.org/10.1016/j.jretconser.2021.102874>
-   **Lee, C.**, Shin, H., Kim, K., & Kogler, D. F.\* (2022). Effects of regional capacity in knowledge recombination on production efficiency. *Technological Forecasting and Social Change, 180,* 121669. <https://doi.org/10.1016/j.techfore.2022.121669>
-   Jung, E., **Lee, C.\***, & Hwang, J. (2022). Effective strategies to attract crowdfunding investment based on the novelty of business ideas. *Technological Forecasting and Social Change, 178,* 121558. <https://doi.org/10.1016/j.techfore.2022.121558>
-   Jeon, H., & **Lee, C.\*** (2022). Internet of Things technology: Balancing privacy concerns with convenience. *Telematics and Informatics, 70,* 101816. <https://doi.org/10.1016/j.tele.2022.101816>
-   Kogler, D. F., Davies, R. B., Lee, C., & Kim, K.\* (2022). Regional knowledge spaces: The interplay of entry-relatedness and entry-potential for technological change and growth. *The Journal of Technology Transfer,* 1–24. <https://doi.org/10.1007/s10961-022-09924-2>
-   Tóth, G., Elekes, Z., Whittle, A., **Lee, C.\***, & Kogler, D. F. (2022). Technology network structure conditions the economic resilience of regions. *Economic Geography, 98*(4), 1–24. <https://doi.org/10.1080/00130095.2022.2035715>
-   Jo, H., Park, S., Shin, D., Shin, J.\*, & **Lee, C.** (2022). Estimating the cost of fighting against fake news during catastrophic situations. *Telematics and Informatics, 66,* 101734. <https://doi.org/10.1016/j.tele.2021.101734>
-   Rocchetta, S.\*, Mina, A., **Lee, C.**, & Kogler, F. D. (2022). Technological knowledge space and the resilience of European regions. *Journal of Economic Geography, 22*(1), 27–51. <https://doi.org/10.1093/jeg/lbab001>

#### **2021**

-   **Lee, C.**, Cho, H., & Lee, D.\* (2021). The mechanism of innovation spill-over across sub-layers in the ICT industry. *Asian Journal of Technology Innovation, 29*(2), 159–179. <https://doi.org/10.1080/19761597.2020.1796725>
-   Jung, S., Kim, K., & **Lee, C.\*** (2021). The nature of ICT in technology convergence: A knowledge-based network analysis. *PLoS ONE, 16*(7), e0254424. <https://doi.org/10.1371/journal.pone.0254424>
-   Na, C., Lee, D., Hwang, J., & **Lee, C.**\* (2021). Strategic groups emerged by selecting R&D collaboration partners and firms’ efficiency. *Asian Journal of Technology Innovation, 29*(1), 109–133. <https://doi.org/10.1080/19761597.2020.1788957>

#### **2020 and earlier**

-   **Lee, C.**, Lee, D., & Shon, M.\* (2020). Effect of efficient triple-helix collaboration on organizations based on their stage of growth. *Journal of Engineering and Technology Management, 58,* 101604. <https://doi.org/10.1016/j.jengtecman.2020.101604>
-   **Lee, C.**, Kogler, D. F., & Lee, D.\* (2019). Capturing information on technology convergence, international collaboration, and knowledge flow from patent documents: A case of information and communication technology. *Information Processing & Management, 56*(4), 1576–1591. <https://doi.org/10.1016/j.ipm.2018.09.007>
-   Kim, E. H. W.\*, & **Lee, C.** (2019). Does working long hours cause marital dissolution? Evidence from the reduction in South Korea’s workweek standard. *Asian Population Studies, 15*(1), 87–104. <https://doi.org/10.1080/17441730.2019.1565131>
-   Kim, E. H. W.\*, **Lee, C.**, & Do, Y. K. (2018). The effect of a reduced statutory workweek on familial long-term care in Korea. *Journal of Aging and Health, 30*(10), 1620–1641. <https://doi.org/10.1177/0898264318797469>
-   **Lee, C.**, Kim, J.H., & Lee, D.\* (2017). Intra-industry Innovation, Spillovers, and Industry Evolution: Evidence from the Korean ICT industry. *Telematics and Informatics.* *34*(8), 1503-1513. doi:[1016/j.tele.2017.06.013](https://doi.org/10.1016/j.tele.2017.06.013)
-   **Lee, C.**, Jung, S., & Kim, K.O.\* (2017). Effect of a Policy Intervention on Handset Subsidies on the Intention to Change Handsets and Households' Expenses in Mobile Telecommunications. *Telematics and Informatics.* *34*(8), 1524-1531. doi:[1016/j.tele.2017.06.017](https://doi.org/10.1016/j.tele.2017.06.017)
-   **Lee, C.**, Kim, H., & Hong, A.\* (2017). Ex-post Evaluation of Illegalizing Juvenile Online Game after Midnight: A Case of Shutdown Policy in South Korea. *Telematics and Informatics.* *34*(8), 1597-1606. doi:[1016/j.tele.2017.07.006](https://doi.org/10.1016/j.tele.2017.07.006)
-   **Lee, C.**, Lee, K., & Lee, D.\* (2017). Mobile Healthcare Applications and Gamification for Sustained Health Maintenance. *9*(5), 772. doi:[10.3390/su9050772](https://doi.org/10.3390/su9050772)
-   **Lee, C.**, Lee, D.\*, & Hwang, J. (2015). Platform Openness and the Productivity of Content Providers: A meta-frontier analysis. *Telecommunications Policy. 39*(7). 553-562. <https://doi.org/10.1016/j.telpol.2014.06.010>

</br>

#### Korean Citation Index (KCI) Journals

-   김가현, **이창준**, & 박유리.\* (2024). 디지털 게임을 통한 힐링: 직무 스트레스가 디지털 게임의 장르 선택과 회복 경험에 미치는 영향 분석. 정보통신정책연구, 31(4), 163-194. <http://doi.org/10.37793/ITPR.31.4.6>

-   채하린, 이수정, **이창준** and 이준민\*. (2024). 지역협력 정책 수립을 위한 지식공간 기반 혁신전략 탐색: 부울경 지역을 중심으로. 한국혁신학회지, 19(4), 319-348. <https://doi.org/10.46251/INNOS.2024.11.19.4.319>

-   최윤슬, 이승경, **이창준\***. (2024). 메타버스 이용자의 인지 수준과 사회적 자본이 메타버스 지속 사용 의도와 추천 의도에 미치는 영향: 자기 효능감과 프레즌스를 매개변인으로. 비즈니스융복합연구, 9(5), 1-8, [10.31152/JB.2024.10.9.5.1](https://www.dbpia.co.kr/journal/articleDetail?nodeId=NODE11971287)

-   박지은, 이승경, **이창준.\*** (2023). 시니어의 심리적 요인과 가구구성형태가 적극적인 SNS 이용에 미치는 영향 : 자아 존중감, 인지 욕구, 가구구성형태를 중심으로. 정보사회와 미디어, 24(3), 1-35. [*https://doi.org/10.52558/ISM.2023.12.24.3.1*](https://doi.org/10.52558/ISM.2023.12.24.3.1){.uri}

-   이승경, 최윤슬, 박영주, **이창준.\*** (2023). 메타버스 사용자의 사회⋅심리적 특성이 아바타 커스터마이징에 미치는 영향. 사이버커뮤니케이션학보, 40(2), 5-52. <https://doi.org/10.36494/JCAS.2023.06.40.2.5>

-   최미연, **이창준.\*** (2022). 비대면 상황에서의 온라인 커뮤니티 활동이 삶 만족도에 미치는 영향 : 코로나19 이전(2017년)과 이후(2021년) 비교를 중심으로. 정보사회와 미디어, 23(3), 83-124. <https://doi.org/52558/ISM.2022.12.23.3.83>

-   염자몽, 이승경, **이창준.\*** (2022). 중국의 애국주의와 한류 팬덤 간의 사이버 갈등: BTS 리더 RM의 ‘밴 플리트 상’ 수상소감 관련 온라인 댓글 분석을 중심으로. 사이버커뮤니케이션학보, 39(4), 5-49. <https://doi.org/10.36494/JCAS.2022.12.39.4.5>

-   강송희, 서영희, **이창준.\*** (2022). 산업별 디지털 전환 갈등 지표 개발 연구. 정보사회와 미디어, 23(1), 41-68. [10.52558/ISM.2022.04.23.1.41](https://www.dbpia.co.kr/journal/articleDetail?nodeId=NODE11057264)

-   김경외, 이준민, **이창준.\*** (2021). 효율적인 기술 정책 제안을 위한 한국 인공지능 지식 구조와 진화 궤적의 탐색적 분석. 한국혁신학회지, 16(3), 139-172. [DOI:https://doi.org/10.46251/INNOS.2021.8.16.3.139](https://doi.org/10.46251/INNOS.2021.8.16.3.139)

-   조한슬, 오명진, 신정우\*, **이창준**. (2021). 재난상황에서의 가짜뉴스 식별: 영상 vs 문자. 사이버커뮤니케이션학보, 38(2), 83-120. <https://doi.org/10.36494/JCAS.2021.06.38.2.83>

-   노태우, 조길수, **이창준.\*** (2021). 미국 ICT기업의 국제특허분류 공동출현 네트워크 특성에 관한 연구 : 기술유사성과 기술응용성을 중심으로. 한국혁신학회지, 16(2), 237-263. doi:<https://doi.org/10.46251/INNOS.2021.5.16.2.237>

-   **이창준\***, 우형진, 박성복. (2020). TV홈쇼핑 이용자의 상품구매 입문 요인 분석: 랜덤포레스트 분석을 활용한 개인의 미디어 레퍼토리 데이터를 중심으로. 한국혁신학회지, 15(2), 113-149. doi:<https://doi.org/10.46251/INNOS.2020.05.15.2.113>

-   김명규, **이창준**, 홍아름.\* (2016). 효과적인 정보 확산을 위한 미디어 이용 패턴 분석. 정보사회와 미디어, 17(1), 77-113. doi:<https://www.dbpia.co.kr/journal/articleDetail?nodeId=NODE06667546>

</br>

#### Book chapters

-   **Lee, C.\*** & Bae, Y. (2019). Development of Information Communication Technology Industry and Public Policy in South Korea, In Ahn, M.J., & Kim, Y. (Eds.), Public Administration and Public Policy in Korea. Springer. Doi: <https://doi.org/10.1007/978-3-319-31816-5_3801-1>

</br>

### Media Coverage

#### **AI, Media, Technology, and Policy**

-   20241128: [\[디지털데일리\] 낡은 방송 규제, 시장 환경 따라 접근법 바꿔야](https://www.ddaily.co.kr/page/view/2024112817502927085)
-   20241128: [\[연합뉴스\] 국내 미디어 향한 역차별 악성 규제 발굴해 개선해야](https://www.yna.co.kr/view/AKR20241127144000017?input=1195m)
-   20241021: [\[파이낸셜뉴스\] 국내 트래픽 30% 차지하는 구글 \[기울어진 미디어 산업\]](https://www.fnnews.com/news/202410211812590787)
-   20240715: [‘대한민국 온라인 콘텐츠 산업 진단’ 한국방송학회 기획 세미나](https://www.epnc.co.kr/news/articleView.html?idxno=304187)
-   20240715: [온라인 플랫폼 규제. 사회적 논의 반영할 수 있는 방안에 대해 고민해야](https://www.banronbodo.com/news/articleView.html?idxno=23071)
-   20240510: [한국언론학회. AI서비스와 사용자의 상호작용](https://www.etoday.co.kr/news/view/2358889)
-   20240605: [\[이데일리\] 빅테크 M&A로 엔터산업 공략. 국내기업 글로벌 확장 지원 필요](https://n.news.naver.com/mnews/article/018/0005756732?sid=105)
-   20240830: [AI 향한 창작자 태도 콘텐츠 결과물에 큰 차이 낳을 것.2024 콘텐츠유니버스](https://www.edaily.co.kr/News/Read?newsId=02624006638992568&mediaCodeNo=257&OutLnkChk=Y)
-   20240830: [\[이데일리\] AI 시대에도 콘텐츠 경쟁력은 ‘스토리텔링’에 있다](https://www.edaily.co.kr/News/Read?newsId=01167686639016184&mediaCodeNo=257&OutLnkChk=Y)
-   20230920: [언론의 생성AI 도입, 기회일까 위기일까(블루오션테크미디어)](https://www.the-tech.co.kr/news/article.html?no=36528)
-   20230914: [\[매일경제\]인공지능 시대, 언론은 살아남을 수 있을까](https://www.mk.co.kr/news/culture/10829606)
-   20220928: [\[매일경제\]韓클라우드 시장, 美中 공룡기업 놀이터로](https://www.mk.co.kr/news/it/10470733)

#### **Lifestyle and Behavioral Insights**

-   20220422: [21세기 우리가 알아야 할 필수 과목, 정보통신](https://www.sciencetimes.co.kr/news/21%EC%84%B8%EA%B8%B0-%EC%9A%B0%EB%A6%AC%EA%B0%80-%EC%95%8C%EC%95%84%EC%95%BC-%ED%95%A0-%ED%95%84%EC%88%98-%EA%B3%BC%EB%AA%A9-%EC%A0%95%EB%B3%B4%ED%86%B5%EC%8B%A0/)
-   20210728: [\[TIG 특집 ⑧\] 선생님들, 게임은 해보셨습니까?](https://www.thisisgame.com/webzine/special/nboard/11/?n=129565)
-   20210721: [\[TIG 특집 ⑥\] 셧다운제 실효성 논란 종결.여러 연구 살펴봐도 "효과 없어"](https://www.thisisgame.com/webzine/special/nboard/11/?category=1&n=129104)
-   20210509: [알고리즘, 누구냐 넌!](http://www.hynews.ac.kr/news/articleView.html?idxno=10923)
-   20210405: [너란 SNS 광고](http://www.hynews.ac.kr/news/articleView.html?idxno=10812)
-   20201224: [\[신문 읽어주는 교수님\] 늦은 밤 넷플릭스 시청이 수면에 미치는 영향](http://www.newshyu.com/news/articleView.html?idxno=1001102)
-   20201202: [수면 루틴 깨는 OTT.잠자리 26분 늦어지고 수면시간 30분 줄어](https://ddaily.co.kr/page/view/2020120211021627520)
-   20201202: [넷플릭스 유튜브 보느라 얼마나 늦게 잠드나요?](http://www.mediatoday.co.kr/news/articleView.html?idxno=210652)

#### **Academic and Mentorship Activities**

-   20241208: [올림플래닛, 성균관대와 확장현실(XR) 기술 활성화 맞손](https://www.metroseoul.co.kr/article/20241208500254)
-   20241003: [2024-1 SKKU 컬처앤테크놀로지 Best Professor](https://www.youtube.com/watch?v=XvXhc-Htn-k)
-   20240305: [2023-2 SKKU 컬처앤테크놀로지 Best Professor](https://www.youtube.com/watch?v=5BqwSXRI18g&t=110s)
-   20231218: [\[성대의 성대한 특강\] 우리 모두가 공유하는 회복탄력성 레시피](https://www.youtube.com/watch?v=ElBFEW-FioM&t=10s)
-   20210223: [한양대 슬기로운 새내기 생활(교수님편)](https://www.youtube.com/watch?v=P7VJqjIMJWM)
-   20200406: [서울대학교 기술경영경제정책 대학원 졸업생 멘토링 세미나](https://temep.snu.ac.kr/?cid=announcement/news-and-events&bm=v&bbsidx=1680)
-   20200812: [에퀴즈 온 더 블럭 (사랑한대)](https://www.youtube.com/watch?v=YJ8nux4nczM&t=6s)
-   20200713: [ERICA 방송국 VOH와 취중젠담 2편](https://www.youtube.com/watch?v=5McJDbjrPMk&t=199s)
-   20200627: [ERICA 방송국 VOH와 취중젠담 1편](https://www.youtube.com/watch?v=W-32_yvmuAU&t=327s)
