---
title: Publications
---

#### International SSCI or SCIE

-   Liu, H. S., **Lee, C.**, Kim, K., Lee, J., Moon, A., Lee, D., & Park, M. (2023). An Analysis of Factors Influencing the Intention to Use" Untact" Services by Service Type. *Sustainability*, *15*(4), 2870. <https://www.mdpi.com/2071-1050/15/4/2870>

-   Shim, D., **Lee, C.**, & Oh, I. (2022). Analysis of OTT Users' Watching Behavior for Identifying a Profitable Niche: Latent Class Regression Approach. *Journal of Theoretical and Applied Electronic Commerce Research*, *17*(4), 1564-1580. <https://www.mdpi.com/0718-1876/17/4/79>

-   Kim, K., Kogler, D. F., **Lee, C.,** & Kang, T.\* (2022). Changes in regional knowledge bases and its effect on local labour markets in the midst of transition: Evidence from France over 1985--2015. *Applied Spatial Analysis and Policy*, 1-22. <https://doi.org/10.1007/s12061-022-09444-4>

-   Shon, M., Lee, D. & **Lee, C.**(2022). Inward or Outward? Direction of Knowledge Flow and Firm Efficiency. *International Journal of Technology Management. 90*(1-2), 102-121. <https://doi.org/10.1504/IJTM.2022.124617>

-   Park, I., Lee, J., Lee, D., **Lee, C.**, & Chung, W. Y.\* (2022). Changes in consumption patterns during the COVID-19 pandemic: Analyzing the revenge spending motivations of different emotional groups. *Journal of Retailing and Consumer Services*, 65, 102874. <https://doi.org/10.1016/j.jretconser.2021.102874>

-   **Lee, C.**, Shin, H., Kim, K., & Kogler, D. F.\* (2022). The effects of regional capacity in knowledge recombination on production efficiency. *Technological Forecasting and Social Change*. *180*, 121669. <https://doi.org/10.1016/j.techfore.2022.121669>

-   Jung, E., **Lee, C.**\*, & Hwang, J. (2022). Effective strategies to attract crowdfunding investment based on the novelty of business ideas. *Technological Forecasting and Social Change*. *178*, 121558. <https://doi.org/10.1016/j.techfore.2022.121558>

-   Jeon, H., & **Lee, C.**\* (2022). Internet of Things Technology: Balancing Privacy Concerns with Convenience. *Telematics and Informatics. 70*, 101816. <https://doi.org/10.1016/j.tele.2022.101816>

-   Kogler, D. F., Davies, R. B., **Lee, C.**, & Kim, K.\* (2022). Regional knowledge spaces: the interplay of entry-relatedness and entry-potential for technological change and growth. *The Journal of Technology Transfer*. 1-24. <https://doi.org/10.1007/s10961-022-09924-2>

-   Tóth, G., Elekes, Z., Whittle, A., **Lee, C.**\*, & Kogler, D. F. (2022). Technology network structure conditions the economic resilience of regions. *Economic Geography. 98*(4), 1-24. <https://doi.org/10.1080/00130095.2022.2035715>

-   Jo, H., Park, S., Shin, D., Shin, J.\*, & **Lee, C.** (2022). Estimating cost of fighting against fake news during catastrophic situations. *Telematics and Informatics*. *66*, 101734. <https://doi.org/10.1016/j.tele.2021.101734>

-   Park, I., Shim, H., Kim, J., **Lee, C.**, & Lee, D.\* (2022). The Effects of Popularity Metrics in News Comments on the Formation of Public Opinion: Evidence from an Internet Portal Site. *The Social Science Journal.* doi:<https://doi.org/10.1080/03623319.2020.1768485>

-   Kim, K., Lee, J., & **Lee, C.**(2022). Which innovation type is better for production efficiency? A comparison between product/service, process, organizational, and marketing innovations using stochastic frontier and meta-frontier analysis. *Technology Analysis & Strategic Management.* doi: <https://doi.org/10.1080/09537325.2021.1965979>

-   Rocchetta, S.*, Mina, A*., **Lee, C.**, & Kogler, F. D. (2022). Technological Knowledge Space and the Resilience of European Regions. *Journal of Economic Geography. 22(1), 27-51*.\* doi: <https://doi.org/10.1093/jeg/lbab001>

-   **Lee, C.**, Cho, H., & Lee, D.\* (2021). The mechanism of innovation spill-over across sub-layers in the ICT industry. *Asian Journal of Technology Innovation. 29*(2), 159-179. doi:<https://doi.org/10.1080/19761597.2020.1796725>

-   Jung, S., Kim, K. & **Lee, C.**(2021). The nature of ICT in technology convergence: A knowledge-based network analysis. *PLOS ONE.* *16*(7): e0254424. <https://doi.org/10.1371/journal.pone.0254424>

-   Na, C., Lee, D., Hwang, J., & **Lee, C.**\* (2021). Strategic Groups Emerged by Selecting R&D Collaboration Partners and Firms' Efficiency. *Asian Journal of Technology Innovation. 29*(1), 109-133. doi:<https://doi.org/10.1080/19761597.2020.1788957>

-   **Lee, C.**, Lee, D., & Shon, M.\* (2020). Effect of efficient triple-helix collaboration on organizations based on their stage of growth. *Journal of Engineering and Technology Management*. *58*, 101604. <https://doi.org/10.1016/j.jengtecman.2020.101604>

-   **Lee, C.**, Kogler, D.F., & Lee, D.\* (2019). Capturing Information on Technology Convergence, International Collaboration, and Knowledge Flow from Patent Document: A Case of Information and Communication Technology. *Information Processing & Management. 56*(4), 1576-1591. doi:[1016/j.ipm.2018.09.007](https://doi.org/10.1016/j.ipm.2018.09.007)

-   Kim, E.H.W.\* & **Lee, C.** (2019). Does Working Long Hours Cause Marital Dissolution? Evidence from the Reduction in South Korea's Workweek Standard. *Asian Population Studies. 15*(1), 87-104. doi:[1080/17441730.2019.1565131](https://doi.org/10.1080/17441730.2019.1565131)

-   Kim E.H.W.\*, **Lee, C.**, & Do, Y.K. (2019). The Effect of Adult Children's Working Times on Visiting with Elderly Parents: A Natural Experiment in Korea. *Population Research and Policy Review. 38*(1), 53-72. doi:[1007/s11113-018-9486-0](https://doi.org/10.1007/s11113-018-9486-0)

    -   Featured in: *Straits Times, Lianhe Zaobao* (In Chinese)

-   **Lee, C.**\* & Hwang, J. (2018). The Influence of Giant Platform on Content Diversity. *Technological Forecasting and Social Change. 136*, 157-165. doi:[1016/j.techfore.2016.11.029](http://dx.doi.org/10.1016/j.techfore.2016.11.029)

-   Kim, E.H.W.\*, **Lee, C.**, & Do Y.K. (2018). The Effect of a Reduced Statutory Workweek on Familial Long-Term Care in Korea. *Journal of Aging and Health. 30*(10), 1620-1641. doi:[1177/0898264318797469](https://doi.org/10.1177/0898264318797469)

    -   Poster Session Winner, 2018 Population Association of America Conference

<!-- -->

-   **Lee, C.** & Kim, H.\* (2018). The Evolutionary Trajectory of ICT Ecosystem: A Network Analysis based on Media User Data. *Information & Management*. *55*(6), 795-805. doi:[1016/j.im.2018.03.008](https://doi.org/10.1016/j.im.2018.03.008)

    -   Best Paper Award, 2015 Korea Media Panel Conference

-   **Lee, C.**, Shin, J., & Hong, A.\* (2018). Does Social Media Use Really Make People Politically Polarized? Direct and Indirect Effects of Social Media Use on Political Polarization. *Telematics and Informatics*. *35*(1), 245-254. doi:[1016/j.tele.2017.11.005](https://doi.org/10.1016/j.tele.2017.11.005)

-   Na, H.S., Lee, D., Hwang, J., & **Lee, C.**(2018). Research on the Mutual Relations between ISP and ASP Efficiency Changes for the Sustainable Growth of Internet Industry. *Applied Economics.* *50*(11), 1238-1253. doi:[1080/00036846.2017.1358443](https://doi.org/10.1080/00036846.2017.1358443)

-   **Lee, C.**, Kim, J.H., & Lee, D.\* (2017). Intra-industry Innovation, Spillovers, and Industry Evolution: Evidence from the Korean ICT industry. *Telematics and Informatics.* *34*(8), 1503-1513. doi:[1016/j.tele.2017.06.013](https://doi.org/10.1016/j.tele.2017.06.013)

-   **Lee, C.**, Jung, S., & Kim, K.O.\* (2017). Effect of a Policy Intervention on Handset Subsidies on the Intention to Change Handsets and Households' Expenses in Mobile Telecommunications. *Telematics and Informatics.* *34*(8), 1524-1531. doi:[1016/j.tele.2017.06.017](https://doi.org/10.1016/j.tele.2017.06.017)

-   **Lee, C.**, Kim, H., & Hong, A.\* (2017). Ex-post Evaluation of Illegalizing Juvenile Online Game after Midnight: A Case of Shutdown Policy in South Korea. *Telematics and Informatics.* *34*(8), 1597-1606. doi:[1016/j.tele.2017.07.006](https://doi.org/10.1016/j.tele.2017.07.006)

    -   Cited in Nature Editorial <http://www.nature.com/news/put-cult-online-games-to-the-test-1.22343>

-   **Lee, C.**, Lee, K., & Lee, D.\* (2017). Mobile Healthcare Applications and Gamification for Sustained Health Maintenance. *9*(5), 772. doi:[10.3390/su9050772](https://doi.org/10.3390/su9050772)

-   **Lee, C.**, Lee, D.\*, & Hwang, J. (2015). Platform Openness and the Productivity of Content Providers: A meta-frontier analysis. *Telecommunications Policy. 39*(7). 553-562. doi:1016/j.telpol.2014.06.010

</br>

#### Korean Citation Index (KCI) Journals

-   Choi, M. & **Lee, C.**\* (2022). The effect of Online Community Activities in Non-face-to-face Situations on Life Satisfaction : Focusing on the Comparison between Before(2017) and After(2021) COVID-19. *Information Society & Media.* *23*(3), 83-124. <https://doi.org/52558/ISM.2022.12.23.3.83>

-   Yeom, J., Lee, S., & **Lee, C.**\* (2022). Analysis of the Characteristics of Extreme Patriotism and Psychological Motives by Understanding the Cyber Conflict Between Chinese Fandom Patriotism and Hallyu Fandom. *Journal of Cybercommunication Academic Society. 39*(4). 5-49. <https://doi.org/10.36494/JCAS.2022.12.39.4.5>

-   Kang, S., Seo, Y., & **Lee, C.**\* (2022). A Study of the Development of Sectoral Digital Transformation Conflict Indicator. *Information Society & Media.* *23*(1), 41-68. <https://doi.org/52558/ISM.2022.04.23.1.41>

    -   Best Paper Award, 2022 Korea Media Management Association

-   Kim, K., Lee, J., & **Lee, C.**\* (2021). Exploratory Analysis of Knowledge Structure and Evolutionary Trajectory in Korean Artificial Intelligence for Effective Technology Policy. *Korean Innovation Study*, 16(3). [DOI:https://doi.org/10.46251/INNOS.2021.8.16.3.139](https://doi.org/10.46251/INNOS.2021.8.16.3.139)

-   Jo, H., Oh, M., Shin, J.\*, & **Lee, C.** (2021). Identifying Fake news in the Disastrous situations: Video versus Text. *Journal of Cybercommunication Academic Society*, 38(2).  DOI: <https://doi.org/10.36494/JCAS.2021.06.38.2.83>

-   Roh, T., Jo, G., & **Lee, C.**\* (2021). Coincidence Analysis with International Patent Classification (IPC) Network of US ICT Companies: Focusing on Technology Similarity and Application. *Korean Innovation Study*, 16(2).  doi:<https://doi.org/10.46251/INNOS.2021.5.16.2.237>

-   **Lee, C.**, Woo, H.J., & Park, S.B. (2020). Factors of newly entering into the purchase on TV home-shopping: Random Forest Analysis based on users' media repertoire data. *Korean Innovation Study*, 15(2), 113-149. doi:<https://doi.org/10.46251/INNOS.2020.05.15.2.113>

-   Kim, M.K., **Lee, C.**, & Hong, A. (2016). The Analysis of Media Usage Pattern for Effective Diffusion of Information. *Information Society & Media. 17*(1). 77-113. doi:<https://www.dbpia.co.kr/journal/articleDetail?nodeId=NODE06667546>

</br>

#### Book chapters

-   **Lee, C.** & Bae, Y. (2019). Development of Information Communication Technology Industry and Public Policy in South Korea, In Ahn, M.J., & Kim, Y. (Eds.), Public Administration and Public Policy in Korea. Springer. Doi: <https://doi.org/10.1007/978-3-319-31816-5_3801-1>

</br>
