---
title: Working in Progress
---

## **Under Review**

-   Dominant and Spark Technologies in Business Methods Innovation

    -   with Keungoui Kim, Dieter F. Kogler, Junmin Lee

-   Grandma's digital play goes to FinTech

    -   with Yoonwoo Choi

-   Movie-Country Relatedness Density and Entry TOP20

    -   with Sung Wook Ji

-   Social Distancing, Innovation Adoption, and Privacy Concern

    -   with Keungoui Kim, Dongnyuk Shim, and Sira Maliphol

-   메타버스의 의미를 통한 네트워크 의제설정 작용원리 탐색 연구

    -   with 박영주, 박세진

-   시니어 SNS 적극적 활용 요인 분석

    -   with 박지은
    
-------------------
## **Working papers**

### *Innovation studies*

-   Regional Knowledge Transformation

    - with Dieter F. Koger, Keungoui Kim, Myungjin Oh

-   Regional Knowledge Structure & Recombination

    - with Dieter F. Koger

-   Government Financial Support on Innovation Performance
   
    - with Chungho Na

-   디지털 트랜스포메이션 생태계 분석
  
    - with 이경선, 박유리

### *Media studies* 

-   Media Relatedness & Political Polarization

    - Keungoui Kim

-   메타버스 사회적 자본이 아바타 커스터마이징에 끼치는 영향
  
    - with 이승경, 최윤슬, 박영주

-   요일과 시간효과를 고려한 OTT vs. TV 선택 모형

    - 심동녘

-   블록체인 기반 미디어 플랫폼 선택 모형
