---
title: About ML101
---

## Course description

::: {.callout-note icon="false"}
### Goal

This course covers the fundamentals of the field, including supervised and unsupervised learning algorithms, regression, classification, and clustering. The course may also cover topics such as model evaluation, feature selection, and regularization.

In a supervised learning setting, students learn about linear regression and logistic regression, as well as more complex algorithms such as Naive Bayes, decision trees, random forests, and kNN. They learn how to train models on a labeled dataset and make predictions on new data.

In an unsupervised learning setting, students learn about clustering algorithms such as k-means and Apriori. They learn how to extract meaningful structure from unlabeled data.

The course may also cover advanced topics such as natural language processing. Students learn how to implement and use these algorithms in R.

Throughout the course, students work on practical projects and assignments to apply the concepts they have learned. By the end of the course, students should have a solid understanding of the basics of machine learning and be able to apply these concepts to real-world problems.
:::

## Syllabus

------------------------------------------------------------------------

-   **Week 1: Introduction to Data Science and R**

-   **Week 2:** About ML & Modelling

------------------------------------------------------------------------

### PART I: Classification

-   **Week 3:** Decision Tree

-   **Week 4:** Random Forest

-   **Week 5:** Naive Bayes

-   **Week 6:** Public Holiday

-   **Week 7:** kNN

-   **Week 8:** **QZ #1**

------------------------------------------------------------------------

### PART II: Regression

-   **Week 9:** Linear regression

-   **Week 10:** Non-linear regression

------------------------------------------------------------------------

### PART III: Unsupervised Learning

-   **Week 11:** Clustering

-   **Week 12:** Apriori

------------------------------------------------------------------------

### PART IV: Model Improvement

-   **Week 13:** Performance Evaluation

-   **Week 14:** Wrap-up

-   **Week 15: QZ #2**

-   **Week 16: Project Presentation**

## Weekly Design

+----------+------------+----------------------------+--------------+----------------------+----------------------------------+
| Week     | Date       | Pre-class                  | Class        | PBL                  | Note                             |
+:========:+:==========:+:===========================+:============:+:====================:+==================================+
| 1        | 09/02/2025 |                            | Course intro |                      | Participate Ars Electronica\     |
|          |            |                            |              |                      | \<Recorded Lecture\>             |
+----------+------------+----------------------------+--------------+----------------------+----------------------------------+
| 2        | 09/09/2025 | Install R & R Studio       | Practice     |                      |                                  |
|          |            |                            |              |                      |                                  |
|          |            | About ML & Modelling       |              |                      |                                  |
+----------+------------+----------------------------+--------------+----------------------+----------------------------------+
| 3        | 09/16/2025 | **Classification**         | Practice     | Problem description  |                                  |
|          |            |                            |              |                      |                                  |
|          |            | -   Decision Tree          |              |                      |                                  |
+----------+------------+----------------------------+--------------+----------------------+----------------------------------+
| 4        | 09/23/2025 | -   Random Forest          | Practice     | Data introduction    |                                  |
+----------+------------+----------------------------+--------------+----------------------+----------------------------------+
| 5        | 09/30/2025 | -   Naive Bayes            | Practice     | Team arrangement     |                                  |
+----------+------------+----------------------------+--------------+----------------------+----------------------------------+
| 6        | 10/07/2025 |                            |              |                      | Thanks giving holiday (추석연휴) |
+----------+------------+----------------------------+--------------+----------------------+----------------------------------+
| 7        | 10/14/2025 | -   kNN                    | Practice     | Team meeting #1      |                                  |
+----------+------------+----------------------------+--------------+----------------------+----------------------------------+
| 8        | 10/21/2025 | **Regression**             | Practice     | Team meeting #2      |                                  |
|          |            |                            |              |                      |                                  |
|          |            | -   Linear regression      |              |                      |                                  |
+----------+------------+----------------------------+--------------+----------------------+----------------------------------+
| 9        | 10/28/2025 | **QZ #1**                  |              | Team meeting #3      |                                  |
+----------+------------+----------------------------+--------------+----------------------+----------------------------------+
| 10       | 11/04/2025 | -   Non-linear regression  | Practice     | Team meeting #4      |                                  |
+----------+------------+----------------------------+--------------+----------------------+----------------------------------+
| 11       | 11/11/2025 | **Unsupervised learning**  | Practice     | Team meeting #5      |                                  |
|          |            |                            |              |                      |                                  |
|          |            | -   Clustering             |              |                      |                                  |
+----------+------------+----------------------------+--------------+----------------------+----------------------------------+
| 12       | 11/18/2025 | -   Apriori                | Practice     | Team meeting #6      |                                  |
+----------+------------+----------------------------+--------------+----------------------+----------------------------------+
| 13       | 11/25/2025 | **Model improvement**      | Practice     | Team meeting #7      |                                  |
+----------+------------+----------------------------+--------------+----------------------+----------------------------------+
| 14       | 12/02/2025 | Text mining & other skills | Practice     | Team consulting #1   |                                  |
+----------+------------+----------------------------+--------------+----------------------+----------------------------------+
| 15       | 12/9/2025  | **QZ #2**                  |              | Team consulting #2   |                                  |
+----------+------------+----------------------------+--------------+----------------------+----------------------------------+
| 16       | 12/16/2025 | **Proj Report**            |              | Project Presentation |                                  |
+----------+------------+----------------------------+--------------+----------------------+----------------------------------+

: {.secondary .hover}

<br>

## Course management

<br>

-   **Lecturer:** Changjun Lee (Associate Professor in SKKU School of Convergence)

    -   [changjunlee\@skku.edu]{.underline}

-   **TA:** Yebom Choi (Master course student in SKKU Graduate School of Interaction Science)

    -   yebom618\@g.skku.edu

<!-- -->

-   **Time:**

    -   (1h): Flipped learning content

    -   (2h): **Tue** 09:00 \~ 10:50

-   **Location:** \[70527\] 중앙학술정보관 Active Learning Classroom(70527)

<br>

> Class consists of **Pre-class**, **Class**, and **PBL project**

-   **Pre-class**

    -   Students will be required to watch the lecturer’s recorded lecture (or other given videos) before the off-line (or online streaming ZOOM) class and learn themselves

    -   Video is about the concept of the ML algorithms

    -   (Sometimes) Students are required to submit Discussions to check the level of their understanding

-   **Class**

    -   Lecturer summarize the pre-class lecture and explain more details

        -   Ask students about the pre-class content to check whether they learned themselves

        -   OK to answer incorrectly, but if you cannot answer at all, it will be reflected in your pre-class discussion score.

    -   Students will practice with the advanced code

    -   A Quiz will be in the class to check the level of understanding

-   **PBL project**

    -   Students organize teams that meet several conditions.

        -   4\~5 members in a team

        -   Background diversity: no homogeneous majors in a team

        -   Exception: Allowed if persuasion is possible for sufficient reasons

    -   Data will be given. Teams are going to choose the data they want to explore considering their interest

    -   Teams can offer a zoom meeting with lecturer if they need

<br>

## Final outputs (An example not limited)

-   Data Preparing (or Collecting)

-   Explore data (Descriptive stats)

-   Set your hypothesis (or research questions)

-   Modeling

-   Scoring the models

-   Expanding your findings to implications

<br>

## Textbooks for the course

-   **R4DS:** [R for Data Science](https://r4ds.had.co.nz/index.html) (written by *Hadley Wickham* and *Garrett Grolemund*)
    -   is an excellent resource for learning data science using R, covering data manipulation, visualization, and modeling with R. The book is available as a free online resource.
-   **RC2E:** [R Cookbook](https://rc2e.com/) (written by *JD Long* and *Paul Teetor*)
    -   is a comprehensive resource for data scientists, statisticians, and programmers who want to explore the capabilities of R programming for data analysis and visualization.
-   **RGC:** [R Graphic Cookbook](https://r-graphics.org/index.html) (written by *Winston Chang)*
    -   is a practical guide that provides more than 150 recipes to help you generate high-quality graphs quickly, without having to comb through all the details of R's graphing systems
-   **MDR:** [Statistical Inference via Data Science (Modern Dive)](https://moderndive.com/index.html) (written by *Chester Ismay* and *Albert Y. Kim*)
    -   is a comprehensive textbook that provides an accessible and hands-on approach to learning the fundamental concepts of statistical inference and data analysis using the R programming language.
-   **ISR:** [Introductory Statistics with R](https://link.springer.com/book/10.1007/978-0-387-79054-1) (written by *Peter Dalgaard*)
    -   is a great resource for learning basic statistics with a focus on R programming. This book covers a wide range of statistical concepts, from descriptive statistic

<br>

## Grade

-   Attendance & Participation (20 %)

-   QZs (40 %)

-   Project (40 %)

<br>

## Communication

-   Notices & Questions

    -   Please join Kakao open-chat room

        -   <https://open.kakao.com/o/gMQqodPh>

        -   When you enter, please make sure to enter your name as it is on the attendance sheet. (입장하셔서 이름을 꼭 출석부에 있는 이름으로 설정해주세요.)

-   Personal counsel (Scholarship, recommendation letter, etc.)

    -   CJ-counselling room (Anything but the class content)

        -   CJ상담실: <https://open.kakao.com/o/s8zTrYCf>
