<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Classification – CJL &amp; Lab</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../../">
<script src="../../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../../../index.html">
    <span class="navbar-title">CJL &amp; Lab</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-courses" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Courses</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-courses">    
        <li>
    <a class="dropdown-item" href="../../../../teaching/index.html">
 <span class="dropdown-text">All Courses</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../../teaching/ds101/index.html">
 <span class="dropdown-text">DS101</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../../teaching/ml101/index.html">
 <span class="dropdown-text">ML101</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../../teaching/grad_stat/index.html">
 <span class="dropdown-text">STAT101</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../../teaching/grad_immersive/index.html">
 <span class="dropdown-text">IMUX</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../../../../research/index.html"> 
<span class="menu-text">Research</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../../blogs/index.html"> 
<span class="menu-text">Blogs</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://axislab.netlify.app/"> 
<span class="menu-text">LAB</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#pre-class-video" id="toc-pre-class-video" class="nav-link active" data-scroll-target="#pre-class-video">Pre-class video</a></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">Discussion</a></li>
  <li><a href="#class" id="toc-class" class="nav-link" data-scroll-target="#class">Class</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Classification</h1>
<p class="subtitle lead">Decision Tree</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><a href="https://changjunlee.com/teaching/ml101/weekly/">Weekly design</a></p>
<p><br></p>
<section id="pre-class-video" class="level3">
<h3 class="anchored" data-anchor-id="pre-class-video">Pre-class video</h3>
<ul>
<li>Learning Types</li>
</ul>
<div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://www.youtube.com/embed/9E8oYU54204" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
<ul>
<li>Supervised learning &amp; Decision Tree</li>
</ul>
<div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://www.youtube.com/embed/UX0PVh-CVkw" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
<ul>
<li>Pre-class PPT <a href="content/ML_pre_03_1.pdf">pdf</a></li>
</ul>
<hr>
</section>
<section id="discussion" class="level3">
<h3 class="anchored" data-anchor-id="discussion">Discussion</h3>
<p>Discussion #2</p>
<iframe src="https://docs.google.com/forms/d/e/1FAIpQLScCxepSa9qy9zmrguoRQc5eO0bCCcb_3Sq-SulwkE4ZIfYciQ/viewform?embedded=true" width="640" height="1900" frameborder="0" marginheight="0" marginwidth="0">
<p>Loading…</p>
</iframe>
<hr>
</section>
<section id="class" class="level3">
<h3 class="anchored" data-anchor-id="class">Class</h3>
<hr>
<section id="why-do-we-need-various-ml-algorithms" class="level4">
<h4 class="anchored" data-anchor-id="why-do-we-need-various-ml-algorithms">Why do we need various ML algorithms?</h4>
<blockquote class="blockquote">
<p>“Each machine learning algorithm serves a specific purpose, much like how each individual serves a unique role in society. There is no one superior ML algorithm, as each is used for a different purpose.”</p>
</blockquote>
<p><img src="img/why_ml.png" class="img-fluid"></p>
<p><br></p>
<ol type="1">
<li><p><strong>Different types of data and problems</strong>: Different ML algorithms are suited to different types of data and problems. For example, linear regression is well-suited for continuous numerical data, while decision trees are well-suited for categorical data. Similarly, some algorithms are better suited for classification problems (predicting a categorical outcome), while others are better suited for regression problems (predicting a continuous outcome).</p></li>
<li><p><strong>Performance trade-offs:</strong> Different ML algorithms can have different trade-offs in terms of performance and interpretability. For example, some algorithms, like k-nearest neighbors, are simple to understand and interpret, but may not perform as well as more complex algorithms like neural networks. On the other hand, some algorithms, like deep learning, can achieve very high performance, but may be more difficult to interpret.</p></li>
<li><p><strong>Model assumptions:</strong> Different ML algorithms make different assumptions about the relationship between the predictors and the outcome. For example, linear regression assumes a linear relationship, while decision trees do not make this assumption. Selecting the appropriate algorithm depends on the nature of the problem and the data, as well as the goals of the analysis.</p></li>
<li><p><strong>Computational resources</strong>: Some ML algorithms are more computationally intensive than others, and may require more resources (such as memory and processing power) to fit and use. In some cases, a more complex algorithm may be necessary to achieve the desired level of performance, but in other cases, a simpler algorithm may be sufficient.</p></li>
<li><p><strong>Model interpretability</strong>: Some ML algorithms are more interpretable than others, which can be important in certain applications. For example, in medical applications, it may be important to understand why a model is making a certain prediction, while in other applications, it may be more important to simply achieve high accuracy.</p></li>
</ol>
<p>The choice of ML algorithm depends on the data, the problem, and the goals of the analysis, and it is important to consider these factors when selecting an algorithm.</p>
<p><br></p>
</section>
<section id="decision-tree" class="level4">
<h4 class="anchored" data-anchor-id="decision-tree">Decision Tree</h4>
<blockquote class="blockquote">
<p>Generates a set of rules that allow for accurate predictions <strong><em>using one explanatory variable at a time,</em></strong> resulting in a structure similar to an <strong>inverted tree: decision tree</strong></p>
<p><strong>한번에 하나씩의 설명 변수를 사용하여 정확한 예측이 가능한 규칙들의 집합을 생성.</strong></p>
</blockquote>
<p><img src="img/dt_eg.png" class="img-fluid"></p>
</section>
<section id="terminologies" class="level4">
<h4 class="anchored" data-anchor-id="terminologies">Terminologies</h4>
<ol type="1">
<li><p><strong>Node</strong>: A point in the decision tree where a decision or split is made.</p></li>
<li><p><strong>Parent</strong> <strong>node</strong>: A node that has other nodes connected to it, called child nodes.</p></li>
<li><p><strong>Child</strong> <strong>node</strong>: A node that is connected to a parent node and splits off in a different direction in the tree.</p></li>
<li><p><strong>Split</strong> <strong>criterion</strong>: The criterion used to determine the split at each node in the decision tree. This can be based on various measures such as information gain, Gini impurity, or chi-squared statistic.</p></li>
<li><p><strong>Root</strong> <strong>node</strong>: The top node in the decision tree that represents the entire dataset.</p></li>
<li><p><strong>Leaf</strong> <strong>node</strong>: A node in the decision tree that represents a final prediction or classification, as it does not have any child nodes connected to it.</p></li>
</ol>
<p><img src="img/dt_term.png" class="img-fluid"></p>
<p>Then, “Why is it called a ‘decision’ tree?”</p>
<ul>
<li><p>This is because it presents results in the form of easily understandable rules,</p></li>
<li><p>reduces the need for pre-processing data such as normalization or imputation,</p></li>
<li><p>and considers both numeric and categorical variables as its independent variables (features).</p></li>
</ul>
</section>
<section id="essential-ideas-of-decision-tree" class="level4">
<h4 class="anchored" data-anchor-id="essential-ideas-of-decision-tree">Essential ideas of decision tree</h4>
<ul>
<li><p><strong>Recursive Partitioning:</strong> The process of dividing the input variable space into two parts, with the goal of increasing the purity of each area after separation rather than before separation</p></li>
<li><p><strong>Pruning the Tree:</strong> The process of consolidating areas that have been separated into overly detailed regions in order to prevent overfitting.”</p></li>
</ul>
<p><br></p>
</section>
<section id="impurity-index-1-gini-index" class="level4">
<h4 class="anchored" data-anchor-id="impurity-index-1-gini-index">Impurity index 1: Gini index</h4>
</section>
<section id="ia1-sum_k-1c-p_k2" class="level4">
<h4 class="anchored" data-anchor-id="ia1-sum_k-1c-p_k2"><span class="math display">\[
I(A)=1-\sum_{k = 1}^{c} p_k^2
\]</span></h4>
<ul>
<li><p><span class="math inline">\(I(A)\)</span> is Gini index of A area in which there is c number of classes</p></li>
<li><p><span class="math inline">\(P_k\)</span> is number of observations in k class</p></li>
</ul>
<p><img src="img/gini_1.png" class="img-fluid"></p>
</section>
<section id="ia1-sum_k-1c-p_k2-1-frac6162-frac10162-0.4688" class="level4">
<h4 class="anchored" data-anchor-id="ia1-sum_k-1c-p_k2-1-frac6162-frac10162-0.4688"><span class="math display">\[
I(A)=1-\sum_{k = 1}^{c} p_k^2
=1-(\frac{6}{16})^2-(\frac{10}{16})^2 = 0.4688
\]</span></h4>
<ul>
<li><p><span class="math inline">\(I(A)\)</span> is 0 when there are only one category in area c</p></li>
<li><p><span class="math inline">\(I(A)\)</span> is 0.5 when there are half of one and half of another category in area c</p></li>
</ul>
<p><br></p>
</section>
<section id="gini-index-when-there-are-two-or-more-areas" class="level4">
<h4 class="anchored" data-anchor-id="gini-index-when-there-are-two-or-more-areas">Gini index when there are two or more areas</h4>
<p><span class="math display">\[
I(A)=\sum_{i = 1}^{d} (R_i(1-\sum_{k = 1}^{c} p_{ik}^2))
\]</span></p>
<ul>
<li><p>After splitting the area A, <span class="math inline">\(I(A)\)</span> is Gini Index for two or more areas</p></li>
<li><p><span class="math inline">\(R_i\)</span> is a ratio of i area in A</p></li>
</ul>
<p><img src="img/gini_2.png" class="img-fluid"></p>
</section>
<section id="ia-frac816-times-1-frac782--frac182-frac816-times-1-frac382--frac5820.3438" class="level4">
<h4 class="anchored" data-anchor-id="ia-frac816-times-1-frac782--frac182-frac816-times-1-frac382--frac5820.3438"><span class="math display">\[
I(A)=
\frac{8}{16}
\times
(1-(\frac{7}{8})^2 -(\frac{1}{8})^2)+
\frac{8}{16}
\times
(1-(\frac{3}{8})^2 -(\frac{5}{8})^2)=0.3438
\]</span></h4>
<ul>
<li>After splitting, the information gain is <span class="math inline">\(0.4668 - 0.3438=0.1250\)</span></li>
</ul>
<p><br></p>
</section>
<section id="impurity-index-2-deviance" class="level4">
<h4 class="anchored" data-anchor-id="impurity-index-2-deviance">Impurity index 2: Deviance</h4>
<p><span class="math display">\[
D_i = -2 \sum_{k}n_{ik} log(P_{ik})
\]</span></p>
<ul>
<li><p><span class="math inline">\(i\)</span> is node index</p></li>
<li><p><span class="math inline">\(k\)</span> is class index</p></li>
<li><p><span class="math inline">\(P_{ik}\)</span> is a probability of class <em>k</em> in node <em>i</em></p></li>
</ul>
<p><img src="img/gini_1.png" class="img-fluid"></p>
<p><span class="math display">\[
D_i = -2 \times (10 \times log (\frac{10}{16})  + 6 \times
(\frac{6}{16}))=21.17
\]</span></p>
<p><br></p>
<p><img src="img/gini_2.png" class="img-fluid"></p>
<p><span class="math display">\[
D_1 =
-2 \times (7 \times log (\frac{7}{8})  +
1 \times log(\frac{1}{8}))=6.03
\]</span></p>
<p><span class="math display">\[
D_2 =
-2 \times (3 \times log (\frac{3}{8})  +
5 \times log(\frac{5}{8}))=10.59
\]</span></p>
<p><span class="math display">\[
D_1 + D_2 = 16.62
\]</span></p>
<p><br></p>
<ul>
<li>After splitting, the information gain is <span class="math inline">\(21.17 - 16.62=4.55\)</span></li>
</ul>
<p><br></p>
</section>
<section id="over-fitting-issue" class="level4">
<h4 class="anchored" data-anchor-id="over-fitting-issue">Over-fitting issue</h4>
<ul>
<li><p>Over-fitting is a common issue in machine learning algorithms, including decision trees. It occurs when a model learns the training data too well and captures not only the underlying patterns but also the noise present in the data. As a result, the model becomes too complex and performs poorly on new, unseen data, even though it may have high accuracy on the training data.</p></li>
<li><p>In the context of decision trees, over-fitting can occur when the tree becomes too deep, with many levels and branches. A deep tree may split the training data into very specific and detailed regions, resulting in a model that is too tailored to the training data and not generalizable to new data.</p></li>
</ul>
<p><img src="img/over_fit.png" class="img-fluid"> <br></p>
<ul>
<li>To address over-fitting in decision trees, several techniques can be employed:</li>
</ul>
<ol type="1">
<li><p><strong>Pruning</strong>: This involves trimming the tree by removing branches that do not significantly improve the model’s performance. Pruning can be done in a top-down manner (pre-pruning), where the tree is stopped from growing further once a certain depth or node count is reached, or in a bottom-up manner (post-pruning), where the tree is fully grown and then branches are removed based on certain criteria.</p></li>
<li><p><strong>Limiting tree depth</strong>: By setting a maximum depth for the tree, the algorithm is forced to make fewer splits and create a simpler model, reducing the likelihood of over-fitting.</p></li>
<li><p><strong>Using minimum node size</strong>: Setting a minimum number of samples required to create a split or leaf node can prevent the tree from making splits that are too specific to the training data.</p></li>
<li><p><strong>Cross-validation</strong>: This technique involves splitting the data into multiple training and validation sets and averaging the model’s performance across these sets. Cross-validation can help in choosing the optimal tree depth and other hyper-parameters that lead to the best generalization performance.</p></li>
</ol>
<p><br></p>
</section>
<section id="pruning" class="level4">
<h4 class="anchored" data-anchor-id="pruning">Pruning</h4>
<p><img src="img/pruning.png" class="img-fluid"> <br></p>
<blockquote class="blockquote">
<p>A technique used to reduce over-fitting in decision tree models by removing branches that do not significantly improve model performance.</p>
</blockquote>
<ul>
<li><p>Goal: To simplify the tree, improving generalizability and reducing complexity, while maintaining prediction accuracy.</p></li>
<li><p>Two main types of pruning:</p>
<ol type="1">
<li><p>Pre-pruning (Top-down): Stops tree growth once certain criteria are met, such as maximum depth or minimum node size.</p></li>
<li><p>Post-pruning (Bottom-up): Allows the tree to fully grow, then iteratively removes branches based on specific criteria, such as error rate or information gain.</p></li>
</ol></li>
<li><p>Criteria for pruning: Can be based on various measures, such as error rate, information gain, or Gini impurity, and the cost of complexity (CC)</p></li>
<li><p>Cross-validation: Often used in conjunction with pruning to determine the optimal level of pruning, by comparing model performance on multiple training and validation sets.</p></li>
<li><p>Benefits: Pruning can lead to better generalization performance, reduced over-fitting, and more interpretable models.</p></li>
</ul>
<p><br></p>
</section>
<section id="cost-of-complexity" class="level4">
<h4 class="anchored" data-anchor-id="cost-of-complexity">Cost of complexity</h4>
<p><span class="math display">\[
CC(T)=Err(T)+\alpha L(T)
\]</span></p>
<ul>
<li><p><span class="math inline">\(CC(T)\)</span> is cost of complexity</p></li>
<li><p><span class="math inline">\(Err(T)\)</span> is error rate of Tree with test dataset</p></li>
<li><p><span class="math inline">\(L(T)\)</span> is the number of last nodes of Tree</p></li>
<li><p><span class="math inline">\(\alpha\)</span> is weight of combining Err(T) and L(T): depends on researcher’s decision.</p></li>
</ul>
<p><br></p>
<section id="cost-of-complexity-example-1" class="level5">
<h5 class="anchored" data-anchor-id="cost-of-complexity-example-1">Cost of complexity Example #1</h5>
<p><img src="img/cc_1.png" class="img-fluid"></p>
<p><br></p>
<ul>
<li><p>Tree 1: Err(T) = 10%</p></li>
<li><p>Tree 2: Err(T) = 15%</p></li>
<li><p>Choose Tree A is better as the same number of last nodes</p></li>
</ul>
<p><br></p>
</section>
<section id="cost-of-complexity-example-2" class="level5">
<h5 class="anchored" data-anchor-id="cost-of-complexity-example-2">Cost of complexity Example #2</h5>
<p><img src="img/cc_2.png" class="img-fluid"></p>
<p><br></p>
<ul>
<li><p>Tree A: Err(T) = 15%</p></li>
<li><p>Tree B: Err(T) = 15%</p></li>
<li><p>Choose Tree A is better as the same Err(T) but low number of last nodes</p></li>
</ul>
<p><br></p>
</section>
</section>
<section id="practice-with-data" class="level4">
<h4 class="anchored" data-anchor-id="practice-with-data">Practice with data</h4>
<p><img src="img/iris.png" class="img-fluid"></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(iris, <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1           5.1         3.5          1.4         0.2  setosa
2           4.9         3.0          1.4         0.2  setosa
3           4.7         3.2          1.3         0.2  setosa
4           4.6         3.1          1.5         0.2  setosa
5           5.0         3.6          1.4         0.2  setosa
6           5.4         3.9          1.7         0.4  setosa
7           4.6         3.4          1.4         0.3  setosa
8           5.0         3.4          1.5         0.2  setosa
9           4.4         2.9          1.4         0.2  setosa
10          4.9         3.1          1.5         0.1  setosa</code></pre>
</div>
</div>
<p>Using ‘rpart’ to train the model with the ‘iris’ dataset</p>
<ul>
<li>The target (response) variable should be ‘factor’ in R</li>
<li>Or, use rpart(…, method=‘class’) option</li>
<li>Otherwise, rpart do regression instead of classification</li>
<li>Then, let’s train the model with the data ‘iris’</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rpart)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>r <span class="ot">=</span> <span class="fu">rpart</span>(Species <span class="sc">~</span> ., <span class="at">data =</span> iris)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(r)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>n= 150 

node), split, n, loss, yval, (yprob)
      * denotes terminal node

1) root 150 100 setosa (0.33333333 0.33333333 0.33333333)  
  2) Petal.Length&lt; 2.45 50   0 setosa (1.00000000 0.00000000 0.00000000) *
  3) Petal.Length&gt;=2.45 100  50 versicolor (0.00000000 0.50000000 0.50000000)  
    6) Petal.Width&lt; 1.75 54   5 versicolor (0.00000000 0.90740741 0.09259259) *
    7) Petal.Width&gt;=1.75 46   1 virginica (0.00000000 0.02173913 0.97826087) *</code></pre>
</div>
</div>
<ul>
<li>Tree visualization</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>), <span class="at">xpd =</span> <span class="cn">NA</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(r)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(r, <span class="at">use.n =</span> T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="03_week_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>The question of the root node (node 0): [Petal.Length&lt;2.45?]
<ul>
<li>Yes of 50 to the left,</li>
<li>No of 100 to the right among 150 sample</li>
<li>50 on the left all belong to ‘setosa’ so STOP 🡪 Make a leaf and record setosa(50/0/0)</li>
</ul></li>
<li>The child node on the right side of the root: [Petal.Width&lt;1.75?]
<ul>
<li>Yes of 54 to the left,</li>
<li>and No of 46 to the right among the 100</li>
</ul></li>
<li>On the left 54, there are 49 versicolor and 5 virginica 🡪 To avoid overfitting the algorithm STOP and record versicolor(0/49/5).</li>
<li>On the right 46, there are 1 versicolor and 45 virginica 🡪 To avoid overfitting the algorithm STOP and record virginica(0/1/45).</li>
</ul>
<p><br></p>
<section id="prediction" class="level5">
<h5 class="anchored" data-anchor-id="prediction">Prediction</h5>
<ul>
<li>Use the function ‘prediction’</li>
<li>type=‘class’ option prints the class (the default is type=‘prob’ which prints probability of each class)</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>p <span class="ot">=</span> <span class="fu">predict</span>(r, iris, <span class="at">type =</span> <span class="st">'class'</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(p, <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     1      2      3      4      5      6      7      8      9     10 
setosa setosa setosa setosa setosa setosa setosa setosa setosa setosa 
Levels: setosa versicolor virginica</code></pre>
</div>
</div>
<ul>
<li><p>Confusion matrix</p>
<ul>
<li>Show the correct and the wrong classifications in detail</li>
<li>See below for example, among 50 versicolor, 49 are correct but one is wrong to virginica</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(p, iris<span class="sc">$</span>Species)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
p            setosa versicolor virginica
  setosa         50          0         0
  versicolor      0         49         5
  virginica       0          1        45</code></pre>
</div>
</div>
<p><br></p></li>
</ul>
<p>New data is from train data but a little bit of change is given.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>newd <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">Sepal.Length =</span> <span class="fu">c</span>(<span class="fl">5.11</span>, <span class="fl">7.01</span>, <span class="fl">6.32</span>),</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">Sepal.Width =</span> <span class="fu">c</span>(<span class="fl">3.51</span>, <span class="fl">3.2</span>, <span class="fl">3.31</span>),</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">Petal.Length =</span> <span class="fu">c</span>(<span class="fl">1.4</span>, <span class="fl">4.71</span>, <span class="fl">6.02</span>),</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">Petal.Width =</span> <span class="fu">c</span>(<span class="fl">0.19</span>, <span class="fl">1.4</span>, <span class="fl">2.49</span>))</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>newd</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Sepal.Length Sepal.Width Petal.Length Petal.Width
1         5.11        3.51         1.40        0.19
2         7.01        3.20         4.71        1.40
3         6.32        3.31         6.02        2.49</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(r, <span class="at">newdata =</span> newd)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  setosa versicolor  virginica
1      1 0.00000000 0.00000000
2      0 0.90740741 0.09259259
3      0 0.02173913 0.97826087</code></pre>
</div>
</div>
<p><br></p>
<p>Let’s read the result with the ‘function ’summary’</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(r)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
rpart(formula = Species ~ ., data = iris)
  n= 150 

    CP nsplit rel error xerror       xstd
1 0.50      0      1.00   1.18 0.05017303
2 0.44      1      0.50   0.70 0.06110101
3 0.01      2      0.06   0.09 0.02908608

Variable importance
 Petal.Width Petal.Length Sepal.Length  Sepal.Width 
          34           31           21           14 

Node number 1: 150 observations,    complexity param=0.5
  predicted class=setosa      expected loss=0.6666667  P(node) =1
    class counts:    50    50    50
   probabilities: 0.333 0.333 0.333 
  left son=2 (50 obs) right son=3 (100 obs)
  Primary splits:
      Petal.Length &lt; 2.45 to the left,  improve=50.00000, (0 missing)
      Petal.Width  &lt; 0.8  to the left,  improve=50.00000, (0 missing)
      Sepal.Length &lt; 5.45 to the left,  improve=34.16405, (0 missing)
      Sepal.Width  &lt; 3.35 to the right, improve=19.03851, (0 missing)
  Surrogate splits:
      Petal.Width  &lt; 0.8  to the left,  agree=1.000, adj=1.00, (0 split)
      Sepal.Length &lt; 5.45 to the left,  agree=0.920, adj=0.76, (0 split)
      Sepal.Width  &lt; 3.35 to the right, agree=0.833, adj=0.50, (0 split)

Node number 2: 50 observations
  predicted class=setosa      expected loss=0  P(node) =0.3333333
    class counts:    50     0     0
   probabilities: 1.000 0.000 0.000 

Node number 3: 100 observations,    complexity param=0.44
  predicted class=versicolor  expected loss=0.5  P(node) =0.6666667
    class counts:     0    50    50
   probabilities: 0.000 0.500 0.500 
  left son=6 (54 obs) right son=7 (46 obs)
  Primary splits:
      Petal.Width  &lt; 1.75 to the left,  improve=38.969400, (0 missing)
      Petal.Length &lt; 4.75 to the left,  improve=37.353540, (0 missing)
      Sepal.Length &lt; 6.15 to the left,  improve=10.686870, (0 missing)
      Sepal.Width  &lt; 2.45 to the left,  improve= 3.555556, (0 missing)
  Surrogate splits:
      Petal.Length &lt; 4.75 to the left,  agree=0.91, adj=0.804, (0 split)
      Sepal.Length &lt; 6.15 to the left,  agree=0.73, adj=0.413, (0 split)
      Sepal.Width  &lt; 2.95 to the left,  agree=0.67, adj=0.283, (0 split)

Node number 6: 54 observations
  predicted class=versicolor  expected loss=0.09259259  P(node) =0.36
    class counts:     0    49     5
   probabilities: 0.000 0.907 0.093 

Node number 7: 46 observations
  predicted class=virginica   expected loss=0.02173913  P(node) =0.3066667
    class counts:     0     1    45
   probabilities: 0.000 0.022 0.978 </code></pre>
</div>
</div>
<ul>
<li>Variable importance shows the order of the explainable (independent) variables which contributes to predicting Y</li>
<li>When the model is trained, it chooses the features that are important at the same time</li>
<li>That’s why the first visualization tree used only two variables: Petal.Width and Length</li>
</ul>
<p><br></p>
<p>The effective visualization helps to read the results of decision tree</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rpart.plot)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rpart.plot</span>(r)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="03_week_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>You can change a style of the graph</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rpart.plot</span>(r, <span class="at">type =</span> <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="03_week_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><br></p>
</section>
<section id="pros-cons-of-dt" class="level5">
<h5 class="anchored" data-anchor-id="pros-cons-of-dt">Pros &amp; Cons of DT</h5>
<ul>
<li><p>Con: the performance is not that good</p></li>
<li><p>Pros</p>
<ul>
<li><p>Easy interpretability<br>
(예를 들어, “꽃받침 길이가 2.54보다 크고, 꽃받침 너비가 1.75보다 작아 versicolor로 분류”했다는 해석을 내놓을 수 있음)</p></li>
<li><p>Fast prediction (몇 번의 비교 연산으로 분류)</p></li>
<li><p>Ensemble techniques make DT the great again (e.g.&nbsp;Random Forest)</p></li>
<li><p>DT accepts categorical variables well (e.g.&nbsp;gender, pclass)</p></li>
</ul></li>
</ul>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>License: <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC BY-SA 2.0</a>.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/ChangjunChrisLee/">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/Dr_CJLee">
      <i class="bi bi-twitter" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>