---
title: Data Science 101
subtitle: 데이터사이언스의 이해
Lecturer: Changjun Lee
---

```{r}
a <- "Data"
b <- "Science"
paste0("Welcome to ", a," ",b," ",100+1)
```

<br>

### Syllabus

**Week 1: Introduction to Data Science and R**

-   What is Data Science?

-   Introduction to R and RStudio

-   R syntax and basic operations

-   Data types and structures in R

**Week 2: Data Import and Export**

-   Reading and writing data in R (CSV, Excel, JSON, etc.)

-   Data from APIs and web scraping

-   Handling missing data and errors

**Week 3: Data Manipulation I**

-   Introduction to [`tidyverse`](https://www.tidyverse.org/)

-   Data cleaning with `dplyr` and `tidyr`

-   Data filtering and aggregation

**Week 4: Data Manipulation II**

-   Data transformation with `dplyr`

-   Grouping and summarizing data

-   Joining datasets

**Week 5: Data Exploration**

-   Descriptive statistics

-   Exploratory data analysis (EDA)

-   Introduction to `ggplot2` for data visualization

**Week 6: Data Visualization I**

-   Grammar of graphics with `ggplot2`

-   Customizing plots with themes and scales

-   Adding labels, titles, and legends

**Week 7: Data Visualization II**

-   Advanced `ggplot2` techniques

-   Creating different types of plots (scatter plots, bar plots, etc.)

-   Visualizing distributions and relationships

**Week 8: Data Visualization III**

-   Faceting and multi-panel plots

-   Plotting time series data

-   Interactive plots with `plotly` or `ggplotly`

**Week 9: Mid-term QZ**

**Week 10: Introduction to Shiny**

-   What is [`Shiny`](https://shiny.rstudio.com/)?

-   Creating Shiny apps with R

-   Adding interactivity to data visualizations

**Week 11: Version Control and Collaboration**

-   Introduction to *Git* and *GitHub*

-   Collaborating with others using version control

-   Best practices for organizing and documenting data science projects

-   Working with AI (*feat.* ChatGPT)

**Week 12: Reproducible Research**

-   Introduction to `R Markdown`

-   Creating reports and presentations with R Markdown

-   Embedding code, visualizations, and results in R Markdown documents

**Week 13: Creating Websites with Quarto**

-   Introduction to [`Quarto`](https://quarto.org/)

-   Creating a Quarto website with R Markdown

-   Customizing the website layout and design

-   Publishing and sharing your Quarto website

**Week 14: Team project consultation**

**Week 15: Project presentation**

<br>

------------------------------------------------------------------------

### Textbooks for the course

-   [R for Data Science](https://r4ds.had.co.nz/index.html) (written by *Hadley Wickham* and *Garrett Grolemund*)

    -   is an excellent resource for learning data science using R, covering data manipulation, visualization, and modeling with R. The book is available as a free online resource.

-   [Introductory Statistics with R](https://link.springer.com/book/10.1007/978-0-387-79054-1) (written by *Peter Dalgaard*)

    -   is a great resource for learning basic statistics with a focus on R programming. This book covers a wide range of statistical concepts, from descriptive statistics to hypothesis testing and linear regression, along with R code examples.

-   [R Cookbook](https://rc2e.com/) (written by *JD Long* and *Paul Teetor*)

    -   is a comprehensive resource for data scientists, statisticians, and programmers who want to explore the capabilities of R programming for data analysis and visualization.

-   [R Graphic Cookbook](https://r-graphics.org/index.html) (written by *Winston Chang)*

    -   is a practical guide that provides more than 150 recipes to help you generate high-quality graphs quickly, without having to comb through all the details of R's graphing systems
