<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>CJL &amp; Lab - 데이터 시각화와 기술 통계(2)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../../">
<script src="../../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../../../index.html">
    <span class="navbar-title">CJL &amp; Lab</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-courses" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Courses</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-courses">    
        <li>
    <a class="dropdown-item" href="../../../../teaching/index.html">
 <span class="dropdown-text">All Courses</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../../teaching/ml101/index.html">
 <span class="dropdown-text">ML101</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../../teaching/grad_stat/index.html">
 <span class="dropdown-text">STAT101</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../../../../research/index.html"> 
<span class="menu-text">Research</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../../proj/index.html"> 
<span class="menu-text">Proj</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../../blogs/index.html"> 
<span class="menu-text">Blogs</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://ctcl.netlify.app"> 
<span class="menu-text">LAB</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#dscriptive-statistics" id="toc-dscriptive-statistics" class="nav-link active" data-scroll-target="#dscriptive-statistics">Dscriptive Statistics</a>
  <ul class="collapse">
  <li><a href="#table-of-contents" id="toc-table-of-contents" class="nav-link" data-scroll-target="#table-of-contents">Table of Contents</a></li>
  <li><a href="#introduction-to-descriptive-statistics" id="toc-introduction-to-descriptive-statistics" class="nav-link" data-scroll-target="#introduction-to-descriptive-statistics">1. Introduction to Descriptive Statistics</a></li>
  <li><a href="#generating-data-for-simulation" id="toc-generating-data-for-simulation" class="nav-link" data-scroll-target="#generating-data-for-simulation">2. Generating Data for Simulation</a></li>
  <li><a href="#measures-of-central-tendency" id="toc-measures-of-central-tendency" class="nav-link" data-scroll-target="#measures-of-central-tendency">3. Measures of Central Tendency</a></li>
  <li><a href="#measures-of-variability" id="toc-measures-of-variability" class="nav-link" data-scroll-target="#measures-of-variability">4. Measures of Variability</a></li>
  <li><a href="#visualizing-data-distribution" id="toc-visualizing-data-distribution" class="nav-link" data-scroll-target="#visualizing-data-distribution">5. Visualizing Data Distribution</a></li>
  <li><a href="#skewness-and-kurtosis" id="toc-skewness-and-kurtosis" class="nav-link" data-scroll-target="#skewness-and-kurtosis">6. Skewness and Kurtosis</a></li>
  <li><a href="#summary-statistics-using-r-functions" id="toc-summary-statistics-using-r-functions" class="nav-link" data-scroll-target="#summary-statistics-using-r-functions">7. Summary Statistics Using R Functions</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises">8. Exercises</a></li>
  <li><a href="#solutions-for-exercises" id="toc-solutions-for-exercises" class="nav-link" data-scroll-target="#solutions-for-exercises">Solutions for Exercises:</a></li>
  </ul></li>
  <li><a href="#practice-with-a-titanic-dataset" id="toc-practice-with-a-titanic-dataset" class="nav-link" data-scroll-target="#practice-with-a-titanic-dataset">Practice with a Titanic dataset</a>
  <ul class="collapse">
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">1. Introduction</a></li>
  <li><a href="#prepare-to-work" id="toc-prepare-to-work" class="nav-link" data-scroll-target="#prepare-to-work">2. Prepare to work</a>
  <ul class="collapse">
  <li><a href="#packages" id="toc-packages" class="nav-link" data-scroll-target="#packages">2.1 Packages</a></li>
  <li><a href="#raw-data-import" id="toc-raw-data-import" class="nav-link" data-scroll-target="#raw-data-import">2.2 Raw data import</a></li>
  <li><a href="#variable-meaning-explanation" id="toc-variable-meaning-explanation" class="nav-link" data-scroll-target="#variable-meaning-explanation">2.3 variable meaning explanation</a></li>
  <li><a href="#change-the-variables-type" id="toc-change-the-variables-type" class="nav-link" data-scroll-target="#change-the-variables-type">2.4 Change the variables type</a></li>
  </ul></li>
  <li><a href="#eda-exploratory-data-analysis" id="toc-eda-exploratory-data-analysis" class="nav-link" data-scroll-target="#eda-exploratory-data-analysis">3. EDA : Exploratory data analysis</a>
  <ul class="collapse">
  <li><a href="#data-confirmation-using-numerical-values" id="toc-data-confirmation-using-numerical-values" class="nav-link" data-scroll-target="#data-confirmation-using-numerical-values">3.1 Data confirmation using numerical values</a></li>
  <li><a href="#missing-values" id="toc-missing-values" class="nav-link" data-scroll-target="#missing-values">3.2 Missing values</a></li>
  <li><a href="#age" id="toc-age" class="nav-link" data-scroll-target="#age">3.3 Age</a></li>
  <li><a href="#pclass" id="toc-pclass" class="nav-link" data-scroll-target="#pclass">3.4 Pclass</a></li>
  <li><a href="#fare" id="toc-fare" class="nav-link" data-scroll-target="#fare">3.5 Fare</a></li>
  <li><a href="#sex" id="toc-sex" class="nav-link" data-scroll-target="#sex">3.6 Sex</a></li>
  </ul></li>
  <li><a href="#feature-engineering-data-pre-processing" id="toc-feature-engineering-data-pre-processing" class="nav-link" data-scroll-target="#feature-engineering-data-pre-processing">4. Feature engineering &amp; Data Pre-processing</a>
  <ul class="collapse">
  <li><a href="#age---age.group" id="toc-age---age.group" class="nav-link" data-scroll-target="#age---age.group">4.1 Age -&gt; Age.Group</a></li>
  <li><a href="#sibsp-parch---familysized" id="toc-sibsp-parch---familysized" class="nav-link" data-scroll-target="#sibsp-parch---familysized">4.3 SibSp &amp; Parch -&gt; FamilySized</a></li>
  <li><a href="#name-sex---title" id="toc-name-sex---title" class="nav-link" data-scroll-target="#name-sex---title">4.4 Name &amp; Sex -&gt; title</a></li>
  <li><a href="#ticket---ticket.size" id="toc-ticket---ticket.size" class="nav-link" data-scroll-target="#ticket---ticket.size">4.5 Ticket -&gt; ticket.size</a></li>
  <li><a href="#embarked" id="toc-embarked" class="nav-link" data-scroll-target="#embarked">4.6 Embarked</a></li>
  <li><a href="#fare-1" id="toc-fare-1" class="nav-link" data-scroll-target="#fare-1">4.7 Fare</a></li>
  </ul></li>
  <li><a href="#relationship-to-target-feature-survived-feature-selection" id="toc-relationship-to-target-feature-survived-feature-selection" class="nav-link" data-scroll-target="#relationship-to-target-feature-survived-feature-selection">5. Relationship to target feature <code>Survived</code> &amp; Feature selection</a>
  <ul class="collapse">
  <li><a href="#data-set-split" id="toc-data-set-split" class="nav-link" data-scroll-target="#data-set-split">5.0 Data set split</a></li>
  <li><a href="#pclass-1" id="toc-pclass-1" class="nav-link" data-scroll-target="#pclass-1">5.1 Pclass</a></li>
  <li><a href="#sex-1" id="toc-sex-1" class="nav-link" data-scroll-target="#sex-1">5.2 Sex</a></li>
  <li><a href="#embarked-1" id="toc-embarked-1" class="nav-link" data-scroll-target="#embarked-1">5.3 Embarked</a></li>
  <li><a href="#familysized" id="toc-familysized" class="nav-link" data-scroll-target="#familysized">5.4 FamilySized</a></li>
  <li><a href="#age.group" id="toc-age.group" class="nav-link" data-scroll-target="#age.group">5.5 Age.Group</a></li>
  <li><a href="#title" id="toc-title" class="nav-link" data-scroll-target="#title">5.6 title</a></li>
  <li><a href="#ticket.size" id="toc-ticket.size" class="nav-link" data-scroll-target="#ticket.size">5.7 ticket.size</a></li>
  <li><a href="#description-of-actual-used-features" id="toc-description-of-actual-used-features" class="nav-link" data-scroll-target="#description-of-actual-used-features">5.8 Description of actual used features</a></li>
  </ul></li>
  <li><a href="#machine-learning-model-generation" id="toc-machine-learning-model-generation" class="nav-link" data-scroll-target="#machine-learning-model-generation">6. Machine learning model generation</a>
  <ul class="collapse">
  <li><a href="#random-forest-model-generation" id="toc-random-forest-model-generation" class="nav-link" data-scroll-target="#random-forest-model-generation">6.1 Random Forest model generation</a></li>
  <li><a href="#feature-importance-check" id="toc-feature-importance-check" class="nav-link" data-scroll-target="#feature-importance-check">6.2 Feature importance check</a></li>
  <li><a href="#predict-test-data-and-create-submit-data" id="toc-predict-test-data-and-create-submit-data" class="nav-link" data-scroll-target="#predict-test-data-and-create-submit-data">6.3 Predict test data and create submit data</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#data-frame-generation" id="toc-data-frame-generation" class="nav-link" data-scroll-target="#data-frame-generation">Data frame generation</a></li>
  <li><a href="#write-the-submit-data-frame-to-file-csv-is-created-in-the-folder-designated-by-setwd." id="toc-write-the-submit-data-frame-to-file-csv-is-created-in-the-folder-designated-by-setwd." class="nav-link" data-scroll-target="#write-the-submit-data-frame-to-file-csv-is-created-in-the-folder-designated-by-setwd.">Write the submit data frame to file : csv is created in the folder designated by setwd().</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">데이터 시각화와 기술 통계(2)</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><a href="https://changjunlee.com/teaching/grad_stat/weekly_2/">Weekly content</a></p>
<section id="dscriptive-statistics" class="level1">
<h1>Dscriptive Statistics</h1>
<p><br></p>
<p>This chapter introduces <strong>descriptive statistics</strong>, which summarize and describe the main features of a dataset. Descriptive statistics are the foundation of exploratory data analysis (EDA) and are used to understand the basic structure and characteristics of data before moving on to more complex analysis.</p>
<p>We’ll explore <strong>measures of central tendency</strong> (mean, median, mode), <strong>measures of variability</strong> (variance, standard deviation, range, IQR), and <strong>distribution</strong> (skewness, kurtosis). In this chapter, we will also introduce some key R functions and simulate data to illustrate these concepts.</p>
<section id="table-of-contents" class="level3">
<h3 class="anchored" data-anchor-id="table-of-contents">Table of Contents</h3>
<ol type="1">
<li><p><strong>Introduction to Descriptive Statistics</strong></p></li>
<li><p><strong>Generating Data for Simulation</strong></p></li>
<li><p><strong>Measures of Central Tendency</strong></p></li>
<li><p><strong>Measures of Variability</strong></p></li>
<li><p><strong>Visualizing Data Distribution</strong></p></li>
<li><p><strong>Skewness and Kurtosis</strong></p></li>
<li><p><strong>Summary Statistics Using R Functions</strong></p></li>
<li><p><strong>Exercises</strong></p></li>
</ol>
</section>
<section id="introduction-to-descriptive-statistics" class="level3">
<h3 class="anchored" data-anchor-id="introduction-to-descriptive-statistics">1. Introduction to Descriptive Statistics</h3>
<p>Descriptive statistics help summarize data by providing key insights into the data’s central tendency, spread, and overall shape of the distribution.</p>
<ul>
<li><p><strong>Central Tendency</strong>: Mean, median, and mode.</p></li>
<li><p><strong>Variability</strong>: Variance, standard deviation, range, and interquartile range (IQR).</p></li>
<li><p><strong>Distribution</strong>: Shape of the distribution including skewness and kurtosis.</p></li>
</ul>
</section>
<section id="generating-data-for-simulation" class="level3">
<h3 class="anchored" data-anchor-id="generating-data-for-simulation">2. Generating Data for Simulation</h3>
<p>We’ll start by generating some <strong>synthetic data</strong> to demonstrate descriptive statistics using the <code>rnorm()</code> function to generate data from a <strong>normal distribution</strong> and <code>runif()</code> for a <strong>uniform distribution</strong>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulate normally distributed data (mean = 50, sd = 10)</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>data_normal <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">1000</span>, <span class="at">mean =</span> <span class="dv">50</span>, <span class="at">sd =</span> <span class="dv">10</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulate uniformly distributed data (min = 10, max = 90)</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>data_uniform <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="dv">1000</span>, <span class="at">min =</span> <span class="dv">10</span>, <span class="at">max =</span> <span class="dv">90</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary of the datasets</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data_normal)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  21.90   43.72   50.09   50.16   56.65   82.41 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data_uniform)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  10.28   28.68   49.72   49.89   69.67   89.97 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Histogram of normally distributed data</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">data.frame</span>(<span class="at">x =</span> data_normal), <span class="fu">aes</span>(x)) <span class="sc">+</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">30</span>, <span class="at">fill =</span> <span class="st">"grey"</span>, <span class="at">alpha =</span> <span class="fl">0.9</span>) <span class="sc">+</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Histogram of Normally Distributed Data"</span>, <span class="at">x =</span> <span class="st">"Value"</span>, <span class="at">y =</span> <span class="st">"Frequency"</span>) <span class="sc">+</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07_week_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Histogram of uniformly distributed data</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">data.frame</span>(<span class="at">x =</span> data_uniform), <span class="fu">aes</span>(x)) <span class="sc">+</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">30</span>, <span class="at">fill =</span> <span class="st">"grey"</span>, <span class="at">alpha =</span> <span class="fl">0.9</span>) <span class="sc">+</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Histogram of Uniformly Distributed Data"</span>, <span class="at">x =</span> <span class="st">"Value"</span>, <span class="at">y =</span> <span class="st">"Frequency"</span>) <span class="sc">+</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07_week_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="measures-of-central-tendency" class="level3">
<h3 class="anchored" data-anchor-id="measures-of-central-tendency">3. Measures of Central Tendency</h3>
<p>The <strong>central tendency</strong> refers to the “center” of a dataset. The most common measures of central tendency are the <strong>mean</strong>, <strong>median</strong>, and <strong>mode</strong>.</p>
<ul>
<li><p><strong>Mean</strong>: The arithmetic average of the data.</p></li>
<li><p><strong>Median</strong>: The middle value when the data is ordered.</p></li>
<li><p><strong>Mode</strong>: The value that occurs most frequently.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Mean, median, and mode for normally distributed data</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>mean_normal <span class="ot">&lt;-</span> <span class="fu">mean</span>(data_normal)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>median_normal <span class="ot">&lt;-</span> <span class="fu">median</span>(data_normal)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>mode_normal <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">names</span>(<span class="fu">sort</span>(<span class="fu">table</span>(data_normal), <span class="at">decreasing =</span> <span class="cn">TRUE</span>)[<span class="dv">1</span>]))</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Mean, median, and mode for uniformly distributed data</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>mean_uniform <span class="ot">&lt;-</span> <span class="fu">mean</span>(data_uniform)</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>median_uniform <span class="ot">&lt;-</span> <span class="fu">median</span>(data_uniform)</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>mode_uniform <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">names</span>(<span class="fu">sort</span>(<span class="fu">table</span>(data_uniform), <span class="at">decreasing =</span> <span class="cn">TRUE</span>)[<span class="dv">1</span>]))</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Display results</span></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Normal Distribution - Mean:"</span>, mean_normal, <span class="st">"Median:"</span>, median_normal, <span class="st">"Mode:"</span>, mode_normal, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Normal Distribution - Mean: 50.16128 Median: 50.0921 Mode: 21.90225 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Uniform Distribution - Mean:"</span>, mean_uniform, <span class="st">"Median:"</span>, median_uniform, <span class="st">"Mode:"</span>, mode_uniform, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Uniform Distribution - Mean: 49.88829 Median: 49.717 Mode: 10.28128 </code></pre>
</div>
</div>
</section>
<section id="measures-of-variability" class="level3">
<h3 class="anchored" data-anchor-id="measures-of-variability">4. Measures of Variability</h3>
<p>Variability tells us how spread out the data points are. Common measures of variability include <strong>range</strong>, <strong>variance</strong>, <strong>standard deviation</strong>, and <strong>interquartile range (IQR)</strong>.</p>
<ul>
<li><p><strong>Range</strong>: The difference between the maximum and minimum values.</p></li>
<li><p><strong>Variance</strong>: The average squared deviation from the mean.</p></li>
<li><p><strong>Standard Deviation</strong>: The square root of variance, representing the spread of data.</p></li>
<li><p><strong>Interquartile Range (IQR)</strong>: The range between the 25th percentile (Q1) and the 75th percentile (Q3).</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Variability measures for normally distributed data</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>range_normal <span class="ot">&lt;-</span> <span class="fu">range</span>(data_normal)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>var_normal <span class="ot">&lt;-</span> <span class="fu">var</span>(data_normal)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>sd_normal <span class="ot">&lt;-</span> <span class="fu">sd</span>(data_normal)</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>iqr_normal <span class="ot">&lt;-</span> <span class="fu">IQR</span>(data_normal)</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Variability measures for uniformly distributed data</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>range_uniform <span class="ot">&lt;-</span> <span class="fu">range</span>(data_uniform)</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>var_uniform <span class="ot">&lt;-</span> <span class="fu">var</span>(data_uniform)</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>sd_uniform <span class="ot">&lt;-</span> <span class="fu">sd</span>(data_uniform)</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>iqr_uniform <span class="ot">&lt;-</span> <span class="fu">IQR</span>(data_uniform)</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Display results</span></span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Normal Distribution - Range:"</span>, range_normal, <span class="st">"Variance:"</span>, var_normal, <span class="st">"SD:"</span>, sd_normal, <span class="st">"IQR:"</span>, iqr_normal, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Normal Distribution - Range: 21.90225 82.4104 Variance: 98.34589 SD: 9.91695 IQR: 12.92926 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Uniform Distribution - Range:"</span>, range_uniform, <span class="st">"Variance:"</span>, var_uniform, <span class="st">"SD:"</span>, sd_uniform, <span class="st">"IQR:"</span>, iqr_uniform, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Uniform Distribution - Range: 10.28128 89.97208 Variance: 546.4433 SD: 23.37613 IQR: 40.98324 </code></pre>
</div>
</div>
</section>
<section id="visualizing-data-distribution" class="level3">
<h3 class="anchored" data-anchor-id="visualizing-data-distribution">5. Visualizing Data Distribution</h3>
<p>To understand the distribution of data, it is helpful to visualize it. We can use <strong>histograms</strong> and <strong>boxplots</strong> to explore the distribution of our datasets.</p>
<p><img src="images/clipboard-940336939.png" class="img-fluid"></p>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Install ggplot2 if not already installed</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(ggplot2)) <span class="fu">install.packages</span>(<span class="st">"ggplot2"</span>)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Histogram of normally distributed data</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">data.frame</span>(<span class="at">x =</span> data_normal), <span class="fu">aes</span>(x)) <span class="sc">+</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">30</span>, <span class="at">fill =</span> <span class="st">"blue"</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Histogram of Normally Distributed Data"</span>, <span class="at">x =</span> <span class="st">"Value"</span>, <span class="at">y =</span> <span class="st">"Frequency"</span>) <span class="sc">+</span></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07_week_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Boxplot of uniformly distributed data</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">data.frame</span>(<span class="at">x =</span> data_uniform), <span class="fu">aes</span>(<span class="at">y =</span> x)) <span class="sc">+</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">"green"</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Boxplot of Uniformly Distributed Data"</span>, <span class="at">y =</span> <span class="st">"Value"</span>) <span class="sc">+</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07_week_files/figure-html/unnamed-chunk-6-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="skewness-and-kurtosis" class="level3">
<h3 class="anchored" data-anchor-id="skewness-and-kurtosis">6. Skewness and Kurtosis</h3>
<p><strong>Skewness</strong> measures the asymmetry of the distribution, while <strong>kurtosis</strong> measures the “tailedness” of the distribution.</p>
<p><img src="images/clipboard-4257836537.png" class="img-fluid"></p>
<ul>
<li><p><strong>Skewness</strong>: If skewness is near 0, the distribution is symmetrical. Positive skewness indicates a right-skewed distribution, while negative skewness indicates a left-skewed distribution.</p></li>
<li><p><strong>Kurtosis</strong>: High kurtosis indicates heavy tails, while low kurtosis indicates light tails.</p></li>
</ul>
<p>We can use the <strong><code>moments</code></strong> package to calculate skewness and kurtosis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Install moments package if not already installed</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(moments)) <span class="fu">install.packages</span>(<span class="st">"moments"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: moments</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(moments)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Skewness and Kurtosis for Normal Data</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>skewness_normal <span class="ot">&lt;-</span> <span class="fu">skewness</span>(data_normal)</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>kurtosis_normal <span class="ot">&lt;-</span> <span class="fu">kurtosis</span>(data_normal)</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Skewness and Kurtosis for Uniform Data</span></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>skewness_uniform <span class="ot">&lt;-</span> <span class="fu">skewness</span>(data_uniform)</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>kurtosis_uniform <span class="ot">&lt;-</span> <span class="fu">kurtosis</span>(data_uniform)</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Display Results</span></span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Normal Distribution - Skewness:"</span>, skewness_normal, <span class="st">"Kurtosis:"</span>, kurtosis_normal, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Normal Distribution - Skewness: 0.06529391 Kurtosis: 2.925747 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Uniform Distribution - Skewness:"</span>, skewness_uniform, <span class="st">"Kurtosis:"</span>, kurtosis_uniform, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Uniform Distribution - Skewness: -0.01377659 Kurtosis: 1.748754 </code></pre>
</div>
</div>
</section>
<section id="summary-statistics-using-r-functions" class="level3">
<h3 class="anchored" data-anchor-id="summary-statistics-using-r-functions">7. Summary Statistics Using R Functions</h3>
<p>R provides a convenient function, <code>summary()</code>, to calculate descriptive statistics such as the mean, median, minimum, maximum, and quartiles in one command.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary statistics for normally distributed data</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data_normal)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  21.90   43.72   50.09   50.16   56.65   82.41 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary statistics for uniformly distributed data</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data_uniform)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  10.28   28.68   49.72   49.89   69.67   89.97 </code></pre>
</div>
</div>
</section>
<section id="exercises" class="level3">
<h3 class="anchored" data-anchor-id="exercises">8. Exercises</h3>
<ol type="1">
<li><p>Generate a dataset of 1000 observations from an <strong>exponential distribution</strong> with a rate parameter of 0.1. Calculate the mean, median, mode, variance, standard deviation, range, and IQR of the data.</p></li>
<li><p>Visualize the distribution of the exponential dataset using both a <strong>histogram</strong> and a <strong>boxplot</strong>.</p></li>
<li><p>Calculate the skewness and kurtosis of the exponential dataset.</p></li>
<li><p>Use the <code>summary()</code> function to summarize the key descriptive statistics of the exponential dataset.</p></li>
</ol>
</section>
<section id="solutions-for-exercises" class="level3">
<h3 class="anchored" data-anchor-id="solutions-for-exercises">Solutions for Exercises:</h3>
<ol type="1">
<li>Exponential Distribution Simulation:</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>data_exp <span class="ot">&lt;-</span> <span class="fu">rexp</span>(<span class="dv">1000</span>, <span class="at">rate =</span> <span class="fl">0.1</span>)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(data_exp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 10.03397</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(data_exp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6.750221</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Mode not well-defined for continuous data, so skipped here</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">var</span>(data_exp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 107.9277</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(data_exp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 10.38883</code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">range</span>(data_exp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  0.03318932 90.81389879</code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">IQR</span>(data_exp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 11.03429</code></pre>
</div>
</div>
<ol start="2" type="1">
<li>Visualization:</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">data.frame</span>(<span class="at">x =</span> data_exp), <span class="fu">aes</span>(x)) <span class="sc">+</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">30</span>, <span class="at">fill =</span> <span class="st">"purple"</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Histogram of Exponentially Distributed Data"</span>, <span class="at">x =</span> <span class="st">"Value"</span>, <span class="at">y =</span> <span class="st">"Frequency"</span>) <span class="sc">+</span></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07_week_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">data.frame</span>(<span class="at">x =</span> data_exp), <span class="fu">aes</span>(<span class="at">y =</span> x)) <span class="sc">+</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">"orange"</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Boxplot of Exponentially Distributed Data"</span>, <span class="at">y =</span> <span class="st">"Value"</span>) <span class="sc">+</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07_week_files/figure-html/unnamed-chunk-10-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ol start="3" type="1">
<li>Skewness and Kurtosis:</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">skewness</span>(data_exp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.103298</code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kurtosis</span>(data_exp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 9.642639</code></pre>
</div>
</div>
<ol start="4" type="1">
<li>Summary:</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data_exp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
 0.03319  2.74731  6.75022 10.03397 13.78160 90.81390 </code></pre>
</div>
</div>
<p><br></p>
</section>
</section>
<section id="practice-with-a-titanic-dataset" class="level1">
<h1>Practice with a Titanic dataset</h1>
<p><br></p>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">1. Introduction</h2>
<p><br></p>
<p>It contains the analysis process of ‘Titanic’, one of the representative ‘Competition’ of ‘<a href="https://www.kaggle.com/">Kaggle</a>’.</p>
<p><br></p>
<hr>
<p><br></p>
</section>
<section id="prepare-to-work" class="level2">
<h2 class="anchored" data-anchor-id="prepare-to-work">2. Prepare to work</h2>
<p><br></p>
<section id="packages" class="level3">
<h3 class="anchored" data-anchor-id="packages">2.1 Packages</h3>
<p>see “<a href="https://cjleelab.netlify.app/blogs/posts/2_about_a_package.html">What is a package in R</a>”</p>
<p><br></p>
<p>This is the process of loading (loading) the <code>Packages</code> I used for analysis, in addition to the representative <code>Packages</code> of <code>R</code>, such as <a href="https://www.tidyverse.org/">tidyverse</a> (including <code>ggplot2</code> and <code>dplyr</code>).</p>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Data input, assesment </span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(titanic)</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)           <span class="co"># Data input with readr::read_csv()</span></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(descr)           <span class="co"># descr::CrossTable() - Frequency by category, check with ratio figures</span></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualization</span></span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(VIM)             <span class="co"># Missing values assesment used by VIM::aggr()</span></span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(RColorBrewer)    <span class="co"># Plot color setting</span></span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(scales)          <span class="co"># plot setting - x, y axis</span></span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-11"><a href="#cb49-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Feature engineering, Data Pre-processing</span></span>
<span id="cb49-12"><a href="#cb49-12" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)     <span class="co"># dplyr, ggplot2, purrr, etc..      # Feature Engineering &amp; Data Pre-processing</span></span>
<span id="cb49-13"><a href="#cb49-13" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggpubr)</span>
<span id="cb49-14"><a href="#cb49-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-15"><a href="#cb49-15" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(randomForest)</span>
<span id="cb49-16"><a href="#cb49-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Model validation </span></span>
<span id="cb49-17"><a href="#cb49-17" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caret)           <span class="co"># caret::confusionMatrix()</span></span>
<span id="cb49-18"><a href="#cb49-18" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ROCR)            <span class="co"># Plotting ROC Curve</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br></p>
</section>
<section id="raw-data-import" class="level3">
<h3 class="anchored" data-anchor-id="raw-data-import">2.2 Raw data import</h3>
<p><br></p>
<p>In <code>titanic competition</code>, <code>train</code> data used to create <code>Model</code> and <code>test</code> data used for actual prediction (estimation) are separated.</p>
<p>Here, we will load those two data and combine them into one. The reason for tying the separate data together is to work the same when feature engineering and pre-processing the input variables used in modeling.</p>
<p>Please see this <a href="https://www.britannica.com/topic/Titanic">link</a> if you want to know about the story of Titanic.</p>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>titanic_train <span class="sc">%&gt;%</span> glimpse</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 891
Columns: 12
$ PassengerId &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17,…
$ Survived    &lt;int&gt; 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1…
$ Pclass      &lt;int&gt; 3, 1, 3, 1, 3, 3, 1, 3, 3, 2, 3, 1, 3, 3, 3, 2, 3, 2, 3, 3…
$ Name        &lt;chr&gt; "Braund, Mr. Owen Harris", "Cumings, Mrs. John Bradley (Fl…
$ Sex         &lt;chr&gt; "male", "female", "female", "female", "male", "male", "mal…
$ Age         &lt;dbl&gt; 22, 38, 26, 35, 35, NA, 54, 2, 27, 14, 4, 58, 20, 39, 14, …
$ SibSp       &lt;int&gt; 1, 1, 0, 1, 0, 0, 0, 3, 0, 1, 1, 0, 0, 1, 0, 0, 4, 0, 1, 0…
$ Parch       &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 1, 0, 0, 5, 0, 0, 1, 0, 0, 0…
$ Ticket      &lt;chr&gt; "A/5 21171", "PC 17599", "STON/O2. 3101282", "113803", "37…
$ Fare        &lt;dbl&gt; 7.2500, 71.2833, 7.9250, 53.1000, 8.0500, 8.4583, 51.8625,…
$ Cabin       &lt;chr&gt; "", "C85", "", "C123", "", "", "E46", "", "", "", "G6", "C…
$ Embarked    &lt;chr&gt; "S", "C", "S", "S", "S", "Q", "S", "S", "S", "C", "S", "S"…</code></pre>
</div>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>titanic_test <span class="sc">%&gt;%</span> glimpse</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 418
Columns: 11
$ PassengerId &lt;int&gt; 892, 893, 894, 895, 896, 897, 898, 899, 900, 901, 902, 903…
$ Pclass      &lt;int&gt; 3, 3, 2, 3, 3, 3, 3, 2, 3, 3, 3, 1, 1, 2, 1, 2, 2, 3, 3, 3…
$ Name        &lt;chr&gt; "Kelly, Mr. James", "Wilkes, Mrs. James (Ellen Needs)", "M…
$ Sex         &lt;chr&gt; "male", "female", "male", "male", "female", "male", "femal…
$ Age         &lt;dbl&gt; 34.5, 47.0, 62.0, 27.0, 22.0, 14.0, 30.0, 26.0, 18.0, 21.0…
$ SibSp       &lt;int&gt; 0, 1, 0, 0, 1, 0, 0, 1, 0, 2, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0…
$ Parch       &lt;int&gt; 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ Ticket      &lt;chr&gt; "330911", "363272", "240276", "315154", "3101298", "7538",…
$ Fare        &lt;dbl&gt; 7.8292, 7.0000, 9.6875, 8.6625, 12.2875, 9.2250, 7.6292, 2…
$ Cabin       &lt;chr&gt; "", "", "", "", "", "", "", "", "", "", "", "", "B45", "",…
$ Embarked    &lt;chr&gt; "Q", "S", "Q", "S", "S", "S", "Q", "S", "C", "S", "S", "S"…</code></pre>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>train <span class="ot">&lt;-</span> titanic_train</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>test  <span class="ot">&lt;-</span> titanic_test</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>full <span class="ot">&lt;-</span> dplyr<span class="sc">::</span><span class="fu">bind_rows</span>(train, test)</span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>full <span class="sc">%&gt;%</span> glimpse</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 1,309
Columns: 12
$ PassengerId &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17,…
$ Survived    &lt;int&gt; 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1…
$ Pclass      &lt;int&gt; 3, 1, 3, 1, 3, 3, 1, 3, 3, 2, 3, 1, 3, 3, 3, 2, 3, 2, 3, 3…
$ Name        &lt;chr&gt; "Braund, Mr. Owen Harris", "Cumings, Mrs. John Bradley (Fl…
$ Sex         &lt;chr&gt; "male", "female", "female", "female", "male", "male", "mal…
$ Age         &lt;dbl&gt; 22, 38, 26, 35, 35, NA, 54, 2, 27, 14, 4, 58, 20, 39, 14, …
$ SibSp       &lt;int&gt; 1, 1, 0, 1, 0, 0, 0, 3, 0, 1, 1, 0, 0, 1, 0, 0, 4, 0, 1, 0…
$ Parch       &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 1, 0, 0, 5, 0, 0, 1, 0, 0, 0…
$ Ticket      &lt;chr&gt; "A/5 21171", "PC 17599", "STON/O2. 3101282", "113803", "37…
$ Fare        &lt;dbl&gt; 7.2500, 71.2833, 7.9250, 53.1000, 8.0500, 8.4583, 51.8625,…
$ Cabin       &lt;chr&gt; "", "C85", "", "C123", "", "", "E46", "", "", "", "G6", "C…
$ Embarked    &lt;chr&gt; "S", "C", "S", "S", "S", "Q", "S", "S", "S", "C", "S", "S"…</code></pre>
</div>
</div>
<p>The reason why <code>rbind()</code> was not used even when combining the two data into full is that Survived, the dependent variable (target variable, Y) of Titanic competition, does not exist in test. Therefore, the dimensions (dimension) of the two data do not match, so they are not merged with rbind(). However, if you use dplyr::bind_rows(), Survived in test is treated as <em>NA</em> and merged into one.</p>
</section>
<section id="variable-meaning-explanation" class="level3">
<h3 class="anchored" data-anchor-id="variable-meaning-explanation">2.3 variable meaning explanation</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 22%">
<col style="width: 54%">
<col style="width: 22%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">variable name</th>
<th style="text-align: left;">Interpretation (meaning)</th>
<th style="text-align: left;">Type</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><strong>PassengerID</strong></td>
<td style="text-align: left;">Unique ID number that identifies the passenger</td>
<td style="text-align: left;">Int</td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>Survived</strong></td>
<td style="text-align: left;">Indicates whether or not the passenger survived. Survival is 1 and death is 0.</td>
<td style="text-align: left;">Factor</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><strong>Pclass</strong></td>
<td style="text-align: left;">The class of the cabin, with 3 categories from 1st class (1) to 3rd class (3).</td>
<td style="text-align: left;">Ord.Factor</td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>Name</strong></td>
<td style="text-align: left;">Passenger’s name</td>
<td style="text-align: left;">Factor</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><strong>Sex</strong></td>
<td style="text-align: left;">Passenger’s gender</td>
<td style="text-align: left;">Factor</td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>Age</strong></td>
<td style="text-align: left;">Age of passenger</td>
<td style="text-align: left;">Numeric</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><strong>SibSp</strong></td>
<td style="text-align: left;">Variable describing the number of siblings or spouses accompanying each passenger. It can range from 0 to 8.</td>
<td style="text-align: left;">Integer</td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>Parch</strong></td>
<td style="text-align: left;">Variable describing the number of parents or children accompanying each passenger, from 0 to 9.</td>
<td style="text-align: left;">Integer</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><strong>Ticket</strong></td>
<td style="text-align: left;">String variable for the ticket the passenger boarded</td>
<td style="text-align: left;">Factor</td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>Fare</strong></td>
<td style="text-align: left;">Variable for how much the passenger has paid for the trip so far</td>
<td style="text-align: left;">Numeric</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><strong>Cabin</strong></td>
<td style="text-align: left;">Variable that distinguishes each passenger’s cabin, with too many categories and missing values.</td>
<td style="text-align: left;">Factor</td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>Embarked</strong></td>
<td style="text-align: left;">Indicates the boarding port and departure port, and consists of three categories: C, Q, and S.</td>
<td style="text-align: left;">Factor</td>
</tr>
</tbody>
</table>
<p><br></p>
</section>
<section id="change-the-variables-type" class="level3">
<h3 class="anchored" data-anchor-id="change-the-variables-type">2.4 Change the variables type</h3>
<p><br></p>
<p>Before the full-scale EDA and feature engineering, let’s transform some variable properties. For example, Pclass is treated as numeric, but actually 1, 2, 3 are factors representing 1st, 2nd, and 3rd grades.</p>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>full <span class="ot">&lt;-</span> full <span class="sc">%&gt;%</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">Survived =</span> <span class="fu">factor</span>(Survived),</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">Pclass   =</span> <span class="fu">factor</span>(Pclass, <span class="at">ordered =</span> T),</span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">Name     =</span> <span class="fu">factor</span>(Name),</span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">Sex      =</span> <span class="fu">factor</span>(Sex),</span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a>                <span class="at">Ticket   =</span> <span class="fu">factor</span>(Ticket),</span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a>                <span class="at">Cabin    =</span> <span class="fu">factor</span>(Cabin),</span>
<span id="cb56-8"><a href="#cb56-8" aria-hidden="true" tabindex="-1"></a>                <span class="at">Embarked =</span> <span class="fu">factor</span>(Embarked))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br></p>
</section>
</section>
<section id="eda-exploratory-data-analysis" class="level2">
<h2 class="anchored" data-anchor-id="eda-exploratory-data-analysis">3. EDA : Exploratory data analysis</h2>
<p><br></p>
<p>It is the process of exploring and understanding raw data, such as how data is structured and whether there are missing values or outliers in it.</p>
<p>We will use various functions and visualizations here.</p>
<p><br></p>
<section id="data-confirmation-using-numerical-values" class="level3">
<h3 class="anchored" data-anchor-id="data-confirmation-using-numerical-values">3.1 Data confirmation using numerical values</h3>
<p>First of all, let’s check the data through the output of various functions such as head() and summary().</p>
<p><br></p>
<section id="head" class="level4">
<h4 class="anchored" data-anchor-id="head">3.1.1 head()</h4>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(full, <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   PassengerId Survived Pclass
1            1        0      3
2            2        1      1
3            3        1      3
4            4        1      1
5            5        0      3
6            6        0      3
7            7        0      1
8            8        0      3
9            9        1      3
10          10        1      2
                                                  Name    Sex Age SibSp Parch
1                              Braund, Mr. Owen Harris   male  22     1     0
2  Cumings, Mrs. John Bradley (Florence Briggs Thayer) female  38     1     0
3                               Heikkinen, Miss. Laina female  26     0     0
4         Futrelle, Mrs. Jacques Heath (Lily May Peel) female  35     1     0
5                             Allen, Mr. William Henry   male  35     0     0
6                                     Moran, Mr. James   male  NA     0     0
7                              McCarthy, Mr. Timothy J   male  54     0     0
8                       Palsson, Master. Gosta Leonard   male   2     3     1
9    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg) female  27     0     2
10                 Nasser, Mrs. Nicholas (Adele Achem) female  14     1     0
             Ticket    Fare Cabin Embarked
1         A/5 21171  7.2500              S
2          PC 17599 71.2833   C85        C
3  STON/O2. 3101282  7.9250              S
4            113803 53.1000  C123        S
5            373450  8.0500              S
6            330877  8.4583              Q
7             17463 51.8625   E46        S
8            349909 21.0750              S
9            347742 11.1333              S
10           237736 30.0708              C</code></pre>
</div>
</div>
<p><br></p>
<p>Looking at the result of head(), we can see that there is a missing value (NA) in Age.</p>
<p>If so, is there only Age missing in the entire data?</p>
<p>For the answer, please refer to 3.2 Missing values.</p>
<p><br></p>
</section>
<section id="str" class="level4">
<h4 class="anchored" data-anchor-id="str">3.1.2 str()</h4>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(full)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   1309 obs. of  12 variables:
 $ PassengerId: int  1 2 3 4 5 6 7 8 9 10 ...
 $ Survived   : Factor w/ 2 levels "0","1": 1 2 2 2 1 1 1 1 2 2 ...
 $ Pclass     : Ord.factor w/ 3 levels "1"&lt;"2"&lt;"3": 3 1 3 1 3 3 1 3 3 2 ...
 $ Name       : Factor w/ 1307 levels "Abbing, Mr. Anthony",..: 156 287 531 430 23 826 775 922 613 855 ...
 $ Sex        : Factor w/ 2 levels "female","male": 2 1 1 1 2 2 2 2 1 1 ...
 $ Age        : num  22 38 26 35 35 NA 54 2 27 14 ...
 $ SibSp      : int  1 1 0 1 0 0 0 3 0 1 ...
 $ Parch      : int  0 0 0 0 0 0 0 1 2 0 ...
 $ Ticket     : Factor w/ 929 levels "110152","110413",..: 721 817 915 66 650 374 110 542 478 175 ...
 $ Fare       : num  7.25 71.28 7.92 53.1 8.05 ...
 $ Cabin      : Factor w/ 187 levels "","A10","A11",..: 1 108 1 72 1 1 165 1 1 1 ...
 $ Embarked   : Factor w/ 4 levels "","C","Q","S": 4 2 4 4 4 3 4 4 4 2 ...</code></pre>
</div>
</div>
<p><br></p>
<p>By combining the train and test data, the total number of observations (record, row, row) is 1309 (train: 891, test: 418), and the number of variables (column, feature, variable, column) is 12.</p>
<p>In addition, you can find out what the attributes of each variable are and how many categories there are for variables that are factor attributes.</p>
<p>In addition, in head(), it can be seen that the missing value (NA), which was thought to exist only in Age, also exists in other variables including Cabin.</p>
<p><br></p>
</section>
<section id="summary" class="level4">
<h4 class="anchored" data-anchor-id="summary">3.1.3 summary()</h4>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(full)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  PassengerId   Survived   Pclass                                Name     
 Min.   :   1   0   :549   1:323   Connolly, Miss. Kate            :   2  
 1st Qu.: 328   1   :342   2:277   Kelly, Mr. James                :   2  
 Median : 655   NA's:418   3:709   Abbing, Mr. Anthony             :   1  
 Mean   : 655                      Abbott, Master. Eugene Joseph   :   1  
 3rd Qu.: 982                      Abbott, Mr. Rossmore Edward     :   1  
 Max.   :1309                      Abbott, Mrs. Stanton (Rosa Hunt):   1  
                                   (Other)                         :1301  
     Sex           Age            SibSp            Parch            Ticket    
 female:466   Min.   : 0.17   Min.   :0.0000   Min.   :0.000   CA. 2343:  11  
 male  :843   1st Qu.:21.00   1st Qu.:0.0000   1st Qu.:0.000   1601    :   8  
              Median :28.00   Median :0.0000   Median :0.000   CA 2144 :   8  
              Mean   :29.88   Mean   :0.4989   Mean   :0.385   3101295 :   7  
              3rd Qu.:39.00   3rd Qu.:1.0000   3rd Qu.:0.000   347077  :   7  
              Max.   :80.00   Max.   :8.0000   Max.   :9.000   347082  :   7  
              NA's   :263                                      (Other) :1261  
      Fare                     Cabin      Embarked
 Min.   :  0.000                  :1014    :  2   
 1st Qu.:  7.896   C23 C25 C27    :   6   C:270   
 Median : 14.454   B57 B59 B63 B66:   5   Q:123   
 Mean   : 33.295   G6             :   5   S:914   
 3rd Qu.: 31.275   B96 B98        :   4           
 Max.   :512.329   C22 C26        :   4           
 NA's   :1         (Other)        : 271           </code></pre>
</div>
</div>
<p><br></p>
<p>summary() provides a lot of information about the data.</p>
<p>The representative values of quantitative variables (Integer, Numeric), the number of categories of categorical (Factor) variables, and the number of observations belonging to each category are all shown as numerical values.</p>
<p>Here are the things to check and move on:</p>
<ul>
<li><p>Survived: This is the target variable for this competition, and 418 missing values are due to the test data.</p></li>
<li><p>Pclass: There are three categories of 1st class, 2nd class, and 3rd class, and 3rd class passengers are the most.</p></li>
<li><p>Name: There are people with similar names. So you can see that some passengers are traveling alone, while others are traveling with their families.</p></li>
<li><p>Sex: There are almost twice as many males as females.</p></li>
<li><p>Age: It ranges from 0.17 to 80 years old, but it seems necessary to check whether it is an outlier that incorrectly entered 17, and there are 263 missing values.</p></li>
<li><p>SibSp: From 0 to 8, and the 3rd quartile is 1, so it can be seen that you boarded the Titanic with a couple or siblings.</p></li>
<li><p>Parch: It ranges from 0 to 9, but the fact that the 3rd quartile is 0 indicates that there are very few passengers with parents and children.</p></li>
<li><p>Both SibSp and Parch are variables representing family relationships. Through this, we will find out the total number of people in the family, although we do not know who was on board, and based on that, we will create a categorical derived variable called FamilySized that represents the size of the family.</p></li>
<li><p>Ticket: Looking at the result of 3.1.2 str(), you can see that some passengers have exactly the same ticket, some passengers have tickets overlapping only a certain part, and some passengers have completely different tickets. We plan to use this to create a derived variable called ticket.size.</p></li>
<li><p>Fare: 0 to 512, with 1 missing value. I care that the 3rd quartile is 31.275 and the max is 512.</p></li>
<li><p>Cabin: It has the most (1014) missing values among a total of 12 features. It’s a variable that represents the ship’s area, but if there’s no way to use it, I think it should be discarded.</p></li>
<li><p>Embarked: It consists of a total of 3 categories, S is the most, and there are 2 missing values.</p></li>
</ul>
<p>When performing a basic exploration of the data, please look at the outputs of various functions besides summary() and str() while comparing them.</p>
<p><br></p>
</section>
</section>
<section id="missing-values" class="level3">
<h3 class="anchored" data-anchor-id="missing-values">3.2 Missing values</h3>
<p><br></p>
<p>This is the process of checking which variables have missing values mentioned above and how many of them exist.</p>
<p>I’m going to check it numerically and visually at the same time using the dplyr, ggplot2, and VIM packages.</p>
<p>You don’t have to use all the code I’ve run, you can use only the parts you think you need or like as you read.</p>
<p><br></p>
<section id="vim-packages" class="level4">
<h4 class="anchored" data-anchor-id="vim-packages">3.2.1 VIM packages</h4>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>VIM<span class="sc">::</span><span class="fu">aggr</span>(full, <span class="at">prop =</span> <span class="cn">FALSE</span>, <span class="at">combined =</span> <span class="cn">TRUE</span>, <span class="at">numbers =</span> <span class="cn">TRUE</span>,</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>          <span class="at">sortVars =</span> <span class="cn">TRUE</span>, <span class="at">sortCombs =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07_week_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
 Variables sorted by number of missings: 
    Variable Count
    Survived   418
         Age   263
        Fare     1
 PassengerId     0
      Pclass     0
        Name     0
         Sex     0
       SibSp     0
       Parch     0
      Ticket     0
       Cabin     0
    Embarked     0</code></pre>
</div>
</div>
<p><br></p>
</section>
<section id="tidyverse-packages" class="level4">
<h4 class="anchored" data-anchor-id="tidyverse-packages">3.2.2 tidyverse packages</h4>
<p><br></p>
<p>In addition to checking missing values at once using the VIM package, these are methods for checking missing values using various packages that exist in the tidyverse.</p>
<p>First, find the proportion of missing values for each variable with dplyr.</p>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>full <span class="sc">%&gt;%</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarize_all</span>(<span class="fu">funs</span>(<span class="fu">sum</span>(<span class="fu">is.na</span>(.))<span class="sc">/</span><span class="fu">n</span>()))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: `funs()` was deprecated in dplyr 0.8.0.
ℹ Please use a list of either functions or lambdas:

# Simple named list: list(mean = mean, median = median)

# Auto named with `tibble::lst()`: tibble::lst(mean, median)

# Using lambdas list(~ mean(., trim = .2), ~ median(., na.rm = TRUE))</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  PassengerId  Survived Pclass Name Sex       Age SibSp Parch Ticket
1           0 0.3193277      0    0   0 0.2009167     0     0      0
          Fare Cabin Embarked
1 0.0007639419     0        0</code></pre>
</div>
</div>
<p><br></p>
<p>There is a way to check the proportion of missing values that exist in variables, but it can also be checked using visual data.</p>
<p>Please see the two bar plots below.</p>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the missing value ratio of each feature -&gt; Data Frame property but has a structure of 1 row and 12 columns.</span></span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>missing_values <span class="ot">&lt;-</span> full <span class="sc">%&gt;%</span></span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarize_all</span>(<span class="fu">funs</span>(<span class="fu">sum</span>(<span class="fu">is.na</span>(.))<span class="sc">/</span><span class="fu">n</span>()))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: `funs()` was deprecated in dplyr 0.8.0.
ℹ Please use a list of either functions or lambdas:

# Simple named list: list(mean = mean, median = median)

# Auto named with `tibble::lst()`: tibble::lst(mean, median)

# Using lambdas list(~ mean(., trim = .2), ~ median(., na.rm = TRUE))</code></pre>
</div>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>missing_values <span class="sc">%&gt;%</span> head</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  PassengerId  Survived Pclass Name Sex       Age SibSp Parch Ticket
1           0 0.3193277      0    0   0 0.2009167     0     0      0
          Fare Cabin Embarked
1 0.0007639419     0        0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate the missing_values obtained above as a 12X2 data frame</span></span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>missing_values <span class="ot">&lt;-</span> tidyr<span class="sc">::</span><span class="fu">gather</span>(missing_values,</span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a>                                <span class="at">key =</span> <span class="st">"feature"</span>, <span class="at">value =</span> <span class="st">"missing_pct"</span>)</span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-5"><a href="#cb72-5" aria-hidden="true" tabindex="-1"></a>missing_values <span class="sc">%&gt;%</span> <span class="fu">head</span>(<span class="dv">12</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       feature  missing_pct
1  PassengerId 0.0000000000
2     Survived 0.3193277311
3       Pclass 0.0000000000
4         Name 0.0000000000
5          Sex 0.0000000000
6          Age 0.2009167303
7        SibSp 0.0000000000
8        Parch 0.0000000000
9       Ticket 0.0000000000
10        Fare 0.0007639419
11       Cabin 0.0000000000
12    Embarked 0.0000000000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualization with missing_values</span></span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>missing_values <span class="sc">%&gt;%</span> </span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Aesthetic setting : missing_pct 내림차순으로 정렬  </span></span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(feature, missing_pct), <span class="at">y =</span> missing_pct)) <span class="sc">+</span></span>
<span id="cb74-5"><a href="#cb74-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Bar plot </span></span>
<span id="cb74-6"><a href="#cb74-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">fill =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb74-7"><a href="#cb74-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Title generation </span></span>
<span id="cb74-8"><a href="#cb74-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Rate of missing values in each features"</span>) <span class="sc">+</span></span>
<span id="cb74-9"><a href="#cb74-9" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Title detail setting </span></span>
<span id="cb74-10"><a href="#cb74-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>,    <span class="co"># 글씨체 </span></span>
<span id="cb74-11"><a href="#cb74-11" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">hjust =</span> <span class="fl">0.5</span>,      <span class="co"># Horizon(가로비율) = 0.5</span></span>
<span id="cb74-12"><a href="#cb74-12" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">size =</span> <span class="dv">15</span>, <span class="at">color =</span> <span class="st">"darkblue"</span>)) <span class="sc">+</span></span>
<span id="cb74-13"><a href="#cb74-13" aria-hidden="true" tabindex="-1"></a>  <span class="co"># x, y axis label setting </span></span>
<span id="cb74-14"><a href="#cb74-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Feature names"</span>, <span class="at">y =</span> <span class="st">"Rate"</span>) <span class="sc">+</span> </span>
<span id="cb74-15"><a href="#cb74-15" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Plot의 x, y축 변환 </span></span>
<span id="cb74-16"><a href="#cb74-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07_week_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><br></p>
<p>If you look at the bar graph above, you can check the percentage of missing values for all <code>features</code>.</p>
<p>However, what we are actually curious about is which variables have missing values and how many missing values exist in them.</p>
<p>Therefore, after calculating the proportion of missing values using the <code>purrr</code> package, I extracted only the variables that had at least one and visualized them.</p>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 변수별 결측치 비율 계산</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>miss_pct <span class="ot">&lt;-</span> purrr<span class="sc">::</span><span class="fu">map_dbl</span>(full, <span class="cf">function</span>(x){<span class="fu">round</span>((<span class="fu">sum</span>(<span class="fu">is.na</span>(x))<span class="sc">/</span><span class="fu">length</span>(x)) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">1</span>) })</span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 결측치 비율이 0%보다 큰 변수들만 선택</span></span>
<span id="cb75-5"><a href="#cb75-5" aria-hidden="true" tabindex="-1"></a>miss_pct <span class="ot">&lt;-</span> miss_pct[miss_pct <span class="sc">&gt;</span> <span class="dv">0</span>]</span>
<span id="cb75-6"><a href="#cb75-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-7"><a href="#cb75-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Data Frame 생성 </span></span>
<span id="cb75-8"><a href="#cb75-8" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="at">miss =</span> miss_pct, <span class="at">var =</span> <span class="fu">names</span>(miss_pct), <span class="at">row.names =</span> <span class="cn">NULL</span>) <span class="sc">%&gt;%</span></span>
<span id="cb75-9"><a href="#cb75-9" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Aesthetic setting : miss 내림차순으로 정렬 </span></span>
<span id="cb75-10"><a href="#cb75-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(var, miss), <span class="at">y =</span> miss)) <span class="sc">+</span> </span>
<span id="cb75-11"><a href="#cb75-11" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Bar plot </span></span>
<span id="cb75-12"><a href="#cb75-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">'identity'</span>, <span class="at">fill =</span> <span class="st">'red'</span>) <span class="sc">+</span></span>
<span id="cb75-13"><a href="#cb75-13" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Plot title setting </span></span>
<span id="cb75-14"><a href="#cb75-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Rate of missing values"</span>) <span class="sc">+</span> </span>
<span id="cb75-15"><a href="#cb75-15" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Title detail setting </span></span>
<span id="cb75-16"><a href="#cb75-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>,    <span class="co"># 글씨체 </span></span>
<span id="cb75-17"><a href="#cb75-17" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">hjust =</span> <span class="fl">0.5</span>,      <span class="co"># Horizon(가로비율) = 0.5</span></span>
<span id="cb75-18"><a href="#cb75-18" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">size =</span> <span class="dv">15</span>, <span class="at">color =</span> <span class="st">"darkblue"</span>)) <span class="sc">+</span></span>
<span id="cb75-19"><a href="#cb75-19" aria-hidden="true" tabindex="-1"></a>  <span class="co"># x, y axis label setting </span></span>
<span id="cb75-20"><a href="#cb75-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">'Feature names'</span>, <span class="at">y =</span> <span class="st">'Rate of missing values'</span>) <span class="sc">+</span></span>
<span id="cb75-21"><a href="#cb75-21" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Plot의 x, y축 변환 </span></span>
<span id="cb75-22"><a href="#cb75-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07_week_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><br></p>
<p>Through this, only 4 variables out of a total of 12 variables have missing values (except <code>Survived</code> because it is due to <code>test</code> data), and there are many missing values in the order of <code>Cabin</code>, <code>Age</code>, <code>Embarked</code>, and <code>Fare</code>.</p>
<p><br></p>
<hr>
<p><br></p>
<p>Now, it is the process of analyzing and exploring <code>feature</code> through visualization.</p>
</section>
</section>
<section id="age" class="level3">
<h3 class="anchored" data-anchor-id="age">3.3 Age</h3>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>age.p1 <span class="ot">&lt;-</span> full <span class="sc">%&gt;%</span> </span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(Age)) <span class="sc">+</span> </span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">80</span>, <span class="at">by =</span> <span class="dv">1</span>), <span class="co"># interval setting </span></span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">col    =</span> <span class="st">"red"</span>,              <span class="co"># bar border color</span></span>
<span id="cb76-5"><a href="#cb76-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">fill   =</span> <span class="st">"green"</span>,            <span class="co"># bar inner color</span></span>
<span id="cb76-6"><a href="#cb76-6" aria-hidden="true" tabindex="-1"></a>                 <span class="at">alpha  =</span> .<span class="dv">5</span>) <span class="sc">+</span>               <span class="co"># Bar Transparency = 50%</span></span>
<span id="cb76-7"><a href="#cb76-7" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb76-8"><a href="#cb76-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Plot title</span></span>
<span id="cb76-9"><a href="#cb76-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"All Titanic passengers age hitogram"</span>) <span class="sc">+</span></span>
<span id="cb76-10"><a href="#cb76-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>,     </span>
<span id="cb76-11"><a href="#cb76-11" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">hjust =</span> <span class="fl">0.5</span>,      <span class="co"># Horizon (horizontal ratio) = 0.5</span></span>
<span id="cb76-12"><a href="#cb76-12" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">size =</span> <span class="dv">15</span>, <span class="at">color =</span> <span class="st">"darkblue"</span>))</span>
<span id="cb76-13"><a href="#cb76-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-14"><a href="#cb76-14" aria-hidden="true" tabindex="-1"></a>age.p2 <span class="ot">&lt;-</span> full <span class="sc">%&gt;%</span> </span>
<span id="cb76-15"><a href="#cb76-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Exclude values where Survived == NA in the test dataset  </span></span>
<span id="cb76-16"><a href="#cb76-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Survived)) <span class="sc">%&gt;%</span> </span>
<span id="cb76-17"><a href="#cb76-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(Age, <span class="at">fill =</span> Survived)) <span class="sc">+</span> </span>
<span id="cb76-18"><a href="#cb76-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">alpha =</span> .<span class="dv">5</span>) <span class="sc">+</span></span>
<span id="cb76-19"><a href="#cb76-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Titanic passengers age density plot"</span>) <span class="sc">+</span> </span>
<span id="cb76-20"><a href="#cb76-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>, <span class="at">hjust =</span> <span class="fl">0.5</span>,</span>
<span id="cb76-21"><a href="#cb76-21" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">size =</span> <span class="dv">15</span>, <span class="at">color =</span> <span class="st">"darkblue"</span>))</span>
<span id="cb76-22"><a href="#cb76-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-23"><a href="#cb76-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the two graphs created above on one screen</span></span>
<span id="cb76-24"><a href="#cb76-24" aria-hidden="true" tabindex="-1"></a><span class="fu">ggarrange</span>(age.p1, age.p2, <span class="at">ncol=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07_week_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><br></p>
</section>
<section id="pclass" class="level3">
<h3 class="anchored" data-anchor-id="pclass">3.4 Pclass</h3>
<p><br></p>
<p>Let’s visualize the frequency of passengers for each <code>Pclass</code>.</p>
<p>After grouping (grouping) by <code>Pclass</code> using <code>dplyr</code> package, <code>Data Frame</code> representing frequency by category was created and visualized with <code>ggplot</code>.</p>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>full <span class="sc">%&gt;%</span> </span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Get Pclass frequencies using dplyr::group_by(), summarize()</span></span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Pclass) <span class="sc">%&gt;%</span> </span>
<span id="cb77-4"><a href="#cb77-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">N =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span> </span>
<span id="cb77-5"><a href="#cb77-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Aesthetic setting </span></span>
<span id="cb77-6"><a href="#cb77-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(Pclass, N)) <span class="sc">+</span></span>
<span id="cb77-7"><a href="#cb77-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>() <span class="sc">+</span></span>
<span id="cb77-8"><a href="#cb77-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> N),       </span>
<span id="cb77-9"><a href="#cb77-9" aria-hidden="true" tabindex="-1"></a>            <span class="at">size =</span> <span class="dv">5</span>,             </span>
<span id="cb77-10"><a href="#cb77-10" aria-hidden="true" tabindex="-1"></a>            <span class="at">vjust =</span> <span class="fl">1.2</span>,           </span>
<span id="cb77-11"><a href="#cb77-11" aria-hidden="true" tabindex="-1"></a>            <span class="at">color =</span> <span class="st">"#FFFFFF"</span>) <span class="sc">+</span>  </span>
<span id="cb77-12"><a href="#cb77-12" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Plot title </span></span>
<span id="cb77-13"><a href="#cb77-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Number of each Pclass's passengers"</span>) <span class="sc">+</span> </span>
<span id="cb77-14"><a href="#cb77-14" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Title setting </span></span>
<span id="cb77-15"><a href="#cb77-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>, <span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">15</span>)) <span class="sc">+</span></span>
<span id="cb77-16"><a href="#cb77-16" aria-hidden="true" tabindex="-1"></a>  <span class="co"># x, y axis name change  </span></span>
<span id="cb77-17"><a href="#cb77-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Pclass"</span>, <span class="at">y =</span> <span class="st">"Count"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07_week_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><br></p>
<p>It can be seen that the largest number of passengers boarded in the 3-class cabin.</p>
<p><br></p>
</section>
<section id="fare" class="level3">
<h3 class="anchored" data-anchor-id="fare">3.5 Fare</h3>
<p><br></p>
<p>This is a visualization of the ‘Fare’ variable, which represents the amount paid by the passenger.</p>
<p>Two histograms and boxplots were used.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Histogram </span></span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>Fare.p1 <span class="ot">&lt;-</span> full <span class="sc">%&gt;%</span></span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(Fare)) <span class="sc">+</span> </span>
<span id="cb78-4"><a href="#cb78-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">col    =</span> <span class="st">"yellow"</span>,</span>
<span id="cb78-5"><a href="#cb78-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">fill   =</span> <span class="st">"blue"</span>, </span>
<span id="cb78-6"><a href="#cb78-6" aria-hidden="true" tabindex="-1"></a>                 <span class="at">alpha  =</span> .<span class="dv">5</span>) <span class="sc">+</span></span>
<span id="cb78-7"><a href="#cb78-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Histogram of passengers Fare"</span>) <span class="sc">+</span></span>
<span id="cb78-8"><a href="#cb78-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>, <span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">15</span>))</span>
<span id="cb78-9"><a href="#cb78-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-10"><a href="#cb78-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Boxplot </span></span>
<span id="cb78-11"><a href="#cb78-11" aria-hidden="true" tabindex="-1"></a>Fare.p2 <span class="ot">&lt;-</span> full <span class="sc">%&gt;%</span></span>
<span id="cb78-12"><a href="#cb78-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Survived)) <span class="sc">%&gt;%</span> </span>
<span id="cb78-13"><a href="#cb78-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(Survived, Fare)) <span class="sc">+</span> </span>
<span id="cb78-14"><a href="#cb78-14" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Observations are drawn as gray dots, but overlapping areas are spread out.  </span></span>
<span id="cb78-15"><a href="#cb78-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">col =</span> <span class="st">"gray"</span>) <span class="sc">+</span> </span>
<span id="cb78-16"><a href="#cb78-16" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Boxplot: 50% transparency</span></span>
<span id="cb78-17"><a href="#cb78-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">alpha =</span> .<span class="dv">5</span>) <span class="sc">+</span> </span>
<span id="cb78-18"><a href="#cb78-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Boxplot of passengers Fare"</span>) <span class="sc">+</span></span>
<span id="cb78-19"><a href="#cb78-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>, <span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">15</span>))</span>
<span id="cb78-20"><a href="#cb78-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-21"><a href="#cb78-21" aria-hidden="true" tabindex="-1"></a><span class="fu">ggarrange</span>(Fare.p1, Fare.p2, <span class="at">ncol=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07_week_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><br></p>
<p>You can see that the survivors have a higher ‘Fare’ than the deceased passengers, but not by much.</p>
<p><br></p>
</section>
<section id="sex" class="level3">
<h3 class="anchored" data-anchor-id="sex">3.6 Sex</h3>
<p>Are there differences in survival rates between men and women? See the <code>plot</code> below.</p>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a>sex.p1 <span class="ot">&lt;-</span> full <span class="sc">%&gt;%</span> </span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">group_by</span>(Sex) <span class="sc">%&gt;%</span> </span>
<span id="cb79-3"><a href="#cb79-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">N =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span> </span>
<span id="cb79-4"><a href="#cb79-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(Sex, N)) <span class="sc">+</span></span>
<span id="cb79-5"><a href="#cb79-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>() <span class="sc">+</span></span>
<span id="cb79-6"><a href="#cb79-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> N), <span class="at">size =</span> <span class="dv">5</span>, <span class="at">vjust =</span> <span class="fl">1.2</span>, <span class="at">color =</span> <span class="st">"#FFFFFF"</span>) <span class="sc">+</span> </span>
<span id="cb79-7"><a href="#cb79-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Bar plot of Sex"</span>) <span class="sc">+</span></span>
<span id="cb79-8"><a href="#cb79-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Sex"</span>, <span class="at">y =</span> <span class="st">"Count"</span>)</span>
<span id="cb79-9"><a href="#cb79-9" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb79-10"><a href="#cb79-10" aria-hidden="true" tabindex="-1"></a>sex.p2 <span class="ot">&lt;-</span> full[<span class="dv">1</span><span class="sc">:</span><span class="dv">891</span>, ] <span class="sc">%&gt;%</span> </span>
<span id="cb79-11"><a href="#cb79-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(Sex, <span class="at">fill =</span> Survived)) <span class="sc">+</span></span>
<span id="cb79-12"><a href="#cb79-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">"fill"</span>) <span class="sc">+</span> </span>
<span id="cb79-13"><a href="#cb79-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">"Set1"</span>) <span class="sc">+</span></span>
<span id="cb79-14"><a href="#cb79-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> percent) <span class="sc">+</span></span>
<span id="cb79-15"><a href="#cb79-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Survival Rate by Sex"</span>) <span class="sc">+</span> </span>
<span id="cb79-16"><a href="#cb79-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Sex"</span>, <span class="at">y =</span> <span class="st">"Rate"</span>)</span>
<span id="cb79-17"><a href="#cb79-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb79-18"><a href="#cb79-18" aria-hidden="true" tabindex="-1"></a><span class="fu">ggarrange</span>(sex.p1, sex.p2, <span class="at">ncol =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07_week_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mosaicplot</span>(Survived <span class="sc">~</span> Sex,</span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>           <span class="at">data =</span> full[<span class="dv">1</span><span class="sc">:</span><span class="dv">891</span>, ], <span class="at">col =</span> <span class="cn">TRUE</span>,</span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">main =</span> <span class="st">"Survival rate by passengers gender"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07_week_files/figure-html/unnamed-chunk-26-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><br></p>
<p>If you interpret the graph, you can see that the survival rate is higher for female passengers, while there are far more males than females.</p>
<p><br></p>
</section>
</section>
<section id="feature-engineering-data-pre-processing" class="level2">
<h2 class="anchored" data-anchor-id="feature-engineering-data-pre-processing">4. Feature engineering &amp; Data Pre-processing</h2>
<p><br></p>
<p>This is the process of filling in missing values (‘NA’) based on the contents of ‘Chapter 3 EDA’ and creating derived variables at the same time.</p>
<p><br></p>
<section id="age---age.group" class="level3">
<h3 class="anchored" data-anchor-id="age---age.group">4.1 Age -&gt; Age.Group</h3>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a>full <span class="ot">&lt;-</span> full <span class="sc">%&gt;%</span></span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a><span class="co"># The missing value (NA) is filled in first, and the average of the values excluding the missing value is filled.</span></span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Age =</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(Age), <span class="fu">mean</span>(full<span class="sc">$</span>Age, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), Age),</span>
<span id="cb81-4"><a href="#cb81-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a categorical derived variable Age.Group based on Age values</span></span>
<span id="cb81-5"><a href="#cb81-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">Age.Group =</span> <span class="fu">case_when</span>(Age <span class="sc">&lt;</span> <span class="dv">13</span>             <span class="sc">~</span> <span class="st">"Age.0012"</span>,</span>
<span id="cb81-6"><a href="#cb81-6" aria-hidden="true" tabindex="-1"></a>                               Age <span class="sc">&gt;=</span> <span class="dv">13</span> <span class="sc">&amp;</span> Age <span class="sc">&lt;</span> <span class="dv">18</span> <span class="sc">~</span> <span class="st">"Age.1317"</span>,</span>
<span id="cb81-7"><a href="#cb81-7" aria-hidden="true" tabindex="-1"></a>                               Age <span class="sc">&gt;=</span> <span class="dv">18</span> <span class="sc">&amp;</span> Age <span class="sc">&lt;</span> <span class="dv">60</span> <span class="sc">~</span> <span class="st">"Age.1859"</span>,</span>
<span id="cb81-8"><a href="#cb81-8" aria-hidden="true" tabindex="-1"></a>                               Age <span class="sc">&gt;=</span> <span class="dv">60</span>            <span class="sc">~</span> <span class="st">"Age.60inf"</span>),</span>
<span id="cb81-9"><a href="#cb81-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert Chr attribute to Factor</span></span>
<span id="cb81-10"><a href="#cb81-10" aria-hidden="true" tabindex="-1"></a>        <span class="at">Age.Group =</span> <span class="fu">factor</span>(Age.Group))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br></p>
</section>
<section id="sibsp-parch---familysized" class="level3">
<h3 class="anchored" data-anchor-id="sibsp-parch---familysized">4.3 SibSp &amp; Parch -&gt; FamilySized</h3>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>full <span class="ot">&lt;-</span> full <span class="sc">%&gt;%</span> </span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a> <span class="co"># First create a derived variable called FamilySize by adding SibSp, Parch and 1 (self)</span></span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">FamilySize =</span> .<span class="sc">$</span>SibSp <span class="sc">+</span> .<span class="sc">$</span>Parch <span class="sc">+</span> <span class="dv">1</span>,</span>
<span id="cb82-4"><a href="#cb82-4" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Create a categorical derived variable FamilySized according to the value of FamilySize</span></span>
<span id="cb82-5"><a href="#cb82-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">FamilySized =</span> dplyr<span class="sc">::</span><span class="fu">case_when</span>(FamilySize <span class="sc">==</span> <span class="dv">1</span> <span class="sc">~</span> <span class="st">"Single"</span>,</span>
<span id="cb82-6"><a href="#cb82-6" aria-hidden="true" tabindex="-1"></a>                                        FamilySize <span class="sc">&gt;=</span> <span class="dv">2</span> <span class="sc">&amp;</span> FamilySize <span class="sc">&lt;</span> <span class="dv">5</span> <span class="sc">~</span> <span class="st">"Small"</span>,</span>
<span id="cb82-7"><a href="#cb82-7" aria-hidden="true" tabindex="-1"></a>                                        FamilySize <span class="sc">&gt;=</span> <span class="dv">5</span> <span class="sc">~</span> <span class="st">"Big"</span>),</span>
<span id="cb82-8"><a href="#cb82-8" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Convert the Chr property FamilySized to a factor</span></span>
<span id="cb82-9"><a href="#cb82-9" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Assign new levels according to the size of the group size</span></span>
<span id="cb82-10"><a href="#cb82-10" aria-hidden="true" tabindex="-1"></a>         <span class="at">FamilySized =</span> <span class="fu">factor</span>(FamilySized, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Single"</span>, <span class="st">"Small"</span>, <span class="st">"Big"</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br></p>
<p>Ceated <code>FamilySized</code> using <code>SibSp</code> and <code>Parch</code>.</p>
<p>Reducing these two variables to one has the advantage of simplifying the model.</p>
<p>A similar use case is to combine height and weight into a BMI index.</p>
<p><br></p>
</section>
<section id="name-sex---title" class="level3">
<h3 class="anchored" data-anchor-id="name-sex---title">4.4 Name &amp; Sex -&gt; title</h3>
<p><br></p>
<p>When looking at the results of ‘Chapter 3.6 Sex’, it was confirmed that the survival rate of women was higher than that of men.</p>
<p>Therefore, in <code>Name</code>, “Wouldn’t it be useful to extract only names related to gender and categorize them?” I think it is.</p>
<p>First, extract only the column vector named <code>Name</code> from <code>full</code> data and save it as <code>title</code>.</p>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="co"># First, extract only the Name column vector and store it in the title vector</span></span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a>title <span class="ot">&lt;-</span> full<span class="sc">$</span>Name</span>
<span id="cb83-3"><a href="#cb83-3" aria-hidden="true" tabindex="-1"></a>title <span class="sc">%&gt;%</span> <span class="fu">head</span>(<span class="dv">20</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] Braund, Mr. Owen Harris                                
 [2] Cumings, Mrs. John Bradley (Florence Briggs Thayer)    
 [3] Heikkinen, Miss. Laina                                 
 [4] Futrelle, Mrs. Jacques Heath (Lily May Peel)           
 [5] Allen, Mr. William Henry                               
 [6] Moran, Mr. James                                       
 [7] McCarthy, Mr. Timothy J                                
 [8] Palsson, Master. Gosta Leonard                         
 [9] Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)      
[10] Nasser, Mrs. Nicholas (Adele Achem)                    
[11] Sandstrom, Miss. Marguerite Rut                        
[12] Bonnell, Miss. Elizabeth                               
[13] Saundercock, Mr. William Henry                         
[14] Andersson, Mr. Anders Johan                            
[15] Vestrom, Miss. Hulda Amanda Adolfina                   
[16] Hewlett, Mrs. (Mary D Kingcome)                        
[17] Rice, Master. Eugene                                   
[18] Williams, Mr. Charles Eugene                           
[19] Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)
[20] Masselmani, Mrs. Fatima                                
1307 Levels: Abbing, Mr. Anthony ... Zimmerman, Mr. Leo</code></pre>
</div>
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Using regular expression and gsub(), extract only names that are highly related to gender and save them as title vectors</span></span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a>title <span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"^.*, (.*?)</span><span class="sc">\\</span><span class="st">..*$"</span>, <span class="st">"</span><span class="sc">\\</span><span class="st">1"</span>, title)</span>
<span id="cb85-3"><a href="#cb85-3" aria-hidden="true" tabindex="-1"></a>title <span class="sc">%&gt;%</span> <span class="fu">head</span>(<span class="dv">20</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Mr"     "Mrs"    "Miss"   "Mrs"    "Mr"     "Mr"     "Mr"     "Master"
 [9] "Mrs"    "Mrs"    "Miss"   "Miss"   "Mr"     "Mr"     "Miss"   "Mrs"   
[17] "Master" "Mr"     "Mrs"    "Mrs"   </code></pre>
</div>
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Save the title vector saved above to full again, but save it as a title derived variable</span></span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a>full<span class="sc">$</span>title <span class="ot">&lt;-</span> title</span>
<span id="cb87-3"><a href="#cb87-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb87-4"><a href="#cb87-4" aria-hidden="true" tabindex="-1"></a>full<span class="sc">$</span>title <span class="sc">%&gt;%</span> <span class="fu">head</span>(<span class="dv">20</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Mr"     "Mrs"    "Miss"   "Mrs"    "Mr"     "Mr"     "Mr"     "Master"
 [9] "Mrs"    "Mrs"    "Miss"   "Miss"   "Mr"     "Mr"     "Miss"   "Mrs"   
[17] "Master" "Mr"     "Mrs"    "Mrs"   </code></pre>
</div>
</div>
<p><br></p>
<p><code>gsub("^.*, (.*?)\\..*$", "\\1", title)</code> In short, this code uses <strong><code>gsub</code></strong> to search for and replace a pattern in the <strong><code>title</code></strong> string, where the pattern is defined by the regular expression <strong><code>"^.*, (.*?)\\..*$"</code></strong> and the replacement is defined by the string <strong><code>"\\1"</code></strong>. If you want to understand more about regular expression. Please see my blog post: <a href="https://cjleelab.netlify.app/blogs/posts/3_regular_expression_part_1.html">What are Regular Expressions and How to Use Them in R</a></p>
<p>Then check what are the <code>Unique</code> <code>title</code>s.</p>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(full<span class="sc">$</span>title)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Mr"           "Mrs"          "Miss"         "Master"       "Don"         
 [6] "Rev"          "Dr"           "Mme"          "Ms"           "Major"       
[11] "Lady"         "Sir"          "Mlle"         "Col"          "Capt"        
[16] "the Countess" "Jonkheer"     "Dona"        </code></pre>
</div>
</div>
<p><br></p>
<p>You can see that there are 18 categories in total.</p>
<p>If you use this derived variable called ‘title’ as it is, the complexity of the model (especially the tree based model) increases considerably, so you need to reduce the category.</p>
<p>Before that, let’s check the frequency and rate for each category using the <code>descr</code> package.</p>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check frequency, ratio by category</span></span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a>descr<span class="sc">::</span><span class="fu">CrossTable</span>(full<span class="sc">$</span>title)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Cell Contents 
|-------------------------|
|                       N | 
|           N / Row Total | 
|-------------------------|

|         Capt |          Col |          Don |         Dona |           Dr |
|--------------|--------------|--------------|--------------|--------------|
|            1 |            4 |            1 |            1 |            8 |
|        0.001 |        0.003 |        0.001 |        0.001 |        0.006 |
|--------------|--------------|--------------|--------------|--------------|

|     Jonkheer |         Lady |        Major |       Master |         Miss |
|--------------|--------------|--------------|--------------|--------------|
|            1 |            1 |            2 |           61 |          260 |
|        0.001 |        0.001 |        0.002 |        0.047 |        0.199 |
|--------------|--------------|--------------|--------------|--------------|

|         Mlle |          Mme |           Mr |          Mrs |           Ms |
|--------------|--------------|--------------|--------------|--------------|
|            2 |            1 |          757 |          197 |            2 |
|        0.002 |        0.001 |        0.578 |        0.150 |        0.002 |
|--------------|--------------|--------------|--------------|--------------|

|          Rev |          Sir | the Countess |
|--------------|--------------|--------------|
|            8 |            1 |            1 |
|        0.006 |        0.001 |        0.001 |
|--------------|--------------|--------------|</code></pre>
</div>
</div>
<p><br></p>
<p>The frequencies and proportions of the 18 categories are very different.</p>
<p>So let’s narrow these down to a total of five categories.</p>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Simplify into 5 categories</span></span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a>full <span class="ot">&lt;-</span> full <span class="sc">%&gt;%</span></span>
<span id="cb93-3"><a href="#cb93-3" aria-hidden="true" tabindex="-1"></a><span class="co"># If you use "==" instead of "%in%", it won't work as you want because of Recyling Rule.</span></span>
<span id="cb93-4"><a href="#cb93-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">title =</span> <span class="fu">ifelse</span>(title <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Mlle"</span>, <span class="st">"Ms"</span>, <span class="st">"Lady"</span>, <span class="st">"Dona"</span>), <span class="st">"Miss"</span>, title),</span>
<span id="cb93-5"><a href="#cb93-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">title =</span> <span class="fu">ifelse</span>(title <span class="sc">==</span> <span class="st">"Mme"</span>, <span class="st">"Mrs"</span>, title),</span>
<span id="cb93-6"><a href="#cb93-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">title =</span> <span class="fu">ifelse</span>(title <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Capt"</span>, <span class="st">"Col"</span>, <span class="st">"Major"</span>, <span class="st">"Dr"</span>, <span class="st">"Rev"</span>, <span class="st">"Don"</span>,</span>
<span id="cb93-7"><a href="#cb93-7" aria-hidden="true" tabindex="-1"></a>                                     <span class="st">"Sir"</span>, <span class="st">"the Countess"</span>, <span class="st">"Jonkheer"</span>), <span class="st">"Officer"</span>, title),</span>
<span id="cb93-8"><a href="#cb93-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">title =</span> <span class="fu">factor</span>(title))</span>
<span id="cb93-9"><a href="#cb93-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb93-10"><a href="#cb93-10" aria-hidden="true" tabindex="-1"></a><span class="co"># After creating the derived variable, check the frequency and ratio for each category</span></span>
<span id="cb93-11"><a href="#cb93-11" aria-hidden="true" tabindex="-1"></a>descr<span class="sc">::</span><span class="fu">CrossTable</span>(full<span class="sc">$</span>title)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Cell Contents 
|-------------------------|
|                       N | 
|           N / Row Total | 
|-------------------------|

|  Master |    Miss |      Mr |     Mrs | Officer |
|---------|---------|---------|---------|---------|
|      61 |     266 |     757 |     198 |      27 |
|   0.047 |   0.203 |   0.578 |   0.151 |   0.021 |
|---------|---------|---------|---------|---------|</code></pre>
</div>
</div>
<p><br></p>
</section>
<section id="ticket---ticket.size" class="level3">
<h3 class="anchored" data-anchor-id="ticket---ticket.size">4.5 Ticket -&gt; ticket.size</h3>
<p><br></p>
<p>As we saw in <code>Chapter 3.1.3 Summary()</code>, the number of passengers (<code>train</code> and <code>test</code> together) is 1309. However, all passengers’ tickets are not different.</p>
<p>See the results of <code>summary()</code> and <code>unique()</code> below.</p>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="co"># We used length() to get only the number of unique categories.</span></span>
<span id="cb95-2"><a href="#cb95-2" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">unique</span>(full<span class="sc">$</span>Ticket))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 929</code></pre>
</div>
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Printing all of them was too messy, so only 10 were printed.</span></span>
<span id="cb97-2"><a href="#cb97-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">summary</span>(full<span class="sc">$</span>Ticket), <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    CA. 2343         1601      CA 2144      3101295       347077       347082 
          11            8            8            7            7            7 
    PC 17608 S.O.C. 14879       113781        19950 
           7            7            6            6 </code></pre>
</div>
</div>
<p><br></p>
<p>Why are there 929 unique tickets when there are no missing values in <code>feature</code>?</p>
<p>Even the ticket is <code>CA. There are 11 exactly the same number of people as 2343</code>.</p>
<p>Let’s see who the passengers are.</p>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a>full <span class="sc">%&gt;%</span> </span>
<span id="cb99-2"><a href="#cb99-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter only 11 passengers with matching tickets</span></span>
<span id="cb99-3"><a href="#cb99-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Ticket <span class="sc">==</span> <span class="st">"CA. 2343"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb99-4"><a href="#cb99-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># We don't need to check for all variables, so we only want to look at the variables below.</span></span>
<span id="cb99-5"><a href="#cb99-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Pclass, Name, Age, FamilySized)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Pclass                              Name      Age FamilySized
1       3        Sage, Master. Thomas Henry 29.88114         Big
2       3      Sage, Miss. Constance Gladys 29.88114         Big
3       3               Sage, Mr. Frederick 29.88114         Big
4       3          Sage, Mr. George John Jr 29.88114         Big
5       3           Sage, Miss. Stella Anna 29.88114         Big
6       3          Sage, Mr. Douglas Bullen 29.88114         Big
7       3 Sage, Miss. Dorothy Edith "Dolly" 29.88114         Big
8       3                   Sage, Miss. Ada 29.88114         Big
9       3             Sage, Mr. John George 29.88114         Big
10      3       Sage, Master. William Henry 14.50000         Big
11      3    Sage, Mrs. John (Annie Bullen) 29.88114         Big</code></pre>
</div>
</div>
<p><br></p>
<p>You can see that the 11 passengers above are all from the same family, brothers.</p>
<p>While there are passengers whose tickets are exactly the same, there are also passengers whose tickets are partially matched.</p>
<p>Create a <code>ticket.unique</code> derived variable that represents the number of unique numbers (number of characters) of such a ticket.</p>
<p>Let’s create a derived variable <code>ticket.size</code> with 3 categories based on <code>ticket.unique</code>.</p>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="co"># First of all, ticket.unique is saved as all 0</span></span>
<span id="cb101-2"><a href="#cb101-2" aria-hidden="true" tabindex="-1"></a>ticket.unique <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">0</span>, <span class="fu">nrow</span>(full))</span>
<span id="cb101-3"><a href="#cb101-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb101-4"><a href="#cb101-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract only the unique ones from ticket features and store them in the tickets vector</span></span>
<span id="cb101-5"><a href="#cb101-5" aria-hidden="true" tabindex="-1"></a>tickets <span class="ot">&lt;-</span> <span class="fu">unique</span>(full<span class="sc">$</span>Ticket)</span>
<span id="cb101-6"><a href="#cb101-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb101-7"><a href="#cb101-7" aria-hidden="true" tabindex="-1"></a><span class="co"># After extracting only passengers with the same ticket by using overlapping loops, extract and store the length (number of characters) of each ticket.</span></span>
<span id="cb101-8"><a href="#cb101-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb101-9"><a href="#cb101-9" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(tickets)) {</span>
<span id="cb101-10"><a href="#cb101-10" aria-hidden="true" tabindex="-1"></a>  current.ticket <span class="ot">&lt;-</span> tickets[i]</span>
<span id="cb101-11"><a href="#cb101-11" aria-hidden="true" tabindex="-1"></a>  party.indexes <span class="ot">&lt;-</span> <span class="fu">which</span>(full<span class="sc">$</span>Ticket <span class="sc">==</span> current.ticket)</span>
<span id="cb101-12"><a href="#cb101-12" aria-hidden="true" tabindex="-1"></a>    <span class="co"># For loop 중첩 </span></span>
<span id="cb101-13"><a href="#cb101-13" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> (k <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(party.indexes)) {</span>
<span id="cb101-14"><a href="#cb101-14" aria-hidden="true" tabindex="-1"></a>    ticket.unique[party.indexes[k]] <span class="ot">&lt;-</span> <span class="fu">length</span>(party.indexes)</span>
<span id="cb101-15"><a href="#cb101-15" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb101-16"><a href="#cb101-16" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb101-17"><a href="#cb101-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb101-18"><a href="#cb101-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Save ticket.unique calculated above as a derived variable</span></span>
<span id="cb101-19"><a href="#cb101-19" aria-hidden="true" tabindex="-1"></a>full<span class="sc">$</span>ticket.unique <span class="ot">&lt;-</span> ticket.unique</span>
<span id="cb101-20"><a href="#cb101-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb101-21"><a href="#cb101-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Create ticket.size variable by dividing it into three categories according to ticket.unique</span></span>
<span id="cb101-22"><a href="#cb101-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb101-23"><a href="#cb101-23" aria-hidden="true" tabindex="-1"></a>full <span class="ot">&lt;-</span> full <span class="sc">%&gt;%</span> </span>
<span id="cb101-24"><a href="#cb101-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ticket.size =</span> <span class="fu">case_when</span>(ticket.unique <span class="sc">==</span> <span class="dv">1</span> <span class="sc">~</span> <span class="st">'Single'</span>,</span>
<span id="cb101-25"><a href="#cb101-25" aria-hidden="true" tabindex="-1"></a>                                 ticket.unique <span class="sc">&lt;</span> <span class="dv">5</span> <span class="sc">&amp;</span> ticket.unique <span class="sc">&gt;=</span> <span class="dv">2</span> <span class="sc">~</span> <span class="st">"Small"</span>,</span>
<span id="cb101-26"><a href="#cb101-26" aria-hidden="true" tabindex="-1"></a>                                 ticket.unique <span class="sc">&gt;=</span> <span class="dv">5</span> <span class="sc">~</span> <span class="st">"Big"</span>),</span>
<span id="cb101-27"><a href="#cb101-27" aria-hidden="true" tabindex="-1"></a>         <span class="at">ticket.size =</span> <span class="fu">factor</span>(ticket.size,</span>
<span id="cb101-28"><a href="#cb101-28" aria-hidden="true" tabindex="-1"></a>                              <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Single"</span>, <span class="st">"Small"</span>, <span class="st">"Big"</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br></p>
</section>
<section id="embarked" class="level3">
<h3 class="anchored" data-anchor-id="embarked">4.6 Embarked</h3>
<p><br></p>
<p>This is <code>feature</code> with two missing values (<code>NA</code>). In the case of <code>Embarked</code>, replace it with <code>S</code>, which is the most frequent value among the three categories.</p>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a>full<span class="sc">$</span>Embarked <span class="ot">&lt;-</span> <span class="fu">replace</span>(full<span class="sc">$</span>Embarked,               <span class="co"># Specify Data$feature to replace</span></span>
<span id="cb102-2"><a href="#cb102-2" aria-hidden="true" tabindex="-1"></a>                         <span class="fu">which</span>(<span class="fu">is.na</span>(full<span class="sc">$</span>Embarked)), <span class="co"># Find only missing values</span></span>
<span id="cb102-3"><a href="#cb102-3" aria-hidden="true" tabindex="-1"></a>                         <span class="st">'S'</span>)                        <span class="co"># specify the value to replace</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br></p>
</section>
<section id="fare-1" class="level3">
<h3 class="anchored" data-anchor-id="fare-1">4.7 Fare</h3>
<p><br></p>
<p>For <code>Fare</code>, there was only one missing value.</p>
<p>Based on the histogram seen above (<code>Chapter 3.5 Fare</code>), missing values are replaced with 0.</p>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a>full<span class="sc">$</span>Fare <span class="ot">&lt;-</span> <span class="fu">replace</span>(full<span class="sc">$</span>Fare, <span class="fu">which</span>(<span class="fu">is.na</span>(full<span class="sc">$</span>Fare)), <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br></p>
<p>At this point, data preprocessing is complete.</p>
<p>The following is the process of selecting the variables to be used for model creation while exploring the derived variables created so far.</p>
<p>In other words, <code>Feature selection</code>.</p>
<p><br></p>
<hr>
<p><br></p>
</section>
</section>
<section id="relationship-to-target-feature-survived-feature-selection" class="level2">
<h2 class="anchored" data-anchor-id="relationship-to-target-feature-survived-feature-selection">5. Relationship to target feature <code>Survived</code> &amp; Feature selection</h2>
<p><br></p>
<p>Prior to full-scale visualization, since the purpose here is to see how well each variable correlates with the survival rate, we did not use the entire <code>full</code> data, but only the <code>train</code> data set that can determine survival and death.</p>
<p>Also, please note that the <code>plot</code> used above may be duplicated as it is.</p>
<p><br></p>
<section id="data-set-split" class="level3">
<h3 class="anchored" data-anchor-id="data-set-split">5.0 Data set split</h3>
<p>First, use the code below to split preprocessed <code>full</code> data into <code>train</code> and <code>test</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb104"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Before feature selection, select all variables first.</span></span>
<span id="cb104-2"><a href="#cb104-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb104-3"><a href="#cb104-3" aria-hidden="true" tabindex="-1"></a>train <span class="ot">&lt;-</span> full[<span class="dv">1</span><span class="sc">:</span><span class="dv">891</span>, ]</span>
<span id="cb104-4"><a href="#cb104-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb104-5"><a href="#cb104-5" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> full[<span class="dv">892</span><span class="sc">:</span><span class="dv">1309</span>, ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br></p>
</section>
<section id="pclass-1" class="level3">
<h3 class="anchored" data-anchor-id="pclass-1">5.1 Pclass</h3>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a>train <span class="sc">%&gt;%</span> </span>
<span id="cb105-2"><a href="#cb105-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(Pclass, <span class="at">fill =</span> Survived)) <span class="sc">+</span> </span>
<span id="cb105-3"><a href="#cb105-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">"fill"</span>) <span class="sc">+</span></span>
<span id="cb105-4"><a href="#cb105-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Set plot theme: Converts to a more vivid color.</span></span>
<span id="cb105-5"><a href="#cb105-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">"Set1"</span>) <span class="sc">+</span></span>
<span id="cb105-6"><a href="#cb105-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Y axis setting </span></span>
<span id="cb105-7"><a href="#cb105-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> percent) <span class="sc">+</span></span>
<span id="cb105-8"><a href="#cb105-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Set x, y axis names and plot main title, sub title</span></span>
<span id="cb105-9"><a href="#cb105-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Pclass"</span>, <span class="at">y =</span> <span class="st">"Rate"</span>,</span>
<span id="cb105-10"><a href="#cb105-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Bar plot"</span>, <span class="at">subtitle =</span> <span class="st">"How many people survived in each Pclass?"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07_week_files/figure-html/unnamed-chunk-39-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><br></p>
</section>
<section id="sex-1" class="level3">
<h3 class="anchored" data-anchor-id="sex-1">5.2 Sex</h3>
<p><br></p>
<p><strong>Same as <code>Chapter 3.6 Sex</code>.</strong></p>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb106"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb106-1"><a href="#cb106-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mosaicplot</span>(Survived <span class="sc">~</span> Sex,</span>
<span id="cb106-2"><a href="#cb106-2" aria-hidden="true" tabindex="-1"></a>           <span class="at">data =</span> train, <span class="at">col =</span> <span class="cn">TRUE</span>,</span>
<span id="cb106-3"><a href="#cb106-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">main =</span> <span class="st">"Survival rate by passengers gender"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07_week_files/figure-html/unnamed-chunk-40-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><br></p>
</section>
<section id="embarked-1" class="level3">
<h3 class="anchored" data-anchor-id="embarked-1">5.3 Embarked</h3>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb107"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a>train <span class="sc">%&gt;%</span> </span>
<span id="cb107-2"><a href="#cb107-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(Embarked, <span class="at">fill =</span> Survived)) <span class="sc">+</span></span>
<span id="cb107-3"><a href="#cb107-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">"fill"</span>) <span class="sc">+</span> </span>
<span id="cb107-4"><a href="#cb107-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">"Set1"</span>) <span class="sc">+</span></span>
<span id="cb107-5"><a href="#cb107-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> percent) <span class="sc">+</span></span>
<span id="cb107-6"><a href="#cb107-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Embarked"</span>, <span class="at">y =</span> <span class="st">"Rate"</span>,</span>
<span id="cb107-7"><a href="#cb107-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Bar plot"</span>, <span class="at">subtitle =</span> <span class="st">"How many people survived in each Embarked?"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07_week_files/figure-html/unnamed-chunk-41-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><br></p>
</section>
<section id="familysized" class="level3">
<h3 class="anchored" data-anchor-id="familysized">5.4 FamilySized</h3>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb108"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb108-1"><a href="#cb108-1" aria-hidden="true" tabindex="-1"></a>train <span class="sc">%&gt;%</span> </span>
<span id="cb108-2"><a href="#cb108-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(FamilySized, <span class="at">fill =</span> Survived)) <span class="sc">+</span> </span>
<span id="cb108-3"><a href="#cb108-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">"fill"</span>) <span class="sc">+</span> </span>
<span id="cb108-4"><a href="#cb108-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">"Set1"</span>) <span class="sc">+</span> </span>
<span id="cb108-5"><a href="#cb108-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> percent) <span class="sc">+</span></span>
<span id="cb108-6"><a href="#cb108-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"FamilySized"</span>, <span class="at">y =</span> <span class="st">"Rate"</span>,</span>
<span id="cb108-7"><a href="#cb108-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Bar plot"</span>, <span class="at">subtitle =</span> <span class="st">"Survival rate by FamilySized"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07_week_files/figure-html/unnamed-chunk-42-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><br></p>
<p>It can be seen that there is a difference in survival rate depending on the number of people on board, and that ‘FamilySized’ and ‘Survived’ have a non-linear relationship.</p>
</section>
<section id="age.group" class="level3">
<h3 class="anchored" data-anchor-id="age.group">5.5 Age.Group</h3>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb109"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1" aria-hidden="true" tabindex="-1"></a>train <span class="sc">%&gt;%</span> </span>
<span id="cb109-2"><a href="#cb109-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(Age.Group, <span class="at">fill =</span> Survived)) <span class="sc">+</span> </span>
<span id="cb109-3"><a href="#cb109-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">"fill"</span>) <span class="sc">+</span> </span>
<span id="cb109-4"><a href="#cb109-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">"Set1"</span>) <span class="sc">+</span> </span>
<span id="cb109-5"><a href="#cb109-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> percent) <span class="sc">+</span></span>
<span id="cb109-6"><a href="#cb109-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Age group"</span>, <span class="at">y =</span> <span class="st">"Rate"</span>,</span>
<span id="cb109-7"><a href="#cb109-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Bar plot"</span>, <span class="at">subtitle =</span> <span class="st">"Survival rate by Age group"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07_week_files/figure-html/unnamed-chunk-43-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><br></p>
</section>
<section id="title" class="level3">
<h3 class="anchored" data-anchor-id="title">5.6 title</h3>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb110"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb110-1"><a href="#cb110-1" aria-hidden="true" tabindex="-1"></a>train <span class="sc">%&gt;%</span> </span>
<span id="cb110-2"><a href="#cb110-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(title, <span class="at">fill =</span> Survived)) <span class="sc">+</span> </span>
<span id="cb110-3"><a href="#cb110-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">"fill"</span>) <span class="sc">+</span> </span>
<span id="cb110-4"><a href="#cb110-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">"Set1"</span>) <span class="sc">+</span> </span>
<span id="cb110-5"><a href="#cb110-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> percent) <span class="sc">+</span></span>
<span id="cb110-6"><a href="#cb110-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"title"</span>, <span class="at">y =</span> <span class="st">"Rate"</span>,</span>
<span id="cb110-7"><a href="#cb110-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Bar plot"</span>, <span class="at">subtitle =</span> <span class="st">"Survival rate by passengers title"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07_week_files/figure-html/unnamed-chunk-44-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><br></p>
</section>
<section id="ticket.size" class="level3">
<h3 class="anchored" data-anchor-id="ticket.size">5.7 ticket.size</h3>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb111"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb111-1"><a href="#cb111-1" aria-hidden="true" tabindex="-1"></a>train <span class="sc">%&gt;%</span> </span>
<span id="cb111-2"><a href="#cb111-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(ticket.size, <span class="at">fill =</span> Survived)) <span class="sc">+</span> </span>
<span id="cb111-3"><a href="#cb111-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">"fill"</span>) <span class="sc">+</span> </span>
<span id="cb111-4"><a href="#cb111-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">"Set1"</span>) <span class="sc">+</span> </span>
<span id="cb111-5"><a href="#cb111-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> percent) <span class="sc">+</span></span>
<span id="cb111-6"><a href="#cb111-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"ticket.size"</span>, <span class="at">y =</span> <span class="st">"Rate"</span>,</span>
<span id="cb111-7"><a href="#cb111-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Bar plot"</span>, <span class="at">subtitle =</span> <span class="st">"Survival rate by ticket.size"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07_week_files/figure-html/unnamed-chunk-45-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><br></p>
</section>
<section id="description-of-actual-used-features" class="level3">
<h3 class="anchored" data-anchor-id="description-of-actual-used-features">5.8 Description of actual used features</h3>
<p><br></p>
<p>Now that all the derived variables created so far have been found to be useful, select and save only the variables you will actually use.</p>
<p>The table below is a brief description of the actual selected variables.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 56%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">variable name</th>
<th style="text-align: left;">Type</th>
<th style="text-align: left;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><strong>Survived</strong></td>
<td style="text-align: left;">factor</td>
<td style="text-align: left;">Target feature, survival == 1, death == 0</td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>Sex</strong></td>
<td style="text-align: left;">factor</td>
<td style="text-align: left;">gender, <code>male</code> or <code>female</code></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><strong>Pclass</strong></td>
<td style="text-align: left;">factor</td>
<td style="text-align: left;">Cabin Class, First Class (1), Second Class (2), Third Class (3)</td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>Embarked</strong></td>
<td style="text-align: left;">factor</td>
<td style="text-align: left;">Port of embarkation, Southampton (S), Cherbourg (C), Queenstown (Q)</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><strong>FamilySized</strong></td>
<td style="text-align: left;">factor</td>
<td style="text-align: left;">Family size, a derived variable created using <code>SibSp</code> and <code>Parch</code>, with 3 categories</td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>Age.Group</strong></td>
<td style="text-align: left;">factor</td>
<td style="text-align: left;">Age group, a derived variable created using <code>Age</code>, with 4 categories</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><strong>title</strong></td>
<td style="text-align: left;">factor</td>
<td style="text-align: left;">A part of the name, a derived variable made using <code>Name</code>, and 5 categories</td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>ticket.size</strong></td>
<td style="text-align: left;">factor</td>
<td style="text-align: left;">The length of the unique part of the ticket, a derived variable created using <code>ticket</code>, with 3 categories</td>
</tr>
</tbody>
</table>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb112"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb112-1"><a href="#cb112-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Excluding ID number, select and save 7 input variables and 1 target variable to actually use</span></span>
<span id="cb112-2"><a href="#cb112-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb112-3"><a href="#cb112-3" aria-hidden="true" tabindex="-1"></a>train <span class="ot">&lt;-</span> train <span class="sc">%&gt;%</span> </span>
<span id="cb112-4"><a href="#cb112-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="st">"Pclass"</span>, <span class="st">"Sex"</span>, <span class="st">"Embarked"</span>, <span class="st">"FamilySized"</span>,</span>
<span id="cb112-5"><a href="#cb112-5" aria-hidden="true" tabindex="-1"></a>         <span class="st">"Age.Group"</span>, <span class="st">"title"</span>, <span class="st">"ticket.size"</span>, <span class="st">"Survived"</span>)</span>
<span id="cb112-6"><a href="#cb112-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb112-7"><a href="#cb112-7" aria-hidden="true" tabindex="-1"></a><span class="co"># For Submit, extract the Id column vector and store it in ID</span></span>
<span id="cb112-8"><a href="#cb112-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb112-9"><a href="#cb112-9" aria-hidden="true" tabindex="-1"></a>ID <span class="ot">&lt;-</span> test<span class="sc">$</span>PassengerId</span>
<span id="cb112-10"><a href="#cb112-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb112-11"><a href="#cb112-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Select and save the remaining 6 variables except for Id and Survived</span></span>
<span id="cb112-12"><a href="#cb112-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb112-13"><a href="#cb112-13" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> test <span class="sc">%&gt;%</span> </span>
<span id="cb112-14"><a href="#cb112-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="st">"Pclass"</span>, <span class="st">"Sex"</span>, <span class="st">"Embarked"</span>, <span class="st">"FamilySized"</span>,</span>
<span id="cb112-15"><a href="#cb112-15" aria-hidden="true" tabindex="-1"></a>         <span class="st">"Age.Group"</span>, <span class="st">"title"</span>, <span class="st">"ticket.size"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br></p>
<hr>
<p><br></p>
</section>
</section>
<section id="machine-learning-model-generation" class="level2">
<h2 class="anchored" data-anchor-id="machine-learning-model-generation">6. Machine learning model generation</h2>
<p><br></p>
<p>Now is the time to create a machine learning model using the <code>train</code> data set.</p>
<p>Originally, it is correct to create <code>train</code>, <code>validation</code>, <code>test</code> data sets first, create various models, and then select the final model through cross validation (<code>CV</code>, Cross Validation), but these processes are omitted here and <code>RandomForest After creating only</code>, we will predict (estimate) the <code>test</code> data and even create data to <code>Submit</code> to <code>competition</code>.</p>
<p><br></p>
<section id="random-forest-model-generation" class="level3">
<h3 class="anchored" data-anchor-id="random-forest-model-generation">6.1 Random Forest model generation</h3>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb113"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb113-1"><a href="#cb113-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set the seed number for reproducibility.</span></span>
<span id="cb113-2"><a href="#cb113-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1901</span>)</span>
<span id="cb113-3"><a href="#cb113-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb113-4"><a href="#cb113-4" aria-hidden="true" tabindex="-1"></a>titanic.rf <span class="ot">&lt;-</span> <span class="fu">randomForest</span>(Survived <span class="sc">~</span> ., <span class="at">data =</span> train, <span class="at">importance =</span> T, <span class="at">ntree =</span> <span class="dv">2000</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br></p>
</section>
<section id="feature-importance-check" class="level3">
<h3 class="anchored" data-anchor-id="feature-importance-check">6.2 Feature importance check</h3>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb114"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb114-1"><a href="#cb114-1" aria-hidden="true" tabindex="-1"></a><span class="fu">importance</span>(titanic.rf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    0        1 MeanDecreaseAccuracy MeanDecreaseGini
Pclass      47.442449 53.94070             64.73724        36.807804
Sex         54.250630 37.30378             58.66109        57.223102
Embarked    -6.328112 38.10930             27.32587         9.632958
FamilySized 32.430898 31.24383             50.13349        18.086894
Age.Group   15.203313 26.72696             29.36321        10.201187
title       48.228450 41.60124             57.02653        73.146999
ticket.size 39.544367 37.80849             59.59915        22.570142</code></pre>
</div>
<div class="sourceCode cell-code" id="cb116"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb116-1"><a href="#cb116-1" aria-hidden="true" tabindex="-1"></a><span class="fu">varImpPlot</span>(titanic.rf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="07_week_files/figure-html/unnamed-chunk-48-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="predict-test-data-and-create-submit-data" class="level3">
<h3 class="anchored" data-anchor-id="predict-test-data-and-create-submit-data">6.3 Predict test data and create submit data</h3>
<p><br></p>
<p>```{r eval=FALSE} # Prediction pred.rf &lt;- predict(object = titanic.rf, newdata = test, type = “class”)</p>
</section>
</section>
</section>
<section id="data-frame-generation" class="level1">
<h1>Data frame generation</h1>
<p>submit &lt;- data.frame(PassengerID = ID, Survived = pred.rf)</p>
</section>
<section id="write-the-submit-data-frame-to-file-csv-is-created-in-the-folder-designated-by-setwd." class="level1">
<h1>Write the submit data frame to file : csv is created in the folder designated by setwd().</h1>
<p>write.csv(submit, file = ‘./titanic_submit.csv’, row.names = F)</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>License: <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC BY-SA 2.0</a>.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/ChangjunChrisLee/">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/Dr_CJLee">
      <i class="bi bi-twitter" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>