<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>구조방정식 모델 – CJL &amp; Lab</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../../">
<script src="../../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../../../index.html">
    <span class="navbar-title">CJL &amp; Lab</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-courses" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Courses</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-courses">    
        <li>
    <a class="dropdown-item" href="../../../../teaching/index.html">
 <span class="dropdown-text">All Courses</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../../teaching/ds101/index.html">
 <span class="dropdown-text">DS101</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../../teaching/ml101/index.html">
 <span class="dropdown-text">ML101</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../../teaching/grad_stat/index.html">
 <span class="dropdown-text">STAT101</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../../teaching/grad_immersive/index.html">
 <span class="dropdown-text">IMUX</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../../../../research/index.html"> 
<span class="menu-text">Research</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../../blogs/index.html"> 
<span class="menu-text">Blogs</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://axislab.netlify.app/"> 
<span class="menu-text">LAB</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#structural-equation-modeling-foundations-and-applications" id="toc-structural-equation-modeling-foundations-and-applications" class="nav-link active" data-scroll-target="#structural-equation-modeling-foundations-and-applications">Structural Equation Modeling: Foundations and Applications</a>
  <ul class="collapse">
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction"><strong>Introduction</strong></a></li>
  <li><a href="#key-concepts-in-sem" id="toc-key-concepts-in-sem" class="nav-link" data-scroll-target="#key-concepts-in-sem"><strong>Key Concepts in SEM</strong></a></li>
  <li><a href="#components-of-sem" id="toc-components-of-sem" class="nav-link" data-scroll-target="#components-of-sem"><strong>Components of SEM</strong></a></li>
  <li><a href="#steps-in-conducting-sem" id="toc-steps-in-conducting-sem" class="nav-link" data-scroll-target="#steps-in-conducting-sem"><strong>Steps in Conducting SEM</strong></a></li>
  </ul></li>
  <li><a href="#cronbachs-alpha-a-measure-of-reliability" id="toc-cronbachs-alpha-a-measure-of-reliability" class="nav-link" data-scroll-target="#cronbachs-alpha-a-measure-of-reliability"><strong>Cronbach’s Alpha: A Measure of Reliability</strong></a>
  <ul class="collapse">
  <li><a href="#conceptual-foundation" id="toc-conceptual-foundation" class="nav-link" data-scroll-target="#conceptual-foundation"><strong>Conceptual Foundation</strong></a></li>
  <li><a href="#interpreting-cronbachs-alpha" id="toc-interpreting-cronbachs-alpha" class="nav-link" data-scroll-target="#interpreting-cronbachs-alpha"><strong>Interpreting Cronbach’s Alpha</strong></a></li>
  <li><a href="#assumptions-of-cronbachs-alpha" id="toc-assumptions-of-cronbachs-alpha" class="nav-link" data-scroll-target="#assumptions-of-cronbachs-alpha"><strong>Assumptions of Cronbach’s Alpha</strong></a></li>
  <li><a href="#practical-example-calculating-cronbachs-alpha-in-r" id="toc-practical-example-calculating-cronbachs-alpha-in-r" class="nav-link" data-scroll-target="#practical-example-calculating-cronbachs-alpha-in-r"><strong>Practical Example: Calculating Cronbach’s Alpha in R</strong></a></li>
  <li><a href="#improving-reliability" id="toc-improving-reliability" class="nav-link" data-scroll-target="#improving-reliability"><strong>Improving Reliability</strong></a></li>
  </ul></li>
  <li><a href="#confirmatory-factor-analysis-cfa" id="toc-confirmatory-factor-analysis-cfa" class="nav-link" data-scroll-target="#confirmatory-factor-analysis-cfa"><strong>Confirmatory Factor Analysis (CFA)</strong></a>
  <ul class="collapse">
  <li><a href="#introduction-2" id="toc-introduction-2" class="nav-link" data-scroll-target="#introduction-2"><strong>Introduction</strong></a></li>
  <li><a href="#key-concepts-in-cfa" id="toc-key-concepts-in-cfa" class="nav-link" data-scroll-target="#key-concepts-in-cfa"><strong>Key Concepts in CFA</strong></a></li>
  <li><a href="#the-cfa-model" id="toc-the-cfa-model" class="nav-link" data-scroll-target="#the-cfa-model"><strong>The CFA Model</strong></a></li>
  <li><a href="#model-fit-indices-in-cfa" id="toc-model-fit-indices-in-cfa" class="nav-link" data-scroll-target="#model-fit-indices-in-cfa"><strong>Model Fit Indices in CFA</strong></a></li>
  <li><a href="#example-of-cfa-in-r" id="toc-example-of-cfa-in-r" class="nav-link" data-scroll-target="#example-of-cfa-in-r"><strong>Example of CFA in R</strong></a></li>
  </ul></li>
  <li><a href="#sem-practice" id="toc-sem-practice" class="nav-link" data-scroll-target="#sem-practice">SEM Practice</a></li>
  <li><a href="#clustering" id="toc-clustering" class="nav-link" data-scroll-target="#clustering">Clustering</a>
  <ul class="collapse">
  <li><a href="#k-means-clustering-in-r" id="toc-k-means-clustering-in-r" class="nav-link" data-scroll-target="#k-means-clustering-in-r"><strong>K-Means Clustering in R</strong></a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">구조방정식 모델</h1>
<p class="subtitle lead">Structural Equation Model</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><a href="https://changjunlee.com/teaching/grad_stat/weekly_2/">Weekly content</a></p>
<p><br></p>
<section id="structural-equation-modeling-foundations-and-applications" class="level2">
<h2 class="anchored" data-anchor-id="structural-equation-modeling-foundations-and-applications">Structural Equation Modeling: Foundations and Applications</h2>
<p><br></p>
<section id="introduction" class="level3">
<h3 class="anchored" data-anchor-id="introduction"><strong>Introduction</strong></h3>
<p>Structural Equation Modeling (SEM) is <strong>a comprehensive statistical methodology that combines factor analysis and multiple regression techniques to examine complex relationships among observed and latent variables</strong>. Over the past few decades, SEM has become a powerful tool for researchers across disciplines such as social sciences, psychology, education, business, and health sciences. This chapter introduces the theoretical underpinnings of SEM, its key components, and practical applications, with an emphasis on latent variables and path analysis.</p>
<p><br></p>
</section>
<section id="key-concepts-in-sem" class="level3">
<h3 class="anchored" data-anchor-id="key-concepts-in-sem"><strong>Key Concepts in SEM</strong></h3>
<section id="observed-and-latent-variables" class="level4">
<h4 class="anchored" data-anchor-id="observed-and-latent-variables"><strong>1. Observed and Latent Variables</strong></h4>
<ul>
<li><p><strong>Observed Variables</strong>: These are directly measured variables, often referred to as indicators. For example, responses to survey items like “I enjoy learning” and “I find studying rewarding” can serve as observed variables for the latent construct “Motivation.”</p></li>
<li><p><strong>Latent Variables</strong>: These are unobserved constructs that are inferred from observed variables. SEM excels in estimating latent variables while accounting for measurement error.</p></li>
</ul>
</section>
<section id="measurement-error" class="level4">
<h4 class="anchored" data-anchor-id="measurement-error"><strong>2. Measurement Error</strong></h4>
<p>Measurement error is the discrepancy between the observed value and the true value of a variable. SEM explicitly incorporates measurement error into its models, which sets it apart from traditional regression approaches.</p>
<p><img src="images/clipboard-167134754.png" class="img-fluid"></p>
</section>
<section id="path-diagrams" class="level4">
<h4 class="anchored" data-anchor-id="path-diagrams"><strong>3. Path Diagrams</strong></h4>
<p>Path diagrams visually represent SEM models. Key components include:</p>
<ul>
<li><p><strong>Circles</strong>: Represent latent variables.</p></li>
<li><p><strong>Squares</strong>: Represent observed variables.</p></li>
<li><p><strong>Arrows</strong>: Depict causal relationships or associations.</p></li>
</ul>
<p><br></p>
</section>
</section>
<section id="components-of-sem" class="level3">
<h3 class="anchored" data-anchor-id="components-of-sem"><strong>Components of SEM</strong></h3>
<section id="measurement-model" class="level4">
<h4 class="anchored" data-anchor-id="measurement-model"><strong>1. Measurement Model</strong></h4>
<p>The measurement model specifies the relationships between latent variables and their observed indicators. It answers the question: <u><em>How well do the observed variables measure the underlying construct?</em></u></p>
<p><strong>Example</strong>: Motivation as a latent variable might be measured by three observed items:</p>
<p><span class="math display">\[
Motivation \sim Item_1 + Item_2 + Item_3
\]</span></p>
<p>​<br></p>
</section>
<section id="structural-model" class="level4">
<h4 class="anchored" data-anchor-id="structural-model"><strong>2. Structural Model</strong></h4>
<p>The structural model specifies the relationships between latent variables (or between latent and observed variables). It answers the question: <em>What are the causal relationships between constructs?</em></p>
<p><strong>Example</strong>: Testing whether motivation mediates the relationship between hours studied and test performance:</p>
<p><span class="math display">\[
Test\_Score = Motivation + Hours\_Studied
\]</span></p>
<p><span class="math display">\[
Motivation = Hours\_Studied
\]</span></p>
<p><br></p>
</section>
</section>
<section id="steps-in-conducting-sem" class="level3">
<h3 class="anchored" data-anchor-id="steps-in-conducting-sem"><strong>Steps in Conducting SEM</strong></h3>
<section id="step-1-define-the-model" class="level4">
<h4 class="anchored" data-anchor-id="step-1-define-the-model"><strong>Step 1: Define the Model</strong></h4>
<p>Develop a theoretical model based on prior research or hypotheses. Clearly specify the relationships among variables in a path diagram.</p>
</section>
<section id="step-2-specify-the-model" class="level4">
<h4 class="anchored" data-anchor-id="step-2-specify-the-model"><strong>Step 2: Specify the Model</strong></h4>
<p>Translate the path diagram into a set of equations. This involves defining the measurement and structural models.</p>
</section>
<section id="step-3-collect-data" class="level4">
<h4 class="anchored" data-anchor-id="step-3-collect-data"><strong>Step 3: Collect Data</strong></h4>
<p>Ensure the dataset includes sufficient sample size and all observed indicators for latent variables.</p>
</section>
<section id="step-4-estimate-the-model" class="level4">
<h4 class="anchored" data-anchor-id="step-4-estimate-the-model"><strong>Step 4: Estimate the Model</strong></h4>
<p>Use software such as R (<code>lavaan</code> package), AMOS, Mplus, or LISREL to estimate the parameters.</p>
</section>
<section id="step-5-evaluate-model-fit" class="level4">
<h4 class="anchored" data-anchor-id="step-5-evaluate-model-fit"><strong>Step 5: Evaluate Model Fit</strong></h4>
<p>Examine fit indices and modify the model, if necessary, based on theoretical justifications.</p>
</section>
<section id="step-6-interpret-the-results" class="level4">
<h4 class="anchored" data-anchor-id="step-6-interpret-the-results"><strong>Step 6: Interpret the Results</strong></h4>
<p>Interpret path coefficients, factor loadings, and fit indices in the context of your research question.</p>
<p><br></p>
</section>
</section>
</section>
<section id="cronbachs-alpha-a-measure-of-reliability" class="level2">
<h2 class="anchored" data-anchor-id="cronbachs-alpha-a-measure-of-reliability"><strong>Cronbach’s Alpha: A Measure of Reliability</strong></h2>
<section id="introduction-1" class="level4">
<h4 class="anchored" data-anchor-id="introduction-1"><strong>Introduction</strong></h4>
<p>Cronbach’s Alpha (α) is a widely used statistic in research to assess the <strong>internal consistency reliability</strong> of a set of items or indicators. It is particularly useful for measuring the reliability of scales, tests, or questionnaires in social sciences, psychology, education, and other fields. Reliability refers to the extent to which a scale produces consistent results across repeated measurements or multiple items measuring the same construct.</p>
</section>
<section id="conceptual-foundation" class="level3">
<h3 class="anchored" data-anchor-id="conceptual-foundation"><strong>Conceptual Foundation</strong></h3>
<section id="internal-consistency" class="level4">
<h4 class="anchored" data-anchor-id="internal-consistency"><strong>Internal Consistency</strong></h4>
<p>Internal consistency evaluates how well the items in a scale measure the same underlying construct. If items are highly correlated, it suggests they are measuring the same concept, which contributes to higher reliability.</p>
<p>For example:</p>
<ul>
<li><p>A scale measuring <strong>motivation</strong> might include items like:</p>
<ul>
<li><p>“I enjoy learning new things.”</p></li>
<li><p>“I am motivated to achieve my goals.”</p></li>
<li><p>“I find studying rewarding.”</p></li>
</ul></li>
</ul>
<p>If these items are highly interrelated, the scale has good internal consistency.</p>
</section>
<section id="definition-of-cronbachs-alpha" class="level4">
<h4 class="anchored" data-anchor-id="definition-of-cronbachs-alpha"><strong>Definition of Cronbach’s Alpha</strong></h4>
<p>Cronbach’s Alpha quantifies internal consistency as a value between 0 and 1. Higher values indicate better reliability. The formula for α is:</p>
<p><span class="math display">\[
\alpha = \frac{k}{k - 1} \left(1 - \frac{\sum s_i^2}{s_t^2}\right)
\]</span></p>
<p>Where:</p>
<ul>
<li><p>k: Number of items in the scale.</p>
<ul>
<li>문항 수가 많을 수록 신뢰도를 과소평가하는 경향이 있어 이를 보정</li>
</ul></li>
<li><p><span class="math inline">\(s_i^2\)</span>​: Variance of each individual item.</p>
<ul>
<li>개별 문항 분산의 합: 개별 문항들이 얼마나 <strong>독립적</strong>으로 변동하는지</li>
</ul></li>
<li><p><span class="math inline">\(s_t^2\)</span>​: Variance of the total scale score.</p>
<ul>
<li><p>총합 점수의 분산으로, 문항ndefined들이 <strong>함께 변동</strong>하는 정도</p></li>
<li><p>비율: 각 문항이 개별적으로 변동하는 정도를 전체 점수의 변동과 비교</p>
<ul>
<li><p>비율의 값이 클 수록 문항들이 서로 독립적으로 작동, 내적 일관성이 낮아짐</p></li>
<li><p>값이 작을 수록 문항들이 함께 움직이며, 내적 일관성이 높아짐</p></li>
<li><p>1에서 이 비율을 뺌으로써 문항들이 공통으로 기여하는 정도를 측정</p></li>
</ul></li>
</ul></li>
</ul>
<p><br></p>
</section>
</section>
<section id="interpreting-cronbachs-alpha" class="level3">
<h3 class="anchored" data-anchor-id="interpreting-cronbachs-alpha"><strong>Interpreting Cronbach’s Alpha</strong></h3>
<ul>
<li><p>α &gt; 0.90: Excellent reliability (possibly redundant items).</p></li>
<li><p>0.80 ≤ α &lt; 0.90: Good reliability.</p></li>
<li><p>0.70 ≤ α &lt; 0.80: Acceptable reliability.</p></li>
<li><p>0.60 ≤ α &lt; 0.70: Questionable reliability.</p></li>
<li><p>α &lt; 0.60: Poor reliability (likely indicates issues with item quality or scale design).</p></li>
</ul>
<p><br></p>
</section>
<section id="assumptions-of-cronbachs-alpha" class="level3">
<h3 class="anchored" data-anchor-id="assumptions-of-cronbachs-alpha"><strong>Assumptions of Cronbach’s Alpha</strong></h3>
<ol type="1">
<li><p><strong>Unidimensionality</strong>: The scale should measure a single construct.</p></li>
<li><p><strong>Equal Variance Contribution</strong>: Each item should contribute equally to the total score (violations can lead to under- or overestimation of reliability).</p></li>
<li><p><strong>Correlation Between Items</strong>: Items should be positively correlated.</p></li>
</ol>
<p><br></p>
</section>
<section id="practical-example-calculating-cronbachs-alpha-in-r" class="level3">
<h3 class="anchored" data-anchor-id="practical-example-calculating-cronbachs-alpha-in-r"><strong>Practical Example: Calculating Cronbach’s Alpha in R</strong></h3>
<section id="simulating-a-dataset" class="level4">
<h4 class="anchored" data-anchor-id="simulating-a-dataset"><strong>Simulating a Dataset</strong></h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulate data for a 5-item motivation scale</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">100</span>  <span class="co"># Number of respondents</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>motivation_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">Q1 =</span> <span class="fu">rnorm</span>(n, <span class="at">mean =</span> <span class="dv">4</span>, <span class="at">sd =</span> <span class="fl">0.8</span>),  <span class="co"># Item 1</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">Q2 =</span> <span class="fu">rnorm</span>(n, <span class="at">mean =</span> <span class="fl">4.2</span>, <span class="at">sd =</span> <span class="fl">0.7</span>),  <span class="co"># Item 2</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">Q3 =</span> <span class="fu">rnorm</span>(n, <span class="at">mean =</span> <span class="fl">3.9</span>, <span class="at">sd =</span> <span class="fl">0.9</span>),  <span class="co"># Item 3</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">Q4 =</span> <span class="fu">rnorm</span>(n, <span class="at">mean =</span> <span class="fl">4.1</span>, <span class="at">sd =</span> <span class="fl">0.6</span>),  <span class="co"># Item 4</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">Q5 =</span> <span class="fu">rnorm</span>(n, <span class="at">mean =</span> <span class="fl">4.0</span>, <span class="at">sd =</span> <span class="fl">0.8</span>)   <span class="co"># Item 5</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(motivation_data, <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         Q1       Q2       Q3       Q4       Q5
1  3.551619 3.702715 5.878929 3.670855 3.941155
2  3.815858 4.379819 5.081172 3.648387 3.065079
3  5.246967 4.027316 3.661369 3.536877 3.492201
4  4.056407 3.956720 4.388875 3.468492 3.976927
5  4.103430 3.533867 3.527094 3.837704 4.536557
6  5.372052 4.168481 3.471378 4.298708 2.679563
7  4.368733 3.650567 3.190257 2.891474 3.720197
8  2.987951 3.032441 3.364844 4.227188 4.605125
9  3.450518 3.933841 5.385817 4.842005 3.568953
10 3.643470 4.843298 3.851375 5.322544 4.181834</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Install and load the psych package</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("psych")</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(psych)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'psych' was built under R version 4.4.2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate Cronbach's Alpha</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>alpha_result <span class="ot">&lt;-</span> psych<span class="sc">::</span><span class="fu">alpha</span>(motivation_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Number of categories should be increased  in order to count frequencies. </code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in psych::alpha(motivation_data): Some items were negatively correlated with the first principal component and probably 
should be reversed.  
To do this, run the function again with the 'check.keys=TRUE' option</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Some items ( Q1 Q2 Q4 ) were negatively correlated with the first principal component and 
probably should be reversed.  
To do this, run the function again with the 'check.keys=TRUE' option</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in sqrt(Vtc): NaNs produced</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(alpha_result)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Reliability analysis   
Call: psych::alpha(x = motivation_data)

  raw_alpha std.alpha G6(smc) average_r   S/N  ase mean   sd median_r
     -0.38     -0.36   -0.24    -0.056 -0.27 0.22  4.1 0.29   -0.044

    95% confidence boundaries 
         lower alpha upper
Feldt    -0.86 -0.38  0.00
Duhachek -0.81 -0.38  0.04

 Reliability if an item is dropped:
   raw_alpha std.alpha G6(smc) average_r    S/N alpha se  var.r  med.r
Q1     -0.11     -0.10  -0.066    -0.024 -0.095     0.18 0.0039 -0.022
Q2     -0.40     -0.39  -0.254    -0.076 -0.282     0.23 0.0049 -0.044
Q3     -0.37     -0.33  -0.203    -0.065 -0.246     0.22 0.0070 -0.047
Q4     -0.43     -0.44  -0.276    -0.083 -0.306     0.23 0.0068 -0.089
Q5     -0.16     -0.14  -0.092    -0.032 -0.125     0.19 0.0039 -0.044

 Item statistics 
     n raw.r std.r r.cor r.drop mean   sd
Q1 100  0.28  0.30   NaN -0.227  4.1 0.73
Q2 100  0.41  0.45   NaN -0.065  4.1 0.68
Q3 100  0.51  0.42   NaN -0.097  4.0 0.85
Q4 100  0.39  0.48   NaN -0.042  4.1 0.62
Q5 100  0.37  0.32   NaN -0.191  4.1 0.79</code></pre>
</div>
</div>
</section>
<section id="output-interpretation" class="level4">
<h4 class="anchored" data-anchor-id="output-interpretation"><strong>Output Interpretation</strong></h4>
<p>The output includes:</p>
<ul>
<li><p><strong>Raw Alpha</strong>: The Cronbach’s Alpha for the current scale.</p>
<ul>
<li><p><strong>raw_alpha (-0.38)</strong></p>
<ul>
<li><p>음수의 알파 값은 <strong>내적 일관성이 전혀 없거나, 문항들이 서로 부정적인 관계를 가질 가능성</strong>을 나타냄</p></li>
<li><p>문항들이 측정하려는 동일한 개념(동일 구성 개념)을 반영하지 않거나, 측정 대상이 전혀 다른 경우에 나타남</p></li>
</ul></li>
</ul></li>
<li><p><strong>Standardized Alpha</strong>: Adjusted for standardized item variances.</p></li>
<li><p><strong>Item-Total Correlations</strong>: Correlation of each item with the total scale score.</p></li>
<li><p><strong>Alpha If Deleted</strong>: The α value if a specific item is removed.</p></li>
</ul>
<p><br></p>
</section>
</section>
<section id="improving-reliability" class="level3">
<h3 class="anchored" data-anchor-id="improving-reliability"><strong>Improving Reliability</strong></h3>
<ol type="1">
<li><p><strong>Increase the Number of Items</strong>: Add more items that measure the same construct.</p></li>
<li><p><strong>Refine Items</strong>: Ensure items are clear, relevant, and unambiguous.</p></li>
<li><p><strong>Remove Low-Quality Items</strong>: Exclude items that weaken the overall reliability (α).</p></li>
</ol>
<p><br></p>
</section>
</section>
<section id="confirmatory-factor-analysis-cfa" class="level2">
<h2 class="anchored" data-anchor-id="confirmatory-factor-analysis-cfa"><strong>Confirmatory Factor Analysis (CFA)</strong></h2>
<section id="introduction-2" class="level3">
<h3 class="anchored" data-anchor-id="introduction-2"><strong>Introduction</strong></h3>
<p>Confirmatory Factor Analysis (CFA) is <strong>a statistical technique used to test whether a hypothesized measurement model fits the observed data</strong>. Unlike Exploratory Factor Analysis (EFA), which identifies underlying factor structures without prior assumptions, CFA is <strong>hypothesis-driven</strong> and requires the researcher to specify the relationships between observed variables and latent factors before analysis.</p>
<p>CFA is widely used in psychology, education, and social sciences to validate measurement scales, confirm theoretical constructs, and ensure the reliability of instruments.</p>
<p><br></p>
</section>
<section id="key-concepts-in-cfa" class="level3">
<h3 class="anchored" data-anchor-id="key-concepts-in-cfa"><strong>Key Concepts in CFA</strong></h3>
<section id="latent-variables" class="level4">
<h4 class="anchored" data-anchor-id="latent-variables"><strong>1. Latent Variables</strong></h4>
<p>Latent variables are unobserved constructs that are inferred from multiple observed variables. For example:</p>
<ul>
<li><strong>Motivation</strong> might be a latent variable inferred from survey items like “I enjoy studying” and “I set academic goals.”</li>
</ul>
</section>
<section id="observed-variables-indicators" class="level4">
<h4 class="anchored" data-anchor-id="observed-variables-indicators"><strong>2. Observed Variables (Indicators)</strong></h4>
<p>These are measurable variables that serve as proxies for the latent variable. In CFA, each observed variable is expected to load on a specific latent factor.</p>
</section>
<section id="factor-loadings" class="level4">
<h4 class="anchored" data-anchor-id="factor-loadings"><strong>3. Factor Loadings</strong></h4>
<p>Factor loadings quantify the relationship between observed variables and their underlying latent factor. Higher loadings indicate stronger relationships.</p>
</section>
<section id="measurement-errors" class="level4">
<h4 class="anchored" data-anchor-id="measurement-errors"><strong>4. Measurement Errors</strong></h4>
<p>CFA explicitly models measurement error for each observed variable, improving the accuracy of parameter estimates compared to traditional methods.</p>
<p><br></p>
</section>
</section>
<section id="the-cfa-model" class="level3">
<h3 class="anchored" data-anchor-id="the-cfa-model"><strong>The CFA Model</strong></h3>
<p>The CFA model is typically represented as:</p>
<p><span class="math display">\[
X = \Lambda \xi + \delta
\]</span></p>
<p>Where:</p>
<ul>
<li><p>X: Vector of observed variables.</p></li>
<li><p>Λ: Matrix of factor loadings.</p></li>
<li><p>ξ: Vector of latent variables.</p></li>
<li><p>δ: Vector of measurement errors.</p></li>
</ul>
<p><br></p>
</section>
<section id="model-fit-indices-in-cfa" class="level3">
<h3 class="anchored" data-anchor-id="model-fit-indices-in-cfa"><strong>Model Fit Indices in CFA</strong></h3>
<p>Several indices are used to assess the goodness of fit of a CFA model:</p>
<ol type="1">
<li><p><strong>Chi-Square</strong>:</p>
<ul>
<li><p>Tests the <u>null hypothesis that the model fits the data perfectly.</u></p></li>
<li><p>Smaller, non-significant values indicate a good fit.</p></li>
<li><p>Sensitive to sample size.</p></li>
</ul></li>
<li><p><strong>CFI (Comparative Fit Index)</strong>:</p>
<ul>
<li><p>Compares the fit of the hypothesized model to a null model.</p></li>
<li><p>Values &gt; 0.90 indicate good fit; &gt; 0.95 indicates excellent fit.</p></li>
</ul></li>
<li><p><strong>TLI (Tucker-Lewis Index)</strong>:</p>
<ul>
<li><p>Adjusts for model complexity.</p></li>
<li><p>Values &gt; 0.90 indicate good fit.</p></li>
</ul></li>
<li><p><strong>RMSEA (Root Mean Square Error of Approximation)</strong>:</p>
<ul>
<li><p>Measures the discrepancy between the model and the data per degree of freedom.</p></li>
<li><p>Values &lt; 0.08 indicate acceptable fit; &lt; 0.05 indicates excellent fit.</p></li>
</ul></li>
<li><p><strong>SRMR (Standardized Root Mean Square Residual)</strong>:</p>
<ul>
<li><p>Measures the average discrepancy between observed and predicted correlations.</p></li>
<li><p>Values &lt; 0.08 indicate a good fit.</p></li>
</ul></li>
</ol>
<p><br></p>
</section>
<section id="example-of-cfa-in-r" class="level3">
<h3 class="anchored" data-anchor-id="example-of-cfa-in-r"><strong>Example of CFA in R</strong></h3>
<p>Here, we validate a hypothetical 3-factor model with 9 observed variables.</p>
<section id="simulating-the-data" class="level4">
<h4 class="anchored" data-anchor-id="simulating-the-data"><strong>Simulating the Data</strong></h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulate data for a 3-factor model</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">300</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Latent variables</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>Factor1 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n, <span class="at">mean =</span> <span class="dv">5</span>, <span class="at">sd =</span> <span class="dv">1</span>)</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>Factor2 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n, <span class="at">mean =</span> <span class="dv">3</span>, <span class="at">sd =</span> <span class="dv">1</span>)</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>Factor3 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n, <span class="at">mean =</span> <span class="dv">4</span>, <span class="at">sd =</span> <span class="dv">1</span>)</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Observed variables</span></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>Item1 <span class="ot">&lt;-</span> <span class="fl">0.8</span> <span class="sc">*</span> Factor1 <span class="sc">+</span> <span class="fu">rnorm</span>(n, <span class="at">sd =</span> <span class="fl">0.5</span>)</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>Item2 <span class="ot">&lt;-</span> <span class="fl">0.7</span> <span class="sc">*</span> Factor1 <span class="sc">+</span> <span class="fu">rnorm</span>(n, <span class="at">sd =</span> <span class="fl">0.5</span>)</span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>Item3 <span class="ot">&lt;-</span> <span class="fl">0.9</span> <span class="sc">*</span> Factor1 <span class="sc">+</span> <span class="fu">rnorm</span>(n, <span class="at">sd =</span> <span class="fl">0.5</span>)</span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>Item4 <span class="ot">&lt;-</span> <span class="fl">0.8</span> <span class="sc">*</span> Factor2 <span class="sc">+</span> <span class="fu">rnorm</span>(n, <span class="at">sd =</span> <span class="fl">0.5</span>)</span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>Item5 <span class="ot">&lt;-</span> <span class="fl">0.7</span> <span class="sc">*</span> Factor2 <span class="sc">+</span> <span class="fu">rnorm</span>(n, <span class="at">sd =</span> <span class="fl">0.5</span>)</span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a>Item6 <span class="ot">&lt;-</span> <span class="fl">0.9</span> <span class="sc">*</span> Factor2 <span class="sc">+</span> <span class="fu">rnorm</span>(n, <span class="at">sd =</span> <span class="fl">0.5</span>)</span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a>Item7 <span class="ot">&lt;-</span> <span class="fl">0.8</span> <span class="sc">*</span> Factor3 <span class="sc">+</span> <span class="fu">rnorm</span>(n, <span class="at">sd =</span> <span class="fl">0.5</span>)</span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a>Item8 <span class="ot">&lt;-</span> <span class="fl">0.7</span> <span class="sc">*</span> Factor3 <span class="sc">+</span> <span class="fu">rnorm</span>(n, <span class="at">sd =</span> <span class="fl">0.5</span>)</span>
<span id="cb12-21"><a href="#cb12-21" aria-hidden="true" tabindex="-1"></a>Item9 <span class="ot">&lt;-</span> <span class="fl">0.9</span> <span class="sc">*</span> Factor3 <span class="sc">+</span> <span class="fu">rnorm</span>(n, <span class="at">sd =</span> <span class="fl">0.5</span>)</span>
<span id="cb12-22"><a href="#cb12-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-23"><a href="#cb12-23" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(Item1, Item2, Item3, Item4, Item5, Item6, Item7, Item8, Item9)</span>
<span id="cb12-24"><a href="#cb12-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-25"><a href="#cb12-25" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data, <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Item1    Item2    Item3     Item4     Item5       Item6    Item7    Item8
1  3.044562 3.417592 3.585079 1.1831242 1.4992570  1.81471450 3.056150 3.476655
2  3.420201 2.960121 4.139212 1.4705645 1.7670278  1.75690647 3.075209 2.616979
3  5.396763 5.016858 5.451788 1.6205070 1.8399821  1.56147279 2.348807 2.052586
4  4.875933 3.175391 4.876992 2.1863633 1.2929837  1.54688911 1.979492 1.390110
5  4.645739 3.905621 5.176536 2.8439994 2.0218909  2.66114923 3.384857 4.652515
6  5.059768 5.248876 7.107165 2.8246841 1.7590390  3.12625963 3.054573 2.633779
7  4.781694 3.328420 5.097882 0.9794274 0.5652273 -0.04096974 2.905108 2.797026
8  2.963667 3.168455 2.924054 2.4477619 2.0382372  1.96048858 1.818510 1.719319
9  3.601175 2.774437 4.394070 3.4133666 3.0635048  3.80159049 2.448991 2.895078
10 3.773651 3.335213 4.551284 3.3277863 3.7049616  4.60878599 2.214880 2.179294
      Item9
1  4.414632
2  4.667474
3  4.004848
4  2.121336
5  3.359624
6  3.267019
7  3.504126
8  2.515587
9  3.466267
10 3.358392</code></pre>
</div>
</div>
<p>Defining and Running the CFA Model</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load lavaan package</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lavaan)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>This is lavaan 0.6-19
lavaan is FREE software! Please report any bugs.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'lavaan'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:psych':

    cor2cov</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the CFA model</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="st">'</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="st">  Factor1 =~ Item1 + Item2 + Item3</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="st">  Factor2 =~ Item4 + Item5 + Item6</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="st">  Factor3 =~ Item7 + Item8 + Item9</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a><span class="st">'</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the model</span></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">cfa</span>(model, <span class="at">data =</span> data)</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary with standardized estimates</span></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit, <span class="at">fit.measures =</span> <span class="cn">TRUE</span>, <span class="at">standardized =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6-19 ended normally after 29 iterations

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                        21

  Number of observations                           300

Model Test User Model:
                                                      
  Test statistic                                16.404
  Degrees of freedom                                24
  P-value (Chi-square)                           0.873

Model Test Baseline Model:

  Test statistic                              1438.055
  Degrees of freedom                                36
  P-value                                        0.000

User Model versus Baseline Model:

  Comparative Fit Index (CFI)                    1.000
  Tucker-Lewis Index (TLI)                       1.008

Loglikelihood and Information Criteria:

  Loglikelihood user model (H0)              -2871.907
  Loglikelihood unrestricted model (H1)      -2863.705
                                                      
  Akaike (AIC)                                5785.814
  Bayesian (BIC)                              5863.593
  Sample-size adjusted Bayesian (SABIC)       5796.994

Root Mean Square Error of Approximation:

  RMSEA                                          0.000
  90 Percent confidence interval - lower         0.000
  90 Percent confidence interval - upper         0.024
  P-value H_0: RMSEA &lt;= 0.050                    0.998
  P-value H_0: RMSEA &gt;= 0.080                    0.000

Standardized Root Mean Square Residual:

  SRMR                                           0.021

Parameter Estimates:

  Standard errors                             Standard
  Information                                 Expected
  Information saturated (h1) model          Structured

Latent Variables:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
  Factor1 =~                                                            
    Item1             1.000                               0.805    0.877
    Item2             0.741    0.051   14.600    0.000    0.596    0.772
    Item3             0.985    0.063   15.559    0.000    0.793    0.834
  Factor2 =~                                                            
    Item4             1.000                               0.768    0.835
    Item5             0.862    0.055   15.806    0.000    0.662    0.807
    Item6             1.203    0.071   17.040    0.000    0.924    0.898
  Factor3 =~                                                            
    Item7             1.000                               0.786    0.845
    Item8             0.823    0.055   15.072    0.000    0.647    0.772
    Item9             1.233    0.073   16.903    0.000    0.969    0.903

Covariances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
  Factor1 ~~                                                            
    Factor2          -0.020    0.040   -0.503    0.615   -0.033   -0.033
    Factor3          -0.009    0.041   -0.228    0.820   -0.015   -0.015
  Factor2 ~~                                                            
    Factor3          -0.016    0.039   -0.412    0.680   -0.027   -0.027

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
   .Item1             0.194    0.034    5.772    0.000    0.194    0.231
   .Item2             0.241    0.026    9.429    0.000    0.241    0.404
   .Item3             0.275    0.037    7.528    0.000    0.275    0.305
   .Item4             0.256    0.031    8.195    0.000    0.256    0.302
   .Item5             0.234    0.026    9.103    0.000    0.234    0.349
   .Item6             0.204    0.037    5.457    0.000    0.204    0.193
   .Item7             0.247    0.033    7.590    0.000    0.247    0.286
   .Item8             0.284    0.029    9.802    0.000    0.284    0.404
   .Item9             0.212    0.043    4.987    0.000    0.212    0.184
    Factor1           0.647    0.073    8.846    0.000    1.000    1.000
    Factor2           0.590    0.070    8.453    0.000    1.000    1.000
    Factor3           0.618    0.072    8.538    0.000    1.000    1.000</code></pre>
</div>
</div>
</section>
<section id="output" class="level4">
<h4 class="anchored" data-anchor-id="output"><strong>Output</strong></h4>
</section>
<section id="chi-square-테스트" class="level4">
<h4 class="anchored" data-anchor-id="chi-square-테스트">(1) <strong>Chi-square 테스트</strong></h4>
<ul>
<li><p><strong>Test statistic = 16.404, Degrees of freedom = 24, P-value = 0.873</strong></p>
<ul>
<li><p>높은 p값(0.873)은 귀무가설(H0)을 기각하지 않음을 나타냄.</p></li>
<li><p><strong>귀무가설:</strong> “모형이 데이터와 잘 맞는다” → p &gt; 0.05이므로, 데이터가 모형에 잘 적합한다고 해석할 수 있음.</p></li>
</ul></li>
</ul>
</section>
<section id="comparative-fit-index-cfi와-tucker-lewis-index-tli" class="level4">
<h4 class="anchored" data-anchor-id="comparative-fit-index-cfi와-tucker-lewis-index-tli">(2) <strong>Comparative Fit Index (CFI)와 Tucker-Lewis Index (TLI)</strong></h4>
<ul>
<li><p><strong>CFI = 1.000, TLI = 1.008</strong></p>
<ul>
<li><p>CFI와 TLI 값이 0.95 이상이면 적합성이 매우 우수하다고 판단.</p></li>
<li><p>여기서는 두 지표 모두 매우 높은 값(1 이상)을 보여, 모델 적합성이 뛰어나다는 것을 보임.</p></li>
</ul></li>
</ul>
</section>
<section id="root-mean-square-error-of-approximation-rmsea" class="level4">
<h4 class="anchored" data-anchor-id="root-mean-square-error-of-approximation-rmsea">(3) <strong>Root Mean Square Error of Approximation (RMSEA)</strong></h4>
<ul>
<li><p><strong>RMSEA = 0.000, 90% CI = [0.000, 0.024], P-value = 0.998</strong></p>
<ul>
<li><p>RMSEA 값이 0.05 이하이고, 90% 신뢰구간의 상한선도 0.05 이하라면 적합성이 우수하다고 볼 수 있음.</p></li>
<li><p>P-value H0: RMSEA ≤ 0.050 = 0.998 → “RMSEA가 0.05 이하”라는 귀무가설을 채택.</p></li>
<li><p>RMSEA가 0에 가까워 매우 좋은 적합도를 나타냄.</p></li>
</ul></li>
</ul>
</section>
<section id="standardized-root-mean-square-residual-srmr" class="level4">
<h4 class="anchored" data-anchor-id="standardized-root-mean-square-residual-srmr">(4) <strong>Standardized Root Mean Square Residual (SRMR)</strong></h4>
<ul>
<li><p><strong>SRMR = 0.021</strong></p>
<ul>
<li>SRMR 값이 0.08 이하라면 적합성이 양호하다고 판단.</li>
</ul></li>
</ul>
</section>
<section id="요인-적재값factor-loadings" class="level4">
<h4 class="anchored" data-anchor-id="요인-적재값factor-loadings">(5) <strong>요인 적재값(Factor Loadings)</strong></h4>
<ul>
<li><p>각 항목이 요인에 대해 얼마나 강하게 연관되어 있는지</p>
<ul>
<li><p><strong>Factor1:</strong></p>
<ul>
<li><p>Item1: 0.805 (표준화된 적재값 0.877)</p></li>
<li><p>Item2: 0.596 (표준화된 적재값 0.772)</p></li>
<li><p>Item3: 0.793 (표준화된 적재값 0.834)</p></li>
</ul></li>
<li><p><strong>Factor2:</strong></p>
<ul>
<li><p>Item4: 0.768 (표준화된 적재값 0.835)</p></li>
<li><p>Item5: 0.662 (표준화된 적재값 0.807)</p></li>
<li><p>Item6: 0.924 (표준화된 적재값 0.898)</p></li>
</ul></li>
<li><p><strong>Factor3:</strong></p>
<ul>
<li><p>Item7: 0.786 (표준화된 적재값 0.845)</p></li>
<li><p>Item8: 0.647 (표준화된 적재값 0.772)</p></li>
<li><p>Item9: 0.969 (표준화된 적재값 0.903)</p></li>
</ul></li>
</ul></li>
<li><p>표준화 적재값이 <strong>0.7 이상</strong>이면 해당 항목이 요인에 강하게 기여한다고 판단.</p></li>
</ul>
</section>
<section id="요인-간-공분산covariances" class="level4">
<h4 class="anchored" data-anchor-id="요인-간-공분산covariances">(6) <strong>요인 간 공분산(Covariances)</strong></h4>
<ul>
<li><p>Factor1 ~~ Factor2 = -0.033 (p = 0.615)</p></li>
<li><p>Factor1 ~~ Factor3 = -0.015 (p = 0.820)</p></li>
<li><p>Factor2 ~~ Factor3 = -0.027 (p = 0.680)</p>
<ul>
<li><p>요인 간 공분산이 매우 낮고 통계적으로 유의하지 않음.</p></li>
<li><p>요인들이 서로 독립적(서로 다른 구성 개념을 측정)을 나타냄.</p></li>
</ul></li>
</ul>
</section>
<section id="항목의-잔차residual-variances" class="level4">
<h4 class="anchored" data-anchor-id="항목의-잔차residual-variances"><strong>(7) 항목의 잔차(Residual Variances)</strong></h4>
<ul>
<li><p>각 항목의 분산 중 설명되지 않는 부분(잔차)</p>
<ul>
<li><p>Item1: 잔차 분산 = 0.194 (설명되지 않는 분산 비율 = 23.1%)</p></li>
<li><p>Item6: 잔차 분산 = 0.204 (설명되지 않는 분산 비율 = 19.3%)</p></li>
<li><p>대부분의 항목에서 설명되지 않는 분산 비율이 적어(50% 미만), 요인이 해당 항목들을 잘 설명하고 있음을 나타냄.</p></li>
</ul></li>
</ul>
<p><br></p>
</section>
</section>
</section>
<section id="sem-practice" class="level2">
<h2 class="anchored" data-anchor-id="sem-practice">SEM Practice</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Install lavaan if not already installed</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("lavaan")</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Load lavaan</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lavaan)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load required package for data simulation</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Set random seed for reproducibility</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Number of observations</span></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">300</span></span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Define factor structure (3 latent factors, uncorrelated)</span></span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>latent_factors <span class="ot">&lt;-</span> <span class="fu">mvrnorm</span>(</span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">n =</span> n,</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">mu =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>),       <span class="co"># Mean of latent factors</span></span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">Sigma =</span> <span class="fu">diag</span>(<span class="dv">3</span>)        <span class="co"># Identity matrix implies no correlation between factors</span></span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Factor loadings for each latent factor</span></span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a>loadings <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb21-19"><a href="#cb21-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">Factor1 =</span> <span class="fu">c</span>(<span class="fl">0.8</span>, <span class="fl">0.7</span>, <span class="fl">0.9</span>),  <span class="co"># Loadings for Item1, Item2, Item3</span></span>
<span id="cb21-20"><a href="#cb21-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">Factor2 =</span> <span class="fu">c</span>(<span class="fl">0.9</span>, <span class="fl">0.8</span>, <span class="fl">0.85</span>), <span class="co"># Loadings for Item4, Item5, Item6</span></span>
<span id="cb21-21"><a href="#cb21-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">Factor3 =</span> <span class="fu">c</span>(<span class="fl">0.85</span>, <span class="fl">0.75</span>, <span class="fl">0.9</span>) <span class="co"># Loadings for Item7, Item8, Item9</span></span>
<span id="cb21-22"><a href="#cb21-22" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb21-23"><a href="#cb21-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-24"><a href="#cb21-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Residual variances (to ensure observed variables are not perfectly predicted by latent factors)</span></span>
<span id="cb21-25"><a href="#cb21-25" aria-hidden="true" tabindex="-1"></a>residuals <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb21-26"><a href="#cb21-26" aria-hidden="true" tabindex="-1"></a>  <span class="at">Factor1 =</span> <span class="fu">c</span>(<span class="fl">0.4</span>, <span class="fl">0.5</span>, <span class="fl">0.3</span>),</span>
<span id="cb21-27"><a href="#cb21-27" aria-hidden="true" tabindex="-1"></a>  <span class="at">Factor2 =</span> <span class="fu">c</span>(<span class="fl">0.3</span>, <span class="fl">0.4</span>, <span class="fl">0.35</span>),</span>
<span id="cb21-28"><a href="#cb21-28" aria-hidden="true" tabindex="-1"></a>  <span class="at">Factor3 =</span> <span class="fu">c</span>(<span class="fl">0.35</span>, <span class="fl">0.5</span>, <span class="fl">0.3</span>)</span>
<span id="cb21-29"><a href="#cb21-29" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb21-30"><a href="#cb21-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-31"><a href="#cb21-31" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate observed variables for each factor</span></span>
<span id="cb21-32"><a href="#cb21-32" aria-hidden="true" tabindex="-1"></a>observed_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb21-33"><a href="#cb21-33" aria-hidden="true" tabindex="-1"></a>  <span class="at">Item1 =</span> latent_factors[, <span class="dv">1</span>] <span class="sc">*</span> loadings<span class="sc">$</span>Factor1[<span class="dv">1</span>] <span class="sc">+</span> <span class="fu">rnorm</span>(n, <span class="dv">0</span>, residuals<span class="sc">$</span>Factor1[<span class="dv">1</span>]),</span>
<span id="cb21-34"><a href="#cb21-34" aria-hidden="true" tabindex="-1"></a>  <span class="at">Item2 =</span> latent_factors[, <span class="dv">1</span>] <span class="sc">*</span> loadings<span class="sc">$</span>Factor1[<span class="dv">2</span>] <span class="sc">+</span> <span class="fu">rnorm</span>(n, <span class="dv">0</span>, residuals<span class="sc">$</span>Factor1[<span class="dv">2</span>]),</span>
<span id="cb21-35"><a href="#cb21-35" aria-hidden="true" tabindex="-1"></a>  <span class="at">Item3 =</span> latent_factors[, <span class="dv">1</span>] <span class="sc">*</span> loadings<span class="sc">$</span>Factor1[<span class="dv">3</span>] <span class="sc">+</span> <span class="fu">rnorm</span>(n, <span class="dv">0</span>, residuals<span class="sc">$</span>Factor1[<span class="dv">3</span>]),</span>
<span id="cb21-36"><a href="#cb21-36" aria-hidden="true" tabindex="-1"></a>  <span class="at">Item4 =</span> latent_factors[, <span class="dv">2</span>] <span class="sc">*</span> loadings<span class="sc">$</span>Factor2[<span class="dv">1</span>] <span class="sc">+</span> <span class="fu">rnorm</span>(n, <span class="dv">0</span>, residuals<span class="sc">$</span>Factor2[<span class="dv">1</span>]),</span>
<span id="cb21-37"><a href="#cb21-37" aria-hidden="true" tabindex="-1"></a>  <span class="at">Item5 =</span> latent_factors[, <span class="dv">2</span>] <span class="sc">*</span> loadings<span class="sc">$</span>Factor2[<span class="dv">2</span>] <span class="sc">+</span> <span class="fu">rnorm</span>(n, <span class="dv">0</span>, residuals<span class="sc">$</span>Factor2[<span class="dv">2</span>]),</span>
<span id="cb21-38"><a href="#cb21-38" aria-hidden="true" tabindex="-1"></a>  <span class="at">Item6 =</span> latent_factors[, <span class="dv">2</span>] <span class="sc">*</span> loadings<span class="sc">$</span>Factor2[<span class="dv">3</span>] <span class="sc">+</span> <span class="fu">rnorm</span>(n, <span class="dv">0</span>, residuals<span class="sc">$</span>Factor2[<span class="dv">3</span>]),</span>
<span id="cb21-39"><a href="#cb21-39" aria-hidden="true" tabindex="-1"></a>  <span class="at">Item7 =</span> latent_factors[, <span class="dv">3</span>] <span class="sc">*</span> loadings<span class="sc">$</span>Factor3[<span class="dv">1</span>] <span class="sc">+</span> <span class="fu">rnorm</span>(n, <span class="dv">0</span>, residuals<span class="sc">$</span>Factor3[<span class="dv">1</span>]),</span>
<span id="cb21-40"><a href="#cb21-40" aria-hidden="true" tabindex="-1"></a>  <span class="at">Item8 =</span> latent_factors[, <span class="dv">3</span>] <span class="sc">*</span> loadings<span class="sc">$</span>Factor3[<span class="dv">2</span>] <span class="sc">+</span> <span class="fu">rnorm</span>(n, <span class="dv">0</span>, residuals<span class="sc">$</span>Factor3[<span class="dv">2</span>]),</span>
<span id="cb21-41"><a href="#cb21-41" aria-hidden="true" tabindex="-1"></a>  <span class="at">Item9 =</span> latent_factors[, <span class="dv">3</span>] <span class="sc">*</span> loadings<span class="sc">$</span>Factor3[<span class="dv">3</span>] <span class="sc">+</span> <span class="fu">rnorm</span>(n, <span class="dv">0</span>, residuals<span class="sc">$</span>Factor3[<span class="dv">3</span>])</span>
<span id="cb21-42"><a href="#cb21-42" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb21-43"><a href="#cb21-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-44"><a href="#cb21-44" aria-hidden="true" tabindex="-1"></a><span class="co"># Check summary</span></span>
<span id="cb21-45"><a href="#cb21-45" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(observed_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Item1              Item2              Item3             Item4         
 Min.   :-2.25631   Min.   :-2.32729   Min.   :-2.5787   Min.   :-2.67780  
 1st Qu.:-0.58956   1st Qu.:-0.60444   1st Qu.:-0.6469   1st Qu.:-0.59562  
 Median : 0.08151   Median : 0.04872   Median : 0.1015   Median : 0.08360  
 Mean   : 0.02416   Mean   : 0.01666   Mean   : 0.0305   Mean   : 0.01016  
 3rd Qu.: 0.65430   3rd Qu.: 0.65044   3rd Qu.: 0.7065   3rd Qu.: 0.68210  
 Max.   : 2.60049   Max.   : 2.56593   Max.   : 2.6296   Max.   : 2.52406  
     Item5              Item6               Item7               Item8          
 Min.   :-2.26428   Min.   :-2.750106   Min.   :-2.716450   Min.   :-2.252780  
 1st Qu.:-0.56261   1st Qu.:-0.567966   1st Qu.:-0.550449   1st Qu.:-0.590119  
 Median :-0.02097   Median :-0.021206   Median : 0.007724   Median :-0.095031  
 Mean   :-0.01454   Mean   : 0.002263   Mean   : 0.044208   Mean   :-0.002405  
 3rd Qu.: 0.58973   3rd Qu.: 0.616462   3rd Qu.: 0.677705   3rd Qu.: 0.578858  
 Max.   : 2.49658   Max.   : 2.368748   Max.   : 3.176766   Max.   : 2.512839  
     Item9         
 Min.   :-2.24574  
 1st Qu.:-0.58138  
 Median :-0.01305  
 Mean   : 0.04343  
 3rd Qu.: 0.62350  
 Max.   : 3.18565  </code></pre>
</div>
</div>
<ul>
<li>CFA first</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load lavaan package for SEM</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lavaan)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the CFA model</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>cfa_model <span class="ot">&lt;-</span> <span class="st">'</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a><span class="st">  # Latent variables</span></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a><span class="st">  Factor1 =~ Item1 + Item2 + Item3</span></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a><span class="st">  Factor2 =~ Item4 + Item5 + Item6</span></span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a><span class="st">  Factor3 =~ Item7 + Item8 + Item9</span></span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a><span class="st">  # Covariances (optional; default assumes correlated factors)</span></span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a><span class="st">  Factor1 ~~ Factor2</span></span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a><span class="st">  Factor1 ~~ Factor3</span></span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a><span class="st">  Factor2 ~~ Factor3</span></span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a><span class="st">'</span></span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the CFA model</span></span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a>cfa_fit <span class="ot">&lt;-</span> <span class="fu">cfa</span>(<span class="at">model =</span> cfa_model, <span class="at">data =</span> observed_data)</span>
<span id="cb23-19"><a href="#cb23-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-20"><a href="#cb23-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Summarize results</span></span>
<span id="cb23-21"><a href="#cb23-21" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cfa_fit, <span class="at">fit.measures =</span> <span class="cn">TRUE</span>, <span class="at">standardized =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6-19 ended normally after 34 iterations

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                        21

  Number of observations                           300

Model Test User Model:
                                                      
  Test statistic                                22.719
  Degrees of freedom                                24
  P-value (Chi-square)                           0.536

Model Test Baseline Model:

  Test statistic                              2339.834
  Degrees of freedom                                36
  P-value                                        0.000

User Model versus Baseline Model:

  Comparative Fit Index (CFI)                    1.000
  Tucker-Lewis Index (TLI)                       1.001

Loglikelihood and Information Criteria:

  Loglikelihood user model (H0)              -2412.941
  Loglikelihood unrestricted model (H1)      -2401.581
                                                      
  Akaike (AIC)                                4867.881
  Bayesian (BIC)                              4945.661
  Sample-size adjusted Bayesian (SABIC)       4879.061

Root Mean Square Error of Approximation:

  RMSEA                                          0.000
  90 Percent confidence interval - lower         0.000
  90 Percent confidence interval - upper         0.044
  P-value H_0: RMSEA &lt;= 0.050                    0.978
  P-value H_0: RMSEA &gt;= 0.080                    0.000

Standardized Root Mean Square Residual:

  SRMR                                           0.024

Parameter Estimates:

  Standard errors                             Standard
  Information                                 Expected
  Information saturated (h1) model          Structured

Latent Variables:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
  Factor1 =~                                                            
    Item1             1.000                               0.862    0.922
    Item2             0.855    0.041   20.832    0.000    0.736    0.835
    Item3             1.072    0.041   26.131    0.000    0.924    0.941
  Factor2 =~                                                            
    Item4             1.000                               0.875    0.944
    Item5             0.881    0.033   26.657    0.000    0.771    0.895
    Item6             0.978    0.033   30.037    0.000    0.856    0.934
  Factor3 =~                                                            
    Item7             1.000                               0.819    0.921
    Item8             0.841    0.044   19.012    0.000    0.689    0.797
    Item9             1.075    0.041   26.020    0.000    0.881    0.952

Covariances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
  Factor1 ~~                                                            
    Factor2          -0.018    0.046   -0.390    0.697   -0.024   -0.024
    Factor3          -0.059    0.043   -1.369    0.171   -0.084   -0.084
  Factor2 ~~                                                            
    Factor3          -0.034    0.044   -0.773    0.439   -0.047   -0.047

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
   .Item1             0.132    0.020    6.568    0.000    0.132    0.151
   .Item2             0.236    0.023   10.305    0.000    0.236    0.303
   .Item3             0.110    0.021    5.143    0.000    0.110    0.114
   .Item4             0.093    0.015    6.252    0.000    0.093    0.108
   .Item5             0.147    0.016    9.441    0.000    0.147    0.198
   .Item6             0.106    0.015    7.098    0.000    0.106    0.127
   .Item7             0.120    0.019    6.260    0.000    0.120    0.151
   .Item8             0.272    0.025   10.852    0.000    0.272    0.365
   .Item9             0.081    0.020    4.014    0.000    0.081    0.094
    Factor1           0.742    0.073   10.233    0.000    1.000    1.000
    Factor2           0.766    0.071   10.807    0.000    1.000    1.000
    Factor3           0.671    0.066   10.185    0.000    1.000    1.000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check model fit indices</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">fitMeasures</span>(cfa_fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 npar                  fmin                 chisq 
               21.000                 0.038                22.719 
                   df                pvalue        baseline.chisq 
               24.000                 0.536              2339.834 
          baseline.df       baseline.pvalue                   cfi 
               36.000                 0.000                 1.000 
                  tli                  nnfi                   rfi 
                1.001                 1.001                 0.985 
                  nfi                  pnfi                   ifi 
                0.990                 0.660                 1.001 
                  rni                  logl     unrestricted.logl 
                1.001             -2412.941             -2401.581 
                  aic                   bic                ntotal 
             4867.881              4945.661               300.000 
                 bic2                 rmsea        rmsea.ci.lower 
             4879.061                 0.000                 0.000 
       rmsea.ci.upper        rmsea.ci.level          rmsea.pvalue 
                0.044                 0.900                 0.978 
       rmsea.close.h0 rmsea.notclose.pvalue     rmsea.notclose.h0 
                0.050                 0.000                 0.080 
                  rmr            rmr_nomean                  srmr 
                0.019                 0.019                 0.024 
         srmr_bentler   srmr_bentler_nomean                  crmr 
                0.024                 0.024                 0.026 
          crmr_nomean            srmr_mplus     srmr_mplus_nomean 
                0.026                 0.024                 0.024 
                cn_05                 cn_01                   gfi 
              481.847               568.532                 0.984 
                 agfi                  pgfi                   mfi 
                0.969                 0.525                 1.002 
                 ecvi 
                0.216 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Inspect modification indices (to identify potential model improvements)</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">modificationIndices</span>(cfa_fit, <span class="at">sort =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       lhs op   rhs    mi    epc sepc.lv sepc.all sepc.nox
76   Item7 ~~ Item8 5.993 -0.412  -0.412   -2.282   -2.282
30 Factor1 =~ Item9 5.133  0.068   0.059    0.063    0.063
46   Item1 ~~ Item5 4.340  0.023   0.023    0.165    0.165
31 Factor2 =~ Item1 3.736  0.059   0.052    0.056    0.056
78   Item8 ~~ Item9 3.427  0.353   0.353    2.379    2.379
50   Item1 ~~ Item9 2.345  0.016   0.016    0.160    0.160
53   Item2 ~~ Item5 2.297 -0.020  -0.020   -0.105   -0.105
51   Item2 ~~ Item3 2.243 -0.358  -0.358   -2.222   -2.222
29 Factor1 =~ Item8 2.198 -0.057  -0.049   -0.057   -0.057
28 Factor1 =~ Item7 2.039 -0.042  -0.036   -0.041   -0.041
44   Item1 ~~ Item3 2.017  0.539   0.539    4.473    4.473
33 Factor2 =~ Item3 1.998 -0.045  -0.039   -0.040   -0.040
38 Factor3 =~ Item2 1.605 -0.048  -0.040   -0.045   -0.045
57   Item2 ~~ Item9 1.523 -0.016  -0.016   -0.113   -0.113
48   Item1 ~~ Item7 1.446 -0.013  -0.013   -0.103   -0.103
34 Factor2 =~ Item7 1.384 -0.034  -0.029   -0.033   -0.033
77   Item7 ~~ Item9 1.264  0.394   0.394    4.011    4.011
47   Item1 ~~ Item6 0.934 -0.010  -0.010   -0.085   -0.085
37 Factor3 =~ Item1 0.841  0.030   0.025    0.027    0.027
36 Factor2 =~ Item9 0.821  0.026   0.023    0.025    0.025
55   Item2 ~~ Item7 0.687  0.010   0.010    0.062    0.062
75   Item6 ~~ Item9 0.646  0.008   0.008    0.084    0.084
70   Item5 ~~ Item7 0.635 -0.008  -0.008   -0.062   -0.062
74   Item6 ~~ Item8 0.634 -0.010  -0.010   -0.060   -0.060
40 Factor3 =~ Item4 0.632  0.023   0.019    0.021    0.021
26 Factor1 =~ Item5 0.589  0.023   0.020    0.023    0.023
41 Factor3 =~ Item5 0.563 -0.024  -0.019   -0.022   -0.022
58   Item3 ~~ Item4 0.430 -0.007  -0.007   -0.067   -0.067
32 Factor2 =~ Item2 0.390 -0.022  -0.019   -0.022   -0.022
62   Item3 ~~ Item8 0.386 -0.009  -0.009   -0.052   -0.052
25 Factor1 =~ Item4 0.380 -0.017  -0.015   -0.016   -0.016
59   Item3 ~~ Item5 0.352 -0.007  -0.007   -0.052   -0.052
67   Item4 ~~ Item8 0.316  0.007   0.007    0.044    0.044
60   Item3 ~~ Item6 0.303  0.006   0.006    0.054    0.054
66   Item4 ~~ Item7 0.302  0.005   0.005    0.050    0.050
54   Item2 ~~ Item6 0.258  0.006   0.006    0.039    0.039
68   Item4 ~~ Item9 0.257 -0.005  -0.005   -0.056   -0.056
63   Item3 ~~ Item9 0.209  0.005   0.005    0.053    0.053
73   Item6 ~~ Item7 0.200 -0.004  -0.004   -0.038   -0.038
52   Item2 ~~ Item4 0.195  0.005   0.005    0.036    0.036
43   Item1 ~~ Item2 0.186  0.092   0.092    0.525    0.525
71   Item5 ~~ Item8 0.173  0.006   0.006    0.028    0.028
69   Item5 ~~ Item6 0.164 -0.134  -0.134   -1.071   -1.071
35 Factor2 =~ Item8 0.118  0.013   0.011    0.013    0.013
65   Item4 ~~ Item6 0.083  0.131   0.131    1.317    1.317
56   Item2 ~~ Item8 0.050 -0.004  -0.004   -0.015   -0.015
42 Factor3 =~ Item6 0.033 -0.005  -0.004   -0.005   -0.005
72   Item5 ~~ Item9 0.032  0.002   0.002    0.017    0.017
64   Item4 ~~ Item5 0.030  0.061   0.061    0.518    0.518
61   Item3 ~~ Item7 0.015 -0.001  -0.001   -0.011   -0.011
45   Item1 ~~ Item4 0.009  0.001   0.001    0.009    0.009
49   Item1 ~~ Item8 0.006  0.001   0.001    0.006    0.006
39 Factor3 =~ Item3 0.000  0.001   0.000    0.000    0.000
27 Factor1 =~ Item6 0.000  0.000   0.000    0.000    0.000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Residuals analysis</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">residuals</span>(cfa_fit, <span class="at">type =</span> <span class="st">"cor"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$type
[1] "cor.bollen"

$cov
       Item1  Item2  Item3  Item4  Item5  Item6  Item7  Item8  Item9
Item1  0.000                                                        
Item2  0.000  0.000                                                 
Item3  0.000 -0.001  0.000                                          
Item4  0.024 -0.021 -0.028  0.000                                   
Item5  0.061 -0.020 -0.005  0.000  0.000                            
Item6  0.026 -0.013 -0.016  0.000  0.000  0.000                     
Item7 -0.016 -0.046 -0.024 -0.007 -0.040 -0.025  0.000              
Item8 -0.030 -0.072 -0.049  0.024  0.002  0.000 -0.002  0.000       
Item9  0.044 -0.021  0.026  0.019 -0.006  0.010  0.000  0.001  0.000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualize the model (optional)</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("semPlot")</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(semPlot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'semPlot' was built under R version 4.4.2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">semPaths</span>(cfa_fit, <span class="at">what =</span> <span class="st">"std"</span>, <span class="at">layout =</span> <span class="st">"tree"</span>, </span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">nCharNodes =</span> <span class="dv">0</span>, <span class="at">edge.label.cex =</span> <span class="fl">0.8</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="14_week_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p><strong>적합도 지표 (Fit Indices):</strong></p>
<ul>
<li><p>좋은 적합도 기준:</p>
<ul>
<li><p><strong>CFI, TLI ≥ 0.95</strong></p></li>
<li><p><strong>RMSEA ≤ 0.05</strong></p></li>
<li><p><strong>SRMR ≤ 0.08</strong></p></li>
</ul></li>
</ul></li>
<li><p><strong>표준화 요인 적재값 (Standardized Factor Loadings):</strong></p>
<ul>
<li><p>각 항목이 대응하는 잠재변수에 대해 얼마나 강하게 기여하는지</p></li>
<li><p>기준: 적재값 ≥ 0.7이면 “강한 기여”로 해석.</p></li>
</ul></li>
<li><p><strong>수정지수 (Modification Indices):</strong></p>
<ul>
<li>모델 개선 가능성이 높은 항목 간의 경로를 제안합니다. 수정이 필요한 경우 수정 후 재분석 가능.</li>
</ul></li>
<li><p><strong>잔차 (Residuals):</strong></p>
<ul>
<li>관찰된 값과 모델로 예측된 값 간의 차이를 분석합니다. 잔차가 작을수록 모델이 데이터를 잘 설명.</li>
</ul></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Standardized loadings table</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">inspect</span>(cfa_fit, <span class="at">what =</span> <span class="st">"std"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$lambda
      Factr1 Factr2 Factr3
Item1  0.922  0.000  0.000
Item2  0.835  0.000  0.000
Item3  0.941  0.000  0.000
Item4  0.000  0.944  0.000
Item5  0.000  0.895  0.000
Item6  0.000  0.934  0.000
Item7  0.000  0.000  0.921
Item8  0.000  0.000  0.797
Item9  0.000  0.000  0.952

$theta
      Item1 Item2 Item3 Item4 Item5 Item6 Item7 Item8 Item9
Item1 0.151                                                
Item2 0.000 0.303                                          
Item3 0.000 0.000 0.114                                    
Item4 0.000 0.000 0.000 0.108                              
Item5 0.000 0.000 0.000 0.000 0.198                        
Item6 0.000 0.000 0.000 0.000 0.000 0.127                  
Item7 0.000 0.000 0.000 0.000 0.000 0.000 0.151            
Item8 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.365      
Item9 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.094

$psi
        Factr1 Factr2 Factr3
Factor1  1.000              
Factor2 -0.024  1.000       
Factor3 -0.084 -0.047  1.000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Covariance matrix of latent factors</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">inspect</span>(cfa_fit, <span class="at">what =</span> <span class="st">"cov.lv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        Factr1 Factr2 Factr3
Factor1  0.742              
Factor2 -0.018  0.766       
Factor3 -0.059 -0.034  0.671</code></pre>
</div>
</div>
<p><br></p>
<section id="fitting-to-sem" class="level4">
<h4 class="anchored" data-anchor-id="fitting-to-sem">Fitting to SEM</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># SEM 모델 정의</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>sem_model <span class="ot">&lt;-</span> <span class="st">'</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a><span class="st">  # Measurement model (측정 모델: 요인 구조 정의)</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a><span class="st">  Factor1 =~ Item1 + Item2 + Item3</span></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a><span class="st">  Factor2 =~ Item4 + Item5 + Item6</span></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a><span class="st">  Factor3 =~ Item7 + Item8 + Item9</span></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a><span class="st">  # Structural model (구조 모델: 요인 간 관계 정의)</span></span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a><span class="st">  Factor2 ~ Factor1  # Factor1이 Factor2에 영향을 미침</span></span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a><span class="st">  Factor3 ~ Factor2  # Factor2가 Factor3에 영향을 미침</span></span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a><span class="st">  Factor3 ~ Factor1 + Factor2 #매개효과</span></span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a><span class="st">'</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># SEM 모델 적합</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>sem_fit <span class="ot">&lt;-</span> <span class="fu">sem</span>(<span class="at">model =</span> sem_model, <span class="at">data =</span> observed_data)</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 결과 요약</span></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(sem_fit, <span class="at">fit.measures =</span> <span class="cn">TRUE</span>, <span class="at">standardized =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6-19 ended normally after 35 iterations

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                        21

  Number of observations                           300

Model Test User Model:
                                                      
  Test statistic                                22.719
  Degrees of freedom                                24
  P-value (Chi-square)                           0.536

Model Test Baseline Model:

  Test statistic                              2339.834
  Degrees of freedom                                36
  P-value                                        0.000

User Model versus Baseline Model:

  Comparative Fit Index (CFI)                    1.000
  Tucker-Lewis Index (TLI)                       1.001

Loglikelihood and Information Criteria:

  Loglikelihood user model (H0)              -2412.941
  Loglikelihood unrestricted model (H1)      -2401.581
                                                      
  Akaike (AIC)                                4867.881
  Bayesian (BIC)                              4945.661
  Sample-size adjusted Bayesian (SABIC)       4879.061

Root Mean Square Error of Approximation:

  RMSEA                                          0.000
  90 Percent confidence interval - lower         0.000
  90 Percent confidence interval - upper         0.044
  P-value H_0: RMSEA &lt;= 0.050                    0.978
  P-value H_0: RMSEA &gt;= 0.080                    0.000

Standardized Root Mean Square Residual:

  SRMR                                           0.024

Parameter Estimates:

  Standard errors                             Standard
  Information                                 Expected
  Information saturated (h1) model          Structured

Latent Variables:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
  Factor1 =~                                                            
    Item1             1.000                               0.862    0.922
    Item2             0.855    0.041   20.832    0.000    0.736    0.835
    Item3             1.072    0.041   26.131    0.000    0.924    0.941
  Factor2 =~                                                            
    Item4             1.000                               0.875    0.944
    Item5             0.881    0.033   26.657    0.000    0.771    0.895
    Item6             0.978    0.033   30.037    0.000    0.856    0.934
  Factor3 =~                                                            
    Item7             1.000                               0.819    0.921
    Item8             0.841    0.044   19.012    0.000    0.689    0.797
    Item9             1.075    0.041   26.020    0.000    0.881    0.952

Regressions:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
  Factor2 ~                                                             
    Factor1          -0.024    0.062   -0.390    0.696   -0.024   -0.024
  Factor3 ~                                                             
    Factor2          -0.046    0.057   -0.811    0.418   -0.049   -0.049
    Factor1          -0.081    0.058   -1.398    0.162   -0.085   -0.085

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
   .Item1             0.132    0.020    6.568    0.000    0.132    0.151
   .Item2             0.236    0.023   10.305    0.000    0.236    0.303
   .Item3             0.110    0.021    5.143    0.000    0.110    0.114
   .Item4             0.093    0.015    6.252    0.000    0.093    0.108
   .Item5             0.147    0.016    9.441    0.000    0.147    0.198
   .Item6             0.106    0.015    7.098    0.000    0.106    0.127
   .Item7             0.120    0.019    6.260    0.000    0.120    0.151
   .Item8             0.272    0.025   10.852    0.000    0.272    0.365
   .Item9             0.081    0.020    4.014    0.000    0.081    0.094
    Factor1           0.742    0.073   10.233    0.000    1.000    1.000
   .Factor2           0.766    0.071   10.806    0.000    0.999    0.999
   .Factor3           0.665    0.065   10.177    0.000    0.990    0.990</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 적합도 지표 확인</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">fitMeasures</span>(sem_fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 npar                  fmin                 chisq 
               21.000                 0.038                22.719 
                   df                pvalue        baseline.chisq 
               24.000                 0.536              2339.834 
          baseline.df       baseline.pvalue                   cfi 
               36.000                 0.000                 1.000 
                  tli                  nnfi                   rfi 
                1.001                 1.001                 0.985 
                  nfi                  pnfi                   ifi 
                0.990                 0.660                 1.001 
                  rni                  logl     unrestricted.logl 
                1.001             -2412.941             -2401.581 
                  aic                   bic                ntotal 
             4867.881              4945.661               300.000 
                 bic2                 rmsea        rmsea.ci.lower 
             4879.061                 0.000                 0.000 
       rmsea.ci.upper        rmsea.ci.level          rmsea.pvalue 
                0.044                 0.900                 0.978 
       rmsea.close.h0 rmsea.notclose.pvalue     rmsea.notclose.h0 
                0.050                 0.000                 0.080 
                  rmr            rmr_nomean                  srmr 
                0.019                 0.019                 0.024 
         srmr_bentler   srmr_bentler_nomean                  crmr 
                0.024                 0.024                 0.026 
          crmr_nomean            srmr_mplus     srmr_mplus_nomean 
                0.026                 0.024                 0.024 
                cn_05                 cn_01                   gfi 
              481.847               568.532                 0.984 
                 agfi                  pgfi                   mfi 
                0.969                 0.525                 1.002 
                 ecvi 
                0.216 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 수정지수 확인 (필요시 모델 수정)</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="fu">modificationIndices</span>(sem_fit, <span class="at">sort =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       lhs op   rhs    mi    epc sepc.lv sepc.all sepc.nox
76   Item7 ~~ Item8 5.993 -0.412  -0.412   -2.282   -2.282
30 Factor1 =~ Item9 5.133  0.068   0.059    0.063    0.063
46   Item1 ~~ Item5 4.340  0.023   0.023    0.165    0.165
31 Factor2 =~ Item1 3.736  0.059   0.052    0.056    0.056
78   Item8 ~~ Item9 3.427  0.353   0.353    2.379    2.379
50   Item1 ~~ Item9 2.345  0.016   0.016    0.160    0.160
53   Item2 ~~ Item5 2.297 -0.020  -0.020   -0.105   -0.105
51   Item2 ~~ Item3 2.242 -0.358  -0.358   -2.222   -2.222
29 Factor1 =~ Item8 2.198 -0.057  -0.049   -0.057   -0.057
28 Factor1 =~ Item7 2.039 -0.042  -0.036   -0.041   -0.041
44   Item1 ~~ Item3 2.017  0.539   0.539    4.474    4.474
33 Factor2 =~ Item3 1.998 -0.045  -0.039   -0.040   -0.040
38 Factor3 =~ Item2 1.605 -0.048  -0.040   -0.045   -0.045
57   Item2 ~~ Item9 1.523 -0.016  -0.016   -0.113   -0.113
48   Item1 ~~ Item7 1.446 -0.013  -0.013   -0.103   -0.103
34 Factor2 =~ Item7 1.384 -0.034  -0.029   -0.033   -0.033
77   Item7 ~~ Item9 1.264  0.394   0.394    4.012    4.012
47   Item1 ~~ Item6 0.934 -0.010  -0.010   -0.085   -0.085
37 Factor3 =~ Item1 0.841  0.030   0.025    0.027    0.027
36 Factor2 =~ Item9 0.821  0.026   0.023    0.025    0.025
55   Item2 ~~ Item7 0.687  0.010   0.010    0.062    0.062
75   Item6 ~~ Item9 0.646  0.008   0.008    0.084    0.084
70   Item5 ~~ Item7 0.635 -0.008  -0.008   -0.062   -0.062
74   Item6 ~~ Item8 0.634 -0.010  -0.010   -0.060   -0.060
40 Factor3 =~ Item4 0.632  0.023   0.019    0.021    0.021
26 Factor1 =~ Item5 0.589  0.023   0.020    0.023    0.023
41 Factor3 =~ Item5 0.563 -0.024  -0.019   -0.022   -0.022
58   Item3 ~~ Item4 0.430 -0.007  -0.007   -0.067   -0.067
32 Factor2 =~ Item2 0.390 -0.022  -0.019   -0.022   -0.022
62   Item3 ~~ Item8 0.386 -0.009  -0.009   -0.052   -0.052
25 Factor1 =~ Item4 0.380 -0.017  -0.015   -0.016   -0.016
59   Item3 ~~ Item5 0.352 -0.007  -0.007   -0.052   -0.052
67   Item4 ~~ Item8 0.316  0.007   0.007    0.044    0.044
60   Item3 ~~ Item6 0.303  0.006   0.006    0.054    0.054
66   Item4 ~~ Item7 0.302  0.005   0.005    0.050    0.050
54   Item2 ~~ Item6 0.258  0.006   0.006    0.039    0.039
68   Item4 ~~ Item9 0.257 -0.005  -0.005   -0.056   -0.056
63   Item3 ~~ Item9 0.209  0.005   0.005    0.053    0.053
73   Item6 ~~ Item7 0.200 -0.004  -0.004   -0.038   -0.038
52   Item2 ~~ Item4 0.195  0.005   0.005    0.036    0.036
43   Item1 ~~ Item2 0.186  0.092   0.092    0.525    0.525
71   Item5 ~~ Item8 0.173  0.006   0.006    0.028    0.028
69   Item5 ~~ Item6 0.164 -0.134  -0.134   -1.071   -1.071
35 Factor2 =~ Item8 0.118  0.013   0.011    0.013    0.013
65   Item4 ~~ Item6 0.083  0.131   0.131    1.316    1.316
56   Item2 ~~ Item8 0.050 -0.004  -0.004   -0.015   -0.015
42 Factor3 =~ Item6 0.033 -0.005  -0.004   -0.005   -0.005
72   Item5 ~~ Item9 0.032  0.002   0.002    0.017    0.017
64   Item4 ~~ Item5 0.030  0.060   0.060    0.518    0.518
61   Item3 ~~ Item7 0.015 -0.001  -0.001   -0.011   -0.011
45   Item1 ~~ Item4 0.009  0.001   0.001    0.009    0.009
49   Item1 ~~ Item8 0.006  0.001   0.001    0.006    0.006
39 Factor3 =~ Item3 0.000  0.001   0.000    0.000    0.000
27 Factor1 =~ Item6 0.000  0.000   0.000    0.000    0.000</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># semPaths() 함수 수정: 경로의 투명도 및 색상 조정</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">semPaths</span>(</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">object =</span> sem_fit,         <span class="co"># SEM 모델 객체</span></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">what =</span> <span class="st">"std"</span>,             <span class="co"># 표준화된 경로 계수 표시</span></span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">layout =</span> <span class="st">"tree"</span>,          <span class="co"># 트리 레이아웃</span></span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">edge.label.cex =</span> <span class="fl">1.2</span>,     <span class="co"># 경로 레이블 크기 (더 크게)</span></span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">edge.color =</span> <span class="st">"black"</span>,     <span class="co"># 선 색상 지정</span></span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">edge.width =</span> <span class="dv">1</span>,         <span class="co"># 선의 두께</span></span>
<span id="cb45-9"><a href="#cb45-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">residuals =</span> <span class="cn">TRUE</span>,         <span class="co"># 잔차 포함</span></span>
<span id="cb45-10"><a href="#cb45-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">intercepts =</span> <span class="cn">FALSE</span>,       <span class="co"># 절편 제거</span></span>
<span id="cb45-11"><a href="#cb45-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">fade =</span> <span class="cn">FALSE</span>,             <span class="co"># 투명도 조정 (FALSE로 설정하여 선을 더 선명하게)</span></span>
<span id="cb45-12"><a href="#cb45-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">nCharNodes =</span> <span class="dv">0</span>            <span class="co"># 노드 이름의 길이 제한 없음</span></span>
<span id="cb45-13"><a href="#cb45-13" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="14_week_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><br></p>
</section>
</section>
<section id="clustering" class="level2">
<h2 class="anchored" data-anchor-id="clustering">Clustering</h2>
<ul>
<li>About Mechanism <a href="content/clustering.pdf">pdf</a></li>
</ul>
<section id="k-means-clustering-in-r" class="level3">
<h3 class="anchored" data-anchor-id="k-means-clustering-in-r"><strong>K-Means Clustering in R</strong></h3>
<blockquote class="blockquote">
<p>The basic idea behind k-means clustering consists of defining clusters so that the total intra-cluster variation (known as <em>total within-cluster variation</em>) is minimized. There are several k-means algorithms available. The standard algorithm is the Hartigan-Wong algorithm (Hartigan and Wong 1979), which defines the total within-cluster variation as the sum of squared distances Euclidean distances between items and the corresponding centroid</p>
</blockquote>
<p><br></p>
<p>Let’s experiment with this simple shiny app</p>
<p><a href="https://jjallaire.shinyapps.io/shiny-k-means/" class="uri">https://jjallaire.shinyapps.io/shiny-k-means/</a></p>
<p><br></p>
<p><strong>Hands-on practice</strong></p>
<p>Data we’ll use is <code>USArrests</code>. The data must <u>contains only continuous variables</u>, as the k-means algorithm uses variable means.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ ggplot2::%+%()   masks psych::%+%()
✖ ggplot2::alpha() masks psych::alpha()
✖ dplyr::filter()  masks stats::filter()
✖ dplyr::lag()     masks stats::lag()
✖ dplyr::select()  masks MASS::select()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"USArrests"</span>)      <span class="co"># Loading the data set</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(USArrests)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           Murder Assault UrbanPop Rape
Alabama      13.2     236       58 21.2
Alaska       10.0     263       48 44.5
Arizona       8.1     294       80 31.0
Arkansas      8.8     190       50 19.5
California    9.0     276       91 40.6
Colorado      7.9     204       78 38.7</code></pre>
</div>
</div>
<p>The <strong><code>USArrests</code></strong> dataset is a built-in dataset in R that contains data on crime rates (number of arrests per 100,000 residents) in the United States in 1973. The dataset has 50 observations, corresponding to the 50 US states, and 4 variables:</p>
<ul>
<li><p><strong><code>Murder</code></strong>: Murder arrests (number of arrests for murder per 100,000 residents).</p></li>
<li><p><strong><code>Assault</code></strong>: Assault arrests (number of arrests for assault per 100,000 residents).</p></li>
<li><p><strong><code>UrbanPop</code></strong>: Urban population (percentage of the population living in urban areas).</p></li>
<li><p><strong><code>Rape</code></strong>: Rape arrests (number of arrests for rape per 100,000 residents).</p></li>
</ul>
<p><br></p>
<p><strong>Visualize the data</strong></p>
<p>See the <a href="https://givitallugot.github.io/articles/2020-03/R-visualization-2-usmap">link</a> for the detail (in Korean)</p>
<ul>
<li>Let’s create a new column for the state name</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co">#change row names to column (variable)</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>crime <span class="ot">&lt;-</span> <span class="fu">rownames_to_column</span>(USArrests, <span class="at">var=</span><span class="st">"state"</span>) </span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(crime)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       state Murder Assault UrbanPop Rape
1    Alabama   13.2     236       58 21.2
2     Alaska   10.0     263       48 44.5
3    Arizona    8.1     294       80 31.0
4   Arkansas    8.8     190       50 19.5
5 California    9.0     276       91 40.6
6   Colorado    7.9     204       78 38.7</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co">#change the upper letter to lower character in state variable</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>crime<span class="sc">$</span>state <span class="ot">&lt;-</span> <span class="fu">tolower</span>(crime<span class="sc">$</span>state) </span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(crime)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       state Murder Assault UrbanPop Rape
1    alabama   13.2     236       58 21.2
2     alaska   10.0     263       48 44.5
3    arizona    8.1     294       80 31.0
4   arkansas    8.8     190       50 19.5
5 california    9.0     276       91 40.6
6   colorado    7.9     204       78 38.7</code></pre>
</div>
</div>
<p>The <strong><code>states_map &lt;- map_data("state")</code></strong> code is used to create a dataframe that contains map data for the 50 states in the United States.</p>
<p>The <strong><code>map_data()</code></strong> function is from the <strong><code>ggplot2</code></strong> package, and it returns a dataframe that contains latitude and longitude coordinates for the boundaries of each state, along with additional information that can be used to plot the map.</p>
<p>The argument to the <strong><code>map_data()</code></strong> function is the name of the region for which to retrieve the map data. In this case, the argument is <strong><code>"state"</code></strong>, which indicates that we want map data for the 50 states in the US.</p>
<p>The resulting <strong><code>states_map</code></strong> dataframe contains the following columns:</p>
<ul>
<li><p><strong><code>long</code></strong>: A vector of longitudes representing the boundaries of the state.</p></li>
<li><p><strong><code>lat</code></strong>: A vector of latitudes representing the boundaries of the state.</p></li>
<li><p><strong><code>group</code></strong>: An integer indicating the group to which each point belongs. This is used to group the points together when plotting the map.</p></li>
<li><p><strong><code>order</code></strong>: An integer indicating the order in which the points should be plotted.</p></li>
<li><p><strong><code>region</code></strong>: A character string indicating the name of the state.</p></li>
<li><p><strong><code>subregion</code></strong>: A character string indicating the name of a subregion within the state, if applicable. This is usually <strong><code>NA</code></strong> for the state maps.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>states_map <span class="ot">&lt;-</span> <span class="fu">map_data</span>(<span class="st">"state"</span>)</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(states_map)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       long      lat group order  region subregion
1 -87.46201 30.38968     1     1 alabama      &lt;NA&gt;
2 -87.48493 30.37249     1     2 alabama      &lt;NA&gt;
3 -87.52503 30.37249     1     3 alabama      &lt;NA&gt;
4 -87.53076 30.33239     1     4 alabama      &lt;NA&gt;
5 -87.57087 30.32665     1     5 alabama      &lt;NA&gt;
6 -87.58806 30.32665     1     6 alabama      &lt;NA&gt;</code></pre>
</div>
</div>
<p>The code <strong><code>library(ggiraphExtra)</code></strong> loads the <strong><code>ggiraphExtra</code></strong> package, which extends the functionality of the <strong><code>ggplot2</code></strong> package to allow for interactive graphics in R.</p>
<p>The <strong><code>ggChoropleth()</code></strong> function is from the <strong><code>ggiraphExtra</code></strong> package and is used to create a choropleth map in which each state is colored according to its value of a specified variable.</p>
<p>The first argument to <strong><code>ggChoropleth()</code></strong> is the data frame containing the data to be plotted, which is <strong><code>crime</code></strong> in this case.</p>
<p>The second argument is the <strong><code>aes()</code></strong> function, which is used to map variables in the data frame to visual properties of the plot. The <strong><code>fill</code></strong> aesthetic is used to specify that the color of each state should be determined by the value of the <strong><code>Murder</code></strong> variable in the <strong><code>crime</code></strong> data frame. The <strong><code>map_id</code></strong> aesthetic is used to specify that each state should be identified by its name, which is found in the <strong><code>state</code></strong> variable in the <strong><code>crime</code></strong> data frame.</p>
<p>The third argument is the <strong><code>map</code></strong> argument, which specifies the data frame containing the map data. In this case, the <strong><code>states_map</code></strong> data frame is used, which was created earlier using the <strong><code>map_data()</code></strong> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("ggiraphExtra")</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggiraphExtra)</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggChoropleth</span>(<span class="at">data=</span>crime, <span class="fu">aes</span>(<span class="at">fill=</span>Murder, <span class="at">map_id=</span>state), <span class="at">map=</span>states_map)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="14_week_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>Remove legend and change background color</p></li>
<li><p>Murder rate by state</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggthemes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'ggthemes'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:ggiraphExtra':

    theme_clean</code></pre>
</div>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggChoropleth</span>(<span class="at">data=</span>crime, <span class="fu">aes</span>(<span class="at">fill=</span>Murder, <span class="at">map_id=</span>state), <span class="at">map=</span>states_map) <span class="sc">+</span> </span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_map</span>() <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">legend.position=</span><span class="st">"right"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="14_week_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>Urban pop by state</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggChoropleth</span>(<span class="at">data=</span>crime, <span class="fu">aes</span>(<span class="at">fill=</span>UrbanPop, <span class="at">map_id=</span>state), <span class="at">map=</span>states_map) <span class="sc">+</span> </span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_map</span>() <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">legend.position=</span><span class="st">"right"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="14_week_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>Assault rate by state</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggChoropleth</span>(<span class="at">data=</span>crime, <span class="fu">aes</span>(<span class="at">fill=</span>Assault, <span class="at">map_id=</span>state), <span class="at">map=</span>states_map) <span class="sc">+</span> </span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_map</span>() <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">legend.position=</span><span class="st">"right"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="14_week_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>Rape rate by state</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggChoropleth</span>(<span class="at">data=</span>crime, <span class="fu">aes</span>(<span class="at">fill=</span>Rape, <span class="at">map_id=</span>state), <span class="at">map=</span>states_map) <span class="sc">+</span> </span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_map</span>() <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">legend.position=</span><span class="st">"right"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="14_week_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Required R packages and functions The standard R function for k-means clustering is <code>kmeans()</code> [stats package], which simplified format is as follow:</p>
<p><code>kmeans(x, centers, iter.max = 10, nstart = 1)</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(USArrests)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 50
Columns: 4
$ Murder   &lt;dbl&gt; 13.2, 10.0, 8.1, 8.8, 9.0, 7.9, 3.3, 5.9, 15.4, 17.4, 5.3, 2.…
$ Assault  &lt;int&gt; 236, 263, 294, 190, 276, 204, 110, 238, 335, 211, 46, 120, 24…
$ UrbanPop &lt;int&gt; 58, 48, 80, 50, 91, 78, 77, 72, 80, 60, 83, 54, 83, 65, 57, 6…
$ Rape     &lt;dbl&gt; 21.2, 44.5, 31.0, 19.5, 40.6, 38.7, 11.1, 15.8, 31.9, 25.8, 2…</code></pre>
</div>
</div>
<ul>
<li><strong>Z-score Standardization</strong> for k-means clustering</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">scale</span>(USArrests) <span class="co"># Scaling the data</span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               Murder   Assault   UrbanPop         Rape
Alabama    1.24256408 0.7828393 -0.5209066 -0.003416473
Alaska     0.50786248 1.1068225 -1.2117642  2.484202941
Arizona    0.07163341 1.4788032  0.9989801  1.042878388
Arkansas   0.23234938 0.2308680 -1.0735927 -0.184916602
California 0.27826823 1.2628144  1.7589234  2.067820292
Colorado   0.02571456 0.3988593  0.8608085  1.864967207</code></pre>
</div>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Murder           Assault           UrbanPop             Rape        
 Min.   :-1.6044   Min.   :-1.5090   Min.   :-2.31714   Min.   :-1.4874  
 1st Qu.:-0.8525   1st Qu.:-0.7411   1st Qu.:-0.76271   1st Qu.:-0.6574  
 Median :-0.1235   Median :-0.1411   Median : 0.03178   Median :-0.1209  
 Mean   : 0.0000   Mean   : 0.0000   Mean   : 0.00000   Mean   : 0.0000  
 3rd Qu.: 0.7949   3rd Qu.: 0.9388   3rd Qu.: 0.84354   3rd Qu.: 0.5277  
 Max.   : 2.2069   Max.   : 1.9948   Max.   : 1.75892   Max.   : 2.6444  </code></pre>
</div>
</div>
<p>To create a beautiful graph of the clusters generated with the <code>kmeans()</code> function, will use the <code>factoextra</code> package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("factoextra")</span></span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(factoextra)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Welcome! Want to learn more? See two factoextra-related books at https://goo.gl/ve3WBa</code></pre>
</div>
</div>
<ul>
<li>How many clusters (k) is the best?</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>g1<span class="ot">&lt;-</span><span class="fu">fviz_nbclust</span>(df, kmeans, <span class="at">method =</span> <span class="st">"wss"</span>)</span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>g1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="14_week_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>g2<span class="ot">&lt;-</span><span class="fu">fviz_nbclust</span>(df, kmeans, <span class="at">method =</span> <span class="st">"silhouette"</span>)</span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>g2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="14_week_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This code uses the <strong><code>fviz_nbclust()</code></strong> function from the <strong><code>factoextra</code></strong> package in R to determine the optimal number of clusters to use in a K-means clustering analysis.</p>
<p>The first argument of <strong><code>fviz_nbclust()</code></strong> is the data frame <strong><code>df</code></strong> that contains the variables to be used in the clustering analysis.</p>
<p>The second argument is the clustering function <strong><code>kmeans</code></strong> that specifies the algorithm to be used for clustering.</p>
<p>The third argument <strong><code>method</code></strong> specifies the method to be used to determine the optimal number of clusters. In this case, two methods are used:</p>
<ul>
<li><p><strong><code>"wss"</code></strong>: <strong>Within-cluster sum of squares</strong>. This method computes the sum of squared distances between each observation and its assigned cluster center, and then adds up these values across all clusters. The goal is to find the number of clusters that minimize the within-cluster sum of squares.</p></li>
<li><p><strong><code>"silhouette"</code></strong>: <strong>Silhouette width</strong>. This method computes a silhouette width for each observation, which measures <u>how similar the observation is to its own cluster compared to other clusters</u>. The goal is to find the number of clusters that maximize the average silhouette width across all observations.</p></li>
</ul>
<p>Let’s run unsupervised clustering given <strong><em>k=4</em></strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute k-means with k = 4</span></span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a>km.res <span class="ot">&lt;-</span> <span class="fu">kmeans</span>(df, <span class="dv">4</span>, <span class="at">nstart =</span> <span class="dv">25</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>As the final result of k-means clustering result is sensitive to the random starting assignments, we specify <code>nstart = 25</code>. This means that R will try 25 different random starting assignments and then select the best results corresponding to the one with the lowest within cluster variation. The default value of nstart in R is one. But, it’s strongly recommended to compute k-means clustering with a large value of nstart such as 25 or 50, in order to have a more stable result.</p>
<ul>
<li>Print the result</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the results</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(km.res)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>K-means clustering with 4 clusters of sizes 8, 13, 16, 13

Cluster means:
      Murder    Assault   UrbanPop        Rape
1  1.4118898  0.8743346 -0.8145211  0.01927104
2 -0.9615407 -1.1066010 -0.9301069 -0.96676331
3 -0.4894375 -0.3826001  0.5758298 -0.26165379
4  0.6950701  1.0394414  0.7226370  1.27693964

Clustering vector:
       Alabama         Alaska        Arizona       Arkansas     California 
             1              4              4              1              4 
      Colorado    Connecticut       Delaware        Florida        Georgia 
             4              3              3              4              1 
        Hawaii          Idaho       Illinois        Indiana           Iowa 
             3              2              4              3              2 
        Kansas       Kentucky      Louisiana          Maine       Maryland 
             3              2              1              2              4 
 Massachusetts       Michigan      Minnesota    Mississippi       Missouri 
             3              4              2              1              4 
       Montana       Nebraska         Nevada  New Hampshire     New Jersey 
             2              2              4              2              3 
    New Mexico       New York North Carolina   North Dakota           Ohio 
             4              4              1              2              3 
      Oklahoma         Oregon   Pennsylvania   Rhode Island South Carolina 
             3              3              3              3              1 
  South Dakota      Tennessee          Texas           Utah        Vermont 
             2              1              4              3              2 
      Virginia     Washington  West Virginia      Wisconsin        Wyoming 
             3              3              2              2              3 

Within cluster sum of squares by cluster:
[1]  8.316061 11.952463 16.212213 19.922437
 (between_SS / total_SS =  71.2 %)

Available components:

[1] "cluster"      "centers"      "totss"        "withinss"     "tot.withinss"
[6] "betweenss"    "size"         "iter"         "ifault"      </code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>The printed output displays: the cluster means or centers: a matrix, which rows are cluster number (1 to 4) and columns are variables the clustering vector: A vector of integers (from 1:k) indicating the cluster to which each point is allocated</p>
</blockquote>
<p>If you want to add the point classifications to the original data, use this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(km.res)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>List of 9
 $ cluster     : Named int [1:50] 1 4 4 1 4 4 3 3 4 1 ...
  ..- attr(*, "names")= chr [1:50] "Alabama" "Alaska" "Arizona" "Arkansas" ...
 $ centers     : num [1:4, 1:4] 1.412 -0.962 -0.489 0.695 0.874 ...
  ..- attr(*, "dimnames")=List of 2
  .. ..$ : chr [1:4] "1" "2" "3" "4"
  .. ..$ : chr [1:4] "Murder" "Assault" "UrbanPop" "Rape"
 $ totss       : num 196
 $ withinss    : num [1:4] 8.32 11.95 16.21 19.92
 $ tot.withinss: num 56.4
 $ betweenss   : num 140
 $ size        : int [1:4] 8 13 16 13
 $ iter        : int 2
 $ ifault      : int 0
 - attr(*, "class")= chr "kmeans"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a>km.res<span class="sc">$</span>cluster</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       Alabama         Alaska        Arizona       Arkansas     California 
             1              4              4              1              4 
      Colorado    Connecticut       Delaware        Florida        Georgia 
             4              3              3              4              1 
        Hawaii          Idaho       Illinois        Indiana           Iowa 
             3              2              4              3              2 
        Kansas       Kentucky      Louisiana          Maine       Maryland 
             3              2              1              2              4 
 Massachusetts       Michigan      Minnesota    Mississippi       Missouri 
             3              4              2              1              4 
       Montana       Nebraska         Nevada  New Hampshire     New Jersey 
             2              2              4              2              3 
    New Mexico       New York North Carolina   North Dakota           Ohio 
             4              4              1              2              3 
      Oklahoma         Oregon   Pennsylvania   Rhode Island South Carolina 
             3              3              3              3              1 
  South Dakota      Tennessee          Texas           Utah        Vermont 
             2              1              4              3              2 
      Virginia     Washington  West Virginia      Wisconsin        Wyoming 
             3              3              2              2              3 </code></pre>
</div>
</div>
<ul>
<li>Create a new data frame including cluster information</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a>dd <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(USArrests, <span class="at">cluster =</span> km.res<span class="sc">$</span>cluster)</span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dd)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           Murder Assault UrbanPop Rape cluster
Alabama      13.2     236       58 21.2       1
Alaska       10.0     263       48 44.5       4
Arizona       8.1     294       80 31.0       4
Arkansas      8.8     190       50 19.5       1
California    9.0     276       91 40.6       4
Colorado      7.9     204       78 38.7       4</code></pre>
</div>
</div>
<ul>
<li>Check groups’ characteristics</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a>dd <span class="sc">%&gt;%</span> </span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(cluster) <span class="sc">%&gt;%</span> </span>
<span id="cb83-3"><a href="#cb83-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize_all</span>(mean)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 5
  cluster Murder Assault UrbanPop  Rape
    &lt;int&gt;  &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;
1       1  13.9    244.      53.8  21.4
2       2   3.6     78.5     52.1  12.2
3       3   5.66   139.      73.9  18.8
4       4  10.8    257.      76    33.2</code></pre>
</div>
</div>
<ul>
<li>Cluster number for each of the observations</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(dd<span class="sc">$</span>cluster)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 1  2  3  4 
 8 13 16 13 </code></pre>
</div>
</div>
<ul>
<li>Reshape the dataset to visualize</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(reshape2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'reshape2'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:tidyr':

    smiths</code></pre>
</div>
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a>dd <span class="sc">%&gt;%</span> </span>
<span id="cb90-2"><a href="#cb90-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">melt</span>(<span class="at">id.vars=</span><span class="st">"cluster"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb90-3"><a href="#cb90-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">cluster=</span><span class="fu">as.factor</span>(cluster)) <span class="sc">%&gt;%</span> </span>
<span id="cb90-4"><a href="#cb90-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">20</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   cluster variable value
1        1   Murder  13.2
2        4   Murder  10.0
3        4   Murder   8.1
4        1   Murder   8.8
5        4   Murder   9.0
6        4   Murder   7.9
7        3   Murder   3.3
8        3   Murder   5.9
9        4   Murder  15.4
10       1   Murder  17.4
11       3   Murder   5.3
12       2   Murder   2.6
13       4   Murder  10.4
14       3   Murder   7.2
15       2   Murder   2.2
16       3   Murder   6.0
17       2   Murder   9.7
18       1   Murder  15.4
19       2   Murder   2.1
20       4   Murder  11.3</code></pre>
</div>
</div>
<ul>
<li>Check groups’ characteristics with ggplot</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a>dd <span class="sc">%&gt;%</span> </span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">melt</span>(<span class="at">id.vars=</span><span class="st">"cluster"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb92-3"><a href="#cb92-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">cluster=</span><span class="fu">as.factor</span>(cluster)) <span class="sc">%&gt;%</span> </span>
<span id="cb92-4"><a href="#cb92-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>cluster, <span class="at">y=</span>value))<span class="sc">+</span></span>
<span id="cb92-5"><a href="#cb92-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()<span class="sc">+</span></span>
<span id="cb92-6"><a href="#cb92-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>variable, <span class="at">scale=</span><span class="st">"free_y"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="14_week_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>cluster 1: Rural area with high murder, assault</li>
<li>cluster 2: Peaceful rural areas</li>
<li>cluster 3: Good city with low crime</li>
<li>cluster 4: City Gotham…?</li>
</ul>
<p>Let’s see clusters are well made</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_cluster</span>(km.res, <span class="at">data =</span> df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="14_week_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Let’s play with different k (number of clusters)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a>k2 <span class="ot">&lt;-</span> <span class="fu">kmeans</span>(df, <span class="at">centers =</span> <span class="dv">2</span>, <span class="at">nstart =</span> <span class="dv">25</span>)</span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a>k3 <span class="ot">&lt;-</span> <span class="fu">kmeans</span>(df, <span class="at">centers =</span> <span class="dv">3</span>, <span class="at">nstart =</span> <span class="dv">25</span>)</span>
<span id="cb94-3"><a href="#cb94-3" aria-hidden="true" tabindex="-1"></a>k4 <span class="ot">&lt;-</span> <span class="fu">kmeans</span>(df, <span class="at">centers =</span> <span class="dv">4</span>, <span class="at">nstart =</span> <span class="dv">25</span>)</span>
<span id="cb94-4"><a href="#cb94-4" aria-hidden="true" tabindex="-1"></a>k5 <span class="ot">&lt;-</span> <span class="fu">kmeans</span>(df, <span class="at">centers =</span> <span class="dv">5</span>, <span class="at">nstart =</span> <span class="dv">25</span>)</span>
<span id="cb94-5"><a href="#cb94-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb94-6"><a href="#cb94-6" aria-hidden="true" tabindex="-1"></a><span class="co"># plots to compare</span></span>
<span id="cb94-7"><a href="#cb94-7" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">fviz_cluster</span>(k2, <span class="at">geom =</span> <span class="st">"point"</span>, <span class="at">data =</span> df) <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">"k = 2"</span>)</span>
<span id="cb94-8"><a href="#cb94-8" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">fviz_cluster</span>(k3, <span class="at">geom =</span> <span class="st">"point"</span>,  <span class="at">data =</span> df) <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">"k = 3"</span>)</span>
<span id="cb94-9"><a href="#cb94-9" aria-hidden="true" tabindex="-1"></a>p3 <span class="ot">&lt;-</span> <span class="fu">fviz_cluster</span>(k4, <span class="at">geom =</span> <span class="st">"point"</span>,  <span class="at">data =</span> df) <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">"k = 4"</span>)</span>
<span id="cb94-10"><a href="#cb94-10" aria-hidden="true" tabindex="-1"></a>p4 <span class="ot">&lt;-</span> <span class="fu">fviz_cluster</span>(k5, <span class="at">geom =</span> <span class="st">"point"</span>,  <span class="at">data =</span> df) <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">"k = 5"</span>)</span>
<span id="cb94-11"><a href="#cb94-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb94-12"><a href="#cb94-12" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gridExtra)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'gridExtra'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:dplyr':

    combine</code></pre>
</div>
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(p1, p2, p3, p4, <span class="at">nrow =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="14_week_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>License: <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC BY-SA 2.0</a>.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/ChangjunChrisLee/">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/Dr_CJLee">
      <i class="bi bi-twitter" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>