---
title: Course description & Communication
format:
  html:
    theme: cosmo  # Choose a theme that supports full-width layouts (e.g., cosmo, flatly)
    toc: false       # Disable the table of contents if unnecessary
    sidebar: false   # Remove the sidebar search
    page-layout: full
---

------------------------------------------------------------------------

### Course description

> 본 수업에서는 실감미디어, 사용자 경험(UX), 기술 채택에 대한 이해를 Conjoint Analysis(CE) 관점에서 탐구한다. 학생들은 Conjoint 실험을 설계, 실행, 분석하는 방법을 배우고, 이를 실감미디어와 관련된 실제 사례에 적용해 본다. 구체적으로는 실감미디어 기술에 대한 이해를 바탕으로 실제로 존재하거나 존재하지 않는 UX에 대한 속성을 추출하고 해당 속성이 사용자 채택에 어떤 영향을 미치는지, 그리고 그 가치를 평가해본다.

<br>

**Goals**

1.  실감미디어와 UX 속성을 기술 채택 맥락에서 이해

2.  Conjoint Analysis 설계 및 분석에 대한 실무 능력을 갖춤

3.  CE 방법론을 실감미디어와 같은 실제 문제에 적용할 수 있음

4.  팀워크와 발표 능력을 팀 기반 연구 프로젝트를 통해 향상

5.  연구 결과는 SSCI 급 논문으로 발전 & 투고

</br>

### Time & Location

-   Thu 09:00 \~ 11:30 \@국제관 첨단강의실\[9B113\]

</br>

### Weekly Design

+------------+------------+----------------------------------------------+-------------------------------------------------+
| **주차**   | **날짜**   | **주제**                                     | 내용 및 실습                                    |
+:==========:+:==========:+==============================================+=================================================+
| 1          | 03/06/2025 | 실감미디어, UX, 기술 채택                    | Course Intro                                    |
+------------+------------+----------------------------------------------+-------------------------------------------------+
| 2          | 03/13/2025 | \[강의\] Conjoint 실험 및 분석 개요          | Conjoint 실험의 기본 개념 및 구성 방법          |
|            |            |                                              |                                                 |
|            |            | \[플립러닝\] 10:30 수업시작                  |                                                 |
+------------+------------+----------------------------------------------+-------------------------------------------------+
| 3          | 03/20/2025 | \[강의\] Conjoint 분석 방법                  | Conjoint 데이터 분석 절차 및 기법               |
|            |            |                                              |                                                 |
|            |            | \[플립러닝\] 10:30 수업시작                  |                                                 |
+------------+------------+----------------------------------------------+-------------------------------------------------+
| 4          | 03/27/2025 | \[발제\] CE를 활용한 기존 연구 발제          | 기존 연구 분석 및 실감미지어 적용 방안 구상     |
+------------+------------+----------------------------------------------+-------------------------------------------------+
| 5          | 04/03/2025 | \[강의\] 실감미디어 UX를 적용한 CE 속성 도출 | \[실습\] UX 원칙을 활용한 CE 속성 설계          |
+------------+------------+----------------------------------------------+-------------------------------------------------+
| 6          | 04/10/2025 | \[실습\] 연구 계획 발제 준비 (팀별 활동)     | 팀별 연구 계획 작성 및 준비                     |
+------------+------------+----------------------------------------------+-------------------------------------------------+
| 7          | 04/17/2025 | \[발제\] 연구 계획 발표 및 피드백            |                                                 |
+------------+------------+----------------------------------------------+-------------------------------------------------+
| 8          | 04/24/2025 | \[발제\] 피드백 반영한 연구 계획 수정        |                                                 |
|            |            |                                              |                                                 |
|            |            | \[강의\] 설문지 개발 강의                    |                                                 |
+------------+------------+----------------------------------------------+-------------------------------------------------+
| 9          | 05/01/2025 | \[실습\] 팀별 설문지 개발                    | [글융세 참여로 강의 시간 외 피드백]{.underline} |
+------------+------------+----------------------------------------------+-------------------------------------------------+
| 10         | 05/08/2025 | 설문 진행                                    | 설문 업체 섭외 및 설문 진행                     |
+------------+------------+----------------------------------------------+-------------------------------------------------+
| 11         | 05/15/2025 | \[발제\] 설문 결과 분석 발표 및 피드백 (1)   | 첫 번째 분석 결과 발표 및 피드백                |
+------------+------------+----------------------------------------------+-------------------------------------------------+
| 12         | 05/22/2025 | \[발제\] 설문 결과 분석 발표 및 피드백 (2)   | 추가 분석 발표 및 피드백                        |
+------------+------------+----------------------------------------------+-------------------------------------------------+
| 13         | 05/29/2025 | \[발제\] 시사점 도출 및 연구 마무리 (1)      | 분석 결과를 바탕으로 한 시사점 도출             |
+------------+------------+----------------------------------------------+-------------------------------------------------+
| 14         | 06/05/2025 | \[발제\] 시사점 도출 및 연구 마무리 (2)      | 연구 마무리 및 페이퍼 준비                      |
+------------+------------+----------------------------------------------+-------------------------------------------------+
| 15         | 06/12/2025 | 최종 과제 제출                               | 팀별 최종 프로젝트 제출                         |
+------------+------------+----------------------------------------------+-------------------------------------------------+

: {.secondary .hover}

<br>

### Evaluation

-   Attendance & Attitude (50 %)

-   Final Research Paper (50%)

</br>

### Communication

-   Notices & Questions

    -   Please join Kakao open-chat room

        -   <https://open.kakao.com/o/gqHmyhbh>

        -   입장하셔서 이름을 꼭 출석부에 있는 이름으로 설정해주세요.

-   Personal counsel (Scholarship, recommendation letter, etc.)

    -   CJ-counselling room (Anything but the class content)

        -   CJ상담실: <https://open.kakao.com/o/s8zTrYCf>
