<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.262">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Changjun Lee">
<meta name="dcterms.date" content="2023-04-24">
<meta name="description" content="구조방정식과 경로분석을 들여다보자">

<title>CJL Lab - Structural Equation Modeling and Path Analysis in R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">CJL Lab</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html">
 <span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-courses" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Courses</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-courses">    
        <li>
    <a class="dropdown-item" href="../../teaching/index.html">
 <span class="dropdown-text">All Courses</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../teaching/ds101/index.html">
 <span class="dropdown-text">Data Science 101</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../teaching/ml101/index.html">
 <span class="dropdown-text">Machine Learning 101</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../teaching/media_ds/index.html">
 <span class="dropdown-text">Media &amp; Data Science</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../teaching/cul_tech/index.html">
 <span class="dropdown-text">Culture &amp; Technology</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../teaching/data_journalism/index.html">
 <span class="dropdown-text">Data Journalism</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-research" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Research</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-research">    
        <li>
    <a class="dropdown-item" href="../../research/index.html">
 <span class="dropdown-text">Publications</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../research/working.html">
 <span class="dropdown-text">Work in progress</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../../proj/index.html">
 <span class="menu-text">Proj</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../blogs/index.html">
 <span class="menu-text">Blogs</span></a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#step-1-install-and-load-required-packages" id="toc-step-1-install-and-load-required-packages" class="nav-link" data-scroll-target="#step-1-install-and-load-required-packages">Step 1: Install and load required packages</a></li>
  <li><a href="#step-2-import-and-prepare-your-data" id="toc-step-2-import-and-prepare-your-data" class="nav-link" data-scroll-target="#step-2-import-and-prepare-your-data">Step 2: Import and prepare your data</a></li>
  <li><a href="#step-3-specify-the-path-model" id="toc-step-3-specify-the-path-model" class="nav-link" data-scroll-target="#step-3-specify-the-path-model">Step 3: Specify the path model</a></li>
  <li><a href="#step-4-estimate-the-path-coefficients" id="toc-step-4-estimate-the-path-coefficients" class="nav-link" data-scroll-target="#step-4-estimate-the-path-coefficients">Step 4: Estimate the path coefficients</a></li>
  <li><a href="#step-5-assess-model-fit-and-interpret-the-results" id="toc-step-5-assess-model-fit-and-interpret-the-results" class="nav-link" data-scroll-target="#step-5-assess-model-fit-and-interpret-the-results">Step 5: Assess model fit and interpret the results</a></li>
  <li><a href="#about-the-result" id="toc-about-the-result" class="nav-link" data-scroll-target="#about-the-result">About the result</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Structural Equation Modeling and Path Analysis in R</h1>
  <div class="quarto-categories">
    <div class="quarto-category">SEM</div>
    <div class="quarto-category">Path Analysis</div>
    <div class="quarto-category">R</div>
    <div class="quarto-category">Statistics</div>
  </div>
  </div>

<div>
  <div class="description">
    구조방정식과 경로분석을 들여다보자
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Changjun Lee </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 24, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p><strong>Structural equation modeling (SEM)</strong> is a powerful multivariate statistical technique used to estimate and test causal relationships among multiple variables. <strong>Path analysis</strong> is an important aspect of SEM that focuses on the relationships between observed variables. In this blog post, let me provide a step-by-step guide on how to perform SEM and path analysis using R.</p>
</section>
<section id="step-1-install-and-load-required-packages" class="level2">
<h2 class="anchored" data-anchor-id="step-1-install-and-load-required-packages">Step 1: Install and load required packages</h2>
<p>To perform SEM and path analysis in R, you’ll need to install and load the <code>lavaan</code> package, which is specifically designed for this purpose. If you haven’t already installed the package, you can do so by running:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("lavaan")</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>After the package is installed, load it into your R session:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lavaan)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>This is lavaan 0.6-15
lavaan is FREE software! Please report any bugs.</code></pre>
</div>
</div>
</section>
<section id="step-2-import-and-prepare-your-data" class="level2">
<h2 class="anchored" data-anchor-id="step-2-import-and-prepare-your-data">Step 2: Import and prepare your data</h2>
<p>For this tutorial, Ill use the built-in <code>HolzingerSwineford1939</code> dataset from the <code>lavaan</code> package. This dataset includes data on <u>mental ability tests for 301 students</u>. Load the dataset into your R session using the following command:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"HolzingerSwineford1939"</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>mydata <span class="ot">&lt;-</span> HolzingerSwineford1939</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(mydata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  id sex ageyr agemo  school grade       x1   x2    x3       x4   x5        x6
1  1   1    13     1 Pasteur     7 3.333333 7.75 0.375 2.333333 5.75 1.2857143
2  2   2    13     7 Pasteur     7 5.333333 5.25 2.125 1.666667 3.00 1.2857143
3  3   2    13     1 Pasteur     7 4.500000 5.25 1.875 1.000000 1.75 0.4285714
4  4   1    13     2 Pasteur     7 5.333333 7.75 3.000 2.666667 4.50 2.4285714
5  5   2    12     2 Pasteur     7 4.833333 4.75 0.875 2.666667 4.00 2.5714286
6  6   2    14     1 Pasteur     7 5.333333 5.00 2.250 1.000000 3.00 0.8571429
        x7   x8       x9
1 3.391304 5.75 6.361111
2 3.782609 6.25 7.916667
3 3.260870 3.90 4.416667
4 3.000000 5.30 4.861111
5 3.695652 6.30 5.916667
6 4.347826 6.65 7.500000</code></pre>
</div>
</div>
<p>Before performing SEM and path analysis, it’s important to check for missing values and data assumptions. You can use functions like <code>summary()</code> and <code>cor()</code> to explore your data and calculate the correlation matrix.</p>
<p>Dataset has three latent variables: <code>Visual</code>, <code>Textual</code>, and <code>Speed</code>, measured by nine observed variables (x1 to x9).</p>
<ul>
<li><p>Visual is measured with X1 to X3</p></li>
<li><p>Textual is measured with X4 to X6</p></li>
<li><p>Speed is measured with X7 to X9</p></li>
</ul>
<p>Let’s create a path model to estimate the relationships between these latent variables.</p>
</section>
<section id="step-3-specify-the-path-model" class="level2">
<h2 class="anchored" data-anchor-id="step-3-specify-the-path-model">Step 3: Specify the path model</h2>
<p>To perform path analysis, you need to specify the hypothesized causal model based on theory or prior research. In this example, Let’s create a model with three latent variables and their corresponding observed variables.</p>
<ul>
<li><p>Visual → Textual</p></li>
<li><p>Visual &amp; Textual → Speed</p></li>
</ul>
<p>In <code>lavaan</code> syntax, you can specify the model using the following format:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="st">'</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="st">  # Latent variable definitions</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="st">  Visual =~ x1 + x2 + x3</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="st">  Textual =~ x4 + x5 + x6</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="st">  Speed =~ x7 + x8 + x9</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="st">  # Direct effects</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a><span class="st">  Textual ~ a*Visual</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a><span class="st">  Speed ~ b*Visual + c*Textual</span></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a><span class="st">  # Covariances</span></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a><span class="st">  Visual ~~ Textual</span></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a><span class="st">  Visual ~~ Speed</span></span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a><span class="st">  Textual ~~ Speed</span></span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a><span class="st">'</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="step-4-estimate-the-path-coefficients" class="level2">
<h2 class="anchored" data-anchor-id="step-4-estimate-the-path-coefficients">Step 4: Estimate the path coefficients</h2>
<p>To estimate the path coefficients, use the <code>sem()</code> function from the <code>lavaan</code> package. This function requires the specified model and the dataset as input:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>sem_results <span class="ot">&lt;-</span> <span class="fu">sem</span>(model, <span class="at">data =</span> mydata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in lav_model_vcov(lavmodel = lavmodel, lavsamplestats = lavsamplestats, : lavaan WARNING:
    Could not compute standard errors! The information matrix could
    not be inverted. This may be a symptom that the model is not
    identified.</code></pre>
</div>
</div>
<p>The warning message you received indicates that the information matrix could not be inverted, which is often a sign that the model is not identified. In other words, the model may not have a unique solution, and the standard errors cannot be computed. This issue can arise due to various reasons, such as insufficient sample size, multicollinearity among variables, or an incorrectly specified model.</p>
<p>Here are some steps you can take to address this warning:</p>
<ul>
<li><p><strong>Check your sample size</strong>: Ensure that your sample size is large enough to estimate the model parameters reliably. As a rule of thumb, a sample size of at least 200 is recommended for SEM, but this can vary depending on the complexity of your model.</p></li>
<li><p><strong>Examine multicollinearity</strong>: Check the correlation matrix for highly correlated variables. If you find variables with very high correlations (e.g., r &gt; 0.9), consider removing or combining them to reduce multicollinearity.</p></li>
<li><p><strong>Re-specify the model</strong>: Revisit the theoretical basis of your model and ensure that all paths and relationships are correctly specified. Sometimes, an unidentified model can result from incorrectly specified relationships or constraints.</p></li>
<li><p><strong>Modify the model</strong>: If the issue persists, you may need to consider alternative models, such as removing some paths or adding new paths based on theory or previous research. Be cautious when making modifications, as overfitting can occur if you rely solely on improving fit indices without considering the theoretical basis for the changes.</p></li>
</ul>
</section>
<section id="step-5-assess-model-fit-and-interpret-the-results" class="level2">
<h2 class="anchored" data-anchor-id="step-5-assess-model-fit-and-interpret-the-results">Step 5: Assess model fit and interpret the results</h2>
<p>After the path coefficients have been estimated, you can assess the model fit and interpret the results using the <code>summary()</code> function:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(sem_results, <span class="at">fit.measures =</span> <span class="cn">TRUE</span>, <span class="at">standardized =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6.15 ended normally after 34 iterations

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                        24

  Number of observations                           301

Model Test User Model:
                                                      
  Test statistic                                85.306
  Degrees of freedom                                21
  P-value (Chi-square)                           0.000

Model Test Baseline Model:

  Test statistic                               918.852
  Degrees of freedom                                36
  P-value                                        0.000

User Model versus Baseline Model:

  Comparative Fit Index (CFI)                    0.927
  Tucker-Lewis Index (TLI)                       0.875

Loglikelihood and Information Criteria:

  Loglikelihood user model (H0)              -3737.745
  Loglikelihood unrestricted model (H1)      -3695.092
                                                      
  Akaike (AIC)                                7523.490
  Bayesian (BIC)                              7612.460
  Sample-size adjusted Bayesian (SABIC)       7536.346

Root Mean Square Error of Approximation:

  RMSEA                                          0.101
  90 Percent confidence interval - lower         0.079
  90 Percent confidence interval - upper         0.124
  P-value H_0: RMSEA &lt;= 0.050                    0.000
  P-value H_0: RMSEA &gt;= 0.080                    0.943

Standardized Root Mean Square Residual:

  SRMR                                           0.065

Parameter Estimates:

  Standard errors                             Standard
  Information                                 Expected
  Information saturated (h1) model          Structured

Latent Variables:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
  Visual =~                                                             
    x1                1.000                               0.900    0.772
    x2                0.554       NA                      0.498    0.424
    x3                0.729       NA                      0.656    0.581
  Textual =~                                                            
    x4                1.000                               0.990    0.852
    x5                1.113       NA                      1.102    0.855
    x6                0.926       NA                      0.917    0.838
  Speed =~                                                              
    x7                1.000                               0.619    0.570
    x8                1.180       NA                      0.731    0.723
    x9                1.082       NA                      0.670    0.665

Regressions:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
  Textual ~                                                             
    Visual     (a)    0.439       NA                      0.399    0.399
  Speed ~                                                               
    Visual     (b)    0.276       NA                      0.402    0.402
    Textual    (c)   -0.310       NA                     -0.495   -0.495

Covariances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
  Visual ~~                                                             
   .Textual           0.053       NA                      0.066    0.066
   .Speed             0.165       NA                      0.279    0.279
 .Textual ~~                                                            
   .Speed             0.292       NA                      0.503    0.503

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
   .x1                0.549       NA                      0.549    0.404
   .x2                1.134       NA                      1.134    0.821
   .x3                0.844       NA                      0.844    0.662
   .x4                0.371       NA                      0.371    0.275
   .x5                0.446       NA                      0.446    0.269
   .x6                0.356       NA                      0.356    0.298
   .x7                0.799       NA                      0.799    0.676
   .x8                0.488       NA                      0.488    0.477
   .x9                0.566       NA                      0.566    0.558
    Visual            0.809       NA                      1.000    1.000
   .Textual           0.777       NA                      0.793    0.793
   .Speed             0.432       NA                      1.126    1.126</code></pre>
</div>
</div>
<p>This function will provide you with the unstandardized and standardized path coefficients, standard errors, p-values, and fit indices (e.g., CFI, RMSEA). If the model fit is not satisfactory, you may need to modify your model and re-estimate the path coefficients.</p>
</section>
<section id="about-the-result" class="level2">
<h2 class="anchored" data-anchor-id="about-the-result">About the result</h2>
<ol type="1">
<li><p><strong>Model Test User Model</strong>: The chi-square test statistic for the specified model is 85.306 with 21 degrees of freedom, resulting in a p-value &lt; 0.001. Since the p-value is less than the significance level (usually 0.05), we reject the null hypothesis, indicating that the model does not perfectly fit the data. However, the chi-square test is sensitive to sample size, and it is essential to consider other fit indices as well.</p></li>
<li><p><strong>User Model versus Baseline Model</strong>: The Comparative Fit Index (CFI) is 0.927, and the Tucker-Lewis Index (TLI) is 0.875. Both indices are close to the recommended cutoff of 0.95, suggesting an acceptable fit. However, there is room for improvement in the model.</p></li>
<li><p><strong>Root Mean Square Error of Approximation (RMSEA)</strong>: The RMSEA value is 0.101, with a 90% confidence interval ranging from 0.079 to 0.124. An RMSEA value below 0.08 is considered acceptable, while below 0.05 indicates a good fit. In this case, the RMSEA value suggests that the model fit is not satisfactory.</p></li>
<li><p><strong>Standardized Root Mean Square Residual (SRMR)</strong>: The SRMR value is 0.065. An SRMR value below 0.08 is generally considered acceptable. In this case, the SRMR value suggests an adequate model fit.</p></li>
<li><p><strong>Parameter Estimates</strong>: This section displays the unstandardized parameter estimates, standard errors, z-values, and p-values for the latent variables (Visual, Textual, and Speed), regressions, and covariances. Notice that standard errors are marked as “NA” because the information matrix could not be inverted. This issue was addressed in a previous response, and you may need to revise the model or examine potential issues such as multicollinearity, insufficient sample size, or incorrect model specification.</p></li>
</ol>
<blockquote class="blockquote">
<p>The model fit indices suggest an acceptable but not excellent model fit. It is essential to consider revising the model based on theoretical knowledge or prior research, as well as addressing the issues that led to the lack of standard errors in the output.</p>
</blockquote>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>In this blog post, we have provided a step-by-step guide on how to perform SEM and path analysis using R with the built-in ‘HolzingerSwineford1939’ dataset. By following these steps, you can gain a deeper understanding of the relationships among multiple variables and test complex causal models. The ‘lavaan’ package in R offers a user-friendly and powerful tool to perform SEM and path analysis, allowing researchers to explore a wide range of research questions in various fields.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">License: <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC BY-SA 2.0</a>.</div>   
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/ChangjunChrisLee/">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/Dr_CJLee">
      <i class="bi bi-twitter" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="mailto:changjun.chris.lee@gmail.com">
      <i class="bi bi-envelope" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>



</body></html>