---
title: Final projects
subtitle: For Exchange Students
---

-   There are 10 dataset you can choose

    -   See [introduction on the data](https://www.analyticsvidhya.com/blog/2021/04/interesting-kaggle-datasets-every-beginner-in-data-science-should-try-out/)

-   Among the dataset in the link, choose two (e.g. one for classification and the other for regression)

-   **Do the process below**

    -   EDA

        -   Data-preprocessing (wrangling)

        -   Deal with Missing values

        -   Data visualization

        -   Factorization

        -   If needed, standardization of the variables

    -   Modeling

    -   Predicting

-   **Data list**

    -   [Netflix show](https://www.kaggle.com/datasets/shivamb/netflix-shows)

    -   [Students performance](https://www.kaggle.com/datasets/spscientist/students-performance-in-exams)

    -   [Mobile Price Classification](https://www.kaggle.com/datasets/iabhishekofficial/mobile-price-classification)

    -   [Dogs & Cats Images](https://www.kaggle.com/datasets/chetankv/dogs-cats-images)

    -   [Trip Advisor Hotel Reviews](https://www.kaggle.com/datasets/andrewmvd/trip-advisor-hotel-reviews)

    -   [Melbourne Housing Market](https://www.kaggle.com/datasets/anthonypino/melbourne-housing-market)

    -   [Churn Modelling](https://www.kaggle.com/datasets/shubh0799/churn-modelling)

    -   [Amazon Best Seller Books](https://www.kaggle.com/datasets/sootersaalu/amazon-top-50-bestselling-books-2009-2019)

    -   [Medial Cost Personal DB](https://www.kaggle.com/datasets/mirichoi0218/insurance)

    -   [Kepler Exoplanet Search Results](https://www.kaggle.com/datasets/nasa/kepler-exoplanet-search-results)

-   Final output

    -   Submit a summary of your work, no more than 10 pages

    -   File type

        -   It can be in any form, such as a PDF, a link after uploading it to your blog, or a link after writing it on a Notion page, and so on.







