---
title: IC-PBL Team assignment
subtitle: 팀 배분 알고리즘
---

### Team assignemtn for Thursday class

```{r}
library(tidyverse)
set.seed(101101)
# input students
students<-c(
"이유정",
"박승연",
"이윤진",
"정재윤",
"김상경",
"정혜림",
"박지원",
"정지윤",
"김재엽",
"김찬우",
"박종현",
"윤지성")

students

# No of people per a team
team_size <- 4

# No of team we need
no_team <- length(students) %/% team_size
no_team

# No of remainders
remainder <- length(students) %% team_size
remainder

# Create a tibble (student_no, team)

if (remainder == 0){
  
  tibble(
    seat = 1:length(students),
    team = rep(1:no_team, team_size)
  ) -> seat_table
  
} else {
  
  tibble(
    seat = 1:length(students),
    team = c(rep(1:no_team, team_size),
             1:remainder)
  ) -> seat_table
  
}

seat_table

# Give random number for the students

tibble(
  seat     = sample(1:length(students), 
                    length(students), 
                    replace = F),
  students = students
) -> given_seat
given_seat


# Join the team - seat - students

seat_table %>% 
  left_join(given_seat) %>% 
  arrange(team, students) %>% 
  select(-seat) -> team_table

knitr::kable(team_table)

```


### Team assignemtn for Tuesday class

```{r}

library(tidyverse)
set.seed(101101)

# input students

students<-c(
"김정환",
"김숭기",
"김원",
"이정헌",
"노솔",
"최지희",
"조민석",
"김민지",
"김가영",
"박은서",
"임예빈",
"문하윤")

students

# No of people per a team
team_size <- 4

# No of team we need
no_team <- length(students) %/% team_size
no_team

# No of remainders
remainder <- length(students) %% team_size
remainder

# Create a tibble (student_no, team)

if (remainder == 0){
  
  tibble(
    seat = 1:length(students),
    team = rep(1:no_team, team_size)
  ) -> seat_table
  
} else {
  
  tibble(
    seat = 1:length(students),
    team = c(rep(1:no_team, team_size),
             1:remainder)
  ) -> seat_table
  
}

seat_table

# Give random number for the students

tibble(
  seat     = sample(1:length(students), 
                    length(students), 
                    replace = F),
  students = students
) -> given_seat
given_seat


# Join the team - seat - students

seat_table %>% 
  left_join(given_seat) %>% 
  arrange(team, students) %>% 
  select(-seat) -> team_table

knitr::kable(team_table)


```

