---
title: PBL Project
subtitle: 문제기반학습 프로젝트 소개
---

### 목표

협력 기업에서 주어진 문제 시나리오를 수업 시간에 배운 문화 사업과 미디어에 대한 이해를 바탕으로 팀 별로 해결을 위한 아이디어를 고안해본다. 인터뷰, 설문, 데이터 분석 등 모든 방법을 동원하여 실제 기업의 문제를 풀어 봄으로써 문화 산업과 기술에 대한 이해를 높이고 현장의 멘토링과 평가를 통해 현장감을 높이고 실전 경험을 갖춘다.

</br>

### 협력 기업

-   TEO 유니버스

    -   담당: 이동찬 경영총괄 (dclee\@teouniverse.kr)
    -   유튜브 계정: [https://www.youtube.com/\@TEO_universe](https://www.youtube.com/@TEO_universe)
    -   인스타 계정: <https://www.instagram.com/teo.universe/>

-   (주)ASSI

    -   담당: 윤영훈 대표이사 (younghoon.yun\@my-assi.com)
    -   독서 어플 리더스: <https://withreaders.com/>
    -   Google Play Store \[[download](https://play.google.com/store/apps/details?id=com.readersrn&hl=ko&gl=US)\]
    -   APPLE App Store \[[download](https://apps.apple.com/kr/app/%EB%A6%AC%EB%8D%94%EC%8A%A4-readers-%EC%99%84%EB%B2%BD%ED%95%9C-%EB%8F%85%EC%84%9C%EB%A5%BC-%EC%9C%84%ED%95%9C-%EC%84%9C%EB%B9%84%EC%8A%A4/id1470113337)\]

</br>

### Team Assignment

-   Random assignment

    |        |        |        |        |        |        |        |        |
    |:------:|:------:|:------:|:------:|:------:|:------:|:------:|:------:|
    | **1**  | **2**  | **3**  | **4**  | **5**  | **6**  | **7**  | **8**  |
    | 김근아 | 김명진 | 김세린 | 김재희 | 등시우 | 왕일범 | 윤동주 | 이소언 |
    | 임서영 | 최지현 | 최진영 | 강태현 | 고재희 | 김가희 | 김민기 | 김민우 |
    | 신소망 | 양제니 | 염다인 | 왕욱경 | 윤지민 | 이자의 | 이채은 | 장현군 |
    | 채자선 | 최은서 | 최혜린 | 김근아 | 김승연 | 김승주 | 김지훈 | 박지원 |
    | 박혜원 | 왕자문 | 유사여 | 이수연 | 임연우 | 정서윤 |        |        |

</br>

### 시나리오

**시나리오 1: 엔터테인먼트 기업**

1.  TEO는 많은 채널과 OTT 중 어느 곳과 전략적 관계를 강화하는 것이 유의미할지? 그 이유는?

2.  넷플릭스의 경우 고정 수익을 게런티해주지만 제작사로서 작품 IP는 확보하지 못하는 한계가 있는데 넷플릭스와 중장기적으로 함께할 경우 사업적 장단점은 무엇일지?

3.  TEO가 글로벌 시장에서 인정받을 수 있는 콘텐츠를 제작하기 위해서 준비해야할 요소는 무엇일지? 글로벌 흥행과 국내 흥행 중 무엇이 먼저일지?

</br>

**시나리오 2: 문화 기술 스타트업**

-   책의 **소비자** 입장

    -   좋은 책이란 무엇일까?

    -   책을 선택하게 되는 방법은 무엇이 있을까?

    -   좋은 책을 고르는 방법은 어떤 것들이 있을까?

    -   그 과정을 기술(IT, AI 등)로 풀어낼 수 있을까? (이 과정에서 더 필요한 것들이 있다면 어떤 것이 필요할까?)

    -   그 과정에 BM을 붙일 수 있을까?

-   책의 **공급자**(저자/출판사/유통사) 입장

    -   책을 제작하고 유통하는 이해관계자들의 경제적 해자는 어디로 부터 기인하는가?

    -   1\) 기술의 발전 2) 트렌드 변화가 영향을 끼치는 것들이 있을까?

    -   어떤 변화와 기회를 잡는 사람이 주도권을 잡게 될 것인가? (책의 공급자에게 중요해지는/필요한 역량은 무엇일까?)

-   벤치마킹/브레인스토밍: 다른 산업에서 힌트 얻기

    -   리더스 서비스에서, 독서 트레이너(PT)를 출시하기 위해, 트레이너가 있는 운동 산업에서 힌트를 얻어보고자 한다.

    -   헬스를 할때 PT를 받는 사람과 그렇지 않은 있다. PT를 받는 사람과 그렇지 않은 사람의 의사결정은 어떤 것에 의해 이루어 지는가?

    -   선생님(트레이너)과 함께하는 것이 일반적인 운동과 그렇지 않은 운동들이 있다. 무엇이 차이를 만드는가?

    -   위에 조사를 통해 얻은 시사점을 "독서"라는 행위에 접목해서 서비스 요소(feature)를 설계해보기

</br>

### PBL 주차별 진행:

-   **W4.** Team assignment (4\~5 students in a team)

-   **W5 \~ W7:** Team building

-   **W8 \~ W9:** Special lecture & Problem description (문제 제공 기업)

-   **W10 \~ W13:** Team Activity in class (수업 중 진행)

-   **W14:** Team activity with mentoring (수업 또는 현장)

-   **W16:** Final project presentation (현장 평가 참여)
