---
title: Weekly Content
# subtitle: 학습 도구
---

<br>

### **Intro**

<br>

#### **Week 1: Course Intro**

-   Date: 20240305

-   Class: Course Introduction

    -   An overview of the course

<br>



### **Part I: 	콘텐츠 기획과 제작**



<br>

#### **Week 2: 융합 콘텐츠 기획과 제작**

-   Date: 20240312

-   Pre-class video

    -   Discussion

-   Class

    -   Guest Lecturer: 강혜원 교수(SKKU)
    
    -   Modulator: 이창준 교수(SKKU)
    

<br>


### **Part II: 문화와 문화 산업**


<br>


#### **Week 3: 음악, K-pop, 엔터테인먼트**


-   Date: 20240319

-   Pre-class video

    -   Discussion

-   Class

    -   Guest Lecturer: 정헌섭 교수(SKKU)
    
    -   Modulator: 이창준 교수(SKKU)
    


<br>

#### **Week 4: 패션과 뉴테크**


-   Date: 20240326

-   Pre-class video

    -   Discussion

-   Class

    -   Guest Lecturer: 류현석 교수(SKKU)
    
    -   Modulator: 이창준 교수(SKKU)
    
<br>


#### **Week 5: 게임 & 인터랙티브 디자인**

-   Date: 20240402

-   Pre-class video

    -   Discussion

-   Class

    -   Guest Lecturer: 김수완 교수(SKKU)
    
    -   Modulator: 이창준 교수(SKKU)
    
<br>


#### **Week 6: 	한류와 팬덤**

-   Date: 20240409

-   Pre-class video

    -   Discussion

-   Class

    -   Guest Lecturer: 이종명 교수(SKKU)
    
    -   Modulator: 이창준 교수(SKKU)
    
<br>




### **Part III: 문화 기술**

<br>


#### **Week 7: 데이터 시각화의 예술**

-   Date: 20240416

-   Pre-class video

    -   Discussion

-   Class

    -   Guest Lecturer: 전서연 강사
    
    -   Modulator: 이창준 교수(SKKU)
    
<br>



#### **Week 8: 문화콘텐츠와 자연어 처리**

-   Date: 20240423

-   Pre-class video

    -   Discussion

-   Class

    -   Guest Lecturer: 구영은 교수(SKKU)
    
    -   Modulator: 이창준 교수(SKKU)
    
<br>


#### **Week 9: 	메타버스와 메타휴먼**

-   Date: 20240430

-   Pre-class video

    -   Discussion

-   Class

    -   Guest Lecturer: 원종서 교수(SKKU)
    
    -   Modulator: 이창준 교수(SKKU)
    
<br>


#### **Week 10: 인터랙션 사이언스, UX**

-   Date: 20240507

-   Pre-class video

    -   Discussion

-   Class

    -   Guest Lecturer: 이대호 교수(SKKU)
    
    -   Modulator: 이창준 교수(SKKU)
    

<br>

#### **Week 11: 서비스 디자인, 데이터 드리븐 마케팅**

-   Date: 20240514

-   Pre-class video

    -   Discussion

-   Class

    -   Guest Lecturer: 설상훈 교수(SKKU)
    
    -   Modulator: 이창준 교수(SKKU)
    

<br>

#### **Week 12: 가상/증강현실 콘텐츠 제작**

-   Date: 20240521

-   Pre-class video

    -   Discussion

-   Class

    -   Guest Lecturer: 김태원 대표(RGB Makers)
    
    -   Modulator: 이창준 교수(SKKU)
    

<br>



### **Part IV: 문화 콘텐츠 경영**

<br>



#### **Week 13: 융합콘텐츠와 창업**

-   Date: 20240528

-   Pre-class video

    -   Discussion

-   Class

    -   Guest Lecturer: 윤영훈 대표 (주)ASSI
    
    -   Modulator: 이창준 교수(SKKU)
    
<br>


#### **Week 14: 	엔터테인먼트 경영**

-   Date: 20240604

-   Pre-class video

    -   Discussion

-   Class

    -   Guest Lecturer: 이동찬 경영총괄 (TEO Universe)
    
    -   Modulator: 이창준 교수(SKKU)

<br>
  


### **Conclusion**

<br>

#### **Week 15: 	Wrap-up Exam**

-   Date: 20240611



