---
title: Course description & Communication
---

------------------------------------------------------------------------

### Course description

Culture & Technology is a comprehensive course exploring the intersection of culture and various forms of media technology. Spanning from the early days of print media to the era of social media, the course traces the transformation of media and its influence on cultural formation and diffusion. Further, the course delves into various facets of the cultural industry, including film, music, publishing, gaming, advertising, public relations, and entertainment. Incorporating lectures, discussions, team activities, and project work, the course offers a multifaceted look into how technology shapes culture and how culture, in turn, shapes technology.

</br>

### Goal

**The course aims to:** 

1.  Understand and analyze the role of different media in shaping and reflecting cultural values and norms.

2.  Explore the policies, laws, and literacy associated with different media.

3.  Investigate various segments of the cultural industry and their impact on society.

4.  Develop critical thinking and analytical skills through team activities and project work.

5.  Foster students' ability to articulate and present their understanding of complex cultural and technological phenomena.

</br>

### Weekly Design

+------+------------+---------------------------------+---------------------+--------------+
| Week | Date       | Class                           | PBL                 | Note         |
+:====:+:==========:+:================================+:===================:+:============:+
| 1    | 08/30/2023 | Course Intro                    |                     |              |
+------+------------+---------------------------------+---------------------+--------------+
| 2    | 09/06/2023 | What is Media?                  |                     |              |
+------+------------+---------------------------------+---------------------+--------------+
| 3    | 09/13/2023 | Broadcast                       |                     | (녹화수업)   |
+------+------------+---------------------------------+---------------------+--------------+
| 4    | 09/20/2023 | Press & Internet                | Team assignment     |              |
+------+------------+---------------------------------+---------------------+--------------+
| 5    | 09/27/2023 | Social Media                    | Team builiding      |              |
+------+------------+---------------------------------+---------------------+--------------+
| 6    | 10/04/2023 | Media Policy, Law, and Literacy | Team builiding      |              |
+------+------------+---------------------------------+---------------------+--------------+
| 7    | 10/11/2023 | Cultural Innovation             | Team builiding      |              |
+------+------------+---------------------------------+---------------------+--------------+
| 8    | 10/18/2023 | **Special lecture (1)\          | Problem description | 엔터산업 PBL |
|      |            | **- Entertainment               |                     |              |
+------+------------+---------------------------------+---------------------+--------------+
| 9    | 10/25/2023 | **Special lecture (2)\          | Problem description | 스타트업 PBL |
|      |            | **- Culture Start-up            |                     |              |
+------+------------+---------------------------------+---------------------+--------------+
| 10   | 11/01/2023 | Film & TV Show                  | PBL activity (2)    |              |
+------+------------+---------------------------------+---------------------+--------------+
| 11   | 11/08/2023 | Music & Publishing              | PBL activity (3)    |              |
+------+------------+---------------------------------+---------------------+--------------+
| 12   | 11/15/2023 | Game & Entertainment            | PBL activity (4)    |              |
+------+------------+---------------------------------+---------------------+--------------+
| 13   | 11/22/2023 | Advertising & PR                | PBL activity (5)    |              |
+------+------------+---------------------------------+---------------------+--------------+
| 14   | 11/29/2023 | PBL mentoring                   | Mentoring           |              |
+------+------------+---------------------------------+---------------------+--------------+
| 15   | 12/06/2023 | Wrap-up **QZ**                  |                     |              |
+------+------------+---------------------------------+---------------------+--------------+
| 16   | 12/13/2023 | **최종 프로젝트 발표**          |                     |              |
+------+------------+---------------------------------+---------------------+--------------+

</br>

### Evaluation

-   **Attendance (0 %)**: No attendance score but F for absence of ⅓ classes.

-   **Participation (20 %)**: Points for active participation in some form, such as questioning and discussion during class.

-   **Wrap-up QZ (30 %)**

-   **PBL Score (50%)**

    -   **Final score: (강의자 점수 30 + 현장 평가 점수 70) x (동료 평가 가중치)**

</br>

### Communication

-   Notices & Questions

    -   Please join Kakao open-chat room

        -   <https://open.kakao.com/o/giqvpYCf>

-   Personal counsel (Scholarship, recommendation letter, etc.)

    -   CJ-counselling room (Anything but the class content)

        -   CJ상담실: <https://open.kakao.com/o/s8zTrYCf>
