---
title: "한국연구재단 이공분야 생애첫연구"
subtitle: "미래 기술 정책을 위한 한국형 스마트 특성화 전략 모델 구축"
mainfont: NanumMyeongjo
monofont: NanumGothic
---

### 개요

-   본 과제는 전 세계 특허 데이터와 양자간 무역 데이터를 활용하여 한국의 미래 기술 혁신과 4차 산업 인재 양성 전략에 기여할 수 있는 정책 개발에 그 목적을 두고 있다.
-   기존의 국가 기술 정책의 경우 특정 지역의 기술적 상황이나 지식 축적의 정도를 제대로 반영하지 못하는 한계점을 가지고 있어 지역 혁신 정책의 기반이 되는 단서를 제공하는 융복합 방법론 개발이 필요하다.
-   따라서 이를 융복합 학문인 경제지리학과 데이터과학을 통해 지역 기술 혁신 정책을 근거 중심으로 체계화 하는 창의적 학술연구를 수행한다.
-   나아가 현재 전 세계에서 일어나고 있는 무역 전쟁의 핵심인 기술 경쟁의 본질을 양자간 무역 데이터를 통해 동아시아의 기술의 흐름을 분석해 봄으로써 향후 정책 방향을 모색하는 도전적 학술연구를 수행한다.
-   마지막으로 연구 과정에서 나오는 성과와 혜안을 공유하기 위한 웹 기반 플랫폼을 구축하고 홍보하여 정부 정책 입안 방향에 적용될 수 있도록 돕는다.

### 연구 배경

> 한국은 1960년대부터 전 세계에서 유례없는 성장률인 연 평균 7%를 기록하며 급속도로 성장해왔다. 그 결과 1960년대 158불(USD)이었던 일인당 국내 총생산이 2017년에는 약 3만불(29,742 USD)까지 증가했다. 현재 한국은 아시아에서는 4번째, 전 세계에서는 12번째로 큰 경제국이다. 호의적이었던 국제 시장 상황, 높은 비율의 숙련공, 노동력의 높은 교육 수준 등의 요소가 물론 주요했지만, 학계에서는 수출 주도의 산업 정책이 성공 요인으로 빈번하게 거론되어 왔다. 하지만 글로벌 경제 위기 이후 한국은 예전의 성장력을 회복하지 못하고 저성장의 길로 들어섰다. 한국은행과 국제통화기금(IMF)는 모두 한국경제의 잠재성장률을 2% 수준으로 보고 있으며 2020년대와 30년대는 1%대로 떨어질 것으로 예측하고 있다. 이는 물론 국제적인 불황과 노동 인구의 감소가 큰 축을 담당하고 있지만 그런 요인들은 현재 모든 선진국의 당면 과제들이다.
>
> \
> 유럽 연합(EU)은 이러한 문제점을 조기에 인식하고 국가를 중심으로 저성장, 실업문제를 해결할 지역정책 모색과 산업정책인 스마트 특성화 전략(Smart Specialization Strategy, S3)을 수행 중이며 하향식(Top-down)과 상향식(Bottom-up) 방법을 적절히 혼합하여 지역 혁신의 성과를 이루어 내고 있다. 유럽 내의 모든 국가와 지역에서 주력 산업 및 미래 성장동력산업 육성을 위해 획일적으로 적용되어 왔던 기술 정책들을 각 지역의 역량, 특성 및 잠재력에 기초하여 새로운 지역별 혁신 모델을 정착시키고 있다. 하지만, 한국은 달라진 기술 환경에 적응하지 못하고 기존의 혁신 모델에서 크게 벗어나고 있지 못하고 있다. 기존에 이루어진 많은 기술 정책들은 지역의 지식 역량을 고려하지 않은 채 바이오, 나노, 정보통신(IT) 등의 유사한 지식 클러스터를 특정 지역에 특화 시키려고 노력했으나 새로운 융합 기술이나 산업의 구조적 변화를 이끌어 내는 데는 한계가 있었다. 또한 이로 인해 지식기반이 획일화되고 국가 및 지역별 지식 구조의 독창성과 차별성을 상실했다는 비판도 면할 수 없었다. 이에, 지역 지식 역량을 고려한 전략과 투자를 차별화하여 불필요한 중복 투자를 막고 지역의 지식, 기술, 인적 자원을 최대한 활용한 지역 혁신정책의 필요성이 제기되고 있다.
>
> \
> 따라서 본 과제에서는 지역별 지식 구조를 분석하는 방법을 체계화하고 이를 근거로 지역의 기술 혁신 정책, 즉 한국형 스마트 특성화 전략(Korean Smart Specialization Strategy, KS3)을 개발하고자 한다. 구체적으로는 한국의 지식 구조의 진화 과정을 특허 데이터에 포함되어 있는 메타 정보를 활용하여 분석해보고 이를 지역별 지식 구조의 진화 과정과 비교해본다. 이를 통해 각 지역의 지식 역량을 기반으로 한 스마트 특성화 전략을 도출할 수 있다. 또한 특허 데이터를 통해 얻어진 지역의 지식 구조와 양국간 무역 데이터와의 연결을 통해 일본과 중국의 특성화된 기술에 비해 한국의 경쟁력이 낮은 기술들을 개발할 때 어떤 지역에서 해당 기술을 특화시켜야 하는지에 대한 전략도 수립해 보고자 한다.

### 기대효과

-   4차 산업 혁명을 대비해 많은 국가들이 인공지능, 로보틱스 등의 신산업을 육성하기 위해 기술 로드맵을 개발하고 있지만 정작 지역별 지식 공간을 분석하여 근거를 가지고 특정 지역을 특정 기술로 특화 시키거나 개발하는 노력은 부족해왔다.

-   본 과제의 성공적 수행을 통해 첫째로 한국형 스마트 특성화 전략에 대한 학문적 근거를 마련할 수 있을 것으로 보인다. 둘째로 현재 이슈가 되고 있는 한국과 미국, 일본, 중국 등의 무역 갈등 기저에 있는 기술 갈등 역시 학문적 접근이 가능하다.

-   이는 정책적으로 상당한 파급효과가 있을 것으로 예상된다. 학문적 성과 외에도 연구 결과가 정책 입안자들이 실용적으로 시의적절한 참고가 될 수 있도록 웹 기반 플랫폼을 구축할 예정이다. 이를 통해 연구 결과가 실제로 정책으로 이어지는 파급 효과가 예상된다.

------------------------------------------------------------------------

### 성과

#### 컨퍼런스 발표: 국내 4회, 국제 1회

-   20200612: 사이버커뮤니케이션학회 춘계정기학술대회. 사이버커뮤니케이션학회

    -   미디어연관도 분석을 통한 미디어 수용자의 선택적 노출 측정과 정치적 양극화

-   20200925: 제8회 한국미디어패널학술대회. 정보통신정책연구원.

    -   늦은 밤 OTT 시청이 수면에 끼치는 영향

```{=html}
<!-- -->
```
-   20201120: 정보통신정책학회 정기학술대회. 정보통신정책연구원.

    -   한국 AI 지식의 진화, 그리고 미래

-   20210903: 제9회 한국미디어패널학술대회. 정보통신정책연구원.

    -   개인적 특성, 환경적 요인, 시간대와 요일효과를 고려한 OTT 선택 요인 분석: TV vs. OTT

-   20221017: ERC TechEvo Workshop. European Research Council. \@Vienna Complex Hub Lab, Austria

    -   Network Methods to Analyze Collective Knowledge

#### 논문 발간: S(S)CI 6편, KCI 1편

-   Shon, M., Lee, D. & **Lee, C.**(2022). Inward or Outward? Direction of Knowledge Flow and Firm Efficiency. *International Journal of Technology Management. 90*(1-2), 102-121. <https://doi.org/10.1504/IJTM.2022.124617>

-   Tóth, G., Elekes, Z., Whittle, A., **Lee, C.**\*, & Kogler, D. F. (2022). Technology network structure conditions the economic resilience of regions. *Economic Geography. 98*(4), 1-24. <https://doi.org/10.1080/00130095.2022.2035715>

-   Kim, K., Lee, J., & **Lee, C.**(2022). Which innovation type is better for production efficiency? A comparison between product/service, process, organizational, and marketing innovations using stochastic frontier and meta-frontier analysis. *Technology Analysis & Strategic Management.* doi: <https://doi.org/10.1080/09537325.2021.1965979>

-   Rocchetta, S.*, Mina, A*., **Lee, C.**, & Kogler, F. D. (2022). Technological Knowledge Space and the Resilience of European Regions. *Journal of Economic Geography. 22(1), 27-51*.\* doi: <https://doi.org/10.1093/jeg/lbab001>

-   **Lee, C.**, Cho, H., & Lee, D.\* (2021). The mechanism of innovation spill-over across sub-layers in the ICT industry. *Asian Journal of Technology Innovation. 29*(2), 159-179. doi:<https://doi.org/10.1080/19761597.2020.1796725>

-   Kim, K., Lee, J., & **Lee, C.**\* (2021). Exploratory Analysis of Knowledge Structure and Evolutionary Trajectory in Korean Artificial Intelligence for Effective Technology Policy. *Korean Innovation Study*, 16(3). [DOI:https://doi.org/10.46251/INNOS.2021.8.16.3.139](https://doi.org/10.46251/INNOS.2021.8.16.3.139)

-   **Lee, C.**, Lee, D., & Shon, M.\* (2020). Effect of efficient triple-helix collaboration on organizations based on their stage of growth. *Journal of Engineering and Technology Management*. *58*, 101604. <https://doi.org/10.1016/j.jengtecman.2020.101604>
