---
title: "한국연구재단 신진연구자지원사업(인문사회)"
subtitle: "가상세계 멀티 페르소나 성향과 사용자의 인지 강화"
mainfont: NanumMyeongjo
monofont: NanumGothic
---

### 연구 목표

메타버스가 새로운 사회적 공간으로 급부상하면서, 그러한 가상세계에서 사용자를 대표하는 아바타 역시 제 2의 사회적 자아로 자리 잡고 있는 상황이다. 그러나 관련된 연구 현황은 변화한 사회 흐름을 반영하지 못한 채 기존의 온라인 플랫폼 속 아바타에 대한 분석에만 머무르고 있는 실정이다. 이에 본 연구는 새로운 가상세계인 메타버스 속 아바타가 어떠한 의도와 양상으로 표현되는지를 탐구하고자 한다. 특히 메타버스 사용자의 아바타 창조에 초점을 맞춰, 멀티 페르소나(다중 정체성) 지표를 개발하고 그에 따른 다양한 실험을 수행할 것이다. 또한 이를 통해 멀티 페르소나 성향이 메타버스 사용자의 감각적 몰입과 창의성에 어떤 영향을 끼치는지를 분석하고자 한다. 이는 국내외 연구에서 단 한 번도 시도된 적 없는 새로운 미디어-사용자 상호작용 프레임 워크의 개발로서, 기존 가상세계의 아바타와는 확연히 구분되는 결과를 제시할 것으로 예측한다.

### 기대 효과

본 연구의 결과물은 아바타 창조에 대한 단편적 분석 수준을 넘어 1) 사회적 측면에서 메타버스의 주요 사용 계층인 1020세대의 미디어 사용 현상과 경험에 관한 심층적 이해를 제시할 수 있을 것이다. 또한 이는 급변하는 미디어 환경에 적절히 대응하도록 하는 미디어 리터러시 교육에 대한 단초까지도 제공할 수 있을 것이라 기대한다. 2) 학문적 측면에서 역시 메타버스라는 새로운 플랫폼 사용자의 아바타 활용 성향에 창의적이고 도전적으로 접근함으로써, 뉴미디어 연구 분야에 다양하고 폭넓은 논의점을 제시할 수 있을 것이라 기대한다. 나아가, 설문과 실험 기법의 창의적인 융합은 복잡다난해지는 미디어 연구 영역에서 보다 과학적이고 체계적인 연구 방법을 제안하는 일이 될 것이다. 3) 연구인력 양성의 측면에서, 본 연구는 아직 충분히 연구되지 못한 메타버스 영역의 관련 서비스와 사용자에 대한 전문적인 연구 인력을 배출할 수 있을 것이다.

### 연구 요약

새롭게 등장한 가상세계 플랫폼인 메타버스는 사회 전반에 걸친 다양한 영역과 연계될 수 있다는 높은 가능성을 지니고 있음에도, 관련된 이해와 탐구는 여전히 미미한 수준이다. 특히 메타버스에서 사용자를 대신할 수 있는 아바타는 제2, 제3의 자아로 존재하며 사회적 상호작용과 가상세계로의 몰입에 중요한 매개체가 되어가고 있다. 이에 본 연구는 관련한 심층적 연구의 필요성을 인식하여 1) 메타버스 속 아바타 창조의도에 대한 탐구를 통해 사용자의 멀티 페르소나 지표를 개발하고 2) 메타버스 가상세계에서의 멀티 페르소나 특성이 사용자의 감각적 몰입에 끼치는 영향에 대해 분석하며 3) 메타버스 가상세계에서의 멀티 페르소나 특성이 사용자의 창의성에 끼치는 영향에 대해 분석하고자 한다. 그에 따라 구체적으로, 1차 년도에는 메타버스 가상공간 속 멀티 페르소나에 대한 이론적 프레임워크를 개발하여 이를 기반으로 멀티 페르소나 지수 측정 아이템을 고안한다. 이는 추후에 이어질 연구에서 사용자의 멀티 페르소나 성향을 제시하는 중요한 단초가 된다. 2차 년도에는 메타버스 속 감각적 몰입에 대한 정의와 측정 아이템을 개발한 후, 멀티 페르소나 성향과 감각적 몰입 간의 관계를 분석한다. 이를 위해, 100% 가상환경(제페토)과 가상-현실 혼합 환경(게더타운)을 중심으로 아바타에 발현되는 멀티 페르소나 성향과 감각적 몰입에 관한 창의적인 실험 환경을 구축할 예정이다. 마지막으로 3차 년도에는 메타버스 속 인지강화 경험 중 창의성에 대한 측정 아이템을 개발하고, 전 해에 구성된 창의적 실험 디자인을 활용하여 멀티 페르소나 성향과 창의성 간의 관계를 분석한다. 이와 같은 과정의 전반은 과거에 시도된 적 없는 매우 새롭고 창의적인 일이며, 미래에 이어질 후속연구에 유의미한 가치를 제공할 수 있을 것이다.

------------------------------------------------------------------------

### 1차 년도 실적(2022.05.01.\~2023.04.30.)

1.  **멀티페르소나 지수 측정 도구 개발 및 설문 실시**

    본 연구는 1년차 연구 목표를 위해 메타버스 사용자의 멀티 페르소나 지수 측정 척도 개발을 수행하였으며, 특히 '아바타 커스터마이징'을 중심으로 설문 도구를 제작하였다. 아바타 커스터마이징에 관한 기존의 연구들은 게임·디자인 영역에 한정되어, 디자인 요소 혹은 디지털 기술 향상에 관한 논의만이 주를 이뤄왔다. 본 연구는 그러한 한계점을 극복하고자 아바타 커스터마이징 항목을 미디어와 사회적 차원으로 가져와 학제 간 융합을 시도하였고, 메타버스 내 멀티 페르소나 지수 측정을 위한 척도 개발에 응용하였다. 구체적으로, 가상의 커스터마이징이 가능한 설문 문항을 통해 현실과 가상세계 아바타의 모습이 얼마나 다른지를 측정하였다. 설문에는 한양대 ERICA 언론정보대학 재학생 112명이 참여하였으며, 그에 따른 주요 연구 성과로서 사회자본이 메타버스 내 멀티 페르소나 지수와 연관이 있음을 도출하였다.

2.  **500명 규모의 2차 설문 실시**

    메타버스 사용자의 멀티 페르소나 특성을 측정한 첫 설문 이후, 분석 결과를 토대로 문항을 수정하여 2차 설문에 착수하였다. 본 연구에서는 약 500명 규모의 참여자를 대상으로, 1회의 파일럿(200명) 테스트와 1회의 본 조사(300명)를 계획하였다. 이를 위해, ㈜마크로밀엠브레인을 통해 2023년 2월 2일부터 파일럿 테스트를 실시하였으며, 그 결과 212명의 데이터를 확보하였다. 추가적으로, 파일럿 테스트에서 확보된 데이터의 심층적 검토를 거쳐 설문 도구를 최종 수정하여 300명 이상 규모의 본 조사를 실시할 예정이다.

3.  **논문 투고**

    본 연구에서는 1년차에 개발된 멀티 페르소나 척도를 메타버스에 관한 다양한 시각에 접목해, 사용자의 내적‧외적 측면을 깊이 있게 탐색할 수 있는 구체적 연구를 설계하였다. 특히 앞서 언급한 아바타 커스터마이징 행위를 통해 사용자의 자아 표현 양상을 다뤘을뿐만 아니라, 그것을 사회적 상호작용의 영역과 연계하였다. 이러한 연구 결과는 KCI급 저널에 투고될 예정이다.

4.  **C&I studies 주관 특별 세미나 '*메타버스 새로운 미래, 새로운 인간*' 개최**

    본 연구팀은 2022년 10월 26일 한양대 ERICA 언론정보관 4층 MCN Open Studio에서 메타버스에 관한 특별 세미나를 실시하였다. 이는 메타버스와 아바타, 멀티페르소나에 대한 총 3개의 섹션('메타버스 트렌드와 전망, 수용자 특성의 주요 쟁점', '가상세계 멀티 페르소나 성향과 사용자의 인지 강화', '관계형성의 장으로서 메타버스에 관한 실증적 접근')으로 나뉘어 진행되었다. 세미나를 통해, 관련 내용을 타 학자들과 논의함으로써 당해 연구 목표인 멀티 페르소나 지수 측정의 주요 요인들을 도출하였다. 또한 2차년도에 수행될 실험 연구를 위해, 보다 정교한 연구 방법(VR기기 활용 및 자체적 실험 환경 구축) 도입을 계획 및 논의 할 수 있는 교류의 장을 마련하였다.

5.  **한국미디어경영학회, 프리드리히나우만재단 주관 특별 세미나 '*메타버스 산업과 이용자, 그리고 디지털 리터러시*' 및 발표**

    본 연구팀은 2022년 11월 8일 홍대 RYSE 호텔 SPACE에서 개최된 세미나에 참석하여, '메타버스 사용자의 사회적 자본, 아바타 커스터마이징과 프레즌스'를 주제로 한 발표를 수행하였다(발표자: 이창준, 한양대학교 교수). 이를 통해 1년차 연구 목표인 멀티 페르소나 측정을 위한 아바타 커스터마이징 방법을 학계에 제시하였으며, 이러한 연구가 단순한 학술적 차원 이상의 실증적·실무적 차원까지 발전할 수 있음을 논의하였다. 또한 세미나의 주제인 진화하는 메타버스 환경에서 필요한 이용자 활동과 경험, 그에 따른 사회현상에 관해 타 학자들과의 활발한 교류를 진행하였다.
