---
title: "Course Intro"
Week: 1
slide-format: revealjs
---

[Weekly design](https://changjunlee.com/teaching/ml101/weekly/)

<br>

### Week 1 Class

```{=html}
<iframe class="slide-deck" src="https://changjunchrislee.github.io/ML101_w1/#/" width="800" height="450"></iframe>
```
[Slide](https://changjunchrislee.github.io/ML101_w1/#/)

<br>

### Install gadgets

-   Install R, R Studio, & Rtools

    -   R

        -   For window <https://cran.r-project.org/bin/windows/base/>

        -   For mac <https://cran.r-project.org/bin/macosx/>

    -   R Studio

        -   <https://posit.co/download/rstudio-desktop/>

    -   Rtools (only for window user)

        -   <https://cran.r-project.org/bin/windows/Rtools/>

        -   To install R packages containing C/C++ language for window users (no need for Linux and Mac users)

-   Things you need to know

    -   Don't use OneDrive.

        -   Use Github instead

        -   Many people get an error when installing becausedf OneDrive

    -   Set Windows user name to English

        -   If Korean characters are mixed in the installation path, there is a high probability of error occurrence

-   Installation Order

    -   Step 1 ‑ Download the file

        -   Download R, Rtools, Rstudio installation files

    -   Step 2 - Install R

        -   Unified installation path: All will be installed in the `C:/R` folder

        -   Run in administrator mode when running the R installation file

        -   After installing R, grant write permission to the R folder, Right-click and turn off read only

    -   Step 3 ‑ Install Rtools

        -   Administrator mode execution installation and folder setting as C:\\R\\rtools40

        -   Create environment variable RTOOLS40_HOME after installation: Value - C:\\R\\rtools40\\

        -   Add *%RTOOLS40_HOME%\\usr\\bin\\* to the Path variable.

    -   Step 4 - Install Rstudio

        -   Right-click and run as administrator - installation path C:\\R\\Rstudio

        -   Check rtools connection with Sys.which("make") command after installation
