---
title: "Syllabus"
# subtitle: "주차별 계획 및 학습도구"
---

------------------------------------------------------------------------

## **Intro**


### **Week 1**: Course Intro

-   Date: 20230302

-   Class

    -   Course Introduction [PDF](pdfs/MDS_W1.pdf)

    -   Install R, RStudio, & Rtools

------------------------------------------------------------------------

## **Data Science Basic**



### **Week 2**: R Basic Syntax (1)

-   Date: 20230309

-   Pre-class: Basic syntax, Vector, Array

-   Class: Hands-on practice [PDF](pdfs/MDS_W2.pdf)

    -   Data in use: [COV19_data](data/COV19_data_for_class.rdata)

    -   Process of creating the data above \[[Code](cov_anal.qmd)\]

### **Week 3**: R Basic Syntax (2)

-   Date: 20230316

-   Pre-class: Data.frame, List

-   Class: Hands-on practice [PDF](pdfs/MDS_W3.pdf)

    -   Data in use: [List_KMP](data/List_KMP.rdata)

### **Week 4**: R Basic Skillset (1)

-   Date: 20230323

-   Pre-class: Read, Write, Condition, Repetition

-   Class: Hands-on practice \[[Code](preclass.qmd)\]

### **Week 5**: R Basic Skillset (2)

-   Date: 20230330

-   Pre-class: Function, Missing values, Outliers

-   Class: Hands-on practice **(Review Week 1 to 5)**

-   데이터사이언스를 활용한 미디어연구에 대한 고찰 \[[PDF](pdfs/future_ds.pdf)\]

    -   KCI 논문 검색 [dbpia](https://www.dbpia.co.kr/)

    -   SSCI 논문 검색 [google scholar](https://scholar.google.com/)

    -   미디어 분야에서 데이터사이언스 활용한 논문 목록 리스트 \[[XLSX](pdfs/ds_in_media.xlsx)\]

------------------------------------------------------------------------

## **Data Pre-processing & Visualization**



### **Week 6**: Data manipulation

-   Date: 20230406

-   Pre-class: Data wrangling (Base R & Tidyverse)

-   Class: Hands-on practice

    -   Introducing tidyverse \[[click](https://www.tidyverse.org/)\]

    -   Go to Posit cheatsheets \[[click](https://posit.co/resources/cheatsheets/)\]

    -   Class code \[[click](tidyverse.qmd)\]

-   Recommended books for the further study

    -   [Statistical Inference via Data Science (Modern Dive)](https://moderndive.com/index.html) (written by Chester Ismay and Albert Y. Kim)

        -   is a comprehensive textbook that provides an accessible and hands-on approach to learning the fundamental concepts of statistical inference and data analysis using the R programming language.

    -   [R for Data Science](https://r4ds.had.co.nz/index.html) (written by *Hadley Wickham* and *Garrett Grolemund*)

        -   is an excellent resource for learning data science using R, covering data manipulation, visualization, and modeling with R. The book is available as a free online resource.

### **Week 7**: Data visualization

-   Date: 20230413

-   Pre-class: Data-visualization, ggplot2, and (ggplot practice, optional)

-   Class: Hands-on practice

    -   ggplot2 world \[[click](https://ggplot2.tidyverse.org/)\]

    -   ggplot2 extension gallery \[[click](https://exts.ggplot2.tidyverse.org/gallery/)\]

    -   Class code for understanding ggplot2 \[[click](ggplot.qmd)\]

    -   Class code for titanic data visualization \[[click](titanic_viz.qmd)\]

-   Recommended books for the further study

    -   [R Graphic Cookbook](https://r-graphics.org/index.html) (written by *Winston Chang)*

        -   is a practical guide that provides more than 150 recipes to help you generate high-quality graphs quickly, without having to comb through all the details of R's graphing systems

    -   [ggplot2: elegant graphics for data analysis](https://ggplot2-book.org/index.html) *published by Springer*

------------------------------------------------------------------------

## **Text Data Analysis**



### **Week 8**: Text mining (1)

-   Date: 20230420

-   전처리, 빈도 분석, 형태소 분석

-   Code for the class [\[here\]](NLP_1.qmd)

-   Recommended books for the text mining in R

    -   [Text Mining with R](https://www.tidytextmining.com/index.html) (written by *Julia Silge* & *David Robinson*)

    -   [R로 하는 텍스트마이닝](https://bookdown.org/ahn_media/bookdown-demo/) (written by *안도현 교수님*)

    -   [Do it 쉽게 배우는 R 텍스트마이닝](https://github.com/youngwoos/Doit_textmining) (written by *김영우*)

### **Week 9**: 휴강

-   Date: 20230427

### **Week 10**: Text mining (2)

-   Date: 20230504

-   TF-IDF, 감정 분석

-   Code for the class [\[here\]](NLP_2.qmd)

### **Week 11**: Text mining (3)

-   Date: 20230511

-   동시출현 분석

-   Code for the class [\[here\]](NLP_3.qmd)

### **Week 12**: Text mining (4)

-   Date: 20230518

-   토픽 모델, 총정리 및 실습

-   Code for the class [\[here\]](NLP_4.qmd)

------------------------------------------------------------------------

## **Media & DS Application**



### **Week 13**: 데이터사이언스를 활용한 연구 기획을 위한 개인 미팅

-   20230525(목) 외부 출장으로 인해 아래 시간 중 찾아올 것.

-   개인 단위 연구도 가능하고 그룹 연구도 가능!

-   **Office Hour**:

    -   20230523 (화) 13:00 \~ 17:00

    -   20230524 (수) 13:00 \~ 16:00

### **Week 14**: 데이터사이언스를 활용한 프로포절

-   Date: 20230601

-   **Class**:

    -   데이터사이언스를 활용해서 풀고 싶은 내용 (5분 발표)

    -   참고한 데이터사이언스를 활용한 논문들도 소개해주면 Even better!

### **Week 15**: 최종 과제 제출

-   Date: 20230608

-   프로포절에서 받은 피드백을 바탕으로 '자유 형식'으로 아래 구글폼을 통해 제출

-   자유 형식이지만 약간의 Guide를 준다면, 

    -   연구 배경: 연구의 중요성
    
    -   문제 제기: 연구의 독창성
    
    -   연구 질문: 풀고자 하는 문제
    
    -   연구 방법: 정의된 문제를 어떻게 풀지에 대한 내용
    
    -   예상 결과, 추진 계획 등



</iframe>

<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSecTZ-lL0L6cHuBXK5u2dvLflqjSWo1tRZRqUbVFdCLSWWUaw/viewform?embedded=true" width="640" height="1000" frameborder="0" marginheight="0" marginwidth="0">

Loading...

</iframe>
