---
title: Weekly Content
# subtitle: 학습 도구
---

#### **Intro**

------------------------------------------------------------------------

#### **Week 1**: Course Intro

-   Date: 20230830

-   Class: Course Introduction

    -   An overview of the course, discussion on the relationship between culture and technology, and the significance of studying this interaction.

    -   PDF \[[download](CNT2_W1.pdf)\]

</br>

------------------------------------------------------------------------

#### **Part I: Media as a Mediation of cultural formation and diffusion**

------------------------------------------------------------------------

</br>

#### **Week 2**: What is Media?

-   Date: 20230906

-   Class

    -   Definition and types of media, exploring the purpose and influence of media on cultural development

    -   PDF \[[download](CNT2_W2.pdf)\]

#### **Week 3**: Broadcast & Tech

-   Date: 20230913

-   Class (Online)

    -   Study of the broadcast industry's evolution and its cultural implications, including radio and television.

-   Broadcast Part I

    {{< video https://youtu.be/Z1a7bedfXNU >}}

-   Broadcast Part II

    {{< video https://youtu.be/JN4VtjwotCE >}}

-   Broadcast Part III

    {{< video https://youtu.be/20-HN65khss >}}

-   PDF \[[download](CNT2_W3.pdf)\]

</br>

#### **Week 4**: Press & Tech

-   Date: 20230920

-   Class

    -   Examination of print media such as newspapers, magazines, its history, evolution, and cultural impact, and Exploration of the Internet's influence on culture, including the shift in information access and the emergence of digital culture.

    -   PDF \[[download](CNT2_W4.pdf)\]

#### **Week 5**: Social Media & Tech

-   Date: 20230927

-   Class

    -   Analysis of the rise of social media platforms, their role in shaping modern culture, and discussion on phenomena like cancel culture, influencers, etc.

    -   PDF \[[download](CNT2_W5.pdf)\]

#### **Week 6**: Media Policy, Law, and Literacy

-   Date: 20231004

-   Class

    -   Examination of media regulations, media laws, and the importance of media literacy in today's digital age.

    -   PDF \[[download](CNT2_W6.pdf)\]

#### **Week 7**: Internet, UI/UX, and Smart-media era

-   Date: 20231011

-   Class

    -   PDF \[[download](CNT2_W7.pdf)\]

</br>

------------------------------------------------------------------------

#### **Part II: Voice from Culture Industry**

------------------------------------------------------------------------

</br>

#### **Week 8**: Special lecture (1): 엔터테인먼트 산업

-   Date: 20231018

-   Pre-class video: **How Netflix And YouTube Changed Entertainment Forever** by CNBC Marathon

    {{< video https://youtu.be/C1KYRMqv_ZA >}}

-   Class: 10:00 \~ 11:30 특강

    -   이동찬 경영총괄 (TEO 유니버스)

    -   강연자료 PDF \[[download](CNT2_W8.pdf)\]

</br>

#### **Week 9**: Special lecture (2): 문화 콘텐츠 애플리케이션 개발

-   Date: 20231025

-   Pre-class video: **Opportunities in AI 2023** by Andrew Ng (Stanford Univ.)

    {{< video https://youtu.be/5p248yoa3oE >}}

-   Class: 10:00 \~ 11:30 특강

    -   윤영훈 대표 (ASSI)

    -   시간사용 PDF \[[download](CNT2_W9_1.pdf)\]

    -   창업에 대한 핵심생각 PDF \[[download](CNT2_W9_2.pdf)\]

</br>

------------------------------------------------------------------------

#### **Part III: Understanding the Cultural Industry**

------------------------------------------------------------------------

</br>

#### **Week 10**: Film

-   Date: 20231101

-   Class

    -   Overview of the film and television industries, analysis of their cultural implications, and their transformation with technology.

    -   PDF \[[download](CNT2_W10.pdf)\]

#### **Week 11**: Music & GenAI

-   Date: 20231108

-   Class

    -   Study of the music industry and publishing sector, their evolution in the digital age, and the resultant cultural shifts.

    -   PDF \[[download](CNT2_W11.pdf)\]

#### **Week 12**: Immersive Tech, Game, & Entertainment Industry

-   Date: 20231115

-   Pre-class video: **How immersive technologies (AR/VR) will shape our future** by Dinesh Punni (TED Talk)

    {{< video https://www.youtube.com/watch?v=QcANba_1xg8&t=480s >}}

-   Class

    -   Exploration of the gaming industry, its rise as a cultural phenomenon, and its influence on society.

    -   Discussion on various forms of entertainment, their cultural impact, and the changes brought about by technological advancements.

    -   PDF \[[download](CNT2_W12.pdf)\]

#### **Week 13**: Advertising & PR

-   Date: 20231122

-   Class

    -   Examination of the advertising and PR industries, their relationship with culture, and the influence of technology on them.

    -   PDF \[[download](CNT2_W13.pdf)\]

</br>

------------------------------------------------------------------------

#### **Part IV: Wrap-up & PBL Activity**

------------------------------------------------------------------------

</br>

#### **Week 14**: PBL mentoring (at ZOOM)

-   Date: 20231129

-   Zoom link 는 당일 단톡방에서 확인

-   미팅 시간표

    | Time        | Team |
    |-------------|------|
    | 09:00-09:20 | 1    |
    | 09:20-09:40 | 2    |
    | 09:40-10:00 | 3    |
    | 10:00-10:20 | 4    |
    | 10:20-10:40 | 5    |
    | 10:40-11:00 | 6    |
    | 11:00-11:20 | 7    |
    | 11:20-11:40 | 8    |

</br>

#### **Week 15**: Individual Essay about *Culture & Technology*

-   Date: 20231206

-   에세이

    -   **내용**: 수업에서 배운 내용을 중심으로 아래 주제 중에서 하나를 택해서 (또는 자유 주제) **2000자 (A4 2 페이지) 이하**로 작성

    -   **가능한 주제** (but not limited)

        -   미디어가 문화 형성에 미치는 영향

        -   방송 산업의 진화와 문화적 함의

        -   인쇄 미디어와 디지털 문화의 상호작용

        -   소셜 미디어의 부상과 새로운 문화 형성

        -   미디어 정책과 법률이 문화에 미치는 영향 (미디어 규제와 법률이 문화적 표현과 소통에 어떤 영향을 미치는지)

        -   인터넷, UI/UX, 그리고 스마트 미디어 시대 (인터넷과 사용자 인터페이스가 문화에 미치는 영향)

        -   AR/VR 기술이 엔터테인먼트 산업에 끼친 영향

        -   음악 산업의 디지털화와 문화적 변화

        -   광고 및 PR 산업의 기술적 변화와 문화적 영향

        -   스트리밍 서비스가 엔터테인먼트 산업에 끼친 영향

    -   주의사항

        -   2000자가 넘으면 안됨

        -   수업 시간에 배운 내용의 요약 + 본인의 의견이 잘 어우러지도록

        -   영어로 작성 가능 (Writing in English is available)

        -   생성형인공지능 활용한 글쓰기도 가능함 (유의해서 사용)

        -   **파일명**: CNT_essay_홍길동.hwp(doc)

-   **제출**: 아래 구글 폼 링크에서 업로드

    -   <https://forms.gle/tABHibRyQg48SK8s6>

</br>

#### **Week 16**: 프로젝트 최종 보고서 발표 및 제출

-   Date: 20231213

-   보고서 = 발표 자료 (PPT)로 제출 가능

-   발제 순서

    | Time        | Team |
    |-------------|------|
    | 09:10-09:30 | Ent1 |
    | 09:30-09:50 | Ent2 |
    | 09:50-10:10 | Ent3 |
    | 10:10-10:30 | Ent4 |
    | 10:30-10:50 | Ent5 |
    | 10:50-11:10 | App1 |
    | 11:10-11:30 | App2 |
    | 11:30-11:50 | App3 |

</br>

-   **최종 팀 보고서 제출**: 아래 구글 폼 링크에서 업로드
    -   <https://forms.gle/U5wWe8b9kSRE8KB58>

    -   **파일 이름:** CNT_PBL_final_1조.pptx(hwp, doc ..)

    -   파일이 너무 커서 업로드가 안되는 등의 이슈가 있을 시 메일로 보내주세요. ([changjunlee\@skku.edu]{.underline})

</br>

-   동료 평가 및 수업에 대한 설문

    -   <https://forms.gle/BWgHoz9GoAtZzjDQ6>
